### ISSUE TITLE
error when updating

### ISSUE THREAD

**Issue by scottiep** [dscottbuch/cTiVo#101]
I'm a relatively new user of cTiVo (less than a year). I am on Mac OS 10.8.5 and currently have cTiVo ver. 2.1 and I wanted to update it (I only just realized that my version was out of date as I was researching the commercial skipping feature.

Is my OS the problem? Is 2.1 the last version that supports my OS?

thanks in advance.

**Comment by mackworth** [comment]
You probably got it off of Google Code; it had an older version there.  And no, you should be ok with 10.8.5  .  If the auto-update isn't working, just download the latest version manually:

https://github.com/dscottbuch/cTiVo/releases/download/2.4.0beta7/cTiVo.zip

**Comment by scottiep** [comment]
thanks mackworth--I'm sure that is it.
