### ISSUE TITLE
List of shows on TIVO is zero

### ISSUE THREAD

**Issue by wdannhauser** [dscottbuch/cTiVo#104]
Hi,

I'm a new cTivo user and have been experimenting with it in the latest Yosemite release (10.10.3) on a Mac Mini Late 2012.  I'm using cTivo 2.3.1.  

I have 2 Tivos and I successfully connected to them both, viewed the list of the shows available on both Tivos and successfully downloaded programs from both Tivos on prior days.

Today, when I looked at the listing of shows for one of the Tivos they were gone:  The main window on top displayed no shows and the number of shows listed in next to the Tivo in the "Filter Tivo" window was "0".  The second Tivo still finds and lists the shows.  In the Preferences/Tivos window, both Tivos are identified and checked.

I've "refreshed" the Tivo, I've open and closed the app, rebooted, disabled and then enabled the Tivo in preferences. None of these steps has resolved the issue.

I can still access the shows on the offending Tivo directly and from my second Tivo.  It's just in cTivo that I'm having trouble.

Any help would be appreciated.

Thanks!

(FYI -- I tried to use screen prints, but can't seem to make that work)

**Comment by mackworth** [comment]
Hi, can you disable the other one,  set the debug level to Verbose, quit the program and run it again (to see it from the launch)?  Then post the log somewhere and post the URL here.  Thanks

**Comment by wdannhauser** [comment]
I've done this, but I can't find the log.  I looked in Drive:Library/Logs but there is no cTivo folder nor anything there that was created tonight.

**Comment by mackworth** [comment]
Oh, sorry; I forgot that I added the "Show Logs" menu item to the beta version, not in 2.3.1

Easiest is `Finder > Cmd_G > ~/Library/Logs/cTiVo`

**Comment by wdannhauser** [comment]
Thanks.  Here you go...

https://www.dropbox.com/s/4ueeur5hiwkth4v/log-B3A9B1.txt?dl=0

**Comment by mackworth** [comment]
Not sure, but you might be having a mDNS problem.  Can you create a manual TiVo with address 192.168.1.103, and default 80/443 ports and see what happens?

**Comment by wdannhauser** [comment]
How do I do that?

**Comment by wdannhauser** [comment]
never mind -- i found it -- remote tivo, right?  Should I create it, turn off the offending tiro, open and close the app and send the log?

**Comment by wdannhauser** [comment]
It's pulling shows, but from the other Tivo, not the one I'm having trouble with...

**Comment by mackworth** [comment]
Oh, sorry, I must have misread it.  change it to 192.168.1.104

**Comment by wdannhauser** [comment]
Nothing shows up with the latest IP address...

**Comment by mackworth** [comment]
Ah, that's too bad.  I don't think it'll fix it, but you could try the latest beta, it did have some changes in this area, and it would definitely give me better log information. It's here:  https://github.com/dscottbuch/cTiVo/releases/tag/v2.4.0-Beta8

**Comment by wdannhauser** [comment]
Any other ideas (e.g. reboot tivo, reboot network, etc.)?  It is a bit strange that it had the shows earlier and now they don't show.

Also, I don't know if this is relevant, but I downloaded and installed this current version before I upgraded to Yosemite -- maybe a clean install?

**Comment by wdannhauser** [comment]
Downloaded the beta and ran it.  I also removed the offending Tivo in preferences (it was my aim to start over)  I also removed the other and the manual (I think).  When I closed and opened it, the "good tivo" was there along with the manual Tivo, but the offending Tivo isn't there -- not sure how to get it back.

The manual tivo still has no shows.  Here is the log:
https://www.dropbox.com/s/ccfmvx5z2t15de7/com.cTiVo.cTiVo%202015-05-22%2001-11.log?dl=0

**Comment by mackworth** [comment]
The Bonjour based "offending" TiVo won't show up as long as there is a manual TiVo with the same address.  (Assuming it was working, it would be bad to treat one TiVo as two). So to get it back, just delete the manual one (in cTiVo).  Hmm, reading the code, you may need to re-enter the program at that point. 

FYI, since Mavericks, just editing a Preferences file doesn't work, unless you then restart the preferences daemon to invalidate the cached copy.

You've definitely got some sort of networking address issue.  Two questions: do you have a lot of Apple gear (e.g. airport express, Apple TV)?  Do you have problems with MyMacintosh  adding a (n) at the end of its name?

I'm concerned that it's saying there are two addresses for each TiVo, even though they are the same. Do you have two networks connected to this Mac (e.g. are both Ethernet and WiFi connected)?   

Can you run Network Utiltity>Netstat > Display Routing Table > (Netstat button) and paste in the results here?

**Comment by wdannhauser** [comment]
First, thanks for your help -- I really appreciate both the insight and responsiveness!!

Now, regarding your questions above, now I can associate a possible catalyst for the issue.  As I was exploring Yosemite and trying to get the "Hand-off" function working with my iPhone, I turned on my wireless networking on my mac, along with my existing ethernet connection.  I believe that the first time I looked at cTivo after doing that was when one of the Tivos no longer displayed shows.

Also, I do have my iPhone (and soon iPad) successfully connected using the "hand off" feature.  I have an AppleTV connected via Ethernet.  We have a common old Mac Mini connected by ethernet.  My wife has a MacBookPro connected via wireless.  I think that is it for Apple products.  I have a PS4 and both Tivos connected by ethernet.  I have a wireless HP printer connected via wireless. Those are my main devices on my network (from my mental inventory).

Now, I turned off the wireless, deleted the manual Tivo and rebooted and there is no change -- the Tivo still has no shows in the list.

Here is the Netstat output you requested.  Of course, since I changed my network setup, these results may, perhaps, be out of synch with the logs.  So, let me know if you want me to turn back on the wireless on my mac for consistency:

Routing tables

Internet:
Destination        Gateway            Flags        Refs      Use   Netif Expire
default            openrg.home        UGSc           87        0     en0
127                localhost          UCS             0        0     lo0
localhost          localhost          UH              1     1060     lo0
169.254            link#4             UCS             0        0     en0
192.168.1          link#4             UCS             6        0     en0
192.168.1.1/32     link#4             UCS             2        0     en0
www.routerlogin.ne c4:4:15:3c:a0:44   UHLWIir        90      280     en0   1183
iphone.home        80:be:5:33:c7:50   UHLWI           0      525     en0    748
mac-mini-lr.home   0:16:cb:a5:f0:9d   UHLWI           0        0     en0   1131
mac.home           10:9a:dd:47:1f:b2  UHLWI           0        0     en0   1131
tivo-6520101806bf3 0:11:d9:25:d:58    UHLWI           0      970     en0    536
tivo-652000180584b 0:11:d9:d:f5:40    UHLWI           0       41     en0    588
192.168.1.121/32   link#4             UCS             1        0     en0
192.168.1.255      ff:ff:ff:ff:ff:ff  UHLWbI          0       49     en0

Internet6:
Destination        Gateway            Flags         Netif Expire
localhost          localhost          UHL             lo0
fe80::%lo0         fe80::1%lo0        UcI             lo0
fe80::1%lo0        link#1             UHLI            lo0
fe80::%en0         link#4             UCI             en0
fe80::8b7:474f:8d4 58:55:ca:30:83:11  UHLWI           en0
fe80::aa20:66ff:fe a8:20:66:29:16:b0  UHLI            lo0
ff01::%lo0         localhost          UmCI            lo0
ff01::%en0         link#4             UmCI            en0
ff01::%en1         link#5             UmCI            en1
ff02::%lo0         localhost          UmCI            lo0
ff02::%en0         link#4             UmCI            en0
ff02::%en1         link#5             UmCI            en1

**Comment by mackworth** [comment]
Ok, well, hmm.  To recap what we've got: your TiVo is correctly being found on the network, we then send it a message, and nothing is coming back, not even a request for authentication. As you've rebooted the TiVo, presumably it's not even getting the message in the first place. And yet, you've tried accessing it from the browser from that same machine and gotten a response. So something in the internal routing is going wrong. 

Let me double-check that when you click on this link: [Your tivo URL](https://DVR-4BE1.local./TiVoConnect?Command=QueryContainer&Container=%252FNowPlaying&Recurse=Yes&AnchorOffset=0&ItemCount=15) in your browser, that you get an list of shows (albeit in rather dense text, and probably after a password request (user: "tivo";  password: your MAK)).

Assuming that's the case, let's keep the wifi off for a bit, and if you don't mind a rather annoying process, I'd like to reset your Bonjour state. More info here: [Plugging leaks](http://www.imore.com/still-plugging-leaks-os-x-yosemite-boat-problem-discoveryd)

So, as Bonjour is peer-to-peer routing, so if the routing info is damaged, rebooting a device just recovers the bad info from another one. So, what this involves is simultaneously shutting down everything that participates and then restarting them. That way all the data is fresh. I can't guarantee it'll fix it, but it might, and it might resolve other issues (e.g. Continuity might work better).  

So, the drill is to basically go around and shut everything down (not just sleep), including router/cable modem, wifi access, macs, phones, tablets, TiVos, and especially the AppleTV. Now luxuriate for a few moments in the blessed tranquility of being totally disconnected from the electronic world.  When you're done with that moment of zen, turn them all back on, starting with the cable modem, then router (if separate), then wifi (if separate), then each device. Having had to do this a couple times at home now, I know how annoying this request is, but I really need to separate out if this is the problem.

Then do another netstat and give me the results. Also, if you can go into Terminal and type `ping -c 2 192.168.1.255` followed by `arp -a` and give me the results, and finally start cTiVo to check and to generate the log one more time.

**Comment by wdannhauser** [comment]
I can appreciate that sometimes you just have to get everything shut down and started up again to clear out the garbage that accumulates over time.  I do have a tendency to start up and keep running quite a bunch of things until they overload.

As for the "your tiro URL" link above - clicking on it never got to a result -- it hung up and timed out (Safari can't establish a secure connection to the server).

By the way, I haven't yet rebooted the Tivo -- it is a bit funky and sometimes takes 3 or 4 tries before it fully works -- I think the WD Hard Drive and or internal HD are on the way out.  So, I don't know if I should try rebooting that one first or just go ahead and start over with a clean refresh of the network.  What do you think?

**Comment by mackworth** [comment]
Ah, I misread your original note; when you said rebooted, I thought you meant the TiVo. 

So the internal file server could simply be down, and rebooting it definitely may fix it, so my leaning would be to do that first, as that's the easiest fix, but if not, you'll have to reboot it twice. 

Which level TiVo do you have? If you've got lifetime service on the TiVo, then replacing/upgrading the internal drive may be worthwhile,  [http://weaknees.com]

And if you do [this TiVo link](https://192.168.1.104/TiVoConnect?Command=QueryContainer&Container=%252FNowPlaying&Recurse=Yes&AnchorOffset=0&ItemCount=15)?

**Comment by wdannhauser** [comment]
I have the original HD Tivo.  That's part of why I'm trying to get cTivo working so I can get some of the stuff off the Tivo in case it's done.

I'm on the monthly plan for these tivos - lifetime to a very old and unused series 2....

The latest link also hangs.  So, I'll go ahead and reboot the Tivo -- see if that corrects the issue.  If not, I'll do the whole network and report back.  Again, thanks!!

**Comment by mackworth** [comment]
Just a thought, before rebooting, do you want to try to copy shows over the network direct to your other TiVo (and that would also test the file server question)?

**Comment by wdannhauser** [comment]
Sure -- I'll copy one over just to see how that works...

**Comment by wdannhauser** [comment]
Problem solved!

I tried to copy over a program from the offending Tivo to the other and it hung up that Tivo, so clearly the other Tivo was just not playing well.

So, I rebooted both and now I can see shows in the list from both.

I appreciate all of your help.  It's a real privilege to be able to work directly with the developer to troubleshoot issues and I appreciate your time!

I will certainly keep in mind the advice on the apple devices and probably will clean up my network from time-to-time.

Since I have the beta installed, I'll keep using that and see how that works.

Again, thank you for all of your help -- you can mark this "closed"!

Regards,
Bill

**Comment by mackworth** [comment]
Glad to hear it.  Especially in the older TiVos the file server process is quite fragile.  You know that TiVo often has lifetime transfer deals, where you could move that subscription to a new device. Might be worth calling them.

**Comment by wdannhauser** [comment]
I will.  Thanks.
