### ISSUE TITLE
Is there a way to not compress the audio with MPEG-2?

### ISSUE THREAD

**Issue by tomhayes-sd** [dscottbuch/cTiVo#107]
I use to use iTivo with the Decrypt-only option to download the full file with the audio intact.

I can not see a way to do this with cTivo, event the MPEG-2 and Decrypted Tivo options compress the audio to an mpeg-2.

I'm archiving files that have Dolby Digital soundtracks (The Tomnight Show.)

Is there a  way to grab the full file and do no post processing on it with cTivo?

**Comment by mackworth** [comment]
Actually, the "Decrypted TiVo Show" format does no processing at all. The "encoder" (normally handbrake or mencoder) in this case, it is "cat2file", (as you can see in Edit>Formats) which consists of writing the file we get from the TiVo to disk (after removing the encryption, which doesn't even change the byte count).

Just to confirm, I downloaded a random Simpson episode in Decrypted format, and in the Finder it shows:
````
Dimensions: 1280 x 720
Codecs: MPEG-2 Video, AC3
Duration: 29:57
Audio Channels: 6
`````
and  QuickTime Player adds the details of: `AC3 48000Hz, 5.1 (L C R Ls Rs LFE)`

So, I'm pretty sure that it brings it over unchanged. Are you certain the Tonight show is in Dolby Digital. Now a different question is which of the Formats will preserve the 5+1 channel format. I confess, I don't really know the answer to that. IIRC the Handbrake ones may pass that through (creating both a stereo and a 5.1 channel), but I don't know.

**Comment by tomhayes-sd** [comment]
mackworth:

You know I can't select Decrypted Tivo Show from the format, and I accidentally did a MPEG-2 HD.

"Decrypted Tivo Show" does not show up in the Video Format pulldown, and if I go into the Preferences > Formats and select it all the options are grayed out. Changing the "Hide n User Interface" has no visible effect either.

I think I'm missing the "cat2file" encoder. I'm new to this, so I just downloaded Version 2.4.0b10 (544) and nothing else. (From https://github.com/dscottbuch/cTiVo/releases)

Do I need to have Handbrake installed? or some other components/encoders that we're part of the ZIP download?"

**Comment by mackworth** [comment]
Ah, that...

Yes, and 99.9999% of the time they are.

Version 9 had a new crashing bug, so yesterday I released v10 quickly before finishing my regression tests, but on finishing them last night, I noticed that cat2file and elgato scripts were broken. 

So, you managed to get it on an embarrassing day.

v11 will be out shortly.

ps Nice work on rebuilding it.  Just FYI, cat2File is over in Resources

**Comment by tomhayes-sd** [comment]
Mackworth,

This was the very first time I downloaded cTivo (just heard about it at TivoCommunity) so I didn't realize that there were missing files. And Github sometimes is confusing - some download links point to one thing, while similarly labeled links point to other things. 

But its free for me, and you're investing a lot of time to it so I am not complaining in the least - I was just confused.

It downloaded the show last night and it's perfect this morning. 

I'll do the "check for updates" thing and keep installing the new betas.

Thanks for helping.

**Comment by mackworth** [comment]
I'm actually not using the updating mechanism for betas, but this round is ending shortly anyways. I believe I finally isolated a really annoying Yosemite bug, so I want to get it out. 

Sorry to "greet" you with a broken release. Beta 11 is available now, so it should fix your problem.  

If you'd like to experiment with the other formats (esp handbrake) to figure out how to maintain the 5+1 through the encoders, I'd love to get the results.

**Comment by tomhayes-sd** [comment]
My workflow is just to simply grab them form the Tivo and do no processing at all on them. They get copied on a hard drive, then archived.

I never use handbrake or re-encode them.

The program's been working great for the last two weeks, much more reliable than iTivo was.
