### ISSUE TITLE
arguments for title creation

### ISSUE THREAD

**Issue by peteeaston** [dscottbuch/cTiVo#108]
It would be great if we could pick arguments for the titles of the shows downloaded or at lease have it create a hierarchy of folders for seasons.

otherwise this is an amazing app

Pete

**Comment by mackworth** [comment]
Could you elaborate or give example of "pick arguments for the titles"?

**Comment by mackworth** [comment]
To be a little less abrupt, the reason for my question is `Filename Templates` in Advanced Preferences. Using a template, you can name your files however you like.  (See [here for more info](https://github.com/dscottbuch/cTiVo/blob/ver2.4/wiki/Advanced-Topics.md#filename-templates)). 

To quote an example from the wiki, a template of

`[mainTitle / "Season " season / mainTitle " - " seriesEpNumber " - " episodeTitle]["Movies"  / mainTitle " (" movieYear ")"]`

will create a folder for each show, with a subfolder for each season, then each show named appropriately e.g. `The Big Bang Theory / Season 07 / The Big Bang Theory - S07E01 - The Hofstadter Insufficiency.mp4`

while your movies are put into a separate folder and named with the title and year: `Movies / Machete (2010)`

**Comment by mackworth** [comment]
Hi, Pete; did this work for you?
