### ISSUE TITLE
Recommendations for editing Tivo recordings

### ISSUE THREAD

**Issue by Rendiggy** [dscottbuch/cTiVo#111]
I've managed to download a decrypted Tivo show, and am looking to trim the beginning and ends of the video. I managed to transfer a recording from Starz (Whiplash) and the recording has some Starz promos I want to trim at both ends o the video. I know that cTivo has a feature to remove commercials, from regular recordings, too. I haven't had the opportunity to try that yet, but I can imagine that there would be times it doesn't trim the commercials out perfectly, so I'd also like the capability to edit those trimmings, if needed. I think I used to use VideoReDo on my PC, which did the job very well, but there doesn't seem to be a version for Mac. If anyone can recommend software (preferably free), I'd greatly appreciate it!

**Comment by mackworth** [comment]
Probably easiest for your described purpose might be [MPEG Streamclip](http://www.squared5.com). It has a simple UI for selecting a range and including it or not, then when you're done, it rewrites the whole file quite quickly.

**Comment by mackworth** [comment]
I'll assume that worked for you; if not, pls reopen.
