### ISSUE TITLE
Not all recordings showing up

### ISSUE THREAD

**Issue by MrBendel** [dscottbuch/cTiVo#112]
There are recordings that I can view / play through my TiVo box, but they don't show up in cTiVo. Do some files have restrictions that don't allow them to be transferred?

**Comment by mackworth** [comment]
Exactly; cable providers can mark certain shows as copy-protected, e.g. HBO shows, or in the case of Time-Warner, just about all of them. You can see these in cTiVo by with the `Options>Show Protected Shows` menu option.
