### ISSUE TITLE
Ability to Watch cTivo uploaded shows on a Tivo Roamio

### ISSUE THREAD

**Issue by ChasM19** [dscottbuch/cTiVo#113]
Does cTivo have the ability to watch previously made cTivo recordings using the Tivo GUI in a similar manner to Tivo Desktop?

By the way the SW update link is broken and returns this message:
"An error occurred while downloading the update. Please try again later."

Charles

**Comment by mackworth** [comment]
Sort of.  If you right-click on a program that has been downloaded (you can tell because they will be bold-faced), you should get the option of Play this video. It will actually launch it in Quicktime player (or whatever your favorite player is configured to be).

Sorry to hear about the update link. Which version are you running?

**Comment by ChasM19** [comment]
From what you say, cTivo cannot support a GUI interface on a Tivo to allow you to view a show using the Roamio Tivo GUi's, as was the case in Tivo Desktop.  With Tivo Desktop, the iMac with its recordings uploaded from the Tivo showed up as a device under the My Shows or list of Devices.   Too bad, as it was very convenient and you did not have to worry about changing to a different video source.  Not all is lost, as I can now pull the cTivo recordings and add it the to iTunes library and then watch it on Apple TV using a QuickTime video format.

My computer runs OS X 10.10.3 with Parallels supporting a windows 7 Windows 7 Virtual machine.  I used to run Tivo Desktop in the Windows 7 VM.  I want to progressively transition from Windows which is why I changed from Tivo Desktop to cTivo.

My version of cTivo is Version 2.1 (439).  Selecting Check for Updates results in a new update 2.2, but the update link appears to be broken.

I notice that there may be several sources for this program.  What is the URL for the updates to cTivo?

**Comment by mackworth** [comment]
Ah, sending a show back to TiVo.  Yes, you can do that using pyTiVo. It's a little tricky to install, but after you do, if you enable the pytivo option for a recording in cTiVo, we record all the metadata in a parallel text file for it, and then you simply point pyTiVo at the directories where you store your video. Then pyTiVo pretends to be a TiVo so other tiVos can pull the shows over.

the googlecode one is old and broken and version 2.1 is very old. 

The latest beta (which is quite stable) is here:
https://github.com/dscottbuch/cTiVo/releases/tag/2.4.0-beta11

**Comment by ChasM19** [comment]
Thank you very much for the info.  I will download the latest version of
cTivo from the website you gave me.  Perhaps sometime I will try pyTivo.

From:  Hugh Mackworth <notifications@github.com>
Reply-To:  dscottbuch/cTiVo
<reply+00c727d8cfb92f7a8092335199721d28bf925f21c77bd2f092cf0000000111a479929
2a169ce056c91fb@reply.github.com>
Date:  Thursday, June 25, 2015 at 9:23 PM
To:  dscottbuch/cTiVo <cTiVo@noreply.github.com>
Cc:  Charles Mortimer <cpu_mortimer@charter.net>
Subject:  Re: [cTiVo] Ability to Watch cTivo uploaded shows on a Tivo Roamio
(#113)


Ah, sending a show back to TiVo.  Yes, you can do that using pyTiVo. It's a
little tricky to install, but after you do, if you enable the pytivo option
for a recording in cTiVo, we record all the metadata in a parallel text file
for it, and then you simply point pyTiVo at the directories where you store
your video. Then pyTiVo pretends to be a TiVo so other tiVos can pull the
shows over.

the googlecode one is old and broken and version 2.1 is very old.

The latest beta (which is quite stable) is here:
https://github.com/dscottbuch/cTiVo/releases/tag/2.4.0-beta11


Reply to this email directly or view it on GitHub
<https://github.com/dscottbuch/cTiVo/issues/113#issuecomment-115465069> .

**Comment by ChasM19** [comment]
Thank you so much for helping me earlier.  I am now a regular user of cTivo
and it does a fantastic job especially when associated with iTunes and Apple
TV.

However, I have noticed a very annoying problem.  From time to time it seems
to forget the location of the download folder.  I like to use a folder
location on my QNAP NAS since it has plenty of capacity.  This causes shows
to be downloaded to an apparent default at User/myname/movies/Tivo.

After defining the folder location, how do I lock this location so it does
not change unless I make the change.  I am defining the folder location in
the Main Window at the top right region ­ "Download Folder:" .

I am currently using version 2.4.0 (547) which seems very stable.
Thanks for a great product.

Charles Mortimer

From:  Hugh Mackworth <notifications@github.com>
Reply-To:  dscottbuch/cTiVo
<reply+00c727d8cfb92f7a8092335199721d28bf925f21c77bd2f092cf0000000111a479929
2a169ce056c91fb@reply.github.com>
Date:  Thursday, June 25, 2015 at 9:23 PM
To:  dscottbuch/cTiVo <cTiVo@noreply.github.com>
Cc:  Charles Mortimer <cpu_mortimer@charter.net>
Subject:  Re: [cTiVo] Ability to Watch cTivo uploaded shows on a Tivo Roamio
(#113)


Ah, sending a show back to TiVo.  Yes, you can do that using pyTiVo. It's a
little tricky to install, but after you do, if you enable the pytivo option
for a recording in cTiVo, we record all the metadata in a parallel text file
for it, and then you simply point pyTiVo at the directories where you store
your video. Then pyTiVo pretends to be a TiVo so other tiVos can pull the
shows over.

the googlecode one is old and broken and version 2.1 is very old.

The latest beta (which is quite stable) is here:
https://github.com/dscottbuch/cTiVo/releases/tag/2.4.0-beta11


Reply to this email directly or view it on GitHub
<https://github.com/dscottbuch/cTiVo/issues/113#issuecomment-115465069> .

**Comment by mackworth** [comment]
Glad to hear it's working well for you.  

On the particular issue, when cTiVo can't open the current download directory, it switches back to the default one as you describe. My guess is that from time to time, the OS and your NAS aren't talking to each other, e.g. network disconnect or waking from sleep, or other reasons.  (Somewhat related, this is exacerbated by a problem in the OS, when you disconnect an external drive, it frequently doesn't forget the old name, and so when you reconnect it, it adds a 1, making our old name useless.)

Not quite sure how to make this better; remember all we know at the time we're about to do a download is that the directory you've asked for isn't available right now.  

If we just put up an error message and ask for a new location, then it would interfere with unattended downloads. If we use the default for the current download, but switch back automatically to the original location when it becomes available again, then how do we signal that we used the default one for some files? Suggestions?

**Comment by ChasM19** [comment]
Thank you very much for your answer explaining the cause to the problem.  I
tend to agree with you since from time to time my Acronis backup to the NAS
seems to fail for not being able to access the NAS.  Most of the time the
Mac has gone to sleep and perhaps the handshakes are going un recognized.
The NAS also goes to sleep and requires some time to fully wakeup all RAID 5
drives. 

Perhaps a warning message that the original location has been changed to the
default is all that is required to draw attention to the change to the
intended download folder.  This may only be a problem for subscriptions that
are largely unattended.

By the way, can cTivo perform subscription recording it it not open or
minimized?  In other words does it check the Tivo without being opened?

Charles

From:  Hugh Mackworth <notifications@github.com>
Reply-To:  dscottbuch/cTiVo
<reply+00c727d822748f7589dd0e94c0d18d9868ce6d031abc91f692cf000000011212af4a9
2a169ce056c91fb@reply.github.com>
Date:  Thursday, September 17, 2015 at 11:41 AM
To:  dscottbuch/cTiVo <cTiVo@noreply.github.com>
Cc:  Charles Mortimer <cpu_mortimer@charter.net>
Subject:  Re: [cTiVo] Ability to Watch cTivo uploaded shows on a Tivo Roamio
(#113)


Glad to hear it's working well for you.

On the particular issue, when cTiVo can't open the current download
directory, it switches back to the default one as you describe. My guess is
that from time to time, the OS and your NAS aren't talking to each other,
e.g. network disconnect or waking from sleep, or other reasons.  (Somewhat
related, this is exacerbated by a problem in the OS, when you disconnect an
external drive, it frequently doesn't forget the old name, and so when you
reconnect it, it adds a 1, making our old name useless.)

Not quite sure how to make this better; remember all we know at the time
we're about to do a download is that the directory you've asked for isn't
available right now.

If we just put up an error message and ask for a new location, then it would
interfere with unattended downloads. If we use the default for the current
download, but switch back automatically to the original location when it
becomes available again, then how do we signal that we used the default one
for some files? Suggestions?


Reply to this email directly or view it on GitHub
<https://github.com/dscottbuch/cTiVo/issues/113#issuecomment-141143784> .

**Comment by mackworth** [comment]
It does need to be running, although it can be minimized, or you can even just close the main window entirely. (You can get it back later by clicking the cTiVo icon in the dock, then Window>Main Window.)

**Comment by ChasM19** [comment]
Thank you

From:  Hugh Mackworth <notifications@github.com>
Reply-To:  dscottbuch/cTiVo
<reply+00c727d8c504663e32c33afe153aae8e01800ae285b7691792cf000000011212ec4a9
2a169ce056c91fb@reply.github.com>
Date:  Thursday, September 17, 2015 at 4:02 PM
To:  dscottbuch/cTiVo <cTiVo@noreply.github.com>
Cc:  Charles Mortimer <cpu_mortimer@charter.net>
Subject:  Re: [cTiVo] Ability to Watch cTivo uploaded shows on a Tivo Roamio
(#113)


It does need to be running, although it can be minimized, or you can even
just close the main window entirely. (You can get it back later by clicking
the cTiVo icon in the dock, then Window>Main Window.)


Reply to this email directly or view it on GitHub
<https://github.com/dscottbuch/cTiVo/issues/113#issuecomment-141227472> .
