### ISSUE TITLE
Shows not showing up in Ctivo

### ISSUE THREAD

**Issue by flyinnc2fl** [dscottbuch/cTiVo#114]
i downloaded this program several months ago and it worked perfectly. i recently moved. at my new place it loaded up perfectly and i was able to download shows. last week i went to open ctivo to download a new show and nothing shows up in my Que.! I thought i needed to refresh my tivo so i deleted it, but when i tried to re-add it i couldn't. i went thru a manual add with IP address but now in the elect tivo drop down it still has the old name and now new name i was using yet both have (0) next to it even though i have about 7 shows in my shows on my tivo.

i can't figure out what happened to make all my shows disappear in ctivo! and i can't figure out how to fix it!

**Comment by mackworth** [comment]
Well, the most obvious would be if you're not displaying Protected shows or Suggestions (see `Options` menu), and all seven of the shows happen to be one of those. 

If that's not it, set your `Debug Level` to` Verbose`, and `Reload (Cmd-R)`, then use the `Help>Show logs in Finder` and open the latest log. It will show you exactly the list of shows being sent over from your TiVo (search for `Data received is`).

**Comment by mackworth** [comment]
Did that help?

**Comment by flyinnc2fl** [comment]
My TiVo had actually lost its streaming feature. I noticed when I couldn't access my shows list on my TiVo mini in another room. Once I reset my Romeo it worked on all devices and showed up in cTiVo.

**Comment by mackworth** [comment]
Good to hear. Let me know if you have any problems or suggestions!
