### ISSUE TITLE
Running on El Capitan Public Beta

### ISSUE THREAD

**Issue by stopcollaboratelisten** [dscottbuch/cTiVo#117]
Hey, I am not sure how else to communicate this to you guys, but I am running El Cap Public Beta 2 and cTivo is working well! Of course, this is the first time I have opened it in a couple weeks.

I did have a question, and maybe someone knows the answer. A Google search does not produce useful results. Every show recorded on Disney Channel on my father in law's Tivo is listed as Copyright protected after 7/10/2015. There is a gap between the 10th and 14th, when the Tivo did not record anything from that channel, so it could have started anywhere in the middle of those dates. Before, nothing on the Disney channel was copy-protected, but now, shows recorded on Disney channel are marked with C in cTivo. Does anyone know if Disney changed their copyright rules to cover this channel?

Also, maybe I should state that this is the HD version of the Disney channel. Maybe I will tell it to record something on the non-HD version. Also, my FIL says that the Tivo is humming loudly (probably the fan), so they will probably replace it, which means I have to try and reconfigure cTivo and my SlingBox from a foreign country! Yay for me!

**Comment by mackworth** [comment]
Haven't heard anything, but the copy-protect bit is set by your cable company; so they may have changed their policy. Which company is it? Time warner is famous for setting it on all kinds of channels.

**Comment by stopcollaboratelisten** [comment]
It is mediacom, a Midwest company.
