### ISSUE TITLE
wine + windows comskip

### ISSUE THREAD

**Issue by ryanchild** [dscottbuch/cTiVo#119]
I was surprised when the bundled comskip executable wasn't able to find any commercials in the first TV show I tried.  So I did a bit of research and found out that people generally have much better success running the windows executable under wine.  So I did a `brew install wine` and replaced the bundled comskip executable with this script:

```tcsh
#!/bin/tcsh

set cmd = "/usr/local/bin/wine /usr/local/bin/comskip.exe"
set ini = $1
shift
set cmd = "$cmd $ini `echo $*:q | sed 's/ /\\ /g'`"
echo $cmd
eval $cmd
```

and voila, commercials found and skipped.  This is a bit hacky though.  If I can make a suggestion for a future enhancement maybe you could provide an option to use wine + windows comskip instead of the native one.  Of course you'd want to search for wine or ask for the path to the wine binary rather than bundling it.

**Comment by mackworth** [comment]
Another user figured out how to compile the latest version for under Windows, so 2.5 should have a much better version of comskip. Let me know if it doesn't work for you.
