### ISSUE TITLE
Download marked as finished only with audio

### ISSUE THREAD

**Issue by EvilHidden** [dscottbuch/cTiVo#120]
1 particular series for me. All others seem to be ok. Download fails on any number of presets, including just decryption. Transfer results in 174.2 MB file consistently across all episodes. Only audio in the file. File downloads fine using the built in TiVo webserver. Wired connection. Mac OS 10.10.5 Log file below

http://pastebin.com/DAuerN9u

**Comment by mackworth** [comment]
Just to confirm, this same episode does correctly downloads as a 3.2GB file from web UI? That's very interesting. You can see from the logs that ctivo notices the discrepancy, but it's being told by the system that it is a complete transfer:
> Show Boston Legal: An Eye for an Eye (TiVo Name) supposed to be 3,261,071,360 bytes, actually 174,049,382 bytes

 Can you confirm the same is true [from this URL in your browser?](http://192.168.1.119:80/download/Boston%20Legal.TiVo?Container=%2FNowPlaying&id=33614) 

If it does work, then if you're comfortable in Terminal, could you try the following command (note you'll need to replace YOURMAK with your MAK)?

````
cd ~/Desktop
curl --digest -k -u tivo:YOURMAK --cookie-jar cookies.txt -o test.tivo   http://192.168.1.119:80/download/Boston%20Legal.TiVo?Container=%2FNowPlaying&id=33614

**Comment by EvilHidden** [comment]
Yes, confirmed the webgui download is fine. For all episodes in this series, not just this particular episode. I'll try the terminal command later today. Thanks for the feedback.

**Comment by mackworth** [comment]
Can you click on the phrase "from this URL in your Browser" above, just to make sure I'm not missing something?

**Comment by EvilHidden** [comment]
Not on my home network at the moment. As soon as I'm able.

**Comment by EvilHidden** [comment]
Clicking your URL hyperlink results in the same 174MB file download in the .tivo wrapper. The terminal command results in 41 byte test.tivo file.

**Comment by mackworth** [comment]
Ah, thank you. That's exactly it. TS streams are not supported by tivodecode, which is necessary to decrypt the files coming over from the TiVo. 

So, I don't know why your TiVo is munging the PS stream, but that's the one we need to read.  Sorry. 
If you have a Windows machine, there are workarounds on that platform, but AFAIK none on Mac.  

FYI:
http://en.wikipedia.org/wiki/MPEG_transport_stream
http://en.wikipedia.org/wiki/MPEG_program_stream
