### ISSUE TITLE
Conversion only for previously downloaded .tivo files?

### ISSUE THREAD

**Issue by zrossnige** [dscottbuch/cTiVo#121]
I REALLY like this piece of software!!

Any chance that your software is able to import local .tivo files (rather than pulling from the TiVo "Now Playing" list) for conversion?

I have several dozen .tivo files that were extracted then deleted from the TiVo device using their ridiculous TiVo Desktop application, it would be great if I could "feed" these local files to cTiVo for conversion.

Is this possible?

**Comment by mackworth** [comment]
I've never gotten around to that, as it's a pretty limited use case.  You can decrypt them with tivodecode and then they're just mpeg2 files that you can either view directly or convert with any video processing programs.  

So assuming they're in a directory and 
have a .TiVo ending (capitalization matters) and 
have no weird characters in the file name (else rename) and 
you have enough disk space to essentially duplicate all the files, then
1) drag that directory (not the files) onto the Terminal icon. 
That will open a Terminal session "in" that directory.
2)Then you can type the following 
(best to copy/paste this into TextEdit, add your MAK and then copy/ paste into Terminal)
````
for file in *.TiVo
do
   /Applications/cTiVo.app/Contents/MacOS/tivodecode --mak YOURMAKHERE -o "${file%.TiVo}.mpg" "$file"
done

**Comment by zrossnige** [comment]
Mate - you are an ABSOLUTE star!    Thank you!!

**Comment by mackworth** [comment]
So I take it that worked for you?
