### ISSUE TITLE
Confusion about Manual Tivos

### ISSUE THREAD

**Issue by aft-luke** [dscottbuch/cTiVo#122]
Hey there, I have quick question for you:

In the Manual Tivo documentation you want us to expose two ports for a remote tivo, but also two IPs. I don't understand why the need for two IPs... is this a typo? Wouldn't we want normal and ssl traffic mapping to the same tivo?

>1) Tell DHCP to start assigning addresses at 192.168.1.11
1) Tell your TiVo to use fixed IP Address 192.168.1.10
1) Tell your router to map external port 3000 to 192.168.1.10:80, and port 3001 to 192.168.1.11:443
1) Tell cTiVo to create a Manual TiVo named Remote using an IP address of 12.34.45.56, Port:3000 and PortSSL:3001

**Comment by mackworth** [comment]
You're correct. The router line, second IP should be .10 also.  Will fix.
