### ISSUE TITLE
Remote Tivo ip:port errors?

### ISSUE THREAD

**Issue by aft-luke** [dscottbuch/cTiVo#123]
I'm trying to figure out why I can nmap verify the correct `<public ip>:<port, ssl port>` configurations, and load my remote Tivo's list of downloaded items, but cannot download any recording?

If I dig into the logs it's almost as if cTiVo is misconfiguring an ip address when looking for a download. If my public IP were `12.345.678.910`, this would be the error message I am getting.

```shell
"A server with the specified hostname could not be found.", NSErrorFailingURLStringKey=http://12.345.678.5849:5849/download/Ari%20Shaffir%20Paid%20Regular.TiVo?Container=%2FNowPlaying&id=167662
```

Notice something strange here `http://12.345.678.5849:5849/download`? It looks like the last 3 digits in my public IP are getting replaced with the port I have opened to passthrough to my internal tivo ip. Say what?

**Comment by aft-luke** [comment]
Strangely enough, I can actually navigate to `https://<public ip>:<exposed ssl port>` and I will be served the /nowplaying/index.html, with (incorrect) download links to my recordings. The download links take me to `<public ip>:/download/<filename>.TiVo?Container=%2FNowPlaying&id=167663&Format=video/x-tivo-mpeg` ... where in order to properly download the recording I need to go to `<public ip>:<exposed port>/download/...` but this will download only 1 small chunk of my recording (around 900mb). Any ideas?

**Comment by mackworth** [comment]
Do the last three digits have an 80 or 443 in them? If so, that's the problem. I've looked through the code and I see a problem: It is replacing all the 80s and 443s with the port number, not the last one. I have an update coming up, I'll include this fix in it.

**Comment by aft-luke** [comment]
Yea, just so happens there's an 80 in the ip. Those darned corner cases, eh?

**Comment by mackworth** [comment]
Yup, that particular line of code was written almost three years ago, with nary a complaint since then!

Thanks for letting me know (and about the 11 typo in docs)

**Comment by mackworth** [comment]
Here's a pre-release of the beta just for you. I'd love to confirm that it fixes the problem.  https://dl.dropboxusercontent.com/u/21507587/cTiVo.zip

**Comment by aft-luke** [comment]
:+1:

**Comment by mackworth** [comment]
Thanks. I've now posted it as the 2.4.1 beta. Same file you already downloaded.
