### ISSUE TITLE
Convert Existing .Tivo files (not on Tivo)

### ISSUE THREAD

**Issue by kstella** [dscottbuch/cTiVo#124]
Can cTivo be used to decrypt .Tivo files from a local drive volume? 

I downloaded many files with web browser or other apps in years past. Tivo (Roamio Plus) no longer supports Toast/vice versa.

I notice Decripted Tivo are downloading as MPG
I notice cTiVo doesn't see the .Tivo files in the directory used for it's download files.
I notice I can still download .Tivo via web browser right from Tivo, one at a time, in two formats.
I hope someday it can push the files UP to Tivo.

**Comment by mackworth** [comment]
We do decrypt the .tivo files as we pull them over from the tivo, which makes them .mpg files. We don't currently convert .Tivo files already on disk, but there is a workaround in Terminal:  

This script looks at the cTivo temp directory, finds any .tivo files, decrypts them and then uses mencoder to convert them.  You have to supply your MAK for your tivo, and you can steal the `<<VIDEO, AUDIO, OTHER Options>>` part from Edit>Edit Formats for your favorite ctivo format (assuming it's mencoder-based). Tip: You can duplicate a built-in format to enable copy/paste.  

```
cd /tmp/ctivo
for file in *.tivo
do
	filename="${file%.*}"
	echo "Processing $filename.tivo"
	/Applications/cTiVo.app/Contents/Resources/tivodecode -m<<MAKHERE>>  $filename.tivo |  /Applications/cTiVo.app/Contents/Resources/mencoder <<VIDEO, AUDIO, OTHER Options>> -- -o %filename.mpg
done
```

Possible changes for above:
If you've got .TiVo files in another directories, you could remove the first line, and just drag the folder onto the Terminal icon in the doc. This opens a Terminal window already in that folder. Then run the rest of the script.
If you just want to decrypt the files, you could delete everything after the "|" character (including it), and replace it with `>> %filename.mpg`

PyTiVo handles the pushing the files up to TiVo. If you're going to a TiVo with the same MAK, I don't think you need to decrypt them first.

**Comment by kstella** [comment]
Cool! Many Thanks.
Now to figure out where I stored the entire collected works of Monty Python and FireFly/Serenity.

**Comment by NoahBuddy** [comment]
I don't suppose there's any standalone apps for those of us that are intimidated by Terminal….?

**Comment by mortax** [comment]
i wrote a ton of scripts to do exactly that. they aren't finished yet - hopefully during/after the holidays. i'm happy to share them when they're ready for public scrutiny.

note that i created my scripts to manipulate, transcode, and enhance the raw decoded tivo videos for use with a plex server.

**Comment by kstella** [comment]
look forward to checking this out!

**Comment by mackworth** [comment]
While looking forward to seeing what mortax will deliver, here's a simple automator script that you can just drop files on, it will ask you for your MAK, and then create decrypted versions of those files in the same directory. No error checking, metadata, or transcoding etc. It assumes you have a copy of cTiVo in your Applications directory. Note that tivo video files are huge and you will double the file space, so be careful not to run out of space.

[tivodecode.zip](https://github.com/dscottbuch/cTiVo/files/69130/tivodecode.zip)

**Comment by debjanimohapatraer** [comment]
iDealshare VideoGo works great to convert .tivo files to any other video format like mp4, avi, wmv, mpg, mov, etc.
Here is the easy guide https://www.idealshare.net/video-converter/tivo-to-mp4-converter-mac-windows.html
