### ISSUE TITLE
2.4.2 beta issues

### ISSUE THREAD

**Issue by mackworth** [dscottbuch/cTiVo#126]
Please let me know here if you have any problems with this beta, or if it's working well for you.

**Comment by gregzw** [comment]
All attempted downloads try a couple times then show "Failed".  Occasionally I see what looks like a progress indicator above the queue header that only shows for a second or two then disappears.

**Comment by gregzw** [comment]
Here is the screen capture showing the progress just before it starts over or show as "failed".


<img width="1288" alt="screen shot 2015-10-23 at 4 58 20 pm" src="https://cloud.githubusercontent.com/assets/2493729/10705934/901121ee-79a7-11e5-93f1-9f0a7826b612.png">

**Comment by mackworth** [comment]
I note the 91 bytes per second, which is absurdly low. Could you be having network problems?  Alternatively, try rebooting the TiVo. Also if you use 'Help>show log files', the recent logs will give more information about what failed.

**Comment by gregzw** [comment]
Rebooting the Tivo solved the problem.  Thanks.  (MacBook Pro, OS X 10.11.1, Tivo Premiere XL)On Oct 23, 2015, at 5:58 PM, Hugh Mackworth <notifications@github.com> wrote:I note the 91 bytes per second, which is absurdly low. Could you be having network problems?  Alternatively, try rebooting the TiVo. Also if you use 'Help>show log files', the recent logs will give more information about what failed. —Reply to this email directly or view it on GitHub.

**Comment by mackworth** [comment]
Glad to hear it.  Hope it does well for you!

**Comment by mackworth** [comment]
2.4.2 is now final.

**Comment by pho-tron** [comment]
Having this same problem with "Failed," even after seeing the formatted file appeariing where I intended, then disappearing.  cTIVO downloads are running about 1MBs on my 1000Gb LAN, whereas transfers to iMac using outdated TIVO Transfer work much faster. Have rebooted TIVO but no change. cTIVO screen shot attached.
![screen shot 2015-11-01 at 10 26 31 am](https://cloud.githubusercontent.com/assets/15590963/10871851/8e21f5f6-80b0-11e5-8dcd-59e80e9aae6d.png)

**Comment by mackworth** [comment]
Sorry, not quite understanding. I'm hearing two different issues (1) that you're getting Failures even though the file looks like it's complete and (2) that the transfers are slow, correct?

On (1), I'll need to see the logs (Help>Show log files and then attach the recent one(s)). Note that you'll have to rename to `.txt` for GitHub to allow them to be attached.  The screen shot doesn't show a failure, so does it happen at the beginning of a transfer, or after it finishes? I see one complete one there, so how often does it fail?

On (2), depending more on which TiVo you have, a megabyte per second is about right. It's not constrained by network speed, but by TiVo's encryption/transmission speed. I'm surprised that TiVo Desktop was faster; what sort of speed were you seeing then?

**Comment by pho-tron** [comment]
On Sun, Nov 1, 2015 at 5:11 PM, Hugh Mackworth <notifications@github.com>
wrote:

> Sorry, not quite understanding. I'm hearing two different issues (1) that
> you're getting Failures even though the file looks like it's complete and
> (2) that the transfers are slow, correct?
>
​Yes on both accounts.

> On (1), I'll need to see the logs (Help>Show log files and then attach the
> recent one(s)). Note that you'll have to rename to .txt for GitHub to
> allow them to be attached. The screen shot doesn't show a failure, so does
> it happen at the beginning of a transfer, or after it finishes? I see one
> complete one there, so how often does it fail?
>

​L​
og file attached
 showing the failures, which occur at the end of the Encoding phase.  I see
a mp4 file being built, with sizes going to GB, but then it disappears.​


> On (2), depending more on which TiVo you have, a megabyte per second is
> about right. It's not constrained by network speed, but by TiVo's
> encryption/transmission speed. I'm surprised that TiVo Desktop was faster;
> what sort of speed were you seeing then?
>
​L​
ike you say TIVO encry/trans​ is slow.  I didn't measure the speed w
Desktop for the encrypted files, just started it and did something else,
but it did finish much faster (non-quantitative).
​

I saw another post about using cTIVO to decrypt TIVO files that I have
moved to my iMac, but haven't tried it as yet as have no experience in
coding (other than Fortran in the ​last millennia.)

​Thanks for the reply.​

**Comment by mackworth** [comment]
Unfortunately, attachments get stripped out from email. You can either open a completely new issue (then Github will let you attach a file, although you'll need to change the extension to `.log.txt`), OR post it somewhere else (like DropBox) and paste a link into your email.

**Comment by pho-tron** [comment]
2nd attempt to get log uploaded.

![20151101_ctivo log](https://cloud.githubusercontent.com/assets/15590963/10899816/e8c47d04-8195-11e5-8cee-9dad4b7b3c25.png)

**Comment by mackworth** [comment]
So it looks like you're having networks issues, with your TiVo going offline every couple hours. Which version of the Mac OS are you using?  Do you have an Airport Express?  Can you increase the log level to Major inPreferences and try it again?  (Pasting in text to the main comment will work.

**Comment by pho-tron** [comment]
OS 10.10.5 
No on Airport Express
Will incr log Pref to Major, retry, and upload.
Again, file downloads, starts Encoding, file shows up in Download Folder, cTIVO window says Complete, but file disappears at end of process.  Seems not be network problem but TIVO authorities/permissions deny cTIVO file to remain.

**Comment by mackworth** [comment]
@pho-tron I'm closing this particular issue as it was specific to 2.4.2.

 Please create a new issue, and post the log there (you might try 2.4.3, but I don't think it'll fix it.) Best would be to set the log level to Detail and post it on another service (like DropBox), and then post a link here.
