### ISSUE TITLE
"Plex Folders" template doesn't work with date-based shows

### ISSUE THREAD

**Issue by treyharris** [dscottbuch/cTiVo#127]
The template `[MainTitle / "Season " Season / MainTitle " - " SeriesEpNumber " - " EpisodeTitle]["Movies"  / MainTitle " (" MovieYear ")"]` unfortunately doesn't work with date-based shows (such as news or late night). According to [this article](https://support.plex.tv/hc/en-us/articles/200381053-Naming-Date-based-TV-Shows), such shows should be in the format `TV Shows/Show_Name/Season XX/Show_Name - YYYY-MM-DD.ext`. That led me to think that perhaps this would work (since many date-based shows don't have `Season`, I used `year`, which Plex seems happy with):

```
["TV Shows" / mainTitle / "Season " season / mainTitle " - " SeriesEpNumber " - " episodeTitle]["TV Shows" / mainTitle / year / mainTitle " - " originalAirDate]["Movies" / mainTitle " (" movieYear ")"]
```

Unfortunately, while that _does_ make the date-based shows come out right, the "normal" episode-based shows come out completely wrong, like `TV Shows/The Big Bang Theory/Season 7/The Big Bang Theory - S07E01 - The Hofstadter InsufficiencyTV Shows/ The Big Bang Theory/2013/The Big Bang Theory - 2013-09-26.mp4`. Since the way this seems to work is by supplying a field that the types of shows you don't want to match _won't have_, and scripted shows seem to have a strict superset of the fields that date-based shows have, there's no way to have part of the template operate only on date-based shows and not on other types of shows, too.

Is this a feature request, or am I missing an obvious tweak?

**Comment by mackworth** [comment]
Great question (thank you for the experimentation), and I don't see an obvious answer. TheTVDB appears to be down now, so I'll experiment some tomorrow.

**Comment by mackworth** [comment]
So, that's quite the rabbit hole you sent me down! 

Yes, it's impossible with the current options to do that, so I added a OR option to allow `[SeriesEpNumber] | [originalAirDate]`. Great, then I realized that if `episodeTitle` was blank, then it would erase the entire filename, so I added a recursive option `[... MainTitle " - " `[SeriesEpNumber] | [originalAirDate] [" - " EpisodeTitle]]`, so it only adds the dash and title if it's available.  Great, but then I needed to test it more, so I added a `Test on Selected Shows` command to the keyword menu that will apply the current pattern to all selected shows, so one can quickly check whether the pattern works or not. Then, assuming this new macro works, I needed to upgrade the older ones (which are stored in user preferences).

Then in further testing, I realized that I had never really cared much about non-episodic shows and hadn't really tested them much. I noticed that they weren't getting artwork, so fixed that. Then I realized that would fix another problem on regular shows when TVDB disagrees with TiVo on originalAirDate, I could still add series artwork, so added that. Then, I noticed that TiVo gives some non-episodic shows spurious season/episode info, so stripped those out.  

Meanwhile, TVDB was going up and down over the last couple days, which had the silver lining of letting me add some better diagnostics to the log

Anyways, please give 2.4.3 alpha1 a try and see if it works for you. As you've edited the default Plex string, just reselect the `• Plex Folders` keyword to get the new format. You can then apply it to any selected shows (or all of them if none selected) using the `Test on SelectedShows` command (in the keyword menu). Make sure all those look good.  Then try a few with Plex and let me know how it goes.

https://dl.dropboxusercontent.com/u/21507587/cTiVo.zip

**Comment by mackworth** [comment]
Note, if you try this release and (for whatever reason) go back to 2.4.2, then be sure to change or just clear out your Filename template field in Advanced Preferences, as the new filename format is incompatible with the older version.

**Comment by treyharris** [comment]
Hey, thanks for all the hard work on this, it's appreciated! I've been traveling and unable to test until now, and it looks like that Dropbox link is gone now. I tried to build it from commit 65b5e8a9f35943b6c33885fa86a6be7dec211f2f, which was the one where you mentioned the change, by checking out the `SHProcessing` branch, but it complained about `Fabric.h` not being installed, so I created a fabric.io account and tried to follow the instructions, but I got as far as it telling me to install a run script build phase the Fabric app gave me a command line for, which I did, but it's still complaining about `Crashlytics/Crashlytics.h` not found.

At this point I'm several steps out of my depth since I don't do Mac development, so hopefully you can give me a hint on how to build cTiVo successfully? Or restore the Dropbox link? :-)

**Comment by mackworth** [comment]
No problem on delay, and yes, building from scratch is a bit of a pain. I updated the mainline, and added those changes to this version as well, which I'm now calling 2.5. 

I'm away from my Mac, but I think it's at https://dl.dropboxusercontent.com/u/21507587/cTiVo%202.5%20alpha1.zip

**Comment by mackworth** [comment]
Did that location work for you?

**Comment by mackworth** [comment]
Also, re building for personal use, if you still want to... I would just strip out the crashlytics/fabric, as that's more about remote reporting. Should be just (1) remove the frameworks entirely, (2) the runScript phase, and (3) the relevant beginning lines in applicationDidFinishLaunching. Nothing else depends on those being available.

**Comment by treyharris** [comment]
Awesome, the option works perfectly, though the default string you get by selecting `• Plex Folders` is wrong, it should be:
```
["TV Shows" / MainTitle / "Season " Season | Year / MainTitle " - " SeriesEpNumber | OriginalAirDate [" - " EpisodeTitle]]["Movies"  / MainTitle " (" MovieYear ")"]
```

I've submitted PR #139.

**Comment by mackworth** [comment]
Agreed.  What do you think of putting the Guests in if there's no episode title? This would make certain interview shows etc more obvious.

```
["TV Shows" / MainTitle / "Season " Season | Year / MainTitle " - " SeriesEpNumber | OriginalAirDate [" - " EpisodeTitle | Guests ]]["Movies"  / MainTitle " (" MovieYear ")"]
```

**Comment by mackworth** [comment]
So I merged your PR as well as adding Guests and another keyword ExtraEpisode.  
See this issue for some discussion; I'd love your thoughts. 
https://github.com/dscottbuch/cTiVo/issues/140

https://dl.dropboxusercontent.com/u/21507587/cTiVo%202.5%20alpha2.zip
