### ISSUE TITLE
"Last Recorded" date for Subscriptions?

### ISSUE THREAD

**Issue by djdonohu** [dscottbuch/cTiVo#128]
So, loving cTivo 2.4.1 so far! Running under OS X 10.11and pulling from a TiVo Premiere. But unless I'm doing something wrong, it seems like the Last Recorded field under subscriptions is showing the date the subscription was created and is not updating it. The subscription itself is working, shows are being downloaded, converted, and are showing up in iTunes automatically, but the date never reflects that. Or am I not understanding what that information is supposed to mean?

**Comment by mackworth** [comment]
You're correct; there is a visual problem. The date is being tracked, but just not updating real-time in the table. If you quit cTiVo and come back in (or if you have enough subscriptions to  drag them out of view and back), the subscription will show you the correct time. I've fixed, but it'll be in the next version (not 2.4.2 which is just finishing beta).

**Comment by mackworth** [comment]
Changed my mind, and slipped the fix into 2.4.2, which I just posted. Check it out.
