### ISSUE TITLE
Bolt Not Showing Up

### ISSUE THREAD

**Issue by StevenMR** [dscottbuch/cTiVo#129]
I recently replaced my Premier with a new Bolt. c/Tivo worked great with the Premier, but the Bolt is not showing up in the list of Tivos. Enable Video Downloads is activated on the Tivo website for the Bolt. I deleted the Premier from the "Edit Tivos" list but the Bolt doesn't appear. If I click add button I get a listing for generic Tivo Named with no IP address. What am I doing wrong?

**Comment by mackworth** [comment]
So it definitely should show up automatically. (The Edit TiVo command is for when you want to access remotely, or have unusual networking situations.)  in fact, it's odd that the premiere was in your list. Do you remember having to add it? Are you sure the Mac is on the same network/wifi as your TiVo?

If it is, then you should download and run a program called "Bonjour Browser". It will give you a list of all the devices that your Mac sees announcing themselves in the network. 

If it sees the TiVo, then I can give you a few more steps to figure it out. If not, then something is off in your network structure (and I'll have a different set of suggestions).

**Comment by StevenMR** [comment]
Now Bolt appears at the top of the c/Tivo window but shows no contents. I've confirmed that the Bolt and Mac are on the same wifi network. I'm not sure how to read the Bonjour Browser window but have included a screenshot.
![screen shot 2015-10-31 at 11 51 29 am](https://cloud.githubusercontent.com/assets/13458105/10865374/a41a94ca-7fc6-11e5-8c31-2f565143aa84.png)
![screen shot 2015-10-31 at 11 56 55 am](https://cloud.githubusercontent.com/assets/13458105/10865376/a47b8866-7fc6-11e5-8ea2-dd6dc401fa63.png)

**Comment by mackworth** [comment]
Well, you see the various _tivo listings, then you can expand the disclosure triangle to see whether the Bolt specifically is showing up, and what its IP address is. You could then see the Now Playing list directly from the Bolt. Nonetheless, now that it's showing up in cTiVo, we can move on!

Next would be to look at the ctivo logs to see if it's giving you an error message. Just use Help>Show logs in Finder and open the most recent one.  If nothing is obviously wrong, I'd suggest setting the debug level to Detail in Preferences, quitting cTiVo and starting it again. Then post the result, and it should give me a clue as to why you're not seeing any shows.

**Comment by StevenMR** [comment]
OK, Here's a screenshot of the expanded Bonjour Browser Tivo entries and I'm attaching the most recent ctivo log - I don't know how to identify errors.

**Comment by StevenMR** [comment]
Oops, I can't attach the log file. Here's a screen shot of all the most recent activity I can capture.
![screen shot 2015-10-31 at 12 33 02 pm](https://cloud.githubusercontent.com/assets/13458105/10865567/3e2a393a-7fcc-11e5-8022-33a266aa11c2.png)

**Comment by StevenMR** [comment]
![screen shot 2015-10-31 at 12 37 21 pm](https://cloud.githubusercontent.com/assets/13458105/10865569/4c45a73e-7fcc-11e5-8445-38d1100742fc.png)

**Comment by mackworth** [comment]
So, we're trying to load the list of shows at `https://dvr-a33.local./TiVoConnect?Command=QueryContainer&Container=%252FNowPlaying&Recurse=Yes&AnchorOffset=0&ItemCount=15`  (btw, text would be better than a graphic image, so I don't have to retype all that!)  and getting a failure. Usually this is due to a mDNSResponder failure. Which version of the Mac OS are you using?

The workaround would be to create a manual TiVo entry with IP address 10.0.0.21 (as shown in Bonjour Browser). This will avoid the name conversion from `dvr-a33.local.` to `10.0.0.21`. But if your TiVo ever changes its number on the local address it will drop off, and you'll have to "find" it again.

So if the workaround works, then either upgrading your OS, or shutting off all your Apple devices  (especially the Airport) and then turning them all back on will probably let it find it again, and you can disable the workaround

**Comment by StevenMR** [comment]
That worked! I created the manual entry and saw 2 listings for the bolt in city. Then shut down and restarted my Airport and iMac and city is seeing only one listing for the Bolt and lists its contents.
Thanks much!

**Comment by mackworth** [comment]
Great to hear. Which version of the OS are you using?  They replaced the problematic discovered with the older mDNSResponder in 10.10.4 and later.

**Comment by StevenMR** [comment]
I'm running 10.10.5

**Comment by mackworth** [comment]
Thanks. Well, do let me know if it recurs. It's possible that you had a corrupted bonjour database in your Airport (the devices all share) that was affecting your Mac whenever it booted up.  Also, wasn't clear from your response, did you turn off the manual one now?
