### ISSUE TITLE
What to do with .tivo files?

### ISSUE THREAD

**Issue by bgerson** [dscottbuch/cTiVo#13]
In the event that cTiVo can't process a show, I download it directly from the TiVo box.  At that point, what is recommended to convert the .tivo file to an .mp4 file which can be imported into iTunes or played on another device?  It seems that the typical converters don't make any difference over changing the file extension.

I would rather not use Toast to do the conversion as they constrain the resolution of the resulting file.

Thank you,

Bruce

**Comment by aimkeepachieve** [comment]
I highly recommend iDealshare VideoGo which can convert Tivo to MP4, MOV with high video and audio quality on Mac for QuickTime, iTunes, iPad, iPod, iPhone, Apple TV, iMovie etc

Step by step guide at http://www.idealshare.net/video-converter/tivo-to-mp4-converter-mac-windows.html


In fact, it also helps to convert Tivo to MOV, DV, ProRes, AVI, 3GP, WMV, FLV, MPG, VOB, RMVB etc on Mac or Windows

**Comment by KKImmiK** [comment]
In order to convert TIVO, first you need to keep is the Media Access Key. [Bigasoft Total Video Converter](http://www.bigasoft.com/total-video-converter.html) is able to convert TIVO to any other formats on Mac and Windows PC. 
![Bigasoft total video converter tivo convert](http://www.bigasoft.com/images/articles/tivo-converter/tivo-video-converter.jpg)

**Comment by impetusdirection** [comment]
To convert TiVo files to MP4, AVI, MOV, MKV, MPG, etc without quality loss, you may try this easy method from http://www.idealshare.net/video-converter/tivo-to-mp4-converter-mac-windows.html

I love its batch conversion and also convert Tivo video files to any video format or even audio format.
It has both Mac and Windows version.
It can convert Tivo videos with HD video quality.
Why not have a try?

**Comment by debjanimohapatraer** [comment]
iDealshare VideoGo 7 is also recommended to convert tivo files to mp4, mov, mpg, avi, wmv, mkv, vob etc.
Here is the easy guide https://www.idealshare.net/video-converter/tivo-to-mp4-converter-mac-windows.html

**Comment by davidharneyhi** [comment]
Here is another method to convert TiVo to MP4, AVI, MPG, MOV, Apple ProRes https://www.avdshare.com/tivo-to-mp4-mov-converter

**Comment by greatlucklucky** [comment]
iDealshare VideoGo can convert .tivo tiles to mp4, mov, avi, mkv, mpg, apple prores if you have the media access key.
