### ISSUE TITLE
Suggestion if practical: cTivo app running directly on the new Apple TV 4

### ISSUE THREAD

**Issue by githubdave** [dscottbuch/cTiVo#130]
Now that the new Apple TV 4 can run apps, it would be really convenient to have cTivo run directly on the Apple TV to transfer and play one's Tivo recordings.

I do not have one of the newer Tivos with the built-in capability to Airplay content to the Apple TV.

I don't believe it is worthwhile to invest anymore in Tivo technology like their extra streaming device for this purpose --   my guess is that Tivo will become a dead end technology or morph into something like an Apple TV.

Thank you....Dave

**Comment by mackworth** [comment]
Not a bad idea, but as there's no real storage in even the new AppleTVs, you're still going to want to convert shows on the (faster processor) Mac and store them there, probably in iTunes in this case (or in Plex). Once that's done, then it's really easy to stream with either system to the AppleTV for live viewing.
