### ISSUE TITLE
Not a bug: Documentation Suggestion

### ISSUE THREAD

**Issue by SteveDavidson** [dscottbuch/cTiVo#132]
In the version notes, it says, "cTiVo is fully compatible with OS X Mavericks (10.9), Mountain Lion (10.8), and Lion (10.7); not compatible with Snow Leopard or earlier."

It is silent on the subject of compatibility with Yosemite (10.10) -- which I know to be the case -- or "El Capitan" (10.11).  I was looking for information on compatibility with the latter (prior to taking the plunge), and that's why I noticed the omission.

Great software, BTW.

**Comment by mackworth** [comment]
Thanks; yes, no problem with El Cap either.
