### ISSUE TITLE
Tito Bolt

### ISSUE THREAD

**Issue by armyguy2989** [dscottbuch/cTiVo#135]
Got the new Tivo Bolt and can't get the cTivo program for my mac to work i know it worked on the Tivo Q system

**Comment by mackworth** [comment]
Sorry to hear that.  What are the symptoms? (Not running at all or is the Bolt now showing up on the screen?)  What does the log say? (Help>Show logs in finder and double-click on latest one.)

**Comment by armyguy2989** [comment]
Never mind i had to manually add it works great now

**Comment by mackworth** [comment]
So that still shouldn't be the case. Which version of the Mac OS are you running? Do you have Apple's airport router (express or extreme)?
