### ISSUE TITLE
Plex support for multiple episodes in a single recording

### ISSUE THREAD

**Issue by mortax** [dscottbuch/cTiVo#140]
the proper format for a recording that contains multiple episodes is:

TV Shows/Show_Name/Season XX/ShowName - sXXeYY-eZZ.ext

where YY is the first episode and ZZ is the second. thus, the show:

Extant: You Say You Want an Evolution; The Other (episodes 6 and 7)

should be:

TV Shows/Extant/Season 02/Extant - S02E06-E07 - You Say You Want an Evolution; The Other.mpg

unfortunately, it doesn't look like the TiVo provides the metadata for cTiVo to know that a given recording is two episodes. that said, you could add an option that let's you do ask for automatic labeling for multi-episode recording based on the following:

1. knowing the standard running time for an episode. i have no problem setting that myself, per show, but i also suspect that that data exists somewhere.
2. when a recording is N times the normal running length, count the show as episode X, X+N.

i can think of a few ways to do this. knowing whether shows are fixed (e.g. The Good Wide) or variable duration (e.g. Fargo, American Horror Story, Tyrant) would be helpful. cTiVo could find episodes that are 'exactly' N times the normal running length and contain the appropriate number of semicolons in the title. this would require rounding to allow for a 1:59 or 2:02 show too be two episodes but a 1:14, 1:30 etc. shows to be a single episode. presence of a semicolon can also be used. the user could even be given the ability to tune this.

additionally, cTiVo could look to see if the next recorded episode is X+2. (and possible adjust file naming accordingly).

just a few thoughts.

**Comment by mackworth** [comment]
I've been trying to avoid keeping any long-term series information, but a potential compromise would be to have an extraEpisode keyword, which would have a value (e.g. E07) iff there's a SxxExx number and (the show is 2 hours (+- 5 minutes) OR if there's a semicolon).  How would that be?

**Comment by mackworth** [comment]
So here's an experimental version. It creates that "extraEpisode" keyword, so you can see if it would help with your existing shows.  My personal results were out of 770 shows, there were 19 that it correctly worked for (almost all kid shows), 7 where it marked it as two episode when it wasn't (e.g. Bastard Executioner, which is considered a two hour episode with two names separated by semcolon). and 14 where TiVo had the wrong number for the base show (again, all kid shows). 

So what happens in Plex if we incorrectly mark it as two episodes?

To test on your system, in Advanced Preferences, put the following string into the Filename Template field: `[SeriesEpNumber]["-" ExtraEpisode]` Then do the `Keywords>Test on Selected Shows` command. For convenience, when you use the ExtraEpisode keyword, this version will ONLY report a filename if there's something in that keyword. 

To try it with a real show for conversion, use the following template:
`["TV Shows" / MainTitle / "Season " Season | Year / MainTitle " - " SeriesEpNumber | OriginalAirDate ["-" ExtraEpisode] [" - " EpisodeTitle]]["Movies"  / MainTitle " (" MovieYear ")"]`

**Comment by mortax** [comment]
sorry. was out of pocket for a few days. i hope to try this out tonight and will let you know.

**Comment by mortax** [comment]
okie dokie. i gave the new version a try and it correctly generated filenames for double episode shows. awesome! is it based on the two-hour heuristic and/or the presence of a semicolon you mentioned in your first comment? i ask because the new version worked for both double 30 minutes shows (total length of an hour) as well as double hour shows (total length of two hours). i'm also pretty sure it didn't incorrectly name a show that happened to have a semicolon in the title.

**Comment by mackworth** [comment]
Nope. the algorithm is simply we'll show an "extra episode value" iff show Length is between 115 and 125 minutes OR it has a semicolon in the title.

**Comment by mortax** [comment]
very interesting. as it happens, this version of cTiVo worked for all of my double episode shows, including half hour shows that were just over an hour and one shows that were two hours (or just under):

media:tv jrd$ find . -name '* - S[0-9][0-9]E[0-9][0-9]-E[0-9][0-9] - *.mpg' -exec ls -l {} \; -exec show {} \;
-rw-r--r--@ 1 jrd  staff  8011161126 Nov 11 09:35 ./Extant/Season 02/Extant - S02E06-E07 - You Say You Want an Evolution; The Other.mpg
S02E06 02:00:01 You Say You Want an Evolution; The Other
S02E07 02:00:01 You Say You Want an Evolution; The Other
-rw-r--r--@ 1 jrd  staff  8424940502 Nov 11 11:44 ./Extant/Season 02/Extant - S02E12-E13 - Double Vision; The Greater Good.mpg
S02E12 01:59:01 Double Vision; The Greater Good
S02E13 01:59:01 Double Vision; The Greater Good
-rw-r--r--@ 1 jrd  staff  3550914085 Nov 11 19:21 ./Galavant/Season 01/Galavant - S01E01-E02 - Pilot; Joust Friends.mpg
S01E01 01:01:00 Pilot; Joust Friends
S01E02 01:01:00 Pilot; Joust Friends
-rw-r--r--@ 1 jrd  staff  3627309430 Nov 11 21:21 ./Galavant/Season 01/Galavant - S01E03-E04 - Two Balls; Comedy Gold.mpg
S01E03 01:00:59 Two Balls; Comedy Gold
S01E04 01:00:59 Two Balls; Comedy Gold
-rw-r--r--@ 1 jrd  staff  3298315333 Nov 11 21:38 ./Galavant/Season 01/Galavant - S01E05-E06 - Completely Mad ... Alena; Dungeons and Dragon Lady.mpg
S01E05 01:01:00 Completely Mad ... Alena; Dungeons and Dragon Lady
S01E06 01:01:00 Completely Mad ... Alena; Dungeons and Dragon Lady
-rw-r--r--@ 1 jrd  staff  3432032055 Nov 11 21:55 ./Galavant/Season 01/Galavant - S01E07-E08 - My Cousin Izzy; It's All in the Executions.mpg
S01E07 01:00:58 My Cousin Izzy; It's All in the Executions
S01E08 01:00:58 My Cousin Izzy; It's All in the Executions
-rw-r--r--@ 1 jrd  staff  6519255572 Nov 13 04:29 ./TURN: Washington's Spies/Season 02/TURN- Washington's Spies - S02E01-E02 - Thoughts of a Free Man; Hard Boiled.mpg
S02E01 02:00:01 Thoughts of a Free Man; Hard Boiled
S02E02 02:00:01 Thoughts of a Free Man; Hard Boiled

it also correct identified an hour long show, with a semicolon, as a single show.

-rw-r--r--@ 1 jrd  staff  4958355238 Nov 14 01:01 ./Crossroads/Season 10/Crossroads - S10E07 - Mumford & Sons; Emmylou Harris.mpg
S10E07 01:00:01 Mumford & Sons; Emmylou Harris

i assume it would fail on a two single show with a semicolon. luckily, i don't have any of those (yet).
