### ISSUE TITLE
Commercial marking and skipping

### ISSUE THREAD

**Issue by mortax** [dscottbuch/cTiVo#141]
i'm using cTiVo 2.5 alpha2 and have the Mark Commercials option selected in preferences. all items in my queue, however, do not have a √ in the Mark column (and have no chapters defined). this leads me to a few questions:

1. is it possible to enable the 'mark commercial' feature? if so, how?
2. can i post-process my existing decoded .mpg files to mark commercials?
3. can i also post-process my existing decoded .mpg files to remove commercials? i want to do this as a separate step because i'd like to have two copies of my shows: one with commercials marked and another with them removed (at least until i have 100% confident in the process).

**Comment by mackworth** [comment]
1) Only certain output file formats have the ability to mark commercials: mp4, m4v, mov, and 3gp
2) there's nothing built-in to do that (or 3), but you could use comskip directly to do so. 

The comskip command line would look like the following (on one line)
`/Applications/cTiVo.app/Contents/MacOS/comskip --ini=/Applications/cTiVo.app/Contents/Resources/comskip.ini    <<input file name>>`
That generates an EDL that you can use with mencoder or ffmpeg to cut out the commercials.

I can pretty much assure you that you won't get to 100% confidence. there's a lot of uncertainty in how it identifies a commercial break, so I personally alway use marking, so it's simple to skip, but when it makes a mistake, it's easy to fix. People that really want 100% will use the EDL and then check it with an MPEG StreamClip or other interactive program.

**Comment by mortax** [comment]
thanks for the information! very helpful. i now have a few followup questions:

1) if i convert my .mpg files to a format compatible with commercial marking, can i also post-process them to mark the commercials? if so, how can i do it?
2) if i use the com skip command you suggest to identify commercials, how can i use the EDL file to act as chapter table of contents?

i'm not looking for anything built in to do the things above. i'll write a few scripts to post-process my files so i have exactly what i need.

**Comment by mackworth** [comment]
So, the reason it's restricted to those formats is that they have the internal "atoms" defined to carry the chapter information. So yes, you could then add that info to those files (which is what ctivo does, after the encoder finishes).  

I think the open source program Subler will let you set Chapter info. I don't know if it will directly import the EDL or not. You could also look at Atomic Parsley. If neither will do it, let me know and I'll see how hard it would be to strip that out of ctivo as a standalone.

**Comment by mortax** [comment]
how does cTiVo 'mark' using the other formats? curious if it's a combination of comskip and then setting the internal atoms. again, i'm just trying to figure out how i can get both the original file (e.g. the .mpg i'm downloading via cTiVo now) and a post-processed file in the right format with chapters defined for viewing via plex. what process does cTiVo use?

**Comment by mackworth** [comment]
Yes, that's what I meant. First, cTiVo runs comskip as a subprocess, creating the EDL. If "skipping", then it hands the EDL to mencoder as part of the conversion process to remove those sections. If marking, it translates the EDL to the MP4 chapter atoms.

**Comment by mortax** [comment]
got it. that's more or less what i thought. last question: how where is the chapter atom format documented and how does cTiVo integrate the atoms into the final file? feel free to direct me to a web page/tool/documentation.

**Comment by mackworth** [comment]
We use a c library called mp4v2, but used to use Atomic Parsley, which can be scripted.  But hold off a bit; I’ve been thinking about adding the option to save the MPG file in addition to the converted file.  No commitment, but let me look at how that might work.

**Comment by mortax** [comment]
understood. it would be super awesome if cTiVo made some of this easier. i'm also a programmer so i'm happy to help implement anything that would be useful (either directly in cTiVo or externally for myself - and others). just let me know how i can help.

**Comment by mrfusiontm** [comment]
One small "skipping commercial" request,  could you save that option as a
preference?  Every time I restart cTiVo I have to remember to check that.

**Comment by mackworth** [comment]
Well, that was an obscure one to find.  It's fixed for the next version. In the meantime, if you launch Terminal and just type:
`defaults write com.ctivo.ctivo SimultaneousEncode NO`
You should be good to go.

**Comment by mortax** [comment]
any update on the whole making question. here's a summary:

1. i want to download a verbatim copy (which i am doing as 'Decrypted TiVo Show').
2. one i have those, i'ld also like to create a second version (of the highest quality/resolution/etc. as possible) that has commercials marked as chapters (but not cut out).

anything cTiVo can do to accomplish my goals would be grand. today, i am automatically downloading the decrypted shows and i am running a post-processing script to generate an EDL file using the bundled comskip program. my only missing link is a way i can generate new versions of the files that adds chapter markers based on the EDL file (after i change the CUT command, 0, to MARK, 2).

thoughts?

**Comment by mortax** [comment]
one more thought/question: it would be awesome if i could download a file in two formats, to two separate l;locations. in my case that would be TiVo decoded file for archiving and another format of my choosing (with commercials marked or skipped) for viewing via plex.

**Comment by gitgoon** [comment]
Im curious what commands you used for mp4v2 to convert the EDL to actual chapter markings? I love cTivo but sometimes it fails to mark the commercials when i do the Handbrake Apple TV setting. I've gotten comskip to work on my mac (OS X El Capitan) via WINE and installed mp4v2 via homebrew but I'm a bit of a newb to all this so wouldn't mind some comments if possible.

**Comment by mackworth** [comment]
Well, it's not actually commands; mp4v2 is a library we include so it's called directly. The Objective-C code used is in MTEdl lines 73-124 ( addAsChaptersToMP4File) after loading it in lines 43-70 (getFromEDLFile).  FYI, @mortax has updated comskip, so the next version will now be much closer to the windows (wine) version.

**Comment by mortax** [comment]
apologies for being out of touch. 

i found the program at http://www.kgarner.com/blog/archives/2010/05/24/addings-chapters-to-an-existing-mp4m4v-file/, which did almost what i wanted. so i modified it to be way more robust (although you do have to link it with mp4v2). then i wrote a script to use that program to add chapter markings to my .mp4 file. it works really well. i'll share all of that in a later post (and try to remember to update this one) when i have time. probably won't be until weekend after this one (20-21 february).

**Comment by tomhoover** [comment]
mortax commented:
> then i wrote a script to use that program to add chapter markings to my .mp4 file. it works really well. i'll share all of that in a later post (and try to remember to update this one) when i have time. probably won't be until weekend after this one (20-21 february).

Did you ever share the completed script?
