### ISSUE TITLE
audio language not set

### ISSUE THREAD

**Issue by mortax** [dscottbuch/cTiVo#144]
when viewing files downloaded as Decrypted TiVo Show, the audio language displays as unset in Plex:

AUDIO Unknown (AC3 5.1)

i haven't tried downloading shows in other formats to see if that works. could cTiVo allow a default language to be set (possibly in preferences)?

as an aside: i've spent a lot of time searching for a simple way for me to tag the AC3 audio track as english, but haven't found anything that works. does anyone know an easy way to do this?

here's sample information for a show:

ffmpeg version 2.8.2 Copyright (c) 2000-2015 the FFmpeg developers
  built with Apple LLVM version 7.0.0 (clang-700.1.76)
  configuration: --disable-yasm
  libavutil      54. 31.100 / 54. 31.100
  libavcodec     56. 60.100 / 56. 60.100
  libavformat    56. 40.101 / 56. 40.101
  libavdevice    56.  4.100 / 56.  4.100
  libavfilter     5. 40.101 /  5. 40.101
  libswscale      3.  1.101 /  3.  1.101
  libswresample   1.  2.101 /  1.  2.101
Input #0, mpeg, from 'The Big Bang Theory - S02E08 - The Lizard-Spock Expansion.mpg':
  Duration: 00:30:01.63, start: 0.464600, bitrate: 11579 kb/s
    Stream #0:0[0x1e0]: Video: mpeg2video (Main), yuv420p(tv, bt709), 1920x1080 [SAR 1:1 DAR 16:9], Closed Captions, max. 38810 kb/s, 29.97 fps, 29.97 tbr, 90k tbn, 59.94 tbc
    Stream #0:1[0x80]: Audio: ac3, 48000 Hz, 5.1(side), fltp, 384 kb/s

**Comment by mortax** [comment]
any ideas?i was hoping this was a simple change/fix.

**Comment by mackworth** [comment]
Sorry, missed this entirely. Have you tried using subler to manually label it?  
On Decrypted shows, we (aka tivodecode) do absolutely nothing except chop off the XML, and remove the decryption. So I don't think there's any way to do that.  You could set up a cTiVo Format with ffmpeg which would just copy the video through, but properly name the audio. IANA ffmpeg expert, so I don't know what that syntax would be.

**Comment by mortax** [comment]
no worries. because i want an entirely batch process (for importing into plex), i’m not going to go down the subler path.

i determined i could set the language for the audio and video using ffmpeg when i convert cTiVo’s .mpg file into a .mp4 file so i can add chapters to mark commercial breaks:

ffmpeg -i "$file".mpg -vcodec copy -acodec copy -f mp4 -metadata:s:v:0 language=$language -metadata:s:a:0 language=$language "$file".mp4

($langauge is eng in my case.)

that will do the trick for now.


john

**Comment by mackworth** [comment]
I like GitHub's emoji substitutions:  :v: for `:v:` and :a: for `:a:` They make ffmpeg commands much more interesting.   (I've tried adding backquotes to your ffmpeg string, but it didn't take).

Are you clear on how to make that into a cTiVo Format?

So.. does that string accomplish the following? A lot of people have asked for a MP4 converter, that would simply re-encode the MP2 without changing the resolution. So it would be much smaller than the MP2, be capable of metadata. And although it would re-encode so there would be some quality lost, it would give the best quality without unnecessarily increasing the file size to a resolution beyond the original. Also the re-encoding should be faster without the scaling.   Again, is that was this does? how does it "copy" but create an mp4?

**Comment by mortax** [comment]
to answer your questions: yes, the command above (and also just sent in another thread) does re-encode the decoded tivo .mpg file as .mp4 at the same resolution. i set the language metadata so plex will recognize it.

the copy happens via the 'copy' codec. give it a while and see what you time in terms of size/quality.

hope that helps. sorry for being slow.
