### ISSUE TITLE
language of subtitles not recognized by Plex

### ISSUE THREAD

**Issue by mortax** [dscottbuch/cTiVo#145]
having the 'Handle Caption' option selected automatically creates .srt files for each download, which is awesome. they show up in flex as a subtitle option but also, unfortunately, as an unknown language (e.g. 'Unknown (SRT)'). if the files are simply named .en.srt, they show up correctly as 'English (SRT)'. any chance you could add a preference set the language/extension/filename pattern for SRT files?

the best solution, of course, would be to detect the subtitling language and name the file appropriately.

**Comment by mortax** [comment]
the same issue appears to be true when the file is encoded for AppleTV:

    Stream #0:0(und): Video: h264 (Constrained Baseline) (avc1 / 0x31637661), yuv420p, 960x544 [SAR 967:960 DAR 967:544], 1995 kb/s, 30 fps, 30 tbr, 30 tbn, 60 tbc (default)
    Metadata:
      creation_time   : 1970-01-01 00:00:00
      handler_name    : VideoHandler
    Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 127 kb/s (default)
    Metadata:
      creation_time   : 1970-01-01 00:00:00
      handler_name    : SoundHandler

interestingly, one of the subtitle tracks seems to be english, the other is undefined:

    Stream #0:3(und): Subtitle: mov_text (text / 0x74786574)
    Metadata:
      creation_time   : 2015-12-05 04:00:37
    Stream #0:4(eng): Subtitle: mov_text (tx3g / 0x67337874), 960x81, 0 kb/s (default)
    Metadata:
      creation_time   : 2015-12-05 04:00:37

**Comment by mackworth** [comment]
So, that's interesting that there are two. After ccextractor runs, we do indeed create one in cTiVo with the atom: mdia.minf.stbl.stsd.tx3g. So that's the last one, and we do default to `eng`.  Maybe mencoder is creating the other one? Have you looked a file that is run without captions? Have you tried deleting Stream 3 and seeing what plex makes of it?

**Comment by mackworth** [comment]
Any further thoughts here?

**Comment by mortax** [comment]
dang. haven't had time to play with this at all. will try to come back to it.

**Comment by mackworth** [comment]
I'll close this for now. Let me know if you have any further thoughts on it. (Does it happen with latest binaries in 2.5 alpha?
