### ISSUE TITLE
upgrade for helper applications

### ISSUE THREAD

**Issue by mortax** [dscottbuch/cTiVo#146]
when i post-process .mpg files with the comskip bundled with cTiVo, it crashes for some files. that lead me to realize that the current bundled version is 0.79.126 (it also includes PowerPC support, which is no longer needed). the latest stable version of comskip is 0.81.089. after compiling the new version and running it against some of the files that crashed the bundled version, it worked. the data also looks a bit better.

any chance you can upgrade to com skip 0.81.089?

**Comment by mackworth** [comment]
Last I looked, all the recent versions didn't support a Mac executable. So you've successfully compiled it?

**Comment by mortax** [comment]
yes, i did. it was a total pain but i got it to work (and it is much nicer). happy to provide details (offline if that's easier or better).

**Comment by dscottbuch** [comment]
Hi All.

Haven’t been contributing lately but have been following.  Congrats on getting it to compile.  To include in cTiVo you’ll need to compile in all static libraries.

I’m assuming this is from the original kaashoek fork and not the kodi fork.  I had played with the kodi fork (up to rev 0.94b) and found it, imperically, inferior which is why the 0.79 is still there.

Scott

**Comment by mortax** [comment]
you are correct that i am using the original kaashoek fork. statically linking the ffmpeg libraries is tricky. will play with it this weekend. stay tuned.

**Comment by dscottbuch** [comment]
Yep. The static linking is what took most of my time the first time :)

D. Scott Buchanan

Sent from my iPhone

This email and any files transmitted with it are confidential and intended solely for the use of the individual or entity to whom they are addressed. If you have received this email in error please notify the system manager

**Comment by mackworth** [comment]
Scott, can you give John any guidance to recreate process?

**Comment by dscottbuch** [comment]
Absolutely. I still have the Xcode project that organized it. I'll find that and let you know. 

D. Scott Buchanan

Sent from my iPhone

This email and any files transmitted with it are confidential and intended solely for the use of the individual or entity to whom they are addressed. If you have received this email in error please notify the system manager

**Comment by dscottbuch** [comment]
Here’s a link to an archive of the static libraries that I used.  I would assume that all, except possibly libargtable2, would still be OK for the current compile.

https://www.dropbox.com/s/y7s7vf3viczpas0/comskipStaticLibs.tar.gz?dl=0

scott

**Comment by mortax** [comment]
thanks. was down to a final two dynamic libraries to remove and had a theory, which seemed to work. i think system libraries should be okay. can you live with this:

$ otool -L comskip
comskip:
	/usr/lib/libiconv.2.dylib (compatibility version 7.0.0, current version 7.0.0)
	/usr/lib/libbz2.1.0.dylib (compatibility version 1.0.0, current version 1.0.5)
	/usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.5)
	/System/Library/Frameworks/QTKit.framework/Versions/A/QTKit (compatibility version 1.0.0, current version 1.0.0)
	/System/Library/Frameworks/Foundation.framework/Versions/C/Foundation (compatibility version 300.0.0, current version 1255.1.0)
	/System/Library/Frameworks/QuartzCore.framework/Versions/A/QuartzCore (compatibility version 1.2.0, current version 1.11.0)
	/System/Library/Frameworks/CoreVideo.framework/Versions/A/CoreVideo (compatibility version 1.2.0, current version 1.5.0)
	/System/Library/Frameworks/AVFoundation.framework/Versions/A/AVFoundation (compatibility version 1.0.0, current version 2.0.0)
	/System/Library/Frameworks/CoreMedia.framework/Versions/A/CoreMedia (compatibility version 1.0.0, current version 1.0.0)
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1255.1.0)
	/System/Library/Frameworks/VideoToolbox.framework/Versions/A/VideoToolbox (compatibility version 1.0.0, current version 1.0.0)
	/System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices (compatibility version 1.0.0, current version 728.4.0)
	/System/Library/Frameworks/VideoDecodeAcceleration.framework/Versions/A/VideoDecodeAcceleration (compatibility version 1.0.0, current version 1.0.0)
	/System/Library/Frameworks/Security.framework/Versions/A/Security (compatibility version 1.0.0, current version 57336.10.29)
	/System/Library/Frameworks/OpenCL.framework/Versions/A/OpenCL (compatibility version 1.0.0, current version 1.0.0)
	/System/Library/Frameworks/CoreGraphics.framework/Versions/A/CoreGraphics (compatibility version 64.0.0, current version 600.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1225.1.1)

let me know. happy to provide it to you for some testing. i’m going to give it a whirl now.


john

**Comment by dscottbuch** [comment]
Looks great.  Was just looking at the svn trunk code and noticed the Makefile for this doesn’t reference any ffmpeg, or other, non-standard libraries.  It looks like the relevant portions of argtable and mpeg2 were directly included.  Am I missing something, or is that correct?

scott

**Comment by mortax** [comment]
interesting. the makefile i have is linking with the avutil, avformat, and avcodec ffmpeg libraries:

gcc -g -O2 -o comskip comskip-comskip.o comskip-mpeg2dec.o comskip-platform.o comskip-video_out_dx.o ccextratorwin/comskip-608.o ccextratorwin/comskip-ccextractor.o ccextratorwin/comskip-encoding.o ccextratorwin/comskip-general_loop.o ccextratorwin/comskip-myth.o -L/usr/local/Cellar/argtable/2.13/lib -largtable2 -L/usr/local/Cellar/ffmpeg/2.8.3/lib -lavutil -lavformat -lavcodec  -lpthread -lm

on a positive note, i just ran the new static comskip i compiled and compared the output with the fully dynamic one i built and it is the same. here’s the version if you want to try it. note: i compiled this on el capitan so not sure if it will run on older macs (but why would you want to? ;-). all my machines are el capitan so i can’t test that.

https://www.dropbox.com/s/47cgsshj2tf2b2p/comskip-0.81.089-static.gz?dl=0


john

**Comment by mackworth** [comment]
This is great! 

Any reason to presume it wouldn’t support older OS's?  We still support all the way back to 10.7 (folks stick old machines in a corner just to do video processing.)

--
Hugh Mackworth
701 Terrace Drive
Lake Oswego, OR
(503) 699-2134

**Comment by dscottbuch** [comment]
This sounds more reasonable.  Just for my curiosity from where did you pull the source code?  I was just looking at svn svn://svn.kaashoek.com.

unfortunately I don’t do much video transfer any more so Hugh will have to test.

**Comment by dscottbuch** [comment]
It should work.  But I also am up to El Capitan on all machines.

**Comment by mortax** [comment]
to be honest, i’m not sure. worst case is that it just has to be build on a machine running 10.7.

**Comment by mortax** [comment]
i grabbed the source via git from git://github.com/erikkaashoek/Comskip.


john

**Comment by mortax** [comment]
the easiest thing to do might be to release a new alpha build including my version of comskip and let users give it a whirl - but that’s obviously your call.

one thing i forgot to mention earlier: of the ~40 mpg files on which comskip crashed, all have worked with the new release so far (only five more to test).


john

**Comment by mackworth** [comment]
Didn't know it was up there. I've tried to get the svn one a few times...

I assume you guys saw this:

You can build a static binary by passing the --enable-static parameter to configure, but beware the following caveats:

True static linking on Mac OS OX is not supported by Apple. You can get close by temporarily removing all .dylib files from /usr/local, leaving their associated .a files behind. See https://dropline.net/2015/10/static-linking-on-mac-os-x/ for more details and a script to automate the process.

Some libraries have incomplete or incorrect dependencies listed in their pkgconfig files. If static linking fails on your system, you'll need to override these by manually specifying the argtable2_LIBS, ffmpeg_LIBS, and sdl_LIBS environment variables with the required list of libraries and their locations.

**Comment by mackworth** [comment]
I will do exactly that this weekend!

**Comment by mortax** [comment]
yes, i did see that, thanks. i tied that option and it didn’t work. that’s also why i selected statically linking the ‘local’ dependencies (e.g. argtable2 and ffmpeg) and leaving the system libraries dynamic. i’m pretty sure that is supported by apple. (i generated my link options by hand.)


john

**Comment by mortax** [comment]
i noticed that ccextractor is also older (0.69 vs 0.77) and that your version of tivodecode, while the same, is larger - partly because it includes powerpc support. i don't even think powerpc is still supported on os x 10.7 so here is a streamlined version of all three executables for your proposed alpha release:

https://www.dropbox.com/s/n1chqc806gvkd6x/ctivo-macos.tgz?dl=0

**Comment by mortax** [comment]
link above updated with new version of:

ccextractor
comskip
mencoder
tivodecode

**Comment by mackworth** [comment]
Well, I haven't had nearly enough time to test these, but I feel like I'm holding up your testing, so here's alpha3 with those embedded:  https://dl.dropboxusercontent.com/u/21507587/cTiVo%202.5%20alpha3.zip

**Comment by mortax** [comment]
thanks. seems fine so far. quick question: the binaries you shipped are slightly different (e.g. not byte for byte) form the ones i posted. just curious what you changed...

**Comment by mackworth** [comment]
Interesting. I downloaded your files, dropped them into Xcode, and generated cTiVo. Maybe the signing process?

--
Hugh Mackworth
hugh@hughm.com
@mackworth
(503) 816-9711

**Comment by mortax** [comment]
ah, right. that makes perfect sense.

i think i've found on small bug with ccextractor. seems it never exists on some files with strange metadata.

should be a simple fix. will work out something this weekend.

**Comment by mackworth** [comment]
If you're interested, the next big issue will be tivodecode. It doesn't support transport stream files. There's a Java equivalent tivolibre that does, but the changes haven't been back ported. See here for more context: http://www.tivocommunity.com/tivo-vb/showthread.php?p=10621316

And tivodecode-ng here:  https://github.com/wmcbrine/tivodecode-ng

**Comment by mortax** [comment]
good news: i was wrong about ccextractor. the version i provided, that you included in alpha 3, doesn't have an issue; it was my mistake. that said, updated my tgz file (at the same link as above) to include a version of ccextractor that uses the system's libz. you should update beta4 with that version (when you get around to it).

i'll have a look at the tivodecode thing when i have time (may be a while).

**Comment by mackworth** [comment]
And they just released 0.78. No indication of what's changed...
http://sourceforge.net/projects/ccextractor/files/ccextractor/0.78/ccextractor.src.0.78.zip/download

**Comment by mortax** [comment]
thanks for the note about ccextractor 0.78. i just updated the binaries at the link above for inclusion in alpha 4.

FYI, i reran it on 300+ .mpg files and all generated captions were the same. still, might as well be current.

**Comment by mackworth** [comment]
Thanks again for this. It's included in the officlal alpha 2.5 release.

**Comment by mackworth** [comment]
Hi, @mortax. in my testing all the different codecs for the next alpha, I ran into two audio problems with the new mencoder binary:

```
MEncoder SVN-r37561 (C) 2000-2015 MPlayer Team
MPlayer was compiled without libmp3lame support.

```
and
```
libavcodec version 57.17.100 (internal)
ADecoder init failed :(
Opening audio decoder: [hwac3] AC3/DTS pass-through S/PDIF
ADecoder init failed :(
Opening audio decoder: [spdif] libavformat/spdifenc audio pass-through decoder.
AUDIO: 48000 Hz, 2 ch, ac3le, 768.0 kbit/50.00% (ratio: 96000->192000)
Selected audio codec: [spdifac3] afm: spdif (libavformat/spdifenc AC-3 pass-through decoder)
[ac3 @ 0x100fa7570]frame sync error
Unknown/missing audio format -> no sound
Requested audio codec family [a52] (afm=liba52) not available.
Enable it at compilation.
AC3/DTS sync failed

```
Could you see if these are easy to enable again?

**Comment by mortax** [comment]
dang. will have a look tonight. stay tuned. 


john

**Comment by mackworth** [comment]
Any thoughts?

**Comment by mackworth** [comment]
Hello, just checking in again.  I want to release the next alpha, but I'll need to either update these or roll them back.

**Comment by mackworth** [comment]
@mortax Last call??

**Comment by mackworth** [comment]
So it appears that comskip now requires VideoToolBox, which was introduced in 10.8....

So unless anyone has a suggestion,  if that's the only issue with 10.7, I'll bundle two comskips for now (the old and the new) and call them appropriately.
