### ISSUE TITLE
Feature Request: S00E00 in show title

### ISSUE THREAD

**Issue by digitalroadies** [dscottbuch/cTiVo#149]
I would like the ability to enable/disable S00E00 in the file name, this info is displayed in the window showing the tivo recordings for most of my shows but it's not being written to the converted file.

**Comment by mackworth** [comment]
You have that now, but it's hidden in Advanced Preferences. I'm looking at making it more obvious.  

Just go to Adv Prefs (Cmd-Opt-Comma), and select Plex Default from the Keywords pulldown.  It will fill in `[MainTitle] - [SeriesEpNumber] - [EpisodeTitle]`, which will do what you are asking for. 

You can then change that format however you'd like. The keywords are [documented in the wiki here](https://github.com/dscottbuch/cTiVo/blob/master/wiki/Advanced-Topics.md#filename-templates)

**Comment by digitalroadies** [comment]
Thank you sir, worked like a champ!
