### ISSUE TITLE
Formats

### ISSUE THREAD

**Issue by phantomtwo** [dscottbuch/cTiVo#150]
I wish to use the elGato 1080p format,but it shows up "greyed out" I have elGato Turbo 264HD installed. I'm no coder. What can I do?

**Comment by mackworth** [comment]
The greyed out just means that it's currently hidden. Turn off "Hide in User Interface" to enable it in your menu.

**Comment by phantomtwo** [comment]
That’s it. Thanks Hugh.

**Comment by mackworth** [comment]
You're welcome
