### ISSUE TITLE
Utilizing Roamio's new commercial skip feature from recent Winter update?

### ISSUE THREAD

**Issue by Mudflapper** [dscottbuch/cTiVo#152]
I live in Chicago and Tivo just released an AWESOME update for my Roamio which allows you to skip commercials by hitting the channel up button. At first I thought it just looked for changes in the video or audio stream to guess where the commercials started and ended, but I was wrong. Turns out Tivo literally has real live people watching the shows, live, and they add the start and end points by hand, so they are accurate. You can't skip commercials watching live TV, of course, and it take a little time for the "SKIP" tag to be added to a recorded show, but it is wonderful.

Is there a way for cTivo to, eventually, leverage this new feature to more reliably edit out commercials while downloading? Couldn't this be HUGE?

**Comment by mackworth** [comment]
I certainly agree it'd be great, but I've looked into this a bit, and there doesn't seem to be any way to access this information from the API we have.
