### ISSUE TITLE
files not downloading completely and/or encoding when transferred

### ISSUE THREAD

**Issue by need-help** [dscottbuch/cTiVo#153]
My transfers aren't.   

I'm not sure if the problem is with cTivo or something else.  I found this in the console log that makes it look like a permission error somewhere...

12/18/15 10:55:14.652 PM cTiVo[46152]:  SecOSStatusWith error:[-34018] Error Domain=NSOSStatusErrorDomain Code=-34018 "client has neither application-identifier nor keychain-access-groups entitlements" UserInfo={NSDescription=client has neither application-identifier nor keychain-access-groups entitlements}

Any thoughts on this?

I can't tell if there's is maybe a problem with the encoder?  I've tried to transfer just as 'decrypted tv show' but still have not had a successful transfer.  (update: just had a successful transfer for 'decrypted...'; so, conversion to mgeg2 may be the issue - any thoughts on making that work?) First three transfers failed, but not sure why.  I have since turned on detailed logs, but I can't tell where the error lies.  Could be wireless network.  Throughput report that I'm getting a whopping (?) 2.8 MPbs.  Time estimates tick down and the shoot back up to double for no apparent reason.

Any help or basic trouble shooting appreciated!

**Comment by mackworth** [comment]
I'd vote for wireless issues, although 2.8MBps is a reasonable throughout. The ticking down probably means zero throughput for a while, followed by a recovery. If you're getting that big a variation, then you're probably losing packets and retransmitting. Enough of those in a gigabyte file transfer and you'll likely get a unrecoverable failure. If you log into the TiVo over the web interface and transfer a file, you can remove all the other things cTiVo is doing as a test.

**Comment by mackworth** [comment]
Any progress on this? Let me know if I can help, or if there's still an issue.
