### ISSUE TITLE
Frequent freezes

### ISSUE THREAD

**Issue by swoelfel** [dscottbuch/cTiVo#154]
I'm seeing very frequent freezing of the application that causes me to force quit it and have to restart my computer before I can reopen it. The freeze can happen when encoding or just when the program is idle. Any help would be appreciated. Log was too long to paste below so it is attached. Thanks. 

[Log.txt](https://github.com/dscottbuch/cTiVo/files/71874/Log.txt)

**Comment by mackworth** [comment]
Hi, sorry for delay; unfortunately it took me a while to translate the log. I believe I have found the problem and have the fix for this; it will be included in 2.5

**Comment by swoelfel** [comment]
Thank you greatly. 

-------------------
Scott Woelfel
