### ISSUE TITLE
cTivo does not load episodes from TiVo

### ISSUE THREAD

**Issue by schroederius** [dscottbuch/cTiVo#155]
My iMac used to work great with cTivo, but somewhere along the line it stopped loading episodes.  My last successful transfer was 8/25.  I've since tried updating cTivo - am now running 2.4.4 (570) - to no avail.  I've connected with another (older, slower) Mac, which works fine, so it's my iMac rather than the network or the TiVo itself.  I looked in the issues list and couldn't find anything similar, so I guess it's just me. The logs show that I can see the TiVo itself, just can't seem to get the list of episodes.  
[com.cTiVo.cTiVo 2015-12-29 00-07.log.zip](https://github.com/dscottbuch/cTiVo/files/74152/com.cTiVo.cTiVo.2015-12-29.00-07.log.zip)

Here's what I see in the logs (attached):
2015-12-29 09:00:28:331 MTTiVo>connection:didFailWithError:@840>URL Connection Failed with error Error Domain=NSURLErrorDomain Code=-1004 "Could not connect to the server." UserInfo={NSUnderlyingError=0x7f8da5d337f0 {Error Domain=kCFErrorDomainCFNetwork Code=-1004 "Could not connect to the server." UserInfo={NSErrorFailingURLStringKey=https://dvr-8acd.local./TiVoConnect?Command=QueryContainer&Container=%252FNowPlaying&Recurse=Yes&AnchorOffset=0&ItemCount=15, NSErrorFailingURLKey=https://dvr-8acd.local./TiVoConnect?Command=QueryContainer&Container=%252FNowPlaying&Recurse=Yes&AnchorOffset=0&ItemCount=15, _kCFStreamErrorCodeKey=49, _kCFStreamErrorDomainKey=1, NSLocalizedDescription=Could not connect to the server.}}, NSErrorFailingURLStringKey=https://dvr-8acd.local./TiVoConnect?Command=QueryContainer&Container=%252FNowPlaying&Recurse=Yes&AnchorOffset=0&ItemCount=15, NSErrorFailingURLKey=https://dvr-8acd.local./TiVoConnect?Command=QueryContainer&Container=%252FNowPlaying&Recurse=Yes&AnchorOffset=0&ItemCount=15, _kCFStreamErrorDomainKey=1, _kCFStreamErrorCodeKey=49, NSLocalizedDescription=Could not connect to the server.}

I wasn't in a huge hurry to mess with this, since I had recently upgraded my TiVo and had huge amounts of available disk space.  Now that I'm using over 60%, I figured it was a good time to restart my archives.  I'm using El Capitan 10.11.2, with all the latest updates, on my iMac Retina 5K, 153GB free on my startup disk, 8TB free on my primary library drive, so lots of free capacity on the Mac side, on my home network so there shouldn't be any crazy networking issues, nothing I can think of has changed meaningfully since it last worked. Any suggestions?

**Comment by mackworth** [comment]
Well, I assume you've rebooted the Mac. What happens when you put that URL in your browser?  (Username: TiVo password: <your MAK>)

https://dvr-8acd.local./TiVoConnect?Command=QueryContainer&Container=%252FNowPlaying&Recurse=Yes&AnchorOffset=0&ItemCount=15

**Comment by schroederius** [comment]
I get a message that that link is unsafe; when I say to proceed, I'm prompted for credentials: The server https://dvr-8acd.local. requires a username and password.  The server says TiVo DVR.  I enter username TiVo, and tried a blank password and the password "password", and the media key as well, can't get in.  What next?

**Comment by schroederius** [comment]
And yes, I've rebooted many times, it doesn't make a difference...

**Comment by mackworth** [comment]
The password is definitely our media key. The username may need to be lower case.

**Comment by schroederius** [comment]
All lower case worked.  The attached XML is the result.
[TiVoConnect.xml.zip](https://github.com/dscottbuch/cTiVo/files/74293/TiVoConnect.xml.zip)
This file does not appear to me to contain nearly all the files on my system, but it looks like it's supposed to... Note that I have a 6TB TiVo from Weaknees, so it does have a large capacity, but, until fairly recently, it didn't actually have that many recordings.

**Comment by schroederius** [comment]
oh, you specified ItemCount=15, no wonder you only got 15. D'oh!  And, since my daughter's Mac worked, it shouldn't be a problem with what the tivo responds with.

**Comment by mackworth** [comment]
Okay, so looks like something's definitely wrong with ctivo on your machine. It sends that URL and gets a failure, but the browser on the same sends it and gets good data. That's strange.  Just to confirm, if you run ctivo now, you get the same result. Can you double check the MAK in Edit>Edit Tivos?

**Comment by schroederius** [comment]
It's showing the right MAK under Local Network TiVo's. I used to have another TiVo, which I decommissioned - it had a smaller drive and only 2 tuners, and I turned it off and removed it from the list.  I wonder if this is related to having had 2 units?  Is there a way to completely uninstall cTivo and restart from scratch?  I've tried deleting the app, but clearly the prefs are stored somewhere.

**Comment by schroederius** [comment]
OK, another data point: My daughter's Macbook CAN see shows, but I tested on yet another Macbook and it doesn't work either.  So 2 out of 3 Macs surveyed don't work here, but one does.  Puzzling.

**Comment by mackworth** [comment]
Hmm. All the same version of the app and OS? No difference on which wifi node they're on?

**Comment by mackworth** [comment]
Sorry, I missed the question on prefs.  They're stored in ~/Library/Preferences/com.cTiVo.cTiVo

**Comment by schroederius** [comment]
My page didn't refresh, so I didn't see your response until now - sorry about that!  All have the latest version of the app.  All are currently running El Capitan, latest updates.

I deleted the prefs, and launched cTivo.  When I go to the TiVos tab, I don't see ANY Local Network TiVo's listed.  Should I?  Or do I need to add my TiVo?  My iMac is on wifi, the same router that the TiVo is connected to via a wired interface (an ASUS wifi router).

**Comment by mackworth** [comment]
Ah, maybe you’re running two different networks through the router. Did any wiring change here recently?   Are all the Macs on the same wireless? Can you run Bonjour Browser  (http://www.tildesoft.com/files/BonjourBrowser.dmg) on both the Macs that can see the Tivo and the ones that can't.

**Comment by mackworth** [comment]
Any status here?

**Comment by mackworth** [comment]
In debugging this with another user, it turned out to be the antivirus program blocking the HTTPS session. Especially if you're running Avast, that would explain it.

**Comment by EurovisionGS** [comment]
I'm running Avast as well, is there an HTTPS server address that can be excluded in Avast, so it will let the program function properly?

**Comment by mackworth** [comment]
I don't know if it will work or not, so let me know if it does.  Each TiVo has their own URL in the form of
https://DVR-WXYZ.local./ where the WXYZ is the last four digits of its social security number.  Er, I mean its serial number. You can either look in its settings for that number, or in the cTiVo logs looking for the https://DVR part. I should note that it also uses http for the actual show downloads: http://dvr-aeda.local.:80/ 

When testing, if you get the message "URL Connection Failed with error" in the logs, then that's not good, but if you get "Finished batch", then the connection is working.  Note that "Finished batch" is only displayed if you set logging to  Major.)

**Comment by loki4191** [comment]
i just discovered cTivo recently, and am excited by what it offers.  Unfortunately, it looks like it can see the Tivos i have, just not the programs.  I have Version 2.5 beta2 (668).  i appreciate any suggestions on getting it working

**Comment by mackworth** [comment]
Well, first, make sure you're not running an antivirus, such as Avast, which can interfere with HTTPS sessions. Second, you should upgrade to beta4. Third, after the program loads, try doing a Refresh(Cmd-R). If none of those help, then go into Settings, set the Debug level to Detail and post the most recent log file (Help>show log files in Finder). You'll have to rename to .txt to post on Github
