### ISSUE TITLE
Build failure

### ISSUE THREAD

**Issue by damacguy** [dscottbuch/cTiVo#158]
Okay, I'm not a programmer. Now that's out of the way... I'm getting a build error in Xcode while trying to compile 2.4.4.
Fabric\Fabric.h not found when the compiler hits MTAppDelegate.m.

**Comment by mackworth** [comment]
I'm impressed you got that far!  Should be no reason for you to build the version from code; just download the zipped executable program from [the releases folder](https://github.com/dscottbuch/cTiVo/releases/)

(For anyone else who does want to build it; you have to either install Fabric and Crashlytics from the Twitter developer folks before building.)

**Comment by damacguy** [comment]
I was looking for the make file too. But fell back to Xcode. For some reason I couldn't find the 2.4.4 built version. Figured I'd give Xcode a shot. But found 2.4.4 after a Google search. Ha! Thanks for the info though.

**Comment by ryanchild** [comment]
trying to build so i can test my feature in #183 😅 

i got that i have to install these frameworks but can't quite figure out how to do that...

per the fabric install instructions, i added a run script build phase with the fabric install script, but that added the build phase to the end of the list, so the build was still failing in compile where MTAppDelegate.m can't find Crashlytics.h.

then i dragged the fabric install run script to the top of the build phase list, and it errored out saying it has to be at the end of the list...?

```
2016-08-21 00:11:47.376 uploadDSYM[91417:6285738] Crashlytics.framework/run 1.4.1 (162)
2016-08-21 00:11:47.690 uploadDSYM[91417:6285738] Launched uploader in validation mode
error: Crashlytics: Info.plist Error

Unable to process Info.plist at path /Users/ryan/Library/Developer/Xcode/DerivedData/cTiVo-gkasvfhncmloedbdcdshlpgzwuhn/Build/Products/Debug/cTiVo.app/Contents/Info.plist
This could be a timing issue, make sure the Crashlytics run script build phase is the last build phase and no other scripts have moved cTiVo.app from the location Xcode generated it.
```

**Comment by mackworth** [comment]
Just leave it out (fabric and crashlytics)!  It only provides anonymous crashing/analytics, so no need during testing. Also it'll get confused about keys.

**Comment by ryanchild** [comment]
Yeah thanks, I'll see if I can figure it how to ifdef it out for debug builds
