### ISSUE TITLE
Specify an output filename structure

### ISSUE THREAD

**Issue by drewmace** [dscottbuch/cTiVo#159]
I have not figured out how to specify an output filename with the format [ShowName] - SXXEXX - [ShowTitle].EXT

Is there a direct way to be able to do this?

**Comment by mackworth** [comment]
Yes, you can use: 
`[MainTitle] - [SeriesEpNumber] ["- " EpisodeTitle]`
but I would recommend:
`[MainTitle] - [SeriesEpNumber | OriginalAirDate] ["- " EpisodeTitle]`

The OriginalAirDate part is if it doesn't have a episode number, that it still puts something there,

**Comment by drewmace** [comment]
Where is this specified? Thanks for the reply!

**Comment by mackworth** [comment]
Ah, sorry. I thought you were experimenting already.  It goes in Advanced Preferences (Hidden under Cmd-Opt-Comma).  It's [documented here:]   (https://github.com/dscottbuch/cTiVo/blob/master/wiki/Advanced-Topics.md#filename-templates)

**Comment by drewmace** [comment]
Hugh - Thanks so much for the pointer.  Worked perfect.  cTivo is a
fantastic program!

**Comment by mackworth** [comment]
glad you like it!
