### ISSUE TITLE
Option to save .TiVo file?

### ISSUE THREAD

**Issue by jsasaki23** [dscottbuch/cTiVo#16]
Loving cTiVo so far; especially enjoying how closed captions are kept. A feature I'd like is the ability to save the .TiVo file in addition to processing it.  It would give me some flexibility if I want to do different processing steps on the file.

**Comment by ADent1** [comment]
I would like the .TiVo file too. I do a lot of transferring from a TiVo at one house to a TiVo at another house. I download the .TiVo file (using KMTTG for now), then use the TiVoDesktop software to pull them back at the other house. If I use a .TiVo file I don't have to keep track of the text file that would have to travel with the .mpg files.

I guess this can't be done with a custom video format?

**Comment by mackworth** [comment]
Just to be clear, you can easily download the .TiVo file, just use the Decrypted TiVo Show format. The request here was to keep that file in addition to a converted format.   Note that if you do use the "Keep temp files" Advanced Option (and turn off Use memory buffer) it will indeed keep the .TiVo file. It will also keep any other intermediate files, but if you're using mencoder, these will be pretty small.

**Comment by ADent1** [comment]
OK. It took quite a while to find the Advanced Preferences (hold option down). And check the box.

Thanx for the help. I should switch to regular format and use PyTiVo, but my existing workflow is working for now.

It would be nice someday if you added a video format for .TiVo - even if it ends up in User-contributed Alternative Video Formats or something.

**Comment by mackworth** [comment]
I may have mislead. Just choosing the "Decrypted TiVo Show" Format is sufficient to download a .tivo file. 

The Advanced Preference option is to never delete the temporary files cTiVo creates. So if you want the .tivo file, in *addition* to, for example, an MP4, then you can use that option. But be aware that it will leave other files around in you /tmp/ctivo directory. If you're using this scenario, then you'll have to delete those other files manually.

**Comment by vtrandal** [comment]
Please consider adding one more Video Format: Encrypted TiVo Show. I've spent quite a bit of time trying to save the .TiVo and the previous suggestion to "Keep temp files" seems to keep everything but the .TiVo file. I would not be interested in a fix to the "Keep temp files" approach. I want to keep only the .TiVo file and I want it in the Download Folder. How was cTiVo ever developed without Encrypted TiVo Show as a test case? With some difficulty I presume.

**Comment by mackworth** [comment]
So I'm curious: why do you want the encrypted format? What would you do with it that the decrypted won't do?

You are correct, the .tivo file is obviously downloaded, and usually stored in your temp directory, which the system puts into /private/var/folders/....  (If you go into Adv Prefs, and click on the Temporary Files Directory, then click on the folder at the top of the Open dialog, it'll show you the exact path.)  You've probably run into this issue: to get the .tivo files, you'd also have to turn on "Don't use memory buffer", as cTiVo writes as few files as possible to disk (including the encrypted file) unless the encoding is slower than the download.

**Comment by vtrandal** [comment]
I have two apps that use the encrypted file directly (Roxio and VideoRedo) with better results suggesting movies are not being decrypted correctly in cTiVo. But why debate it? Look back over this thread and consider how much information is actually correct. A lot of time is wasted hunting for the .TiVo file. From a software engineering perspective "(Encrypted) TiVo Show" is the base case and would have been the first thing to implement in cTiVo.

**Comment by mackworth** [comment]
Have you tried the Java version tivoLibre version of decryption versus those apps?  The majority of the discussion above was about the decrypted version (incorrectly referred to as .tivo). And from a sw engineering view, the purpose of ctivo is to simplify the complexity of a multi-step conversion process (decrypt, encode, commercial, caption, etc). The system assumes that the pipeline starts by decrypting the file as nothing else can happen otherwise. If you just want the tivo file, why use a separate program at all? you could just use the web browser to download the .tivo files.

BTW, I thought Toast gave up on Tivo for the Mac, and VideoRedo is Windows only; so do you move the files over to Windows after downloading?

**Comment by vtrandal** [comment]
Use tivoLibre on what file? The encrypted TiVo file that cTiVo users are punished waiting for while cTiVo downloads it again? Your logic is akin to saying zero is not a number. The output of the null processing chain is the encrypted TiVo file transferred from the TiVo device. The null processing chain is the only processing chain whose correctness proof is trivial. I recommend implementing it. Otherwise, please do provide details for using the browser interface to download all shows (more than 50) and provide those shows as input to cTiVo so users don't have to repeatedly download their shows just to apply a change in the cTiVo processing change.

**Comment by mackworth** [comment]
Ok, I think we're not understanding each other here. 

1) You said that "movies are not being decoded correctly in cTiVo".  My suggestion of trying tivoLibre was to see if it behaved better for you than tivodecode is doing. If so, you could avoid having to change over to Toast or VideoRedo and use cTiVo's chain entirely. If you have Java or Java runtime installed on your Mac, to try this, just go to Advanced Preferences and switch "Decode with:" to "tivoLibre". I'm not recommending this for your existing downloads (unless you still have a case that you know fails in tivodecode), but for new ones. I'd love to know if tivoLibre works better for you, and I'd love to get access to a a sample file that demonstrates the problem you're having with tivodecode.

2) I'm truly don't understand what you mean about "downloading it again" and "repeatedly download".  Under what circumstance is cTiVo downloading a show more than once? 

3) I obviously agree with you that not decrypting the show is simpler than decrypting it. However, I can assure you that cTiVo's current architecture assumes that decryption always takes place. If I were writing ctivo from scratch without that assumption, it would be easy to implement, but changing it now is a major change to a stable system used by tens of thousands of users. I'm not trying to be combative or unsupportive here, but to be clear, you're asking for a new feature in ctivo that, while it sounds simple, would actually be a significant effort to implement, and no one else has asked for in the many years the app has been available.

3) I wasn't suggesting using the browser interface as a way to get shows to input to cTiVo. I was saying that if the ONLY thing you're using cTiVo for is to download encrypted shows, it's probably the wrong tool, especially if you're then migrating it to Windows. Why not use KMTTG on Windows, which can then drive VideoRedo directly? Or you could use a shell script such as [this one](http://www.dealdatabase.com/forum/showthread.php?62218-Linux-OSX-script-to-pull-recordings-off-tivo) with a cron job to automatically download the files and then drive whatever decoding software you like.

**Comment by mackworth** [comment]
@ADent1  thanks for your note. The phase "write a decrypt module that just copies the file" was very helpful. Although, as I said, it's a big deal to remove the decypt stage, making it a copy stage instead is actually pretty simple.  

So, @vtrandal  I've implemented just that, and it will be in the next release. There's now a Encrypted Tivo Format which still does all the scheduling, subscriptions, autodownloading, filenaming, sorting by directories, etc. It obviously doesn't do commercialling, or subtitling.

**Comment by vtrandal** [comment]
Thank you.
