### ISSUE TITLE
Failure with partial shows

### ISSUE THREAD

**Issue by twenty-one** [dscottbuch/cTiVo#161]
I have a few shows on my relatively new Roamio that are shorter than their broadcast length. One is a portion at the end of an episode of "House;" the other is the end portion of a 2 hour film.

cTivo is working fine with all of my other downloads, but I always get a failure with the two shorter (<10 minute) shows.

I've looked into the logs and there are of the following issues:
Warning: Show may be damaged/incomplete./House: It's a Wonderful Lie: Possible Problem
TiVo show failed; retrying.../House: It's a Wonderful Lie: Can't Download

Then I get:
TiVo show failed; cancelled./House: It's a Wonderful Lie: End Download

So, I know the shows are incomplete (not damaged because they play fine on the Tivo). Is there a way to fix this?

Thank you.

**Comment by mackworth** [comment]
Sorry for delay; missed this one.  So are these manually recorded (hitting record while watching them)?

There are some bugs in TiVo's file transfer. We put up the "damaged/incomplete" message when TiVo says it has sent the entire show, but it's <80% of the size that TiVo says it should be. Typically this is exactly what it says it is.  That is not enough to fail the download though. (retry v cancelled is just that we try three times to get through it). My guess is that the encoder is also saying something's broken.

First step would be to increase the logging to Detail and run the shows again; the logs will then give you much more information about why they failed.. Secondly, try doing it with the "Decrypted TiVo Show" format. This avoids re-encoding the file so it may get through.

**Comment by twenty-one** [comment]
Not a problem for the delay; I simply appreciate your response.

I was able to get a file (the last eight or nine minutes of an hour nighttime drama) transferred from the Tivo by setting the quality
to “Decrypted TiVo Show” format as you suggested. The problem with the file, though, was that the file was only playable as an audio file.

I did set the logging to Detail, but I don’t know what to do with that.

Any other suggestions?

Once again, thank you.

**Comment by mackworth** [comment]
Sounds like you might be running into the Transport Stream issue (are you on Comcast and what city?)

You could try the alpha version of the next release to see if it fixes your problem.  See near the end of the issue at https://github.com/dscottbuch/cTiVo/issues/156

**Comment by mackworth** [comment]
And you can now download the [official alpha version here](https://github.com/dscottbuch/cTiVo/releases) Let me know if that helps.

**Comment by twenty-one** [comment]
I will try the 2.5 Alpha Release 1. I just don’t know how comfortable I feel with all the machinations after reading through the page. There seem to be so many irregularities for which there are two or more options.

It’s a little overwhelming. I’m a very general technie, but when it gets into “If you have this issue, try this or this.” and there are several of those. It seems daunting to me.

I’ll let you know when I install it and how it goes.

Thank you.

**Comment by twenty-one** [comment]
Hi, Hugh. I’m sorry for the delay in my response. I downloaded the cTiVo-2.5.0alpha1 release, but I’m not sure what to do with it. Once I unzip it I get a folder with that name. Under that, there are a cTiVo directory that’s relatively large, a cTiVo.xcodeproj file and a README.md file, and two other small directories.

So, I’m technologically comfortable, but I don’t know what to do with these files to install this alpha release.

I’d like to try it to see if it can download those two partial programs, but I need some help with the installation.

Thank you again,
Matthew

**Comment by mackworth** [comment]
Sounds like you downloaded the source instead of the executable.  Try this link instead:
https://github.com/dscottbuch/cTiVo/releases/download/2.5.0alpha1/cTiVo.zip

**Comment by mackworth** [comment]
And then just go to Advanced Options:  (Cmd-Option-Comma) and turn on Transport Stream. Then try the shows again.

**Comment by twenty-one** [comment]
I didn’t know about the Advanced Preferences, but I’ve got it up now. I don’t know which option turns on Transport Stream.

**Comment by mackworth** [comment]
Should be right there "Use TiVo's Transport Stream Format"

**Comment by twenty-one** [comment]
Sorry, I kept both the current version and the alpha. I was downloading a 30 minute sitcom on the current version and tried to open the alpha, but it didn’t seem to do. So when I hit the Cmd-Opt-comma I had the old Advanced Preferences without the Transport Stream option.

One problem I’ve found with the current version is that it doesn’t stop the Mac from going to sleep in the middle of a download. Then when you wake it, the current download immediately gets overwritten and the program restarts the download.

Anyway, I tried this new version with the Transport Stream checked on Advanced Preferences and it wouldn’t download the sitcom that had been downloading on the current version, even after I changed download directories. Also, when I tried the partial programs it didn’t work either.

Again, I’m sorry if I made you a little crazy by telling you I didn’t see the Transport Stream option. My mistake.

And thank you.

**Comment by twenty-one** [comment]
BTW, the alpha version did download the partial program when I selected “Decrypted TiVo Show.” It didn’t when I had H.264 Medium Quality.

Won’t be able to get back to you any more this evening.

Thank you.

**Comment by mackworth** [comment]
No problem on the preference; I assumed something like that was going on.

And, yeah, definitely don't run two copies at once, it can lock up your Tivo's downloading and you'll need to reboot!

Haven't changed anything near sleeping. Is "Disable Sleep" still checked in Preferences?

Glad to hear download worked; confirms my basic theory. I know H.264 is broken. Try AppleTV format.  And if you don't need to load it into iTunes, you can actually just use MP4 FFMPeg. It converts to MP4 without doing any re-encoding. Unfortunately, the result doesn't work with iTunes, but it seems to work well with VLC and Plex.
