### ISSUE TITLE
Downloads Immediately Failing

### ISSUE THREAD

**Issue by jimccjr** [dscottbuch/cTiVo#164]
I have a TiVo Premiere and an iMac and a MBP both running Yosemite. cTiVo is 2.4.4 (570).
I get immediate fail errors from both my iMac and MBP. My provider is Cox. Here is the log: 
https://www.dropbox.com/s/gp07k6ewij07lvm/com.cTiVo.cTiVo%202016-04-08%2001-24.log?dl=0

Any help would be greatly appreciated!!

Thanks!

**Comment by mackworth** [comment]
So it's saying "Unable to open destination 2 /Volumes/TiVo/Masterpiece Mystery!- Grantchester Season 2.mpg for pipe Permission denied"  That particular error msg (with the odd 2) comes from the cat2File program and all it's trying to do is open a file.

The most obvious thing would be if that disk is write-protected, or corrupted, or a read-only file format.  Can you manually create a file on that disk?

**Comment by jimccjr** [comment]
So...I feel a little dumb. Apparently cTiVo was pointing to a Download folder that I must have moved or deleted. When I reassigned the download folder, everything worked fine! Thanks for your help. This issue is now complete!

**Comment by mackworth** [comment]
Glad to hear it!
