### ISSUE TITLE
Download Folder Preference Isn't Persistent

### ISSUE THREAD

**Issue by gfmorris** [dscottbuch/cTiVo#165]
I really like this project and am glad that it exists.

My issue is that the Download Folder won't stay to what I set it.  The default is ~/Movies/TV Shows//, but I want it to be the source folder for my Plex library.  Once or twice, cTiVo has reverted this setting while started; every time it's quit (or the Mac restarted), it reverts to the default setting.  I would really like for this to persist.

Thanks!

Geof Morris

**Comment by mackworth** [comment]
Only time it should revert is if your folder is not "available" when it starts up. In particular, if you're on an external or network drive, and it hasn't spun up by the time ctivo launches, it'll reset.  Does that match your situation?   (BTW, I'm also confused about "Once or twice" vs "every time"?)

I'll look at trying the drive again after a few seconds.

**Comment by gfmorris** [comment]
Ah, that makes sense. The when-powered reversions have come when my drive unmounted.

Trying an external volume after 15 or 30 seconds makes sense to me.

Geof


--
Geof F. Morris :gfmorris@gfmorris.net:(256)527-8152

"We must collect facts and use them asammunition."— Samuel Gridley Howe
