### ISSUE TITLE
Native Comskip Support with iTunes mp4chaps Feature Request

### ISSUE THREAD

**Issue by essandess** [dscottbuch/cTiVo#166]
This is a request to add natively compiled [GitHub comskip](https://github.com/erikkaashoek/Comskip) and use mp4chaps to add commercials markings to MP4/iTunes transcodings.

We use this for [etv-comskip](https://github.com/essandess/etv-comskip), and the [Makefile](https://github.com/essandess/etv-comskip/blob/master/Makefile) there shows how comskip can be compiled and distributed with OS X shared libraries. The use of mp4chaps to add comskip commercial markings to transcodings is done within the python script [MarkCommercials](https://github.com/essandess/etv-comskip/blob/master/src/scripts/MarkCommercials/MarkCommercials.py).

From experience with EyeTV, comskip is highly reliable, the native compile runs very fast, and it's great to have commercial skipping in the MP4s.

Many of us are happy using EyeTV, however Elgato's support has dwindled and they just sold this brand to [Geniatech](https://www.geniatech.eu/eyetv/). It would be great if Geniatech is successful reviving EyeTV, but TiVo also appears to be a good PVR option if exports can be bundled with comskip markings.

**Comment by mackworth** [comment]
Have you tried the alpha version 2.5?  I believe it has the natively compiled version of comskip, and cTiVo's been doing the mp4 commercial marking for a long time now (just select Mark commercials v Skip commercials). Let me know if you see anything different.

**Comment by essandess** [comment]
The latest version appears to use a [compiled version of comskip](https://github.com/dscottbuch/cTiVo/blob/master/cTiVo/comskip) that is three years old, without the latest ffmpeg multithreading support, and not the fast donators version.

The latest comskip code at GitHub is v89 not 79, and runs over 250 fps on 1080i content. There's no reason not to add a submodule to the latest comskip code and compile with it.

Similarly, mp4v2 on this repo appears to be three years old.

It's straightforward to make updated binaries using Macports or brew, then include the binaries in the release, and avoid the issues of pasting old code or binaries into the repo.

**Comment by mackworth** [comment]
That is true on the main release line. On the 2.5 alpha line, we have the latest version of comskip:
https://github.com/dscottbuch/cTiVo/blob/2.5/cTiVo/comskip
Have you tried out the [alpha version of 2.5?](https://github.com/dscottbuch/cTiVo/releases/tag/2.5.0alpha1)

**Comment by essandess** [comment]
When I test the binary in this repo, https://github.com/dscottbuch/cTiVo/blob/2.5/cTiVo/comskip, it reports 25 fps.

When I test the binary compiled from [GitHub comskip](https://github.com/erikkaashoek/Comskip), available in the latest [etv-comskip](https://github.com/essandess/etv-comskip) release available here, https://github.com/essandess/etv-comskip/releases/download/v3.5.3/ETVComskip-3.5.3-10.11.dmg, it reports 263 fps.

I suggest taking a look at the Makefile mentioned above and compile comskip using the donator's option and the gnu make tools.

**Comment by essandess** [comment]
Also, I see these `comskip.ini` directives reported from https://github.com/dscottbuch/cTiVo/blob/2.5/cTiVo/comskip, which shouldn't be part of a BSD-based build:

```
mpeg2schnitt_options="mpeg2schnitt.exe /S /E /R25  /Z %2 %1"
avisynth_options="LoadPlugin(\"MPEG2Dec3.dll\") \nMPEG2Source(\"%s\")\n"
```

**Comment by mackworth** [comment]
So I tried building it that way and it generates a version that requires dylibs to be installed. (the exe is 384K versus 16M for the static one.  There's some arcane magic involved in building a static one.  @dscottbuch  and @mortax figured it out, but I haven't been able to recreate it.

**Comment by mackworth** [comment]
See [Issue #146 ](https://github.com/dscottbuch/cTiVo/issues/146)

**Comment by essandess** [comment]
I don't see the relevance to #146. The comskip binary you point to in the cTivo repo runs tens times slower than it should.

The fix is easy: add the latest github as a submodule to this project, compile using the autoconf tools, and use a recursive otool like (matryoshka-name-tool)[https://github.com/essandess/matryoshka-name-tool] for the dynamic libraries.

**Comment by essandess** [comment]
I'd recommend against trying to use static libraries with OS X, which doesn't support them.

Rather, make a distribution with `./bin` and `./lib` directory, and use `otool` to point the binary's library dependencies at `./lib`. It's easy to do this recursively with [matryoshka-name-tool](https://github.com/essandess/matryoshka-name-tool).

**Comment by essandess** [comment]
This has the added benefit of incorporating upgrades from the actual dependency chain, which in the case includes the comskip repo, ffmpeg, mp4v2, and a few others.

**Comment by dscottbuch** [comment]
Let me take a look at this and Steve's suggestion over the next week. 

It is not the case that OS X does not support static libraries, it does. It does not support static system libraries. I did, with the original distributions create and link in all required non-system libraries to the binaries. 

That being said, creating the required static libraries is extreme burdensome these days with lack of support for their creation in the various support modules so the proposed approach would be significantly less effort. 


D. Scott Buchanan

Sent from my iPhone

This email and any files transmitted with it are confidential and intended solely for the use of the individual or entity to whom they are addressed. If you have received this email in error please notify the system manager

**Comment by mackworth** [comment]
It's possible that mencoder and ffmpeg could then share the libraries, no?

**Comment by dscottbuch** [comment]
Yep

D. Scott Buchanan

Sent from my iPhone

This email and any files transmitted with it are confidential and intended solely for the use of the individual or entity to whom they are addressed. If you have received this email in error please notify the system manager

**Comment by essandess** [comment]
> It's possible that mencoder and ffmpeg could then share the libraries, no?

Yes, that's how you'd organize it. The call

`python matryoshka-name-tool.py binary1 binary2 […]`

should do this recursively, adding all dependent libraries to `./lib`.

**Comment by mackworth** [comment]
So, this is all included in 2.5 alpha versions, so I'm closing out this issue. Let me know if you see any problems with the current version.

**Comment by mackworth** [comment]
@dscottbuch any chance of documenting an updating mechanism here for the binaries (e.g. submodule to the comskip github as mentioned above). e.g. we've currently got 2.8.6, and I'd like to incorporate 3.1.1 instead.

**Comment by dscottbuch** [comment]
I'll take a look.  I don't see why not. 

D. Scott Buchanan

Sent from my iPad

This email and any files transmitted with it are confidential and intended solely for the use of the individual or entity to whom they are addressed. If you have received this email in error please notify the system manager

**Comment by dscottbuch** [comment]
I have these instructions

1) git clone git://github.com/erikkaashoek/Comskip <git://github.com/erikkaashoek/Comskip> (or pull update) and then follow the build instructions
2) git clone git://github.com/essandess/matryoshka-name-tool <git://github.com/essandess/matryoshka-name-tool> (not needed if you already have it)
3) port install (or upgrade) ffmpeg
4) port install (or upgrade) mplayer @1.2_2+a52+mencoder_extras(for mencoder)
5) port install  (or upgrade) argtable
6) create a target directory with bin and lib subdirectories (or use exiting structure in cTiVo xcode project)
7) copy comskip, mencoder and ffmpeg to the bin directory
8) cd to the bin directory used above
9) run  -  python $PATH_TO/matryoshka_name_tool.py -d ../lib/ comskip ffmpeg mencoder

Do you want to try and incorporate these into the build script, or possibly into another target in the cTiVo project?

**Comment by mackworth** [comment]
I think just documenting the steps is good enough. I ran through these and updated with a couple of issues:

Assuming you have XCode command-line, Macports, and GNU autotools (autoconf, automake, and libtool) installed...
1) Create and cd to a new directory somewhere;
2) git clone git://github.com/essandess/matryoshka-name-tool 
3) git clone git://github.com/erikkaashoek/Comskip
4) sudo port install ffmpeg  ## or upgrade
5) sudo port install mplayer @1.2_2+a52+mencoder_extras ## or upgrade
6) sudo port install argtable   ## or upgrade
7) cd comskip;  ./autogen.sh; ./configure; make; cd ..
8) mkdir cTiVoBinaries; cd cTiVoBinaries; mkdir bin; mkdir lib; cd bin
7) cp ../../comskip/comskip comskip; cp /opt/local/bin/mencoder mencoder; cp /opt/local/bin/ffmpeg ffmpeg
9) python ../../matryoshka-name-tool/matryoshka_name_tool.py -d ../lib/ comskip ffmpeg mencoder
10) cd .. ; copy ctivoBinaries to cTivo/ctivoBinaries
11) Download latest handbrakeCLI from https://handbrake.fr/downloads2.php (not part of matryoshka process

Just for future reference, I ran into one problem, and threw away the lib folder to recreate it. However, as the matryoshka tool changes the binaries, the process needs fresh copies of the binaries to go through it again. No error msgs, just no libs get copied.

Any thoughts on how to compile mencoder so that it uses the external dynamic libraries rather than building them in? Also, does the @1.2_2

**Comment by dscottbuch** [comment]
I don’t think the libraries are linked in.  When I run nm on mencoder I get, for example, 

                 U _ogg_page_continued
                 U _ogg_page_serialno
                 U _ogg_stream_clear
                 U _ogg_stream_init

The U indicates that the symbol is undefined.  From one page...

An undefined symbol is a symbol that the library uses but was not defined in any of the object files that went into creating the library. 


This would apply just as well to executable as library. So I think these are the references to the .dyld files.

BTW if you are ‘upgrading’ already installed ports and what you want it the active variant, all you need is - sudo port upgrade mplayer ,  for example.

I did spend a little time on trying to figure out how to script XCode to update the lib directory link as the names of the libraries change with the variants.  That was a mess in applescript and I didn’t figure it out - sorry.

Scott

**Comment by mackworth** [comment]
Assuming you have XCode command-line, Macports, and GNU autotools (autoconf, automake, and libtool) installed...

The tricky part is getting it all to compile for previous versions of macOS.  

First, with the stdc++ lib transition, MacPorts has given up on 10.7 and 10.8. We're just using the old binaries for the 10.7 version.
Second, to configure MacPorts for compilation, you need to add `macosx_deployment_target  10.9` to the macports configuration file: `/opt/local/etc/macports/macports.conf`
Third, set the environment variable `export MACOSX_DEPLOYMENT_TARGET=10.9`  (This should be good enough for MacPorts as well, but it is unclear if this worked for MacPorts.)
Fourth, to get the "official" (downloaded) versions of all the library at the right version level, 
in macports, make the following patch.
/opt/local/libexec/macports/lib/port1.0/portutil.tcl   lines 2572-2573:
Change from:
```
    global portdbpath subport version revision portvariants os.platform os.major portarchivetype
    set ret "${subport}-${version}_${revision}${portvariants}.${os.platform}_${os.major}.[join [get_canonical_archs] -].${portarchivetype}"
```
TO:
```
    global portdbpath subport version revision portvariants os.platform os.major portarchivetype macosx_deployment_target
    set OSVersion ${os.major}
    if {[string first 10. $macosx_deployment_target] == 0} {
         set testVersion [string range $macosx_deployment_target 3 end]
         if {[string is integer -strict $testVersion]} {
            set OSVersion [expr {$testVersion + 4}]
         }
    }
    set ret "${subport}-${version}_${revision}${portvariants}.${os.platform}_${OSVersion}.[join [get_canonical_archs] -].${portarchivetype}"
#for completness you could change os.major to OSVersion in line 2584 also
```
0) To make sure you're getting correct versions, 
1) Create and cd into a new ctivoBinaries directory somewhere;
2) git clone git://github.com/essandess/matryoshka-name-tool 
3) git clone git://github.com/erikkaashoek/Comskip
4) sudo port install ffmpeg +nonfree+gpl2+gpl3 
5) sudo port install mplayer +a52+mencoder_extras 
6) sudo port install argtable
7) cd comskip;  ./autogen.sh; ./configure; make; cd ..
8) mkdir cTiVoBinaries; cd cTiVoBinaries; mkdir bin; mkdir lib; cd bin
7) cp ../../comskip/comskip comskip; cp /opt/local/bin/mencoder mencoder; cp /opt/local/bin/ffmpeg ffmpeg
9) python ../../matryoshka-name-tool/matryoshka_name_tool.py -d ../lib/ comskip ffmpeg mencoder
10) cd .. ; copy ctivoBinaries to cTivo/ctivoBinaries
11) Download latest handbrakeCLI from https://handbrake.fr/downloads2.php (not part of matryoshka process

Note: Use the following command to check version number of all files in a directory:
`for f in *; do otool -l $f| grep -A 2  'LC_VERSION_MIN_MACOSX'; done`

Just for future reference, I ran into one problem, and then to restart just threw away the lib folder and ran matryoshka again. However, as the matryoshka tool changes the master binaries (mencoder, comskip and ffmpeg), the process needs fresh copies of the original binaries to go through it again. No error msgs, just no libs get copied.

**Comment by essandess** [comment]
@mackworth 
> as the matryoshka tool changes the master binaries (mencoder, comskip and ffmpeg), the process needs fresh copies of the original binaries to go through it again. No error msgs, just no libs get copied

You can blame me for that one. Please describe the high-level expected error behavior and I'll add the functionality to [matryoshka-name-tool](../../../essandess/matryoshka-name-tool).

**Comment by mackworth** [comment]
Well, can't really argue that it's an error (at least on the part of matryoshka rather than myself!). After it successfully goes through the tool, going through it again will have no effect, as there are no libraries to relocate.  Maybe if it noticed that case and gave a message saying something like "No shared libraries to relocate; has this executable already been through matryoshka process?"

Great little tool btw! I can't possibly imagine doing it by hand.

**Comment by mackworth** [comment]
And ... while we're chatting, two questions. 

 Is 2.5.0 comskip working to your expectations?

Secondly, as you are the only person I know who understands the dylib relocation issue... 
Any thoughts why I'm having a problem creating a version to run on macOS 10.9/10.11?  the discussion is in Issue #220 and the [experimental version is here](https://dl.dropboxusercontent.com/u/21507587/cTiVo.zip) 

When he runs comskip, he gets:
dyld: Library not loaded: @executable_path/../lib/libiconv.2.dylib
Referenced from: /Applications/cTiVo.app/Contents/lib/libavutil.55.dylib
Reason: Incompatible library version: libavutil.55.dylib requires version 8.0.0 or later, but libiconv.2.dylib provides version 7.0.0 

But when I run the same version of the app on 10.12, it works fine (unless I rename the included version of libiconv to something else, then I get the exact same msg.)

Using otool -l, it looks like everything's pointing to the right thing. Except I did notice that the dylibs still have their original compiled locations embedded in the file (e.g.  /opt/local/lib/libavutil.55.dylib in libavutil's Load command 3. Is that normal? Seems to be, looking at other files.

any thoughts?

**Comment by essandess** [comment]
Re: `name_tool` issue.

It sounds like it's working on your box because you have all the libraries installed, both in `/opt/local/lib` and `../lib`. If there was some mess-up, it would still work on your box, but not on deployments because they don't have `/opt/local/lib`.

In fact, your question prompted me to see that I just made this very mistake on my latest release of etv-comskip—my distributed `../lib` is empty! I have to go dig into this and get back.

**Comment by essandess** [comment]
I found my build issue:

1. `matryoshka_name_tool` calls `otool`. My `PATH` finds the otool binary in `/opt/local/bin`.
2. My Macports configuration fails with this otool:
```
/opt/local/bin/otool -L ./comskip
fatal error: /opt/local/bin/otool: can't find or exec: /opt/local/bin/llvm-objdump (No such file or directory)
fatal error: /opt/local/bin/otool: internal objdump command failed
```
3. The fix:
```
sudo port select --summary
sudo port select --set llvm mp-llvm-3.9
```

Or you could set up `PATH` so that otool points to the binary in `/usr/bin`.

I have to go back and ensure that my Makefile fails if this happens.

Is this in any way related to your issue?
