### ISSUE TITLE
Downloads failing consistently

### ISSUE THREAD

**Issue by thornburyt** [dscottbuch/cTiVo#167]
I can see the list of items in my Tivo, but every download fails with Tivo Show Failed; retrying.  Looking for any insight in how to debug and fix.  Attached is the error file from  /tmp/cTivo.
[com.cTiVo.cTiVo 2016-04-15 16-43.log.zip](https://github.com/dscottbuch/cTiVo/files/221388/com.cTiVo.cTiVo.2016-04-15.16-43.log.zip)

cTivo version is 2.4.4.  OS is El Capitan 

System Version:	OS X 10.11.4 (15E65)
  Kernel Version:	Darwin 15.4.0
  Boot Volume:	Macintosh HD
  Boot Mode:	Normal
  Secure Virtual Memory:	Enabled
  System Integrity Protection:	Enabled
  Time since boot:	1:59

**Comment by mackworth** [comment]
Sorry for delay.  So, I only see one show here; I assume others are failing as well?

Have you tried rebooting your tivo?

cTiVo is not getting any download data at all.  
Can you try just downloading the raw tivo file?  Just [click here ](http://dvr-5380.local.:80/download/Modern%20Marvels.TiVo?Container=%2FNowPlaying&id=5515628)in your browser.  You'll have to give it `tivo` as the user and your MAK as the password. Best not to save password in your browser. it'll be quite large, so you can stop the download after a few megabytes.

**Comment by thornburyt** [comment]
Correct.  I just sent the one because they are all the same, just the episode name changes.  I have tried rebooting the Tivo.  I  looked at the log file and saw this entry also. I know the name isn't resolving, so I replaced it with the IP and the file still isn't downloading.  So I replaced the %20 with a space and the %2F with a / and my browser can see it now.

**Comment by thornburyt** [comment]
So I got it to work.  Wow. The Tivo web server is very unpredictable!  :-)  Do you know a way to reset the web server remotely without rebooting the Tivo every time?

**Comment by mackworth** [comment]
Nope. that's how you do it.  If you're not accessing it from multiple systems, it should be reliable.  (We work pretty hard in ctivo to not hit it too often.)

Sorry 'bout the space and / stuff; glad it's working!
