### ISSUE TITLE
Ctivo crashes every time I start a download

### ISSUE THREAD

**Issue by clintonz15** [dscottbuch/cTiVo#168]
As soon as i try to download any show (have tried several) I get an error that says ctivo has quit unexpectedly. Below is the text of the error message.

Any help would be greatly appreciated

Process:         cTiVo [1546]
Path:            /Applications/cTiVo.app/Contents/MacOS/cTiVo
Identifier:      cTiVo
Version:         ??? (???)
Code Type:       X86-64 (Native)
Parent Process:  cTiVo [1540]

Date/Time:       2016-04-15 20:40:32.944 -0700
OS Version:      Mac OS X 10.7.5 (11G63b)
Report Version:  9

Interval Since Last Report:          2912862 sec
Crashes Since Last Report:           120
Per-App Crashes Since Last Report:   119
Anonymous UUID:                      63E6FD2A-C62A-4768-8B9E-14958C5F4935

Crashed Thread:  Unknown

Exception Type:  EXC_BAD_ACCESS (SIGSEGV)
Exception Codes: KERN_INVALID_ADDRESS at 0x00007fff5fc01028

Backtrace not available

Unknown thread crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000055  rbx: 0x0000000000000000  rcx: 0x0000000000000000  rdx: 0x0000000000000000
  rdi: 0x0000000000000000  rsi: 0x0000000000000000  rbp: 0x0000000000000000  rsp: 0x0000000000000000
   r8: 0x0000000000000000   r9: 0x0000000000000000  r10: 0x0000000000000000  r11: 0x0000000000000000
  r12: 0x0000000000000000  r13: 0x0000000000000000  r14: 0x0000000000000000  r15: 0x0000000000000000
  rip: 0x00007fff5fc01028  rfl: 0x0000000000010203  cr2: 0x00007fff5fc01028
Logical CPU: 6

Binary images description not available

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 6765
    thread_create: 2
    thread_set_state: 0

Model: MacPro5,1, BootROM MP51.007F.B03, 8 processors, Quad-Core Intel Xeon, 2.4 GHz, 6 GB, SMC 1.39f11
Graphics: ATI Radeon HD 5770, ATI Radeon HD 5770, PCIe, 1024 MB
Memory Module: DIMM 1, 1 GB, DDR3 ECC, 1066 MHz, 0x80AD, 0x484D54313132553754465238432D48392020
Memory Module: DIMM 2, 1 GB, DDR3 ECC, 1066 MHz, 0x80AD, 0x484D54313132553754465238432D48392020
Memory Module: DIMM 3, 1 GB, DDR3 ECC, 1066 MHz, 0x80AD, 0x484D54313132553754465238432D48392020
Memory Module: DIMM 5, 1 GB, DDR3 ECC, 1066 MHz, 0x80AD, 0x484D54313132553754465238432D48392020
Memory Module: DIMM 6, 1 GB, DDR3 ECC, 1066 MHz, 0x80AD, 0x484D54313132553754465238432D48392020
Memory Module: DIMM 7, 1 GB, DDR3 ECC, 1066 MHz, 0x80AD, 0x484D54313132553754465238432D48392020
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x8E), Broadcom BCM43xx 1.0 (5.106.198.19.22)
Bluetooth: Version 4.0.8f17, 2 service, 18 devices, 1 incoming serial ports
Network Service: Ethernet 2, Ethernet, en1
Network Service: Wi-Fi, AirPort, en2
PCI Card: ATI Radeon HD 5770, sppci_displaycontroller, Slot-1
Serial ATA Device: HL-DT-ST DVD-RW GH61N
Serial ATA Device: WDC WD1001FALS-41Y6A1, 1 TB
Serial ATA Device: WDC WD1001FALS-41Y6A1, 1 TB
Serial ATA Device: ST1000DM003-9YN162, 1 TB
USB Device: Keyboard Hub, apple_vendor_id, 0x1006, 0xfa400000 / 2
USB Device: Apple Optical USB Mouse, apple_vendor_id, 0x0304, 0xfa430000 / 4
USB Device: Apple Keyboard, apple_vendor_id, 0x024f, 0xfa420000 / 3
USB Device: FCR-HS219/1 Mobile Reader, 0x11b0  (ATECH FLASH TECHNOLOGY), 0x6148, 0xfd300000 / 3
USB Device: Drobo, 0x19b9, 0x4d10, 0xfd100000 / 2
USB Device: BRCM2046 Hub, 0x0a5c  (Broadcom Corp.), 0x4500, 0x5a100000 / 2
USB Device: Bluetooth USB Host Controller, apple_vendor_id, 0x8215, 0x5a110000 / 4
FireWire Device: built-in_hub, 800mbit_speed

**Comment by clintonz15** [comment]
Attached is the log file as well. I forgot to attach it before.

Thanks again for any help you can provide



[log.pdf](https://github.com/dscottbuch/cTiVo/files/222041/log.pdf)

**Comment by mackworth** [comment]
It looks like you're running into the MP4 transition (are you on Comcast?).  Try out the[ 2.5 alpha version here](https://github.com/dscottbuch/cTiVo/releases):   and see if it improves things.... Unfortunately, the current one requires some manual settings, so you'll need to read the introduction page.

**Comment by mackworth** [comment]
Any progress?
