### ISSUE TITLE
Downloads failing on Pace Tivo from RCN

### ISSUE THREAD

**Issue by ejschenck** [dscottbuch/cTiVo#169]
I recently moved and RCN installed the new Pace XG1 box at the new apartment.  I've got the new box added to cTivo but I keep getting failed downloads.

I did try upgrading to the Alpha release (2.5) to see if that would help resolve the issue, but it doesn't seem to have.  I attached the log if that helps.
[com.cTiVo.cTiVo 2016-04-17 18-10.log.zip](https://github.com/dscottbuch/cTiVo/files/222795/com.cTiVo.cTiVo.2016-04-17.18-10.log.zip)

**Comment by mackworth** [comment]
Looks like network issues to me. Try loading the show into your browser and see what happens :  

http://dvr-cb7a.local.:80/download/Saturday%20Night%20Live.TiVo?Container=%2FNowPlaying&id=42

**Comment by mackworth** [comment]
Oh, username: tivo and password is your MAK

**Comment by ejschenck** [comment]
<h2>Access Forbidden</h2>
feature not enabled

Somehow that doesn't sound good...

**Comment by mackworth** [comment]
No, it's not...

First: are you sure you have the right MAK?

Then, go to your TiVo's System Information screen, and check if TiVoToGo should be a,a,a (or a,a,a,a).  If not, call Tivo and ask why you can't use TiVoToGo from your Windows machine, that it doesn't seem tobe enabled.  Do NOT say the words Macintosh or cTiVo, or they won't help you. 

If it does, try rebooting Tivo and see what happens (same URL).  
Check if you can see the list of shows at https://dvr-cb7a.local.:80/nowplaying/index.html 

Maybe try rebooting your router and then restart Tivo.

**Comment by ejschenck** [comment]
Ok. Thanks. Will update tomorrow after I follow all this. Thanks and have a great weekend!

**Comment by ejschenck** [comment]
Ok, found the issue.  TivoToGo was set to i,i,a,a.  I logged into my Tivo account, went to device preferences, and turned on Video Downloads.  After a reboot, it works and is downloading FAST.

Thanks for pointing out that potential issue!

However... the link you gave me doesn't pull anything up from the box in Safari.  But cTivo works fine so...

**Comment by mackworth** [comment]
Interesting; try this one: https://dvr-cb7a.local.  What error do you get?

There's a few possible reasons for a slow download. First, check that it's not the reencoding, by trying Decrypt Format. This just downloads and decrypts, so us fast as it can go. It should tell you the net speed there.  Second, is there any network issue?  Third, what box is this?  I've never heard of a download pixelating the TiVo. That's really surprising.

**Comment by ejschenck** [comment]
Safari can't connect to the server...

It's the Pace MG1.  I switched to using just the Decrypted Tivo File format and it's up to 3.1 MBps.

I don't think we have a network issue.  I mean, the TiVo is hardwired to my router (a Netgear R8000) and I'm connected from my MacBook Pro at 1300mbps.

**Comment by mackworth** [comment]
3.1 MBps is quite reasonable; depending on device, we see 1-7 MBps. You'll see a wide variation of speeds on format conversion. 

If the pixelation continues, you could try asking TiVo about it; again, just ask about for TiVoToGo.

**Comment by ejschenck** [comment]
Unofficially... where did I get the TivoToGo software?  That hasn't been available for like 2 years or more I think...

**Comment by mackworth** [comment]
Sorry didn't get notified. I think it's still avail in the PC

**Comment by IpgGitCode** [comment]
@ejschenck I have an RCN Pace TiVo that also has TTG set to i,i,a,a and forbids downloads. What site did you log in to access your RCN TiVo settings? RCN2GO.com doesn't seem to have it and I can't find out how to add the RCN TiVo to my regular tivo.com account - ??
Thanks

**Comment by ejschenck** [comment]
Try logging into your TiVo account, then click Device Preferences on the left side. Enable video downloads for your Pace box then force it to connect to the TiVo service.

I THINK that's what fixed it. Let me know either way, though...

**Comment by IpgGitCode** [comment]
I have a TiVo account for a non RCN TiVo and that has the preferences but I can't see any way to add the RCN TiVo to that account. I also have an RCN2GO account that manages their TiVo but it doesn't have (or I can't find) the device preferences, similarly with a MyRCN account..

**Comment by ejschenck** [comment]
RCN automatically makes an account when it gets activated. Call TiVo customer service and they can move things around or give you a login for the Pace box. They're really quite helpful.

**Comment by IpgGitCode** [comment]
In case anyone else is searching, eventually found this page, https://www.tivo.com/tivo-mma/login/show.do , that has a link to create an account for a cable company TiVo, https://www.tivo.com/cyril/addemail With the service number and MAK key I was able to create an account, log in  and change the device preferences there.
