### ISSUE TITLE
HD Download Fail

### ISSUE THREAD

**Issue by nicetry1000** [dscottbuch/cTiVo#170]
I'm a returnee to cTiVo after a couple years away.

Recent purchase of TiVo Bolt. Installed it, recorded SD and HD programming.

Non-HD programs downloaded and encoded okay. Any HD programs (8) tried from 3 different channels so far has failed in the download. I selected decrypt only just to test and the HD programs still failed to download. The HD's will download for perhaps 30 seconds then report a fail and retry. After a few retries, I've stopped them.

Any suggestions? Explanations? Perhaps copy-protected content?

cTiVo 2.4.4, OSX 10.10.5 (Yosemite), Latest TiVo Bolt update

Update:
After recognizing problem may be part of the Comcast switch to MPEG-4, I used cTiVo 2.5 alpha with tivodecode-ng and selecting Tivo's transport stream from Advanced Preferences to download an MPEG-2 file. Repeat download and processing to H.264 failed. Currently trying Handbrake on MP2.

**Comment by buck97** [comment]
I may be experiencing the same problem; I use Comcast and downloads recently started failing from BBC America, TNT and a few others. Did Handbrake solve the problem? And did you mean using the Handbrake format built into Tivo, or were you taking a file over to Handbrake itself?
