### ISSUE TITLE
No Sound - Skip Commercials

### ISSUE THREAD

**Issue by mantzm** [dscottbuch/cTiVo#173]
When I encode using Skip Commercials option I get no sound on any of the formats. Yet when I do not use Skip Commercials I get sound just fine. 

What am I doing wrong? Checked the log files and nothing jumps out at me, and I get no error during the process. I'm sure it's something simple that I may have missed.

I'm having no problem connecting to the Tivo Bolt - 

This is on an iMac (Retina 5K, 27-inch, Late 2015) - Processor 4 GHz Intel Core i7 - Memory 32 GB
OS X El Captain Ver 10.11.5

Thanks, Mark M

**Comment by mantzm** [comment]
An additional note - tried just the Mark Commercials option and that work's as it should, still have sound... still no sound with the Skip Commercials option.

**Comment by mackworth** [comment]
So haven't heard anyone with this issue, so nothing obvious. (The other way round: audio, but no video would mean you're running into MP4 issue). 

Which Format are you using?  I know you said "any", but which ones specifically?  Which version of the software? You might use [Mediainfo](https://github.com/dscottbuch/cTiVo/releases/download/2.5.0alpha1/MediaInfo.Document.zip) to diagnose exactly what's in the file.  And try setting debug level to Detail and see if you get any warnings in the log.

**Comment by mantzm** [comment]
The cTiVo version is: Version 2.5 alpha7 (591)
The Media Info Document is here: 
https://dl.dropboxusercontent.com/u/7986262/MediaInfo-Output.txt
This show was done CTiVo format iPhone - Heres the link to them here -https://dl.dropboxusercontent.com/u/7986262/Mark%20Comm%20-%202%20Broke%20Girls%20-%20S03E02%20-%20And%20the%20Kickstarter.mp4

https://dl.dropboxusercontent.com/u/7986262/No%20Comm%20-%202%20Broke%20Girls%20-%20S03E02%20-%20And%20the%20Kickstarter.mp4

Here is the logfile:  
https://dl.dropboxusercontent.com/u/7986262/com.cTiVo.cTiVo%202016-05-25%2013-59.log

Hope the links work - and maybe you can help find the problem.

**Comment by mackworth** [comment]
So the mediainfo shows that it's got an audio track, but it's only 64 milliseconds long.  My guess is there's something wrong with the copy of mencoder in the alpha.
 
Next step would be to get mencoder's log file, which is correctly deleted, as mencoder is reporting no problem. To get it, go to Adv Prefs (`Cmd-Opt-Comma`) and turn on `Don't delete tmp Files`. Then run the download again, and get the log files; they should be named something like `/tmp/ctivo/encode2 Broke Girls- And the Kickstarter.err` and `/tmp/ctivo/encode2 Broke Girls- And the Kickstarter.txt` (To get to the hidden tmp directory, type Cmd-Shift-G in the Finder then `/tmp/ctivo`)  Be sure to turn off the option afterwards.

It would also be great to try the 2.4.4 version. Available here: https://github.com/dscottbuch/cTiVo/releases/tag/2.4.4
to see if it does the same thing.

**Comment by mantzm** [comment]
Good thing is I had already set that option in Adv Prefs - here are the links to the files:
https://dl.dropboxusercontent.com/u/7986262/encode2%20Broke%20Girls-%20And%20the%20Kickstarter.err

https://dl.dropboxusercontent.com/u/7986262/encode2%20Broke%20Girls-%20And%20the%20Kickstarter.txt

I can download the newer version and try that as well.

**Comment by mantzm** [comment]
same problem using Version 2.4.4

**Comment by mackworth** [comment]
Hmm, and this is true for all programs, some, or just a few?

**Comment by mantzm** [comment]
So far I have tested 4-5 programs with all same result

**Comment by mackworth** [comment]
Can you do a Decode-only download (no commercials, etc), and post the mediainfo on it?

**Comment by mantzm** [comment]
forgive me - but how do I do the decode only?

**Comment by mackworth** [comment]
It's one of the Formst choices. I Forget the exact name.

**Comment by mantzm** [comment]
ok I believe were talking about "Decrypted Tivo Show" 
https://dl.dropboxusercontent.com/u/7986262/Decrypted%20Version%20-%20MediaInfo.txt

**Comment by mackworth** [comment]
So that confirms we're not dealing with the MP4 issue. Can you post the resulting decrypted file? Then I can run mencoder on it directly. Thanks

**Comment by mantzm** [comment]
Here is the link to the video - 
https://dl.dropboxusercontent.com/u/7986262/2%20Broke%20Girls%20-%20S03E02%20-%20And%20the%20Kickstarter.mpg

**Comment by sugyfelix** [comment]
I've had problems with mencoder and AC-3 5 channel audio. Could depend on mencoder build options. I've also had problems when the audio has a negative delay to the video (seems common on OTA video.) A quick audio transcode to AAC tends to clean this up @ the cost of another step.

**Comment by mackworth** [comment]
Indeed, @sugyfelix, that seems to be the case. @mantzm, can you try this test version, and let me know if it fixes your problem?  

https://dl.dropboxusercontent.com/u/21507587/cTiVo.zip

**Comment by mantzm** [comment]
@mackworth - no sound with your updated version - just a click sound at the very beginning and video.

**Comment by mackworth** [comment]
Can you post the Mediainfo data on the resulting file?

**Comment by mantzm** [comment]
Here you go - https://www.dropbox.com/s/bouljqeijt5s21p/2%20Broke%20Girls-%20And%20the%20Kickstarter.txt?dl=0

**Comment by mackworth** [comment]
Hmm. That's the same file I tried. Can I get the encoder log file?

**Comment by mantzm** [comment]
where would the encoder log file be hiding?

**Comment by mantzm** [comment]
sorry - figured it out - 
encoder err file - https://db.tt/0zeWOACL
encoded txt file - https://db.tt/T6JjUcUh

**Comment by mackworth** [comment]
Thanks, and can I get the EDL file as well (something like /tmp/ctivo//buffer2 Broke Girls- And the Kickstarter-1.edl )?

**Comment by mantzm** [comment]
sure - https://db.tt/fygFNCJa

**Comment by mackworth** [comment]
So, I'm seeing the same thing; my previous attempt had no EDL file, so no cutting happened, so the bug was not triggered. Basically, mencoder seems to deleting all audio starting at the first cut; in this particular case at the beginning of the file. You've got the older Program Stream format, not the TS, so it's not that problem.   Obvious workaround is to "not do that", just Mark commercials instead of Skipping them. 

What I find surprising is that I can't get mencoder to correctly process audio while cutting commercials with any file, with any options, with the old version or the new. I don't see how this could be true.

**Comment by mantzm** [comment]
@macworth - I going a drastic move here, after having another issue no related at all to this, so I doing a clean install of the OS X operating system. Maybe there was something corrupt in the old. I will follow-up and let you know if that fixes it.

**Comment by mackworth** [comment]
Unfortunately, I see the exact same symptom with mencoder, so I'm pretty sure it's not specific to your system.

**Comment by mantzm** [comment]
ok - well dang...

**Comment by sugyfelix** [comment]
Check to see if the audio offset is negative, i.e. Audio starts before video. Only way I've cured this is to transcode the audio with ffmpeg. I've seen references to skipping the first 1-2 seconds of the recording using a mencoder option (doc not handy @ the moment) but never tried this.

**Comment by ryanchild** [comment]
I was having the same issue, my audio streams also start at a negative timestamp so @sugyfelix may be on to something.  However I gave up on trying to find a solution with mencoder and instead started using ffmpeg with -ss and -to multiple times according to the edl and then merging together.  Works quite nicely as long as you put the -ss before the input file.

**Comment by mackworth** [comment]
That's interesting. Can you give a specific example?

**Comment by ryanchild** [comment]
of mencoder failing? or ffmpeg?

**Comment by mackworth** [comment]
I meant of an edl and matching ffmpeg command

**Comment by ryanchild** [comment]
so for example if the edl is:

4 10 0
15 18 0

ffmpeg -i input.mpg -to 4 segment1.mp4; echo segment1.mp4 >> filelist
ffmpeg -ss 10 -i input.mpg -to 5 segment2.mp4; echo segment2.mp4 >> filelist
ffmpeg -ss 18 -i input.mpg segment3.mp4; echo segment3.mp4 >> filelist

ffmpeg -f concat -i filelist -c copy output.mp4

add in your video and audio options of choice while encoding the segments.  "-to 5" in the second segment is not a typo; i believe when -ss is provided before the input file ("input seeking"), the -ss time is considered to be 00:00:00, so -to effectively becomes a duration rather than a timestamp.  if -ss is provided after the input file, the encode time of later segments increases greatly.  my understanding is that if -ss is provided after the input file then ffmpeg actually encodes up to the -ss time and then tosses it.  it may be possible to achieve the same result with mencoder -ss and -endpos, i have not tried.

[https://trac.ffmpeg.org/wiki/Seeking](url)

**Comment by mackworth** [comment]
Oh, I was hoping you meant one could now put multiple -ss on one command line.  

Still this could be possible with ctivo's architecture by downloading first and then encoding, although it might get confusing about what % completed means.

**Comment by ryanchild** [comment]
yeah sorry to disappoint, i know it's not exactly groundbreaking.  but it seems to be a low-overhead workaround to mencoder's flaky-ness with edls.  i think it should be possible to use this technique to create a wrapper script for cTiVo to call, uncheck simultaneous download and encoding and output a % based on segment lengths after encoding each segment?  obviously would work better when there are more commercial breaks.  haven't tried yet.

**Comment by ryanchild** [comment]
i figured out how to show correct % completed independent of the number of segments with some elaborate scripting.  but now can't seem to figure out how to set some of the fields in the format pane of the preferences that i need to set to work with my script, i opened #181 for that

**Comment by mackworth** [comment]
So while researching this last night, I came across [select/aselect](http://www.ffmpeg.org/ffmpeg-all.html#toc-select_002c-aselect) instead, which looks like it could do it in a single pass.  Have you tried this? 

So in this example, we want to include from 40 seconds to 698 and from 808 seconds to 838.  (the \ in the middle of the line are to quote the following comma
```
0.00	40.00	0
698.00	808.00	0

ffmpeg \
-i /tmp/ctivo/show.mpg \
-vcodec h264  -acodec ac3  \
-vf  select='between(t\,40\,698)+between(t\,808\,838)',setpts=N/FRAME_RATE/TB  \
-af aselect='between(t\,40\,698)+between(t\,808\,838)',asetpts=N/SR/TB \
/tmp/ctivo/show.mp4 
```

the between function returns 1 if t is between the two timevalues, and if the whole value is 1, then select includes the frame in the output buffer.   aselect does the same for the audio stream.  Then you have to fix the timestamp, which is what setpts does.

I tried a couple of passes and it seems good. I did find one comment that aselect is not frame accurate, but I didn't see that problem, so maybe that's been fixed.

See what you think.  If it works, this is something I could include in the main program

**Comment by ryanchild** [comment]
Thanks, gave this a try, it appears to still be decoding/encoding the whole video, just not copying the unselected frames to output (maybe mencoder works the same way?) whereas if you use ss/to it does a fast but accurate seek to the ss point.  So the overall encode time will be longer, depending on how much you're cutting out.  But I think it does avoid some pitfalls with merging certain streams and container types.  I no longer have my testcase so unfortunately can't tell you if this is a valid workaround for this particular bug but maybe you can try on @mantzm 's testcase if it's still in his dropbox.

This seems like it might be tricky to implement cleanly in cTiVo, you'd have to munge the user's own filter settings with aselect/select/setpts/asetpts and if someone tried to do their own aseletct/select filter, they'd be in for a surprise.  awk makes quick work of translating an edl into a filter string or series of ss/to for ffmpeg so IMO either way this is best left to a shell script.  cTiVo's flexibility in encoding options is a major strength here.

BTW, can cTiVo really do simultaneous download & encode while commercial skipping?  doesn't the encoder require a complete .edl before beginning?

**Comment by mackworth** [comment]
Sounds reasonable. If you feel like creating the aselect shell script, I can do some testing of both variants. 

You are correct. commercial skipping disables the simultaneous-ness.

There's an initial version (604) of alpha11 here for you
https://dl.dropboxusercontent.com/u/21507587/cTiVo.zip

**Comment by ryanchild** [comment]
Here you go.  There's some extra junk in both of them to support detecting commercials, extracting captions, fixing the srt, and checking if any of the edl markers are past the end of the video file, so that it can be run without cTiVo and with a custom edl if needed.  You won't need any of that, just pass it an edl with --edl, input with -i and output with -o.  You'll need to brew install gnu-getopt ffmpeg (or update the ffmpeg path to point to the one in cTiVo).

[archive_tivo_one_ffmpeg.sh.txt](https://github.com/dscottbuch/cTiVo/files/417354/archive_tivo_one_ffmpeg.sh.txt)
[archive_tivo.sh.txt](https://github.com/dscottbuch/cTiVo/files/417355/archive_tivo.sh.txt)

Thanks for the new build.

**Comment by mackworth** [comment]
Included in Beta release
