### ISSUE TITLE
cTivo won't accept my correct media access key

### ISSUE THREAD

**Issue by iamrealdave** [dscottbuch/cTiVo#174]
cTivo immediately finds my Tivo box, but won't accept the media access key. It's asking for a new key, even though the media access key is correct.

**Comment by mackworth** [comment]
Does it say "Need new Media key" or "Incorrect Media Key"?

 AFAIK, the only time it asks for a replacement key is if when the login fails. Try logging in directly with the browser (you can get the URL from the logs).  (userName: tivo password: yourMediaKey)

**Comment by iamrealdave** [comment]
Hey, thanks for the quick response. It says incorrect media key. I also tried logging in via browser and it won’t let me in with my media key. Weird , because I know without doubt that is the number that shows up in the Tivo settings area.

**Comment by iamrealdave** [comment]
Just an FYI…I had an old copy of roxio toast that had a tivo transfer app in it. I opened it up and it asked for the media key, I put it in and  connected without a problem.  Crazy …

**Comment by mackworth** [comment]
Make sure no extra spaces? Maybe reboot the TiVo?  If you call TiVo, and tell them the browser won't login? (Don't mention Mac!)

**Comment by iamrealdave** [comment]
I rebooted my Mac and it started working. Go figure. Guess I should have done that first? Oh well thanks for your help. Sorry to bother you….

**Comment by mackworth** [comment]
No problem. Glad it's working!
