### ISSUE TITLE
Metadata to txt file option failing with 570; reverted to earlier version

### ISSUE THREAD

**Issue by Ordinant** [dscottbuch/cTiVo#175]
I heavily rely on the metadata .txt files completely independent of their usefulness to pyTivo. Upgrading from 547 (2.4.0) to 570 (2.4.4) broke the generation and saving of these .txt files, despite the Preference settings that specify doing so. I had to revert back to cTivo 547. 

The metadata .txt files have turned out to be very handy to help catalog and keep track of my enormous collection of movies downloaded from TCM-HD and other channels. Thus, I use and rely on the .txt files for searching and grepping. I do not yet use pyTivo at all.

I have read the notes on 2.4.5 Alpha 1, and I am aware that I will soon have no choice other than upgrading to cTivo's latest version as soon as Comcast in the Boston area puts their H.264 short-sheeting plan in place. At the same time, I am desperate to continue creating and using the metadata .txt files for my own cataloging system.

The Mac that does all of my cTivo-ing is a 2014 Mini running 10.10.5 Yosemite with its latest updates. I specify that cTivo saves to Decrypted TiVo Show format. "Export pyTivo metadata" is selected both in the Options menu and in cTivo's Preferences dialog. Yes, I have exited and restarted cTivo several times, and have rebooted the Mac twice since upgrading to 570. 

I saw your long thread with NoahBuddy in Oct 2015, where he had the identical problem. The .txt files just started working for him, so the thread ended in peace. However, no such peace descends on this house. 

Looking in the cTivo log file for today (the only day that 570 was installed), I see a long series of the "Couldn't convert XML to text using ... pytivo_txt.xslt" errors that you asked NoahBuddy to look for. I am attaching a zip file containing this log file in plain text format.

I have limited time to go through debugging steps, but I will try to comply as much as I can. Please let me know what I can do to make the "it just started working" magic happen here. Is there a cache folder or temporary file folder I can clear? Do you need to compare the xslt files from the two versions? Tell me what I can do to help you figure out this failure. I am very computer literate and Unix/OS X command line literate. Just point me in the right direction. 

Thanks immensely for giving us cTivo and for all the unpaid hours of work it involves. I am sorry to be asking for even more of your time, but there it is.

~Barton Wright

[cTivo_log.zip](https://github.com/dscottbuch/cTiVo/files/290117/cTivo_log.zip)

**Comment by mackworth** [comment]
So, NoahBuddy didn't just start working. He (and you) found a bug in 2.4.4, which accidentally disabled the export. After I generated a test version, it started working (with a minor diversion due to some network problems. If you try the 2.5 alpha, you should be fine; the changes in it should not affect you. Give it a try and let me know.

**Comment by mackworth** [comment]
Hi, @Ordinant  did that work ok for you?

**Comment by Ordinant** [comment]
I didn't get a chance to try it yet. I'll try to find a spare moment tomorrow, Sunday 6/5/16.
