### ISSUE TITLE
Video and audio slightly out of sync

### ISSUE THREAD

**Issue by burdell1** [dscottbuch/cTiVo#176]
I haven't used cTivo in awhile, but just started to again recently and i am having some issues with the video & audio slightly out of sync. I am using H.264 high quality

**Comment by burdell1** [comment]
Is anyone else having this problem?

**Comment by jasonian** [comment]
Yes. Anywhere from a small fraction of a second to a second. Decrypted TiVo Show does not have this issue. 

I noticed it with an older version of cTiVo (2.1), and 2.5 Alpha 7 (591) also has it.

**Comment by mackworth** [comment]
So this is due to the encoding process, and thus will vary based on which Format you use. I primarily use the AppleTV one and have not noticed much problem here.  The alpha release has ffmpeg bundled into it, and so you may be able to create a better Format using that.

**Comment by mackworth** [comment]
See the answer to issue #179 for a possible fix here as well...
