### ISSUE TITLE
Is there a setting to download file in original .Tivo format?

### ISSUE THREAD

**Issue by hito0** [dscottbuch/cTiVo#177]

**Comment by mackworth** [comment]
No, but you can get the decrypted version (no video processing, exact byte copy) with Decrypted TiVo show (or some such name)

**Comment by mackworth** [comment]
Oh, if you're looking to this file for some debugging reason, then you can go to Adv Pref (Cmd-Op-Comma) and turn on "Don't delete temp files". Thus will leave ALL the temp files created (including the .tivo) during processing; most in /tmp/ctivo. Be sure to turn it off when done with it. Note you will also want to turn off the Use Memory Buffer, or it will create the .tivo file solely in memory.

**Comment by hito0** [comment]
I wanted to do it this way so that I would be able to send them back to the TiVo box. Is there an easier way? Also, what is decrypted TiVo? Thanks for your help

**Comment by mackworth** [comment]
The best to send back is pyTivo. Actually any format video can be used, and it will convert on the fly as needed.
