### ISSUE TITLE
input fields in formats not editable

### ISSUE THREAD

**Issue by ryanchild** [dscottbuch/cTiVo#181]
If I create a new format or duplicate an existing one, the "Edit List (edl) switch" and "RegEx for Encoder Log" fields are not editable.  What am I missing?

**Comment by ryanchild** [comment]
Using 2.5 alpha10 (602) on os x 10.11.6

**Comment by mackworth** [comment]
You are correct; I'm not sure when this got introduced. My apologies, and I'll fix it in the next version. 

Easiest work around is to export the format to a plist (File>Export Format); then edit the plist in any text editor and then reimport it (File>Import Format). It will create a new format with those changes and -x added to the name.  If you're not familiar with plists, you'll see the fields:

```
		<key>edlFlag</key>
		<string></string>
		...
		<key>regExProgress</key>
		<string></string>
```

Just put the value you want between the `<string>` and `<\string>`. Note that you'll need to escape certain characters:
```
&lt; represents "<";
&gt; represents ">";
&amp; represents "&";
&apos; represents "'";
&quot; represents '"'.
```

**Comment by ryanchild** [comment]
No need to apologize and thanks for the workaround.  Looks like NSNegateBoolean somehow got dropped from edl and regex text box control bindings in 761df5169254fd3386f0748b40ee698a1a275b8b back in May. 

Yes I'm familiar with plists.  I use the property list editor, now part of xcode, I think it's smart enough to not need escapes.

**Comment by mackworth** [comment]
Yup; it's still strange. I took out the enabled bindings on all the fields, so one could copy/paste from a built-in one. Still puzzled how that removed the negate transform.
