### ISSUE TITLE
General Question, Sorry.

### ISSUE THREAD

**Issue by miadlor** [dscottbuch/cTiVo#182]
I've downloaded and clicked on the program and it came right up. I'm in the process of running it now. My question is, 1. is this self contained? I'm not able to find any file folders for the program. 2. It auto magically grabbed my TiVo's MAK  from somewhere.....I never entered it.

**Comment by mackworth** [comment]
Sorry to be so ... easy to use?  :)  Hope it continues for you...

Yes, there is just the program itself on the download. For data, it does create a temporary folder (/tmp/ctivo), but that will be transparent to you. Secondly, it has the download directory (displayed on upper right).

On the MAK, maybe you ran iTivo long, long ago? If so, we'll pick up that MAK.

**Comment by miadlor** [comment]
Thank you!
I did try iTiVo......I removed it though......do you know where it's holding the info?

**Comment by mackworth** [comment]
It's in ~/Library/Preferences/com.ctivo.ctivo.plist  (and on first startup, we check for com.itivo.itivo.plist)

**Comment by miadlor** [comment]
Thanks again, I'm not seeing either the chive or the itivo plist. (I have hidden files  set to show), not anywhere and a search brings nothing (el Capitan).

**Comment by miadlor** [comment]
Found a hidden library....all set, Sorry again.

**Comment by mackworth** [comment]
No problem!  Hope you like it.

**Comment by miadlor** [comment]
Well first dL failed....investigating.

**Comment by mackworth** [comment]
So, Help>Show Logs and doubleclick to see what happened.
To get more info, Preferences>Debug Level to Detail and try again.  If not obvious, feel free to post the relevant part of the log here!

**Comment by miadlor** [comment]
So, log showed it lost connection to the TiVos (1st try H.264 small 1Mbps).....maybe because computer might have went to sleep.
Changed setting...2nd try was Decrypted TiVo Show.....fast and ran good, but not compatible with iMovie (All I have right now to edit with).
3rd try was with Apple TV setting and it works iMovie. You did a great job!

**Comment by miadlor** [comment]
Playback through PLEX works also.

**Comment by mackworth** [comment]
If you’re using Plex, make sure you set the filename Template in Adv Preferences (Cmd-Opt-Comma, then Keywords>•Plex Folders). Turn off Preferences>Create SubFolders for Series.

That should put the files exactly where they should be…

**Comment by miadlor** [comment]
Thanks for the Plex info!!!!
