### ISSUE TITLE
add wrapper script to allow commercial skipping with ffmpeg

### ISSUE THREAD

**Issue by ryanchild** [dscottbuch/cTiVo#183]
or maybe it's user error.  I'm using one of the scripts I posted in #173 with this "RegEx for Encoder Log"

 ([\d\.]*?) \%

After it got to the encode step there was no progress bar for a minute or so and then the status went to "failed."  but the encoding is still happening as evidenced by ps, my mac mini's fan and the cTiVo log file, which keeps printing this:

016-08-18 20:23:04:916 MTDownload>encodeTask@1275>Encode progress with Rx failed for task encoder for show Austin City Limits: Beck
Encoder report: 7 %
19.83 %
19.99 %
20.19 %
20.35 %
20.51 %
20.64 %
20.80 %

The %s are my script's STDOUT and reflect the encode progress.  cTiVo seems to be having trouble reading it?

**Comment by mackworth** [comment]
So, I've spent a lot of time on this, and I think I've figured it out.

First a few notes on the script ( I worked with the archive_tivo_one_ffmpeg.sh one)
A) wow.  serious script-fu; some nice tricks in there. Just reading took a while.
B) It then took me quite a while to create a matching Format, and then figure how to debug, where the output was going etc. Trickiest one to figure out was apparently `-edl` option doesn't work; has to be -e. awk says "can't open file dl"
C) At least my copy of ffmpeg complained that " experimental aac requires -strict -2" 

Finally got it to launch, and then it seemed to run fine (although it only seemed to clip the first EDL line), with progress reporting just fine.

Then I tried a different video and it failed. 

So, I think I know what's going on. Because of occasionally crashy/flaker sub-binaries, cTiVo notices if it doesn't get a progress update every two minutes. That works great if the encoding is simultaneous with the downloading, but I think it has a chance of failing if not. Specifically, we reset progress to zero at the launch of each phase, but we don't reset that timer.  So, if your script takes a little while to run, it would keep the encoding progress at zero for a little while. If the prior progress check also happened to be in a period where progress was zero (e.g. start of commercial-ing), then it would immediately fail even though there has been progress since then.

So, one workaround is to write "1.00 %" to the output stream immediately upon the start of your script. 

Another  to increase the MaxProgressDelay preference to a much bigger number than the default 120.
`defaults write com.cTivo.cTivo MaxProgressDelay 1200`

Let me know if those fix it for you.  If so, sounds I've got two things to fix; one to reset that timer on each phase during non-simultaneous encoding, and two to actually cancel background tasks when we cancel the subtask within ctivo.  (ffmpeg should not have continued on by itself...)

**Comment by mackworth** [comment]
Ah, just went back to your original post. Nope, if my theory was correct, you wouldn't have gotten the "Encode progress with Rx failed"; that only comes up if the regex fails to match anything, which doesn't make sense given that regex and that data dump.  Can you export your Format and post your copy of ffmpeg somewhere so I can try to recreate exactly what you got?

````
                    if (data) {
                        values = [percents matchesInString:data options:NSMatchingWithoutAnchoringBounds range:NSMakeRange(0, data.length)];
                    }
                    if (values && values.count) {
                        NSTextCheckingResult *lastItem = [values lastObject];
                        NSRange r = [lastItem range];
                        if (r.location != NSNotFound) {
                            NSRange valueRange = [lastItem rangeAtIndex:1];
                            returnValue =  [[data substringWithRange:valueRange] doubleValue]/100.0;
                            DDLogVerbose(@"Encoder progress found data %lf",returnValue);
                        }

                    }
                    if (returnValue == -1.0) {
                        DDLogMajor(@"Encode progress with Rx failed for task encoder for show %@\nEncoder report: %@",self.show.showTitle, data);

                    }
````

**Comment by mackworth** [comment]
Another theory: you're getting errors in the ffmpeg log, so you're not finding timestamps in the last 200 chars, so you're outputting 0.00 % to the log?

**Comment by ryanchild** [comment]
Thanks for looking into this Hugh.

The option is actually --edl (two hyphens) or -e rather than -edl with a single hyphen like the mencoder option, sorry for the confusion.  I haven't come across any issues with it skipping edl sections or failing yet, I've tried it on 3 different OTA broadcast types so far.

I'm using the latest ffmpeg in homebrew, 3.1.1, though I get the same result using the ffmpeg binary bundled with cTiVo.  You're right, the -strict -2 is required when encoding aac with the ffmpeg binary bundled with cTiVo.  In 3.1.1, it's not required.

In the time since I posted those scripts I found the same thing you did; it could output 0% when there were errors in the input, so I increased the tail to 1000 characters and no longer notice it jumping back and forth between 0%.  If I download the same video and run archive_tivo.sh on it standalone, I don't see any 0.00% except at the very beginning.

cTiVo only leaves the script running after failing if commercial skipping is enabled.  If I turn off commercial skipping, cTiVo comes to terms with the fact it can't figure out the script's progress and kills it:

```
2016-08-20 02:09:55:567 MTDownload>encodeTask@1275>Encode progress with Rx failed for task encoder for show Austin City Limits: Beck
Encoder report: 30 %
1.44 %
1.55 %
1.66 %
1.78 %
1.86 %
1.97 %
2.08 %
2.19 %
2.33 %
2.41 %
2.55 %
2.66 %
2.80 %
2.91 %
3.08 %
3.25 %
3.41 %
3.55 %
3.66 %
3.80 %
3.97 %
4.19 %
4.24 %
4.33 %
4.44 %
2016-08-20 02:09:55:950 MTDownload>checkStillActive@2105>process stalled at 0.0%; rescheduling show Austin City Limits: Beck 
2016-08-20 02:09:55:950 MTDownload>cancel@2048>Canceling of Austin City Limits: Beck
2016-08-20 02:09:55:950 MTTask>cancel@100>Terminating task encode
2016-08-20 02:09:55:950 MTDownload>cancel@2072>Waiting 0.000001 seconds for write data to complete during cancel
2016-08-20 02:09:55:950 MTDownload>cleanupFiles@487>Austin City Limits: Beck cleaningup files
2016-08-20 02:09:56:027 MTDownload>rescheduleShowWithDecrementRetries:@247>Stalled at Encoding, canceled download of Austin City Limits: Beck with progress at 0.000000 with previous check at 2016-08-20 08:07:55 +0000
2016-08-20 02:09:56:027 MTDownload>observeValueForKeyPath:ofObject:change:context:@155>Changing DL status of Austin City Limits: Beck (Living Room) to Failed (16)
2016-08-20 02:09:56:027 
```

So aside from the apparent bug where cTiVo doesn't kill the encoder when commercial skipping is enabled, the issue at hand seems to be a matter of cTiVo just not being able to match the regex.  The very first line of data after "Encoder report:" looks weird... it says 30% even though the script is only at 5%.  Maybe this is just because of cTiVo grabbing the last 180 bytes of the encoder output and it just happens to get cut off after the decimal point.  HandBrake does have a lot of other output that would make this less likely to happen?  But I tried changing the regex to (\d+\.\d+) \% to no avail.

[archive_tivo.plist.txt](https://github.com/dscottbuch/cTiVo/files/428173/archive_tivo.plist.txt)

**Comment by ryanchild** [comment]
OK I got it working

1. There was a leading space before the regex which I copied from HandBrake, works for Handbrake since the % is part of a long status string but not for my script.
2. I updated my script to print updates every second instead of every 5 seconds. cTiVo was just grabbing the first match in the latest 180 bytes from the encoder output, and since my script was only outputting 5 or so bytes every 5 seconds, cTiVo kept getting the first match in the first 180 bytes (0%) and thought it was stalled.  180 bytes might be a reasonable assumption for a program like Handbrake but I guess not necessarily for user scripts like this.  I don't know if you want to either document that or provide an option to configure how far back in the encoder output cTiVo searches.

I guess let's close this bug and you can investigate cTiVo not killing the encoder when commercial skipping is enabled separately if you want.

Again, thanks for looking into this.

**Comment by mackworth** [comment]
1) Ah, the joy of having a single character screw everything up (both the space and the hyphen)
2) ctivo grabs the last match, not the first (`[values lastObject]`), but I can look into that more.
3) After further testing, I'm planning on including this script in the process. can you do a version that can't be run standalone, but does pass the ffmpeg options through from the Format? Then if someone wants to do a simple change, just change those parameters, but more complicated ones (e.g. changing aselect) they'd have to copy and edit the script

**Comment by ryanchild** [comment]
Oh ok I didn't see `[values lastObject]` ...I copied that code into a test area and looks like it does indeed grab the last match.  So there goes that theory.  It must have just been like you said, cTiVo kills the encoder if it sees no progress during the checkStillActive which if it doesn't take the data on stdin, is determined by the regexp match, correct?  I guess it just needed a few more seconds to get to 1% which is why switching to updating every 1s instead of 5s worked.

I'm not sure what you mean by "can't be run standalone"
I guess I can modify archive_tivo_one_ffmpeg.sh to take --ffmpeg-options like archive_tivo.sh, scan it for -vf and -af options, append those to the auto-generated select filters, and pass the rest through.
When you say "including this script in the process" do you mean you're going to call it behind the scenes when "ffmpeg" is found in the format encoder string?  Or you just want to bundle these scripts as examples for people to use if they want in their user formats?  I guess I had the latter in mind.
Either way I should probably just contribute these rather than continually attaching them to bug comments.  Let me know where.

**Comment by mackworth** [comment]
If you just put out "1.00%" at the beginning, that would help. For the case of not finding a %, maybe remember the last value and repeating it, if you can't find one.  Better than reporting 0%!

I meant that this would be bundled in ctivo, called "ffmpegSkip.sh" or something, so usable if someone wants to use comskip with ffmpeg. Not hiding ffmpeg, but acting like it from the options point of view. 

So, I'm hoping you can just copy the video, audio, and other options through, adding the select/aselect as necessary. 

I'm away from home for the next couple days, so I'll have to get back to you on the where question. 

Thanks for contributing!

**Comment by ryanchild** [comment]
Yep that's what I was thinking too.  Maybe put in cTiVo/cTiVo/cTiVoBinaries/bin/scripts and then the format encoder field would be something like "scripts/ffmpegSkip.sh"?

Thanks for the suggestion, I've made a few changes:
* print 1% if progress is less than 1%
* don't print 0%
* only print when the % changes
* add `--ffmpeg-options` to the accepted arguments
   * look for "-vf" and "-af" and save those off, append to the cut filters if an edl file is present, or pass them through
* fixed the bug where only the first edl cut was applied

Now that I've had a chance to test the filter version of the script a bit with a smaller video file, I'm seeing a/v sync issues.  I am having better luck with trim/atrim/concat filters but it looks like progress will be harder to track.  I am still partial to -ss and -to 😀 

The 1% thing feels like a hack and I have to admit I'm still a bit confused on this; don't we risk getting canceled by outputting a non-changing percentage (1% for the duration between 0 and 1%) for two minutes, when encoding a very large file?  And what if checkStillActive ran when the previous task was at exactly 1% (very very unlikely but still technically possible)?  Ideally shouldn't checkStillActive be done on a per-sequential-barrier basis instead of over the entire download/decode/ccextract/comskip/encode process?

**Comment by mackworth** [comment]
I think .../bin is fine, so we can skip the scripts/, and so it can refer just to ./ffmpeg (which I'm getting upgraded). 

Rather than --ffmpegoptions, can it just pass through any unrecognized options?  

The 1% is just to reduce the odds. I agree I do need to figure out how to reset the check on each phase. It's a little tricky because it's a pipelined architecture.

**Comment by ryanchild** [comment]
Sure I can have it pass its args directly to ffmpeg but intercepting -edl (I'll change it to the single dash to keep consistent with ffmpeg's argument naming convention).  I need to get rid of the use of /usr/local/opt/gnu-getopt/bin/getopt before I check in anyway.  I think I will add another option to enable the detection of 5.1 audio and if present, create an ac3 stream in addition to the aac, which the script does today but could cause conflicts if the user provides their own audio settings.  This is something I wanted and have seen requested on other issues here as well.

Before I re-write the filter string to use trim/concat instead of select/setpts which causes a/v sync issues, remind me again why we don't just want to use -ss and -to?  Using filters might seem cleaner because we're only calling ffmpeg once, but it's all the same to the user. There's a chance cTiVo might kill the filter version since progress will pause while ffmpeg is decoding and throwing away frames not selected by the filters.  And -ss/-to is faster.

**Comment by mackworth** [comment]
I haven't really been able to try/compare the two, so happy to take your lead ( on filter v ss). 

Be sure to use unique file names (might have two running at once); you can rely on the output name being unique, just add a counter. 

5.1 is great, but don't worry about option, the audio size is so small compared to video, redundancy is not a problem.

**Comment by ryanchild** [comment]
As I start to use this more heavily in cTiVo I'm noticing that some downloads move from "Encoding" to "Encoded" but never move from "Encoded" to "Complete"
The output shows up and the queue moves on so there don't appear to be any other consequences, but would be nice to get a consistent "Complete."  Could this also have to do with the regex output?  Maybe I need to output "100 %" at the end?

**Comment by ryanchild** [comment]
whoops, probably should wait for if/when you merge my pull request before closing

**Comment by mackworth** [comment]
)n your last point of not moving from Encoded to Complete:
The encodeTask's completion handler (called when the subtask terminates without an error code) marks the download as Encoded.
Then i followed the code to see what msgs/exits are possible.

1) Assuming the output file is found (else msg: " file not found after encoding complete")
2)  it checks to see if all the tasks are completed; if not, wait until they are (Msg: "Finishing up, but processes still running")
3) Msg: "Started finishing"
3) it confirms both the decrypt and encoder tasks successfully completed (would be odd to get here otherwise, Msg: "Strange; thought we were finished...")
4) then it does various optional postprocessing steps (pytivo metadata, adding artwork, markgin commercials, embedding subtitles, embedding metadata, moving to itunes, adding the Xattrs); none of which can prevent the last last step:
5) the notification "TiVo Show transferred", and it's marked as Done

So if you can set Download to Verbose (I assume you've seen the Adv Pref screen) and run until one fails like you said, then see which msgs come out.  I'll also keep an eye out as I try your script.

**Comment by ryanchild** [comment]
Thanks. I think the encode was getting killed as stalled at 100% so I added a second 0-100% progress meter during the merge step of the script and that seems to have fixed it.  In my branch, ffmpeg_edl_ac3.sh counts to 100 while encoding the segments and then starts over and counts to 100 again during the merge, to make sure it doesn't stall for longer video lengths that may take 2 minutes or longer to merge.

**Comment by mackworth** [comment]
Note further comments in pull request:  https://github.com/dscottbuch/cTiVo/pull/185

I note that I didn't yet install the new Format as a built-in.  So here's my proposed version; haven't thought about the name yet.

[Wrapper dup.plist.txt](https://github.com/dscottbuch/cTiVo/files/438490/Wrapper.dup.plist.txt)

**Comment by mackworth** [comment]
Hi, Ryan. In further testing, found that `dirname $0` for the ffmpeg script fails if the ctivo path has a space in it.  How do I fix that, and are there other such places in the script?

**Comment by ryanchild** [comment]
Hmm try wrapping "$ffmpeg_path" in double quotes wherever it's used.  Hopefully all other file names in the script are double quoted.

**Comment by ryanchild** [comment]
Yeah that seems to have fixed it, see #186

**Comment by mackworth** [comment]
Still needs much testing, but I've pushed what I have to date.

**Comment by mackworth** [comment]
Ok, a question...
1) I'm getting an error sometimes when I don't give the script an EDL. The error is that the log file "tmpdir/filename_ffmpeg/ffmpeg.txt: No such file or directory"

 It might be when filename has a single quote in it. 
What is the purpose of >& in   `"$ffmpeg_path" "$@" "$output" >& "$logfile" &`?  When I try an `"echo 'hello' >& filename"` I get the same msg, whether or not filename exists, but again it seems to require a ` in the filename

**Comment by ryanchild** [comment]
the `>& "$logfile"` just means redirect both stdout and stderr to $logfile.  If you have a chunk of code I can type into bash interactively I can try to suggest a workaround?

**Comment by mackworth** [comment]
It does seem to be specific to single-quotes:

echo "hello" > "/tmp/ctivo/test's/junk.txt"
echo "hello" >> "/tmp/ctivo/test's/junk.txt"
echo "hello" >& "/tmp/ctivo/test's/junk.txt"
-bash: /tmp/ctivo/test's/junk.txt: No such file or directory

**Comment by ryanchild** [comment]
Fascinating.  No idea what's going on here, but rewriting `>&` as `&>` seems to fix it.  According to the bash man page these both do the same thing but the latter format is preferred.

**Comment by mackworth** [comment]
Thanks. That does seem to work, although I agree it shouldn't matter.

**Comment by ryanchild** [comment]
`read -t 1.0 -N 0` is giving me this error:

```
read: 1.0: invalid timeout specification
```

I wonder if this is for a different version of bash?  This works: `read -t1 -n0`

**Comment by ryanchild** [comment]
Although on second thought I'm not sure I'm convinced that using `sleep` is an issue.  The `tail`, `grep`, and `awk` commands in the loop also increment the PID counter once per command per loop (actually twice for `tail`), so that is happening anyway.  The OS will recycle the PIDs but if you're worried about it the best thing to do would be to increase the loop iteration rate from 1s to 10s or longer.

**Comment by mackworth** [comment]
I think you're right on both counts. Somehow I got up into the 100,000s of PIDs,  and I thought the sleep changed fixed it.   However you want to set it up is fine.

**Comment by mackworth** [comment]
Ah,and could you look into two other things from testing. First, instead of pointing to the log files, could you copy them (or a reasonable chunk of the end of them)?  They normally get deleted automatically.  Second, there's an issue with single quotes in the filename: 
````
 [concat @ 0x104000800] Impossible to open '/Volumes/External/ctivo tmp/CatDog - S02E27-E28 - Surfing Dog; Guess Whos'
/Volumes/External/ctivo tmp/CatDog - S02E27-E28 - Surfing Dog; Guess Who's Going to Be Dinner-1_ffmpeg/ffmpeg_merge.txt: No such file or directory
````

**Comment by ryanchild** [comment]
Ok I think I can fix the quoting issue, but not sure what you mean by pointing to the log files vs copying? Which log files should we be copying and to where?  cTiVo won't delete `$tmpdir` while the script is running will it?

**Comment by mackworth** [comment]
Sorry, I was referring to the line  "error: problem generating $output, see $logfile for details". When running in Detail mode when a failure happens, the last bit of the script's logfile gets copied to the ctivo log to help figure out what's wrong. So I see that message, but by that point the ffmpeg directory is gone. So it would be good to copy the last bit of that "sub"-logfile into the script's log.

**Comment by ryanchild** [comment]
Oh I see.  Yeah I guess I could add the last line of the ffmpeg log to the wrapper script log. Would this work:

```
error: problem generating $output:
$lastline
see $logfile for details 
```

How many lines of the encoder log does cTiVo copy to the cTiVo log?

**Comment by mackworth** [comment]
The last 2000 characters.

**Comment by ryanchild** [comment]
While investigating the quote thing I realized the merge step was mixing up streams in some cases, copying the video stream twice which is obviously a pretty big flaw 😳 
So I fixed that as well, along with the two things you mentioned above and some other minor things.  See #192

**Comment by mackworth** [comment]
Great, and thank you.  This stuff is always harder than it looks. 

I've spent a lot of time chasing down interprocess issues, and I think this version is, by far, the most reliable to date, and with better tracking.  Among many others, I found mencoder in streaming mode was buffering ~28M and then just stopping import for about 2.5 minutes, which is about how long it takes to process that much, then running again, so I extended the timeout to 4 minutes.  Also, you can now Quit or Pause without affecting the current task and it will properly complete.

I ran ~100 shows last night with all the kinds of different configurations (Formats, comskip, captions, PS/TS, etc) without a single failure. I've got a couple more steps, then I think we've got a beta.

I tried out your new version, and it wasn't putting out enough characters to keep the main program happy (started reading when there were 180). So I reduced that in cTiVo to 20, as well as ramped up your output to 3 seconds.  

Latest built version (641):  https://dl.dropboxusercontent.com/u/21507587/cTiVo.zip

Next step is to update the binaries.

**Comment by ryanchild** [comment]
Excellent.  BTW note there are some TODO comments in the script to remove the -strict -2 ffmpeg args after upgrading the ffmpeg binary.

**Comment by mackworth** [comment]
Ok, so I've got a file, which is definitely a problem video file, but the script reports it as completing, but with a zero length video file.  When I run it standalone, I get the following:

````
/Users/hugh/Library/Developer/Xcode/DerivedData/cTiVo-efjhciycmsjgiwduxrumsyrgqxji/Build/Products/Debug/cTiVo.app/Contents/MacOS/ffmpeg -i '/Volumes/External/ctivo tmp/bufferThe Thin Man - S02E09 - Murder in Mink-14.mpg' -map 0:0 -map 0:1 -vcodec h264 -vf yadif -c:a:0 aac '/Volumes/External/TivoShows/TV Shows/The Thin Man/Season 02/The Thin Man - S02E09 - Murder in Mink-14.mp4'
ffmpeg version 3.1.3 Copyright (c) 2000-2016 the FFmpeg developers
  built with Apple LLVM version 8.0.0 (clang-800.0.38)
  configuration: --prefix=/opt/local --enable-swscale --enable-avfilter --enable-avresample --enable-libmp3lame --enable-libvorbis --enable-libopus --enable-libtheora --enable-libschroedinger --enable-libopenjpeg --enable-libmodplug --enable-libvpx --enable-libsoxr --enable-libspeex --enable-libass --enable-libbluray --enable-lzma --enable-gnutls --enable-fontconfig --enable-libfreetype --enable-libfribidi --disable-indev=jack --disable-outdev=xv --mandir=/opt/local/share/man --enable-shared --enable-pthreads --cc=/usr/bin/clang --enable-vda --enable-audiotoolbox --enable-videotoolbox --arch=x86_64 --enable-yasm --enable-gpl --enable-postproc --enable-libx264 --enable-libxvid --enable-nonfree --enable-libfdk-aac --enable-libfaac
  libavutil      55. 28.100 / 55. 28.100
  libavcodec     57. 48.101 / 57. 48.101
  libavformat    57. 41.100 / 57. 41.100
  libavdevice    57.  0.101 / 57.  0.101
  libavfilter     6. 47.100 /  6. 47.100
  libavresample   3.  0.  0 /  3.  0.  0
  libswscale      4.  1.100 /  4.  1.100
  libswresample   2.  1.100 /  2.  1.100
  libpostproc    54.  0.100 / 54.  0.100
[mpegts @ 0x7fc28a809200] start time for stream 0 is not set in estimate_timings_from_pts
[mpegts @ 0x7fc28a809200] PES packet size mismatch
[mpegts @ 0x7fc28a809200] Could not find codec parameters for stream 0 (Video: mpeg2video ([2][0][0][0] / 0x0002), none(tv)): unspecified size
Consider increasing the value for the 'analyzeduration' and 'probesize' options
[mpegts @ 0x7fc28a809200] Could not find codec parameters for stream 2 (Unknown: none ([151][0][0][0] / 0x0097)): unknown codec
Consider increasing the value for the 'analyzeduration' and 'probesize' options
Input #0, mpegts, from '/Volumes/External/ctivo tmp/bufferThe Thin Man - S02E09 - Murder in Mink-14.mpg':
  Duration: 00:35:00.03, start: 79903.353711, bitrate: 2337 kb/s
  Program 1 
    Stream #0:0[0xe05]: Video: mpeg2video ([2][0][0][0] / 0x0002), none(tv), 90k tbr, 90k tbn, 90k tbc
    Stream #0:1[0xe06]: Audio: ac3 ([129][0][0][0] / 0x0081), 48000 Hz, stereo, fltp, 192 kb/s
    Stream #0:2[0xe07]: Unknown: none ([151][0][0][0] / 0x0097)
File '/Volumes/External/TivoShows/TV Shows/The Thin Man/Season 02/The Thin Man - S02E09 - Murder in Mink-14.mp4' already exists. Overwrite ? [y/N] y
[buffer @ 0x7fc28a5321e0] Unable to parse option value "0x0" as image size
[buffer @ 0x7fc28a5321e0] Unable to parse option value "-1" as pixel format
[buffer @ 0x7fc28a5321e0] Unable to parse option value "0x0" as image size
[buffer @ 0x7fc28a5321e0] Error setting option video_size to value 0x0.
[graph 0 input from stream 0:0 @ 0x7fc28a5320c0] Error applying options to the filter.
Error opening filters!
Hughs-MacBook-Pro:~ hugh$ echo $?
1
````
So, it looks like the script is not checking the return code from ffmpeg, and because ffmpeg is creating a zero length file, it's reporting everything is good. Thoughts?

**Comment by ryanchild** [comment]
You're right, the script only checks if a video stream is present and ffmpeg writes a file. Try replacing `-f` with `-s` to check if the file exists AND is not zero size.  You can check for a nonzero ffmpeg exit status if you want too, with `wait $pid` after complete and then reading `$?`

**Comment by mackworth** [comment]
And in another error situation, I'm getting the following in the log.

````
awk: syntax error at source line 1
 context is
	BEGIN {total=0} {total += ( >>>  < <<<  $2 ?  : $2)-$1} END {print total}
awk: illegal statement at source line 1
(standard_in) 2: parse error
````
and when I print out $fileinfo, I get:
````
ffmpeg version 3.1.3 Copyright (c) 2000-2016 the FFmpeg developers built with Apple LLVM version 8.0.0 (clang-800.0.38) configuration: --prefix=/opt/local --enable-swscale --enable-avfilter --enable-avresample --enable-libmp3lame --enable-libvorbis --enable-libopus --enable-libtheora --enable-libschroedinger --enable-libopenjpeg --enable-libmodplug --enable-libvpx --enable-libsoxr --enable-libspeex --enable-libass --enable-libbluray --enable-lzma --enable-gnutls --enable-fontconfig --enable-libfreetype --enable-libfribidi --disable-indev=jack --disable-outdev=xv --mandir=/opt/local/share/man --enable-shared --enable-pthreads --cc=/usr/bin/clang --enable-vda --enable-audiotoolbox --enable-videotoolbox --arch=x86_64 --enable-yasm --enable-gpl --enable-postproc --enable-libx264 --enable-libxvid --enable-nonfree --enable-libfdk-aac --enable-libfaac libavutil 55. 28.100 / 55. 28.100 libavcodec 57. 48.101 / 57. 48.101 libavformat 57. 41.100 / 57. 41.100 libavdevice 57. 0.101 / 57. 0.101 libavfilter 6. 47.100 / 6. 47.100 libavresample 3. 0. 0 / 3. 0. 0 libswscale 4. 1.100 / 4. 1.100 libswresample 2. 1.100 / 2. 1.100 libpostproc 54. 0.100 / 54. 0.100 /Volumes/External/ctivo tmp/bufferSea Hunt - S03E08 - Missile Watch-3.mpg: Invalid data found when processing input
````

 I think the gist of it is that $original_duration is empty in this case. So I think we just need  to add:
````
if [ -z "$original_duration"]; then
  echo "Problem with ffmpeg's info: No Duration information:"
  echo "$file_info"
  exit 1
endif
````
Does that look right?

**Comment by mackworth** [comment]
So, how does `wait $pid` interact with `kill -0 $pid`? If the latter returns an error, doesn't that mean that the process is over, so won't the `wait` fail because there is no such process?

**Comment by ryanchild** [comment]
Yes your code to handle no duration looks correct. 
I believe you can call `wait` on a completed pid and it will simply store the exit status returned by that pid when it completed in `$?` and return.

**Comment by ryanchild** [comment]
See #193

**Comment by mackworth** [comment]
Okay, so if I can impose then, here are the two changes I did. If you can confirm that they are represented in your changes, so I can just throw mine away and pull yours, that'd be great.

````
  wait $pid
  ffmpeg_result=$?
  if [[ $ffmpeg_result > 0 ]]; then
    echo "error from mpeg: $ffmpeg_result; ffmpeg logfile ($logfile):" >&2
    cat "$logfile"
    exit 1
  elif [ ! -s "$output" ]; then
    echo "error: No output file found (or empty); ffmpeg logfile ($logfile):" >&2
    cat "$logfile"
    exit 1
  fi

  last_percent="$max_percent"
  echo "$last_percent" | awk '{printf("%.2f %%\n",$1)}'
  pid=
````

and 
````
if [[ -z "$original_duration" ]]; then
  echo "Problem with ffmpeg's info: No Duration information:"
  echo "$file_info"
  exit 1
fi
````

**Comment by ryanchild** [comment]
Yeah, except the error text is a little different, and I check after printing last_percent instead of before.

**Comment by ryanchild** [comment]
OK you're right the check should happen before printing last_percent, now my branch should match except for slight differences in the error text.

**Comment by mackworth** [comment]
Thank you; merge went smoothly this time!  

Bash programming is just the worst. While making that original duration change, I got the so-helpful error msg of "Unexpected end of file"; It took me ten minutes of staring at it to see the problem. fie on bash; just fie!

**Comment by ryanchild** [comment]
Yeah debugging shell scripts is a pain compared to C, especially when they start to get long 😄 

Currently the script encodes ac3 5.1 to both aac and ac3, what do you think about adding `-ac:a:0 2` to the audio options?  This will make sure the aac track is stereo, currently they're both 5.1 even though I think most players can't play 5.1 aac (which is why I added the ac3 to begin with)

**Comment by mackworth** [comment]
Whatever you think, but that sounds good to me.

**Comment by ryanchild** [comment]
OK, I added it in #194

Since the audio options are added after the post-input user options, any user audio encoding options will take precedence.

**Comment by mackworth** [comment]
Oh, btw: When a show is launched, Detail logging now gives the exact arguments in a string that can be just copy/pasted into bash for each of the subcomponents, so you can recreate it without launching the whole chain. Two caveats: if it's piped, you'll need to cat it a source file, and I strip out the media key from the log in general.

**Comment by ryanchild** [comment]
OK nice, that should make debugging easier.

**Comment by ryanchild** [comment]
Wow, great detail in the Background section, and thanks for the props!

I have to admit I'm not very informed on the technical details of TS vs PS but your explanation sounds right to me.  I've noticed issues with decrypting MPEG2 in transport streams too, I came across this comment in this thread which seems to suggest that even tivodecode-ng isn't perfect when it comes to decoding TS: http://www.tivocommunity.com/tivo-vb/showthread.php?p=10421061#post10421061

**Comment by ryanchild** [comment]
It might be good to clarify the "few limitations" of the wrapper script, these are the only ones I'm currently aware of:

* If `-edl` is provided, the video will be encoded in several chunks, so don't assume anything about duration.  In particular, don't use `-ss`, `-to` or any filters that select or cut segments as these are likely to conflict with the script's own ffmpeg options used to implement the `-edl` option
* By default, the stereo track is encoded with the aac ffmpeg codec and the 5.1 track is encoded with the ac3 ffmpeg codec, with no additional options.
* Any audio encoder options will apply to both the 5.1 and stereo streams, if a video is known to include an ac3 5.1 track, it can be assumed that the stereo stream in the output will be audio 0 and the 5.1 stream will be audio 1.  For example `-b:a 128k` will set a bitrate of 128k on both streams which is probably not desirable, instead if a custom bitrate is desired it should be set on both streams separately (5.1 requires a higher bitrate than stereo) i.e. `-b:a:0 128k -b:a:1 396k`

**Comment by mackworth** [comment]
Good, and I'm just about to post the beta. Thanks again for your help!

Anyone using the script will probably look at it script, so I've added a documentation comment to the scrip, with the introduction of.
# Script to drive ffmpeg, adding Edit Decision List capability (e.g. comskip) and dual stereo/5.1 audio tracks capabilities
# Calls ffmpeg to get duration and audio stream information about the input file
# If a 5.1 audio stream exists, both it and a derived AAC stereo stream will be copied through
# For EDL, just pass parameter of "-edl filename.edl"
# Other parameters will be passed through from calling program , with a few limitations :
--then three bullets above.

**Comment by ryanchild** [comment]
Sounds good but maybe put in the Usage string instead of comments in the script?

**Comment by mackworth** [comment]
Eh, too much text for a mouseover text.  I added "See script for some rules on options."

**Comment by ryanchild** [comment]
Sorry I meant the usage string in the script

```
usage() {
  cat << EOF 1>&2
Usage: $0 -edl <edl file> <ffmpeg options>
       $0 -h

<Add documentation here>
EOF
exit 1
}
```

**Comment by mackworth** [comment]
Included in beta release

**Comment by mackworth** [comment]
Just FYI, I discovered that egrep doesn't support /S in 10.7  So the terminal command 
`echo "time=00:07:12.72"  | egrep -o 'time=\S+' `
returns nothing in 10.7 and the time string in 10.11.

I replaced with `time=[0-9:\.]+` and it's working fine in both.

**Comment by ryanchild** [comment]
Sounds good, thanks
