### ISSUE TITLE
Could not connect to the server

### ISSUE THREAD

**Issue by mk553** [dscottbuch/cTiVo#187]
Hello,
I had to reinstall my operating system (El Capitan) recently, and after I reinstalled cTiVo, it no longer seems to work for some reason. 

Here is a portion of my logs:
016-08-27 07:40:58:825 MTTiVo>connection:didFailWithError:@840>URL Connection Failed with error Error Domain=NSURLErrorDomain Code=-1004 "Could not connect to the server." UserInfo={NSUnderlyingError=0x7fc7fb120070 {Error Domain=kCFErrorDomainCFNetwork Code=-1004 "Could not connect to the server." UserInfo={NSErrorFailingURLStringKey=https://dvr-e2f6.local./TiVoConnect?Command=QueryContainer&Container=%252FNowPlaying&Recurse=Yes&AnchorOffset=0&ItemCount=15, NSErrorFailingURLKey=https://dvr-e2f6.local./TiVoConnect?Command=QueryContainer&Container=%252FNowPlaying&Recurse=Yes&AnchorOffset=0&ItemCount=15, _kCFStreamErrorCodeKey=49, _kCFStreamErrorDomainKey=1, NSLocalizedDescription=Could not connect to the server.}}, 

When I download Bonjor Browser, I can see my tivo's there. And when I log into the https link above, I can successfully log in with tivo as the username and my MAK as the password.

Any ideas? 

For what it's worth, I initially got the new Alpha version, but after I noticed problems, I deleted it and downloaded v2.4.4.   I also tried deleting the ~/Library/Preferences/com.ctivo.ctivo.plist and allowing it to be re-created.

**Comment by mackworth** [comment]
So, when you click on that URL in the browser, does it show you the XML file?    (Starts with something like `TiVoContainer xmlns="http://www.tivo.com/developer/calypso-protocol-1.6/">`

Have you tried rebooting the TiVo?

Probably best to delete the plist again, log all the way out to login screen, and then log back in. Recent versions of the OS cache the preferences, so just deleting the file doesn't really work.

**Comment by mk553** [comment]
Hi mackworth,

Yes, the XML looks good, and I can see the list of my shows on the various tivo's. The only peculiar thing is that the https login fussed that the ssl certificate isn't valid, for what it's worth.

I've tried rebooting the tivo's and my mac (after deleting the plist file). 

When I launch cTiVo, it identifies my TiVo's, but just loads up a blank grid view. It doesn't ask me for my Media Access Key or anything like that either. If I try to add it manually in the preferences, the '+' plus symbol is missing to do so. Not sure if that is normal or not.

What else do you think the problem might be?

thanks!

**Comment by mackworth** [comment]
That's a correct message. The SSL that tivo gives you isn't based on a root that the Mac knows. So, someone could pretend to be your tivo and you wouldn't know.  Not really a problem.

Can you set the logging to Verbose, then quit TiVo, and run it again, then post it as an attachment? That will give me the most logging during the startup phase. thx

**Comment by mk553** [comment]
No problem, attached is a clean verbose log. 

Appreciate your help!

[com.cTiVo.cTiVo 2016-08-28 13-46.zip](https://github.com/dscottbuch/cTiVo/files/441147/com.cTiVo.cTiVo.2016-08-28.13-46.zip)

**Comment by mackworth** [comment]
If you can load the [the URL for your TiVo ](https://DVR-E2F6.local./TiVoConnect?Command=QueryContainer&Container=%252FNowPlaying&Recurse=Yes&AnchorOffset=0&ItemCount=15), and cTiVo gets an error on the same URL, that's an odd combination.  

Ah, you know...the fact cTiVo didn't ask for a MAK might be a clue.  Maybe go into Keychain Access and search for "dvr" and delete any tivo passwords there. (Don't worry about tivo.com; not relevant) . I thought Safari and the mechanism cTiVo uses access the same passwords, but maybe not.

Final thing to try (not that it will fix anything, just maybe give a clue) is to copy the following, paste/edit/copy YOURMAK in TextEdit, then go into Terminal and paste in:

`curl -k --digest -u tivo:YOURMAK https://DVR-E2F6.local./TiVoConnect?Command=QueryContainer&Container=%252FNowPlaying&Recurse=Yes&AnchorOffset=0&ItemCount=15`

That should echo the same XML file in Terminal.

**Comment by mk553** [comment]
Thanks -- didn't find any dvr entries in the keychain, but got this response from curl:

[1] 19473
[2] 19474
[3] 19475
[4] 19476
[2]   Done                    Container=%252FNowPlaying
[3]   Done                    Recurse=Yes
[4]+  Done                    AnchorOffset=0
mk553-mp:~ mk553$ curl: (56) SSLRead() return error -9806
<?xml version="1.0" encoding="utf-8"?><TiVoContainer xmlns="http://www.tivo.com/developer/calypso-protocol-1.6/"><Details><ContentType>x-tivo-container/tivo-server</ContentType><SourceFormat>x-tivo-container/tivo-dvr</SourceFormat><Title>Living Room</Title><TotalItems>2</TotalItems></Details><ItemStart>0</ItemStart><ItemCount>2</ItemCount><Item><Details><ContentType>x-tivo-container/tivo-videos</ContentType><SourceFormat>x-tivo-container/tivo-dvr</SourceFormat><Title>Living Room</Title><UniqueId>Living Room</UniqueId></Details><Links><Content><Url>https://DVR-E2F6.local:443/TiVoConnect?Command=QueryContainer&amp;Container=%2FNowPlaying</Url><ContentType>x-tivo-container/tivo-videos</ContentType></Content></Links></Item><Item><Details><ContentType>x-tivo-container/tivo-videostream</ContentType><SourceFormat>x-tivo-container/tivo-dvr</SourceFormat><Title>Living Room</Title><UniqueId>Living Room</UniqueId></Details><Links><Content><Url>https://DVR-E2F6.local:443/TiVoConnect?Command=QueryContainer&amp;Container=%2FNowPlaying</Url><ContentType>x-tivo-container/tivo-videostream</ContentType></Content></Links></Item></TiVoContainer>

**Comment by mackworth** [comment]
So, that looks fine too.  Sigh.  And when you load the original URL in Safari you see 15 "items", and when you run cTiVo you see nothing, correct?

Do you have your network set up for remote access to your TiVo?

**Comment by mk553** [comment]
Yep, all good in  Safari.  I checked the remote access from my iPad, and the tivo app works fine too.

It occurred to me to run cTiVo from my MacBook Pro, which wasn't reinstalled and was working ... up until now. It now has the same problem as my Mac Pro (seeing the Tivo's, but not getting a list of anything). It's an 8-core system with 64gb RAM (I only mention that for the sake of bragging). ;-)

So I'm not sure what's changed in my environment or with the tivo's. 

Are we out of ideas?  :-(

I half-heartedly tried downloading the source code and running it from XCode to see if I could get any more details, but I'm a .NET person and it looked like it was going to be a hassle to get the third party Fabric dependencies setup, but I can try again if you think it might help.

**Comment by mackworth** [comment]
Not quite out of ideas, but certainly puzzled.  What I meant was whether you had ever set up your router to allow remote ctivo access to your tivo.  That would let me access it remotely to debug it directly.  If you're ok with doing that, I could walk you through how to set it up.

**Comment by mackworth** [comment]
Let me know if you want to further debug

**Comment by mackworth** [comment]
Ah, found it. I bet you're running an antivirus program, maybe Avast? If so, it's interfering with the HTTPS connection to the server, producing that error message.

**Comment by mk553** [comment]
Yep, that seems to have been the problem. Kaspersky, in my case.  

Appreciate the help!

**Comment by mackworth** [comment]
Great!  I'm adding an error message to alert future users.  If you figure out the steps to whitelist it in Kaspersky, let me know and I'll create a troubleshooting guide.
