### ISSUE TITLE
"Skip Commericals" Preference Not Retained

### ISSUE THREAD

**Issue by tomwickland** [dscottbuch/cTiVo#189]
Each time I start cTiVo, I need to recheck the "Skip Commercials" preference.
This preference isn't retained. Other preferences are.
What should I do?

Thanks so much for being here to give us all help.
Tom

**Comment by mackworth** [comment]
Hmm, this was fixed a while ago. Which version ctivo are you running?

**Comment by mackworth** [comment]
Actually, it's fixed in 2.5.  If you don't want to use the alpha, then just close cTiVo; open yout Terminal program (in Utilities) , and type `defaults write com.ctivo.ctivo SimultaneousEncode NO`<return>.  Then (unfortunately), you have to log out and back in again.

That should fix it for you.

**Comment by tomwickland** [comment]
Wow, that was a fast response.

It worked

Thanks so much!


________________________________

**Comment by mackworth** [comment]
It's easy when you've fixed it before! Just need to ship 2.5, but it has a lot of changes.
