### ISSUE TITLE
Crash on subscription

### ISSUE THREAD

**Issue by saltsugar** [dscottbuch/cTiVo#190]
Recently, whenever I subscribe to a series, cTiVo immediately crashes.  I have been unable to set up any new show subscriptions.  I have tried deleting preference/ restarting/  etc. without success.

I am enclosing the log output set to verbose from the time I tried to set up a subscription.

Thanks,

David

[com.cTiVo.cTiVo 2016-09-02 21-58.log.zip](https://github.com/dscottbuch/cTiVo/files/452998/com.cTiVo.cTiVo.2016-09-02.21-58.log.zip)

**Comment by mackworth** [comment]
Can you run ctivo and use a right-click on the show table headers (the upper table) to display the column "episode id" and "Tivo"?  Then look at 'Curious George: All-New Hundley; Signs Up' and tell me what's displayed there?

Then

**Comment by mackworth** [comment]
Actually, I was just finishing 2.5 alpha 14, so I threw in an extra debug line.  If you could download and run this version, and let it crash again, then post the log again.  thanks

https://dl.dropboxusercontent.com/u/21507587/cTiVo.zip

**Comment by saltsugar** [comment]
Sorry for the delay.  Here is the cTiVo log.  I enabled verbose logging just before I subscribed to the show.  

Other than this one issue, I love the software.

David

[com.cTiVo.cTiVo 2016-09-03 00-25.log.zip](https://github.com/dscottbuch/cTiVo/files/453100/com.cTiVo.cTiVo.2016-09-03.00-25.log.zip)

**Comment by mackworth** [comment]
Thanks, I've got enough to patch it not to crash now, but I want to know what's causing this condition, if you don't mind a couple more questions....

I would like to know what the episode ID column is showing (see above). The log says its Null , which it should never be. Second, if you could also enable the "Tivo ID" column, and find what the number is there.  Say it's 12345, then type Cmd-Shift-G in the Finder to Go to the Folder: `/tmp/ctivo_details`, and find the file `Tivo HD_12345_Details.xml` and send that to me as well, that would be great.

**Comment by mackworth** [comment]
Oh, after you turn on the episode ID column, if Curious George is showing nil or empty for Episode ID, then let me know if that's the only one, or if it's all of them, or if there are lots of them (click on table header to sort by that id)

**Comment by saltsugar** [comment]
The episode column shows S05E01.  I am including the file as well.  All of the Curious George episodes have an Episode ID.  Some of my other shows do not.

Thanks, 

David

[Roamio_196808_Details.xml.zip](https://github.com/dscottbuch/cTiVo/files/453125/Roamio_196808_Details.xml.zip)

**Comment by mackworth** [comment]
S05E01 is probably the Episode Number column (as opposed to Episode ID)?  Episode ID should look like EP00422134234 or something.

**Comment by saltsugar** [comment]
Sorry, realized my mistake.  All shows do have an episode ID displayed in the column, similar to EP0075810431-0168508711.

David

**Comment by mackworth** [comment]
Ok, sorry to press on this, but it's very weird. I'm looking at the code, and both the showTable's episode ID column and the subscription routine refer to the show's episodeID. The log you sent me shows the episodeID is null, but the column apparently has no nulls in it.  One last check, if you don't mind.  Do a find on Curious George to see all the episodes at once, and confirm that they all have EP0075810431-xxxxxxxxxx numbers. Then drag one into the subscription to let it crash again.

And a question, I take it from your original question that you've been having this crash with other shows as well?

**Comment by mackworth** [comment]
Another question. Looks like you have two TiVos. Is `Curious George: All-New Hundley; Signs Up` on both of them?  (Because you sent me the one from Roamio, but the one that crashed is from Tivo HD)

**Comment by saltsugar** [comment]
I think I figured out what is going on.  On my TiVo HD, I reloaded Curious George episodes which I had cut the commercials out of.  For the reload, I created custom metadata files which did not have an episode ID.  I was just looking at the Roamio originally, and all those shows had episode IDs.  Since I deleted all of the Curious George episodes from the TiVo HD, cleared the ctivo_details folder,  and restarted, I am able to subscribe to Curious George on the Roamio without a crash.  Sorry to torture you with this issue.  I will just recreate episode IDs for my cut episodes metadata.  Everything seems to be working smoothly now. 

Great product,

David

**Comment by mackworth** [comment]
Glad to hear how the "impossible" could actually be.  I've put in a patch to prevent crashing under that scenario anyways.  Thanks for reporting it; I noticed the fatal crash reported by Crashlytics, but couldn't see how it could happen.
