### ISSUE TITLE
MP4-FFMpeg

### ISSUE THREAD

**Issue by tdlivings** [dscottbuch/cTiVo#198]
Transfer completed successfully. However, quicktime and Apple compressor both report the file is corrupt and can not be open.

Recorded from regular OTA signal.

**Comment by mackworth** [comment]
Short version: if the source channel hasn't converted to H.264 OR is 1080i, then this isn't surprising.

Long version: So, MP4-FFMpeg doesn't do any conversion, just copies the video track over into a new container format. This is very fast, but seems to work with iTunes/Quicktime only if (a) the source channel is compressed to H.264 (aka MP4), not the older MP2 and (b) it's progressive (e.g. 720p).  If the video track is MPEG2 or interlaced, then Quicktime Player and iTunes will get confused.  Nothing wrong with that combination per se, but QTPlayer and iTunes just don't handle it.    (I haven't worked with Compressor at all).

This is an area I'm still working in. But today, if you want to sure it will be usable with QuickTime iTunes, try "FFMpeg-Comskip" Format instead.

OR try using VLC as a player

**Comment by tdlivings** [comment]
I don’t see that in the preferences> formats and in the drop down.

Yes, 1080 is the original size. I should have noticed that and been aware from the other posts, sorry.

and, yep super quick transfer.

Thomas Livings

**Comment by mackworth** [comment]
Ah, have you upgraded to the Beta1 version?

https://github.com/dscottbuch/cTiVo/releases/tag/2.5.0beta1

**Comment by mackworth** [comment]
Oh, just to be clear, FFMpeg comskip" does do a full conversion, so you lose the speed, but it seems to do a really good job.

**Comment by tdlivings** [comment]
Awesome… Thank you
Thomas Livings
