### ISSUE TITLE
Incomplete downloads

### ISSUE THREAD

**Issue by bp888** [dscottbuch/cTiVo#200]
I've been using cTiVo for a long while and have been happy with it for the most part. Well, something strange has happened lately. Starting 9/27, all the shows that I download in Decrypt mode stops at around 300-400 MB. Shows that were recorded prior to 9/27 no problem. Any shows on and after 9/27, incomplete. cTiVo shows the post-9/27 shows as download completed but they are clearly short of that by their file sizes. They're also unplayable. FYI: Mac OS X Yosemite 10.10.5; TiVo Roamio Plus; Comcast; cTiVo 2.5 beta 1 (same outcome with previous release, 2.4.? I think). TIA for any help.

**Comment by mackworth** [comment]
From tivoCommunity site:

> Well, I would have guessed it was the H.264 transition, except that 2.5beta1 should have handled that for you. Can you open an issue on the ctivo site? A couple of steps to try. First, download the mediainfo program to look inside the file and see if there's a video stream in the downloaded file
> Second: if you could set the logging to Detail and post the results (Help > Show Logs in Finder). 
> Third: If you're comfortable reading logs, then look for the line with "Starting URL", then try that URL in your browser. (You'll need user: tivo password: YourMAK). See if it also is truncated.
> 

> > No video stream in .mpg file downloaded by cTiVo
> > IDK if I did the right steps. But when I open the URL on my browser, I get a .TiVo file with ~ same size as the cTiVo-decrypted .mpg file

Ok, so that really, really sounds like the H.264 transition; no surprise 2.4.x failed, but  I'm surprised that 2.5beta1 didn't fix it.  Can you set the Debug level (Preferences) to Detail, do the Decrypt download again, and then post the log here (may have to rename to .txt)?

**Comment by bp888** [comment]
[com.cTiVo.cTiVo 2016-09-30 20.txt](https://github.com/dscottbuch/cTiVo/files/503671/com.cTiVo.cTiVo.2016-09-30.20.txt)

**Comment by mackworth** [comment]
So, that's interesting.  I'm pretty sure what's going on is this: The H.264 transition causes TiVo to fail to transmit the video stream in a PS transfer. 2.5 cTiVo detects this by noting a failure in the encoding process and switching future downloads to Transport Stream (TS). But you're using Decrypted TiVo Show, which doesn't do a real encoding, so no failure is noted (other than the too-short file).  

I'll look at detecting this case in the next beta, but to work around, go to Preferences>Channels, and hit Test All Channels. It will then go through all the shows on your TiVo and run a quick test on each channel, marking it as either H.264 or not.  This will take an hour or two. (As we have to wait a minute between transfers to avoid overloading the TiVo, it will run at about 50 channels/hr).  Then you should be all set.

If you want to try before doing that, just select this same show, and download it as a "Test PS" Format.  That will then mark the channel.  (Or you could just manually mark the channel by hitting "+", then the channel name and a check in the Use TS column). Either way, the next download you do (even Decrypted) should be successful.

Please let me know how it goes.

**Comment by bp888** [comment]
It worked! Thanks a million!!!

I went the Test PS format route and downloaded the same show. It downloaded to completion! I will do the Test All Channels next.

**Comment by mackworth** [comment]
Great! And thanks for reporting the problem, so I can prevent it for others.
