### ISSUE TITLE
DL Stage failed.

### ISSUE THREAD

**Issue by patmacster** [dscottbuch/cTiVo#201]
I have use cTivo on my mac and tivo every once in awhile and it worked great every time then I tried it about a month ago about the time Rovi guide data update and now it fails to download every time.

I used the last release and last 2 beta version of Ctivo.

I have a Roamio and use a MacBook Air mid 2011 with Sierra 10.12 but it also failed El Capitan. 

The other thing my readynas still download my shows.

**Comment by mackworth** [comment]
Were you able to find the log?

**Comment by patmacster** [comment]
When I tried to drop log file on it would not take it turned it into a txt file

[log.txt](https://github.com/dscottbuch/cTiVo/files/504564/log.txt)

**Comment by mackworth** [comment]
I'm not quite sure what you mean by "my readynas still download my shows". What I'm seeing in the log is a download failure.  Can you try downloading in your browser directly and see what you get:

[http://dvr-5f71.local.:80/download/Suits.TiVo?Container=%2FNowPlaying&id=61588](http://dvr-5f71.local.:80/download/Suits.TiVo?Container=%2FNowPlaying&id=61588)
You'll need to use user: tivo and password of your MAK

I assume you've tried rebooting your TiVo?

**Comment by patmacster** [comment]
http://kb.netgear.com/app/answers/detail/a_id/20900/~/how-to-archive-and-playback-tivo-recordings-to-the-readynas

**Comment by patmacster** [comment]
Downloaded without a problem via browser via link.

**Comment by mackworth** [comment]
So, you're the second to report this combination: 1004 error, but downloads ok in browser.
 
Question: any chance that the ReadyNAS is accessing the TiVo at the same time as cTiVo?  That won't work.

Can you try this version and post the log.  It won't work either, but it generates a bit more information:

[https://dl.dropboxusercontent.com/u/21507587/cTiVo.zip](https://dl.dropboxusercontent.com/u/21507587/cTiVo.zip)

thanks

**Comment by mackworth** [comment]
Oh, I forgot to mention; you need to set to Verbose; preferably in Advanced Preferences (Cmd-Opt-Comma), then set Debug level to Major, and down below set Download to Verbose.

**Comment by patmacster** [comment]
[new log.txt](https://github.com/dscottbuch/cTiVo/files/504784/new.log.txt)

My readynas is setup downloads after midnight so no not at the sametime.

**Comment by mackworth** [comment]
Thanks.  BTW, do you have another Mac?  I'd be curious if it has the same issue.

**Comment by mackworth** [comment]
And there's no problem with the show list, correct?

**Comment by patmacster** [comment]
No. Thank you for trying to help me out. I will ask my friend to bring her computer over my other computer is a windows 10 pc. I don't see any problem with the show list. I do have a question why did ctivo want access to my contacts.

**Comment by mackworth** [comment]
Nope; that's very weird. cTiVo absolutely shouldn't be asking for contacts. What did that look like? Go to Security & Privacy > Privacy tab > Contacts > and if it's there, disable ctivo access.

Are you running any antivirus software? Any network spy stuff (little snitch), Management software (Sophos, etc).

Actually, let me know whether there are any errors in your main system log in  Console..  Look for any messages around the time of 21:25:08:732. should see ctivo msgs duplicated there, but I'm looking for anything that doesn't start with com.cTiVo.cTiVo

**Comment by patmacster** [comment]
I'm very Sorry the one thing I did not check was my virus program.
Avast was blocking cTivo from downloading.
We can close this problem but maybe the new feature could check for running virus apps or just a message telling people might need to turn off their virus app or it might block your download.

**Comment by patmacster** [comment]
Is their a video format that doesn't need to be re-encoded? HD video programs?

**Comment by mackworth** [comment]
Ok, that's great to know! I'll add an error message specific to this problem; it'd be great if you could test tit for me.  

BTW,  Avast's website tells me that they will replace the SSL certificate with their own in HTTPS traffic. As TiVo's SSL is self-generated, that's undoubtedly the problem.
To disable the HTTPS scanning feature:
1. Open the Avast user interface → select Settings.
2. Select Active protection → click Customize next to Web Shield.
3. Select Main settings → check/uncheck Enable HTTPS scanning to turn this feature on/off.

Second, in that same area, is there a place to whitelist your TiVo?

**Comment by mackworth** [comment]
Oh, and did you look into the Contacts question?

**Comment by mackworth** [comment]
And here's a version to test if you get the warning.  As I can't test it here, it may take a couple tries to get it right.

**Comment by wkoffel** [comment]
I'm having a very similar issue, but I have no anti-virus installed on my mac here.

I *can* download directly from the web.  But in the logs I see:

```
2016-10-02 23:29:57:820 MTTiVo>updateShowsStartingAt:withCount:@348>Initial loading from TiVo Living Room HD at URL https://DVR-15DF.local./TiVoConnect?Command=QueryContainer&Container=%252FNowPlaying&Recurse=Yes&AnchorOffset=0&ItemCount=15
2016-10-02 23:30:18:548 MTDownload>download@1743>Starting URL http://dvr-15df.local.:80/download/MLB%20Baseball.TiVo?Container=%2FNowPlaying&id=425489 for show MLB Baseball: Blue Jays at Red Sox in 0.0 seconds
2016-10-02 23:30:24:526 MTTask>failedTaskCompletion@182>Task encode failed
2016-10-02 23:30:29:542 MTTiVoManager>notifyWithTitle:subTitle:isSticky:forNotification:@1387>Notify: TiVo show failed; retrying.../nMLB Baseball: Blue Jays at Red Sox: Can't Download
2016-10-02 23:30:31:586 MTDownload>download@1743>Starting URL http://dvr-15df.local.:80/download/MLB%20Baseball.TiVo?Container=%2FNowPlaying&id=425489 for show MLB Baseball: Blue Jays at Red Sox in 52.9 seconds
2016-10-02 23:31:27:152 MTTask>failedTaskCompletion@182>Task encode failed
2016-10-02 23:31:32:153 MTTiVoManager>notifyWithTitle:subTitle:isSticky:forNotification:@1387>Notify: TiVo show failed; retrying.../nMLB Baseball: Blue Jays at Red Sox: Can't Download
```

I'm not sure what else to check.  Let me know if I can provide any additional debug information.

**Comment by wkoffel** [comment]
Also @mackworth , I *do* see that cTivo asked for access to my contacts (this is on macOS sierra), for what it's worth.

**Comment by mackworth** [comment]
Which version of cTiVo are you using?  If 2.4.4 (or earlier), try the beta at https://dl.dropboxusercontent.com/u/21507587/cTiVo.zip  

That may fix it; if not, then set logging to Major, run the show again and post the log here (Help>Show logs in Finder). You'll have to change the filename to .txt to allow posting.

Just saw the contacts note. I'll look into that.

**Comment by wkoffel** [comment]
Still failing for me on `2.5 beta1 (661)`.  Notably, some shows seem to download okay.  But two shows from this channel (NESN) do not download correctly.  I tried another show, and it appeared to download, but I did a warning about the show possibly being corrupted(?)

The broken shows fail immediately upon trying to start the download.  And they **do** download fine from the web, I was able to manually download, and then use `tivodecode` from the cTivo bundle to decrypt them, and they seem totally fine.  So it's something about cTivo handling them.

Log file attached from `LOG_LEVEL=Major`

[com.cTiVo.cTiVo 2016-10-03 17-01.txt](https://github.com/dscottbuch/cTiVo/files/506752/com.cTiVo.cTiVo.2016-10-03.17-01.txt)

**Comment by mackworth** [comment]
Try a different Format. We're moving away from mencoder (used in most of the "simple" named Formats: AppleTV, H.264 High Quality, etc.)  Try ffmpeg/comskip in particular.

**Comment by mackworth** [comment]
The contacts thing is baffling me. With two reports, I gotta assume it's real :) . 

But we don't even load the framework that accesses contacts, and the docs say that starting in 10.10, if we do access the contacts, then we have to provide a string explaining why to the user, or the program will crash, and we don't provide that string. 

Questions:
When did it ask for permission?  On initial launch, or doing some other operation?
Do you remember what it says?
In your System Preferences > Security & Privacy > Privacy tab > Contacts, does cTiVo appear?
  If not, what apps do appear?

**Comment by wkoffel** [comment]
Sure enough, that fixed the problem.  I was confused in that it failed right away at the download stage, so didn't consider that the encoder was the culprit.  Thanks @mackworth .

**Comment by mackworth** [comment]
Ah, the joys of multitasking!  And ... the contacts questions?

**Comment by wkoffel** [comment]
@mackworth (speaking of multitasking, this clearly should have been at least 2 different GH issues...maybe 3!)

It prompted me to use Contacts on initial launch.  And yes, it shows in the privacy preferences: https://cl.ly/3n0L0e0F2X3d

Also, notable, when I tried the new beta that you suggested, I believe it prompted me again for that version, even though it already had permissions.

This is on macOS 10.12 Sierra.  I know that Apple is constantly tweaking the sandboxing and permissions, so it could be a side effect of the new OS.  Just thinking that some call that seems innocuous and unrelated could now require Contacts access (something like getting the user's name, or something about access to the keychain?  Now I'm just totally guessing, but you get the gist....)
