### ISSUE TITLE
Compiling a debug build in Xcode leads to crash on file download

### ISSUE THREAD

**Issue by ryanchild** [dscottbuch/cTiVo#202]
Most of the time when I start a download, my debug build crashes with the EXC_BAD_ACCESS at some point during the download.  The crash takes me to main.m with a bunch of system stuff in a bunch of different thread traces.  I tried deleting my git clone and compiling the 2.5 beta source you released to eliminate the possibility that something was messed up in my local copy and got the same result.  I just pulled your latest changes to 2.5 tonight and am still getting the same result.  This all started happening when I upgraded to Xcode 8, I'm using El Capitan 10.11.6.

Might be worth noting that I'm getting this build warning, which I think is also new since upgrading to xcode 8?

```
clang: warning: libstdc++ is deprecated; move to libc++ with a minimum deployment target of OS X 10.9
```

When it crashes, sometimes there are cTiVo function calls in the stack and sometimes there aren't.  There is always an NSURLConnectionLoader thread when it crashes.  Some of the cTiVo lines I've seen in stack traces are:

```
MTTaskChain teeInBackground:isDone:forHandle:

                    ssize_t amountSent= write ([[pipe fileHandleForWriting] fileDescriptor], [readData bytes]+readData.length-bytesLeft, bytesLeft);
```

and

```
MTDownlaod connection:didReceiveData:

  @synchronized (self.urlBuffer) {
```

I was getting the same unhelpful stack trace several times in a row so tried enabling guard malloc, and got some SIGPIPEs at these two lines in MTDownload after canceling an active download:

```
            [fm removeItemAtPath:self.nameLockFilePath error:nil];

    NSString *log = [NSString stringWithContentsOfFile:_decryptTask.errorFilePath encoding:NSUTF8StringEncoding error:nil];
```

So all signs seem to be pointing to an I/O error of some kind?  I tried changing the download location to a different disk, didn't make a difference.

I haven't actually seen a crash while downloading with guard malloc enabled tonight, which seems odd to me as I thought guard malloc was supposed to help crash programs earlier.  I don't understand how using guard malloc could be preventing the crash, but sure enough as soon as I disable guard malloc I get the crash again.  The good news is I guess I can use this as a workaround if I'm playing around with debug builds in the meantime (as long as I don't cancel anything 😄 ).

**Comment by mackworth** [comment]
The SIGPIPEs are actually correct. When you cancel an active download, you're closing open pipes, so you get the SIGPIPE warning; if you can figure out how to prevent that, that'd be great. When operating under the debugger, this traps (and you can just continue), but in normal operation we just continue.

The build warning is indeed new with Xcode 8. It has to do with mp4v2, which is compiled using libstdc++, which is deprecated. We could move to a new compilation of mp4v2 using libc++, which is available, but it would have to be compiled with 10.7 support, which is possible, but I haven't done it. I don't know why it says "with a minimum deployment of 10.9" as Lion /Mt Lion has libc++    (cf https://trac.macports.org/wiki/LibcxxOnOlderSystems ) Note this library is only called after a download has completed, so I don't think it's your problem.

Have you tried the new thread and address sanitizers? The thread sanitizer found one long-standing bug in seconds for me. And you are def in threading land when you start a download.

I can't think of any reason why you'd be having this problem and not me....I'm still on El Cap, but the latest compiler.

Have you tried removing the Fabric and crashlytics libraries as a test? The debug version isn't calling them, but that might be a difference between your system and mine.

**Comment by mackworth** [comment]
Hmm, I'll just put this here for future reference:  
[How to disable SIGPIPE](http://stackoverflow.com/questions/108183/how-to-prevent-sigpipes-or-handle-them-properly/450130)
`int set = 1;
setsockopt(sd, SOL_SOCKET, SO_NOSIGPIPE, (void *)&set, sizeof(int));
`
Not sure if one then has to check for EPIPE

**Comment by mackworth** [comment]
So...just FYI, I just started seeing this myself yesterday... 

😱  
So, now it matters!

Never seen it before; exact same symptoms that you saw; completely reproducible runs fine until a download, then about half-way/three quarters through a 1GB simple download (decrypt-only, no captions etc): a EXC_BAD_ACCESS occurs, deep in the NSURLConnectionLoader code.  

I also found that guard malloc fixes it, as does any of Address Sanitizer, Thread Sanitizer, Zombies, and malloc Scribbler as does doing a Release build. Turning these tools off: same symptom. Cleaning didn't help.

I rolled back to beta2, same symptom.

And....

Finally, after enough of that kind of thrashing, it just went away again, and now I can't recreate it again.

**Comment by mackworth** [comment]
And it's back.  Found this though:
http://stackoverflow.com/questions/40371536/nsurlsession-causing-exc-bad-access

> After speaking with Apple Technical Support we confirmed that it's a bug within the libBacktraceRecording.dylib library, which is used for debugging within Xcode. I have filed a bug report and have been told that it won't crash on a users device since this is a debug error that occurs within a library not present on most users' devices.

So, nothing we can do about it. I'll close this as a result.

**Comment by ryanchild** [comment]
That's annoying, though I'll admit it's good to know it's not just me 😄 
I guess I'll just permanently enable guard malloc.

**Comment by mackworth** [comment]
I haven't run a benchmark, but I would think that malloc scribbler (which just writes 0xAA in new blocks and 0x55 in freed blocks) would have less performance impact, and for whatever reason, it seems to avoid the bug as well.
