### ISSUE TITLE
Just a comment - noticed an improvement

### ISSUE THREAD

**Issue by WhyAkron** [dscottbuch/cTiVo#204]
Using 2.4.4 I had shows that would fail the download part or most of the way through, but Tivo Transfer (old Roxio app) downloaded the whole program so Tivo file likely OK. (Also had shows that would fail with everything.) Decided to see if 2.5 beta1 (657) would be any different. It works on the ones that Tivo Transfer completed! Thank you.

**Comment by mackworth** [comment]
Great to hear!  I'm madly trying to fix the last bugs, so I can update 2.4.4.
