### ISSUE TITLE
Comm skip analysis

### ISSUE THREAD

**Issue by tdlivings** [dscottbuch/cTiVo#205]
First of all, thank you for all of you efforts. 

I thought it might be helpful to run a side by side comparison of the FFmpeg com skip with a manual edit. The sizes differed, manual 42 minutes, FFmpeg 46 min. The FFmpeg caught some unwanted frames of previews of upcoming shows and ran over from the end of the show to include a part of the next show. My settings are 3 minutes before and 5 minutes after show for my default recording settings. The output was mp4 and included a .txt with the meta data.
 The decrypted file was 1920x1080 and the ffmpeg was 1920x1080. The sound track was active along with the video. The source is OTA HD. Conclusion: All is Well. However, make sure you have some beef under the computer hood as an i5 chip took 1:1. That is to say, the recode time was equal to the recording original.

**Comment by mackworth** [comment]
Thanks, both for the nice note and for the comparison.  Which version is this? We have a new version in the beta, which should be much faster, and maybe more accurate.  IIRC, comskip has an option to tune whether it checks at the beginning and end of the shows if you want to play with them.

**Comment by tdlivings** [comment]
Version 2.5 beta1 (657)

Awesome additions by the way…

Thomas Livings
