### ISSUE TITLE
2.5.0 Beta 2

### ISSUE THREAD

**Issue by mackworth** [dscottbuch/cTiVo#206]
A place to discuss latest beta

**Comment by alecksjaycubs** [comment]
Can you explain the Channel pref a bit more? When I do a test all channels the first one says Test PS but all the others default to the YouTube preset. And if I want to enter a manual channel do I just add the "station id' in the Channel field? When I try that I can only type one letter at a time. Just not sure what I'm doing in that pref.

**Comment by mackworth** [comment]
Sorry 'bout that; those are indeed both bugs in beta2. To work around the first, go into Prefs>Format and Unhide the TestPS format, it should work fine. For the second, type the channel name somewhere else (textedit or wherever) and just paste it over the ???. Beta3 coming in a couple days.

**Comment by alecksjaycubs** [comment]
Thanks! One other question. Is there a way to mark commercials in the Decryped TiVo format?

**Comment by mackworth** [comment]
Nope,  you can't add metadata to the MPG format.  You could try the mp4 ffmpeg one though. If it's h264, that'll work great (not with iTunes though if its interlaced).  If it's MP2 compressed, your player may get confused.

**Comment by max-webster** [comment]
I upgraded to Beta 1 and started having a lot of problems on Yosemite. (Downloads would fail instantly, or the results would include audio but no video, and trying to bring up advanced prefs would crash the app.) Then I upgraded to both Sierra and Beta 2. Now retrieving the program list on startup, and downloads and conversions, are very slow and the ctivo UI is unresponsive when anything is happening. I'm running a FFMPEG+MP4 conversion that's been running for 20 minutes, and in that time ctivo has been continuously "application not responding" in the dock, although I can see the .bin and .mpg files growing in /tmp/ctivo. 'top' shows that ctivo is only using about 20% CPU. Is there a known problem of slowness / low CPU use / unresponsive UI during download and conversion?

**Comment by alecksjaycubs** [comment]
Thanks mackworth. I'd like to use the handbrake preset but call my own. Will that preset call a user preset that I've created or only work on the default built in presets? I tried with my own but it obviously used something other than my preset because the quality was pretty bad.

**Comment by tannebil** [comment]
I've used my own HB video presets without a problem by custom preset name, standard preset+arguments, and just with arguments without any issues. Look in the log to see the encoding command that's actually getting used.

**Comment by alecksjaycubs** [comment]
Thanks I'll keep trying. What's the best mode for logging to look for this info?

**Comment by tannebil** [comment]
I think you'll see it with normal logging but I'm sure Hugh will tell you if something different is needed. I'm not in front of my machine so I can't check.

**Comment by mackworth** [comment]
You'll have to do Detail for Download in Adv Prefs (Cmd-Opt-Comma).

Note the HandbrakeCLI included in Beta2 is the "production" one, so it's relatively old. In beta3, I'm going to one of their nightlys as it includes a huge number of new presets. 

I don't know what the interaction is between the GUI and the CLI on custom presets. I'll look into it.

**Comment by alecksjaycubs** [comment]
I tried again and no luck. Does my preset have to be in the path that the cTivo app is looking for? Or some other place?

**Comment by mackworth** [comment]
@max-webster I haven't heard of similar problems. Something sounds really messed up. Have you tried trashing the preferences file? (Unfortunately, you then have to log out and back in to override the caching.) Maybe save a copy, so that if that fixes it, I can take a look at the file.

That %CPU is reasonable, but the unresponsiveness is not. If you'd like to set the log to Detail and run a conversion, I can take a look if there's anything unusual.

**Comment by mackworth** [comment]
@alecksjaycubs Sorry, Bill might know. I haven't done any work with custom presets, and it's about to change dramatically with Beta 3.

**Comment by tannebil** [comment]
I checked one of my custom encodes and it's working fine. The arguments are in the clear (no quotes) in the Video Options field and show in the log as:

2016-11-13 20:32:35:815 MTDownload>encodeTask@1267>encoderArgs: (
    "-e",
    x264,
    "-q",
    "24.0",
    "-r",
    30,
    "--pfr",
    "-a",
    1,
    "-E",
    faac,
    "-B",
    160,
    "-6",
    dpl2,
    "-R",
    Auto,
    "-D",
    "0.0",
    "--audio-copy-mask",
    "aac,ac3,dtshd,dts,mp3",
    "--audio-fallback",
    ffac3,
    "-f",
    mp4,
    "-4",
    "-X",
    640,
    "-Y",
    360,
    "--loose-anamorphic",
    "--modulus",
    2,
    "-m",
    "--x264-preset",
    medium,
    "--h264-profile",
    high,
    "--h264-level",
    "4.2",
    "-o",
    "/Volumes/Drobo/TiVoShows/Doctor Who -  - Sneak Peek - 2016-10-20.m4v",
    "-i",
    "/tmp/ctivo//bufferDoctor Who -  - Sneak Peek - 2016-10-20.mpg"
)

Doesn't appear I'm actually using custom presets at the moment but poking around I found this article that might help. It's a couple of years old so no guarantee it's still relevant

http://superuser.com/questions/783373/set-a-custom-preset-for-handbrakecli

**Comment by max-webster** [comment]
@mackworth OK, I did another conversion, this time with H.264 medium quality. This one produced a viewable output file, but again ran all day with top reporting about 20% CPU, but with the UI unresponsive and anything else CPU-intensive crawling. Which log file(s) exactly do you need, and shall I attach them here or drop them somewhere else?

Here's what was left in the temp directory:

```-rw-r--r--  1 cirrus  staff           0 Nov 13 14:36 Austin City Limits- Florence + the Machine; Andra Day.lck
-rw-r--r--  1 cirrus  staff  4146811050 Nov 13 17:26 bufferAustin City Limits- Florence + the Machine; Andra Day.bin
-rw-r--r--@ 1 cirrus  staff          32 Nov 13 20:15 bufferAustin City Limits- Florence + the Machine; Andra Day.edl
-rw-r--r--  1 cirrus  staff      313464 Nov 13 20:15 bufferAustin City Limits- Florence + the Machine; Andra Day.log
-rw-r--r--  1 cirrus  staff  4297531341 Nov 13 20:08 bufferAustin City Limits- Florence + the Machine; Andra Day.mpg
-rw-r--r--  1 cirrus  staff         102 Nov 13 20:15 bufferAustin City Limits- Florence + the Machine; Andra Day.txt
-rw-r--r--  1 cirrus  staff           0 Nov 13 14:36 catAustin City Limits- Florence + the Machine; Andra Day.err
-rw-r--r--  1 cirrus  staff           0 Nov 13 14:36 catAustin City Limits- Florence + the Machine; Andra Day.txt
-rw-r--r--  1 cirrus  staff           0 Nov 13 14:36 commercialAustin City Limits- Florence + the Machine; Andra Day.err
-rw-r--r--  1 cirrus  staff      339908 Nov 13 20:15 commercialAustin City Limits- Florence + the Machine; Andra Day.txt
-rw-r--r--  1 cirrus  staff     3530425 Nov 13 17:31 decryptAustin City Limits- Florence + the Machine; Andra Day.err
-rw-r--r--  1 cirrus  staff           0 Nov 13 14:36 decryptAustin City Limits- Florence + the Machine; Andra Day.txt
-rw-r--r--  1 cirrus  staff       13561 Nov 13 20:08 encodeAustin City Limits- Florence + the Machine; Andra Day.err
-rw-r--r--  1 cirrus  staff     8758313 Nov 13 20:08 encodeAustin City Limits- Florence + the Machine; Andra Day.txt
```

**Comment by mackworth** [comment]
You can get to the logs with Help>show logs in Finder. 

Do you have logging turned up to Verbose?  That will slow things down considerably.

**Comment by alecksjaycubs** [comment]
@tannebil thanks. Arguments are probably the way to go. I think I can get. All that info right from handbrake so I'll give it a try.

**Comment by max-webster** [comment]
I've "Don't delete temp files", and various log levels set (nothing higher than Detail) for the different cTivo phases. That's why I don't know exactly which log(s) are involved for debugging this particular issue.

I ran another conversion overnight of 4-5 shows. The first went really quick, I could see the download bar moving and the UI stayed responsive. As soon as it got to the second show, everything slowed to a crawl again. In the morning, conversions were still running and the UI was still frozen. I did a Force Quit because I needed to use the computer (a fairly recent / beefy Mac) for other things. Now cTivo doesn't start when I click the icon -- doesn't bounce in the dock at all.

**Comment by mackworth** [comment]
So, official release of beta3.  Massive changes in Formats. New handbrake. New documentation on selecting a Format. Lots of little bug fixes. 
-----

@max-webster  give the new cTivo release a try. I doubt that it will change anything, but I can then help you see what's wrong. Let's keep working in this thread to avoid messing up the beta3 one, though.

@alecksjaycubs github doesn't notify on edits, so I didn't see your second part.  Yes, ffmpeg arguments are bloody miserable. Now that beta3 has updated to the newer Handbrake, try that route again.  Haven't heard back from Handbrake folks on custom presets, but let's get those working.

**Comment by mackworth** [comment]
So,  @alecksjaycubs , Handbrake did get back to me, 

just add "--preset-import-gui " before "-Z customPresetName" in the encoderVideoOptions, and you should be able to import (using beta 3).

Let me know if that works and I'll add the autogenerating feature for these as well.

**Comment by mackworth** [comment]
@alecksjaycubs   Well, I got around to doing just that, and it works really nicely. So you can edit any preset in Handbrake GUI, name it, and then use it in cTiVo.  Note that you have to (a) quit Handbrake GUI and then (b) start cTiVo. HB only saves on quit, and cTivo only loads on start. It'll be in the next version, but if you can try it out, that'd be great:

https://dl.dropboxusercontent.com/u/21507587/cTiVo.zip

**Comment by max-webster** [comment]
OK, progress report on beta 2 before I switch to the other thread for beta 3.

I had cTivo completely freeze up, and after force quit it seemed to forget all its settings upon restart. (For example, the list of completed transfers was blank.) So there may be something to the notion that the preferences were corrupted. After some fiddling to get the preferences back to where they were, I had about 2 days of successful transfers, where the CPU didn't go too high and the computer didn't slow down very much during transfer or encoding.

Then there was another freeze, after which "Force Quit" had no effect - the icon remained "running" in the Doc. There wasn't any corresponding process I could find via 'ps ax'. But the Mac wouldn't shut down normally, claiming cTivo was still running. And despite 'top' not reporting much CPU use, the computer was really slowed to a crawl. I did a hard shutdown, then installed beta 3 after the reboot.

**Comment by max-webster** [comment]
Beta 3 isn't working for me yet. Shows in the transfer list stay in "Waiting" status forever, with a periodic Growl message saying "Server busy". I'm going to reboot the Tivo just in case. (Although it's awake and working fine AFAICT.)

**Comment by mackworth** [comment]
The file transfer process in the TiVo is somewhat delicate. If it crashes, there are no other symptoms, even the program listing in cTiVo will update.

**Comment by max-webster** [comment]
A couple of other things I noticed starting with beta 2, that continued with beta 3. I'll frequently go off with nothing running other than a cTivo conversion, and when I come back there'll be an error dialog "quicklookd quit unexpectedly". That's never happened for me when cTivo wasn't active. Also, I renamed my app to "cTivo Beta 2.app" and similarly for Beta 3. When I do options -> keep in dock from the Dock icon, a second icon appears. After I quit the app, clicking the remaining icon doesn't do anything, as if the Dock icon will only start an app with the original name.

I've been trying to convert a couple of "troublesome" files the last couple of days, ones that fail even when a bunch of others succeed that are converted all at the same time. I happened to notice some error dialogs flash up just for a moment and then disappear with no dismissal by me. One said something like "this channel always requires Transport Stream". In Preferences, I've got "Always Use Tivo's Transport Stream Format" selected. Does that setting apply to all channels everywhere, or only somehow to channels listed in the channel list in that same panel?

**Comment by mackworth** [comment]
so, on quicklookd, my guess is that's coincidental, or related to the video files being converted.  
If you look here: https://www.google.com/search?client=safari&rls=en&q=quicklookd&ie=UTF-8&oe=UTF-8 or here: https://discussions.apple.com/thread/1982954?tstart=0
lots of discussion on problems there (and possible fix)/

"Warning: This channel requires Transport Stream// But this TiVo does not support TS" is a new message in beta3, but it should only appear for Tivo Series HD devices. What kind of TiVo is that particular machine (named "Name"?) 

On "Does that setting apply to all channels everywhere, or only somehow to channels listed in the channel list in that same panel? "
All channels, all tivos (except HDs).

**Comment by mackworth** [comment]
I take it rebooting the server worked for you?

**Comment by mackworth** [comment]
OTOH, the error msg disappearing looks like a mistake in the beta2 release; will fix.

**Comment by mackworth** [comment]
Could not recreate the dock issue. Did you rename while it was running (not recommended)?
Are you on Sierra, or Yosemite or ... ? Have you tried dragging to the doc before running instead?  
Anybody else reproduce?

**Comment by mackworth** [comment]
@tannebil You're welcome to try out the new Handbrake GUI/CLI integration.  Just edit your presets in Handbrake, save as a custom name, then create a cTiVo format using that name; easy as pumpkin...

**Comment by max-webster** [comment]
I have a Roamio, not a Tivo HD. I'm trying again with this same show, and the converted shows list has an entry with about 1/5 of the progress bar filled in, but the status says "Downloaded" not "Downloading" and all downloading or converting stopped for about 10 minutes. Oh now the "does not support Transport Stream" message just popped up and now the status says "Failed". So it definitely takes its time deciding to halt due to the TS error, and it happens when the download is only fractionally finished. I'm going to reboot the Tivo again before turning in tonight and try this same show again.

Somewhere between rebooting the Tivo and the Mac bogging down to the point where I had to reboot it too, transfers started working again. However, it seems (just my intuition) like once one transfer fails, that sets off a cascade of problems where many others fail too. If a failed transfer leaves behind a small / incomplete blahblah.mp4 file behind in my cTivo output directory, a subsequent attempt for that same show also fails, but might succeed after I manually delete the original problematic .mp4 file and 'Delete' and 'Add to Queue' again in cTivo rather than 'Reschedule' the failed entry in the completed show list.

On the Dock issue, I definitely renamed the app before opening it for the first time. If I 'Keep in Dock' the icon of the running app, a new (non-running, non-functional) icon appears in the Dock. If I drag the app icon straight into the Dock, clicking on the icon runs the app, but a second copy of the icon (with the "running" dot indicator) appears. Both icons have the correct renamed name "cTivo 2.5 beta 3" as hover help. If I do "Keep in Dock" while both icons are present, both icons remain once I quit cTivo. If I drag icon #2 off the Dock, icon #1 becomes non-functional. If I drag icon #1 off the Dock, the remaining icon launches the app but spawns a second Dock icon while it's running.

This is all happening now on Sierra. The flakiness did start under beta 2 but I can't be sure exactly which aspects. I was forced to try the betas when Comcast switched the local channels to the new format. With beta 2 I seemed to lose a number of the choices in the format dropdown on the main window. When my preferences got nuked and I reinstalled beta 2, the format choices seemed to come back. Now with beta 3 I again have a small set of format choices, 10 total from "1080p", to "Default" which I'm using exclusively, down to "Faster / Smaller / Standard Def". I used to use H.264 Medium all the time, is that no longer an option or is that renamed to "Default"?

**Comment by mackworth** [comment]
So the log definitely demonstrates that cTiVo thinks it's an HD (or older). Thus the shows are being transferred in Program Stream and therefore TiVo sends over just 10% of the file, which is the audio-only portion of the show (and then ffmpeg complains that it has no video to work with).  All that is "normal", except for the starting point that this is a Roamio.  I'm truly puzzled. You only have the one TiVo, correct? Yet, other shows are being transferred with TS on that TiVo? Given the code, I don't see how that can happen. 

So let's start at the beginning. During initial cTiVo startup under Detail logging ( or just TivoManager Detail in Adv pref if you prefer), you'll get a set of lines that start with TXTKey. Let me know what those say (and the next few lines until 'Got new TiVo" ....).

On the file stuff, have you set the filename template in Adv Preferences? It shouldn't affect it, but depending on what a different template says, I could imagine it having that effect. Actually... those failed files should be deleted automatically. Oh, wait, is "Don't delete tmp files" in Adv Pref (Cmd-Opt-Comma) turned on?  That really should be off for production use. That can definitely have some of those effects.

You can still get to the old Formats, but they're strongly not recommended due to the TS/MP4 transition. It's explained in the [release notes under](https://github.com/dscottbuch/cTiVo/releases); see "Encoding the file (Formats)"  H.264 Medium used mencoder, which screws up a lot especially with TS files, (including FYI, crashing the processor and other very weird problems.) If you do want to use H.264Medium for PS streams, then turn off the global Use TS, and cTiVo wil still use PS for non-converted channels.

Sorry you're running into so many issues.

**Comment by mackworth** [comment]
On the dock, given the issues you've had, you might run a check on your preferences files.  In Terminal, cut and paste the following:

```
cd ~/Library/Preferences 
plutil -s *.plist
```
That will show you any files that can't be parsed, which probably means they're corrupted. (Not necessarily the other way around, though, as files could have wrong info and still be in proper format.) If it just gives you the prompt again, that means no problems. 

if you want to experiment (and don't mind resetting to default), you could delete your dock pref file:

In Finder's "Go" menu, hold the option key to choose "Library". Then go to `Preferences/com.apple.dock.plist` and trash that file. Immediately log out and then back in to reset.

**Comment by max-webster** [comment]
Only 1 Tivo. I had a 1st-gen model that I retired (unplugged) before ever trying cTivo. I think other shows must have transferred in TS because I've definitely converted shows that were on Comcast channels that became problematic due to the format switch. Also there were many downloads that went much faster than previously, which I guess it the hallmark of TS.

All prefs files validate OK.

I haven't done anything with the filename templates.

I can't find any TXTKey lines in the logs. I switched to Detail logging instead of Major, quit cTivo, and restarted. Should that have done it? In advanced preferences, TivoManager was already set to "Detail" and I had logs from a number of restarts over the last few days.

```$ grep -i txtkey /Users/cirrus/Library/Logs/cTiVo/*
(no output)```

One other oddness I have noticed is that sometimes once something has gone wrong and nothing will transfer anymore, physically deleting the .app file and unzipping it again seems to reset to a better state. Does cTivo actually write back into its own .app directory while it's running?

Today cTivo was halfway through a download when the progress bar appeared to stall, the UI became unresponsive, and the computer slowed to a crawl (although top still didn't think anything was using a lot of CPU). The slowness remained even after Force Quitting cTivo -- e.g. it took ~2 minutes for the unarchiver to unpack the cTivo .zip file again when I threw away the app. But after unpacking and restarting a fresh copy of cTivo, performance went back to normal. That's similar to what I observed in earlier beta when copies of mencoder would be left running after a Force Quit, except that any processes left behind now are invisible to top and Activity Monitor. Does cTivo get the chance to do any cleanup of child processes when it's Force Quit? (Is there a better signal to send to it to let it shut down gracefully?)

**Comment by mackworth** [comment]
That should definitely have done it.  Do you see the phrase "Got new TiVo"?

**Comment by mackworth** [comment]
Under Detail debug, can you post the log section from "Starting cTiVo" to "Initial loading from TiVo?

**Comment by mackworth** [comment]
Aha! I bet you have configure this as a manual TiVo, isn't it?  That goes through a different path, and might explain this problem.

**Comment by max-webster** [comment]
The original setup was a long time ago, but I do remember the Tivo wasn't recognized through Bonjour and I had to find its IP address myself.

**Comment by max-webster** [comment]
Here's how the "starting ctivo" piece looks:

```
2016-11-25 22:07:02:193 MTTiVoManager>restoreOldQueue@231>Restoring old Queue(57 elements)
2016-11-25 22:07:02:199 MTTiVo>initWithTivo:withOperationQueue:manual:withID:@161>testing reachability for tivo TiVo Name with address <80020050 0a00000b 60351100 00600000>
2016-11-25 22:07:02:650 MTTiVo>manageDownloads@725>Checking TiVo Name (10.0.0.11:80/443) queue
2016-11-25 22:07:40:203 MTTiVo>updateShowsStartingAt:withCount:@374>Initial loading from TiVo TiVo Name (10.0.0.11:80/443) at URL https://10.0.0.11:443/TiVoConnect?Command=QueryContainer&Container=%252FNowPlaying&Recurse=Yes&AnchorOffset=0&ItemCount=15
2016-11-25 22:07:40:457 MTTiVoManager>observeValueForKeyPath:ofObject:change:context:@824>Changed TiVo list to (
        {
        IPAddress = "10.0.0.11";
        enabled = 1;
        id = 1;
        manualTiVo = 1;
        mediaKey = <<TiVo Name MediaKey>>;
        userName = "TiVo Name";
        userPort = 80;
        userPortSSL = 443;
    }
)
2016-11-25 22:07:40:664 MTTiVo>parserDidEndDocument:@618>Finished batch for TiVo Name (10.0.0.11:80/443). Added 15 shows.
```

**Comment by mackworth** [comment]
Exactly, you have a manual TiVo configuration, and that didn't set up the serial number properly, so it didn't know it was a Roamio. I was able to recreate, and fix.  New version to test shortly.

**Comment by mackworth** [comment]
Here you go. Try this version out:

https://dl.dropboxusercontent.com/u/21507587/cTiVo.zip

**Comment by max-webster** [comment]
OK thanks. It failed about 1/3 of the way through the download progress bar, with "tivodecode-ng quit unexpectedly":

```
Process:               tivodecode-ng [5279]
Path:                  /Volumes/VOLUME/*/cTiVo Special Fix.app/Contents/MacOS/tivodecode-ng
Identifier:            tivodecode-ng
Version:               0
Code Type:             X86-64 (Native)
Parent Process:        cTiVo [5205]
Responsible:           tivodecode-ng [5279]
User ID:               504

Date/Time:             2016-11-26 17:32:07.626 -0800
OS Version:            Mac OS X 10.12 (16A323)
Report Version:        12
Anonymous UUID:        9ABACDEF-1B3A-74D3-7A29-48912669AEE7


Time Awake Since Boot: 64000 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Application Specific Information:
abort() called
*** error for object 0x7fc8abe06b60: pointer being freed was not allocated
 

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	0x00007fffc45a7dda __pthread_kill + 10
1   libsystem_pthread.dylib       	0x00007fffc4692797 pthread_kill + 90
2   libsystem_c.dylib             	0x00007fffc450d440 abort + 129
3   libsystem_malloc.dylib        	0x00007fffc45fd097 free + 530
4   tivodecode-ng                 	0x000000010e83790f TiVoDecoderTsStream::addPkt(TiVoDecoderTsPacket*) + 2767
5   tivodecode-ng                 	0x000000010e835b05 TiVoDecoderTS::process() + 965
6   tivodecode-ng                 	0x000000010e83406e main + 1518
7   libdyld.dylib                 	0x00007fffc4479255 start + 1

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000000  rbx: 0x0000000000000006  rcx: 0x00007fff513cc8f8  rdx: 0x0000000000000000
  rdi: 0x0000000000000307  rsi: 0x0000000000000006  rbp: 0x00007fff513cc920  rsp: 0x00007fff513cc8f8
   r8: 0x0000000000000000   r9: 0x0000000000000000  r10: 0x0000000008000000  r11: 0x0000000000000206
  r12: 0x000000010e845188  r13: 0x0000000000000001  r14: 0x00007fffcd16e3c0  r15: 0x0000000000000000
  rip: 0x00007fffc45a7dda  rfl: 0x0000000000000206  cr2: 0x00007fffcd150128
  
Logical CPU:     0
Error Code:      0x02000148
Trap Number:     133
```

**Comment by mackworth** [comment]
Well, that's not good; that's a nasty little bug I fixed long ago. Looks like you got the old version. This should fix that:
https://dl.dropboxusercontent.com/u/21507587/cTiVo.zip
Make sure you're using Version 2.5 beta4 (695) (in About cTiVo screen)

**Comment by max-webster** [comment]
Hmm. Mixed bag with this one. 3 out of 3 conversions I left running overnight finished successfully. I was prepared to declare 100% success. Then I tried doing some conversions today. The UI became unresponsive and the Mac slowed to a crawl, but I thought that was just ffmpeg using a lot of CPU. Then hours later when things calmed down, I found this:

```
2016-11-27 13:36:53:215 MTTiVo>updateShowsStartingAt:withCount:@377>Loading from TiVo TiVo Name (10.0.0.11:80/443) shows from 15 to 65 at URL https://10.0.0.11:443/TiVoConnect?Command=QueryContainer&Container=%252FNowPlaying&Recurse=Yes&AnchorOffset=15&ItemCount=50
2016-11-27 13:38:57:440 MTTiVo>connection:willSendRequestForAuthenticationChallenge:@789>TiVo Name (10.0.0.11:80/443) password ask
2016-11-27 13:38:57:440 MTTiVo>connection:willSendRequestForAuthenticationChallenge:@797>sending mediaKey from userDefaults
2016-11-27 13:38:57:444 MTMainWindowController>manageLoadingIndicator:@146>LoadingIndicator: MTNotificationTiVoUpdating for TiVo Name
2016-11-27 13:38:57:452 MTTiVo>manageDownloads:@711>TiVo Name (10.0.0.11:80/443) got manageDownload notification MTNotificationDownloadQueueUpdated
2016-11-27 13:38:57:452 MTTiVo>manageDownloads@726>Checking TiVo Name (10.0.0.11:80/443) queue
2016-11-27 13:38:57:452 MTDownloadTableView>reloadData@117>Reloading DL table
2016-11-27 13:38:57:630 MTTiVo>connection:didFailWithError:@818>URL Connection Failed with error Error Domain=NSURLErrorDomain Code=-1200 "**An SSL error has occurred and a secure connection to the server cannot be made.**" UserInfo={_kCFStreamErrorCodeKey=-9802, NSLocalizedRecoverySuggestion=Would you like to connect to the server anyway?, NSUnderlyingError=0x610000a49720 {Error Domain=kCFErrorDomainCFNetwork Code=-1200 "An SSL error has occurred and a secure connection to the server cannot be made." UserInfo={NSErrorFailingURLStringKey=https://10.0.0.11:443/TiVoConnect?Command=QueryContainer&Container=%252FNowPlaying&Recurse=Yes&AnchorOffset=15&ItemCount=50, NSLocalizedRecoverySuggestion=Would you like to connect to the server anyway?, _kCFNetworkCFStreamSSLErrorOriginalValue=-9802, _kCFStreamPropertySSLClientCertificateState=0, NSLocalizedDescription=An SSL error has occurred and a secure connection to the server cannot be made., _kCFStreamErrorDomainKey=3, NSErrorFailingURLKey=https://10.0.0.11:443/TiVoConnect?Command=QueryContainer&Container=%252FNowPlaying&Recurse=Yes&AnchorOffset=15&ItemCount=50, _kCFStreamErrorCodeKey=-9802}}, NSLocalizedDescription=An SSL error has occurred and a secure connection to the server cannot be made., NSErrorFailingURLKey=https://10.0.0.11:443/TiVoConnect?Command=QueryContainer&Container=%252FNowPlaying&Recurse=Yes&AnchorOffset=15&ItemCount=50, NSErrorFailingURLStringKey=https://10.0.0.11:443/TiVoConnect?Command=QueryContainer&Container=%252FNowPlaying&Recurse=Yes&AnchorOffset=15&ItemCount=50, _kCFStreamErrorDomainKey=3}
**2016-11-27 13:38:57:630 MTMainWindowController>manageLoadingIndicator:@146>LoadingIndicator: MTNotificationTiVoUpdated for TiVo Name
2016-11-27 16:14:41:683 MTDownload>connectionDidFinishLoading:@2635>finished loading TiVo file: 6740415.7 of 6784286.7 KB expected; 99.4%**
2016-11-27 16:14:48:683 MTTiVo>manageDownloads:@711>TiVo Name (10.0.0.11:80/443) got manageDownload notification MTNotificationTransferDidFinish
2016-11-27 16:14:48:683 MTTiVo>manageDownloads@726>Checking TiVo Name (10.0.0.11:80/443) queue
```

The first show that was being converted was still listed as "downloading" but the progress bar was stalled. All the other conversions were inactive. More than an hour later, that first show's status changed to "complete" when I wasn't looking, but the resulting file is audio-only. That log output went into a different log file:

```
2016-11-27 18:09:46:513 MTDownload>writeData@2407>Writedata all done for show Simon and Garfunkel: The Concert in Central Park
2016-11-27 18:09:46:673 MTTask>completeProcess@191>Finished task decrypt of show Simon and Garfunkel: The Concert in Central Park with completion code 0 and reason exit
2016-11-27 18:09:46:673 MTDownload>observeValueForKeyPath:ofObject:change:context:@188>Changing DL status of Simon and Garfunkel: The Concert in Central Park (TiVo Name) to Downloaded (3)
```

It looks like from 13:38:57:630 to 16:14:41:683, cTivo was spinning all my cores at 100% but not actually doing anything, or not anything loggable. When it hits an SSL error like this, does it go into some sort of busy loop? I do have "disable sleep" set in my cTivo preferences and the computer itself didn't go to sleep during this period.

**Comment by mackworth** [comment]
So, that looks like it did fix your TS issue, so that's good. I didn't really think the fix would change your load issue, but important to get out of the way
Assuming the connection is working, it should never have an SSL error. 
What level logging are you at?
Were there messages in the systems' log at the same time (in Console)?

**Comment by max-webster** [comment]
In Console, under 'System', I find just these couple of messages by searching for cTivo:

```
Nov 27 00:41:34 Stratus cTiVo[6691]: BUG in libdispatch client: kevent[EVFILT_MACHPORT] monitored resource vanished before the source cancel handler was invoked
Nov 27 12:48:13 Stratus cTiVo[10888]: BUG in libdispatch client: kevent[EVFILT_MACHPORT] monitored resource vanished before the source cancel handler was invoked
```

Within that timeframe, I get a lot of messages (can't really tell which app) like so:

```
Nov 27 13:38:36 Stratus com.apple.xpc.launchd[1] (com.apple.auditd[11559]): Endpoint has been activated through legacy launch(3) APIs. Please switch to XPC or bootstrap_check_in(): com.apple.auditd
Nov 27 13:39:15 Stratus com.apple.xpc.launchd[1] (com.apple.imfoundation.IMRemoteURLConnectionAgent): Unknown key for integer: _DirtyJetsamMemoryLimit
Nov 27 13:40:06 Stratus com.apple.xpc.launchd[1] (com.apple.imfoundation.IMRemoteURLConnectionAgent): Unknown key for integer: _DirtyJetsamMemoryLimit
Nov 27 13:40:57 Stratus com.apple.xpc.launchd[1] (com.apple.imfoundation.IMRemoteURLConnectionAgent): Unknown key for integer: _DirtyJetsamMemoryLimit
Nov 27 13:41:00 Stratus com.apple.xpc.launchd[1] (com.apple.auditd[11587]): Endpoint has been activated through legacy launch(3) APIs. Please switch to XPC or bootstrap_check_in(): com.apple.auditd
```

All the other system console messages during the same time period, look to be from Google software update.

My own log level is set to 'Detail'. I went into advanced prefs, and it looks like either installing the new version or flipping the log level in the normal preferences dialog has changed the level to 'Detail' for everything in the advanced prefs checkboxes.

**Comment by mackworth** [comment]
Beta 4 is now available.

@max-webster I'm not sure what to do next here. What does your activity Monitor show during the high usage times?  (Set View>All Processes, Hierarchically to see what's underneath cTiVo.)

**Comment by max-webster** [comment]
Hmm. In the hierarchical view (thanks, didn't know about that), cTivo is listed as about 20%, and underneath are tivodecode-ng, ccextractor, and cat all listed as 0%. I asked it to do a conversion (a 1-hr show) about 3 hours ago and last time I could see what the UI was doing it was still in "Downloading" phase about halfway through the progress bar. Doing 'top -o rsize', I see spindump near the top in memory usage and constantly in 'stuck' state. I wonder if some background diagnostic stuff is dragging the system down?  (Now I just did Force Quit on cTivo, and system responsiveness came back to normal, so despite all the 0% figures in Activity Monitor I think cTivo child processes must have been the cause of the slowdown.)

**Comment by mackworth** [comment]
That's normal in tivodecode, there's currently no way to get it to echo the progress info without a massive export.  Does it change anything if you don't do the captioning?  

Yes, it's possible. the OS does work for other processes and doesn't report it as part of User CPU time.  Next time you could try killing the child processes one at a time and see which one fixes it. Start with cat and then ccextractor and then tivodecode.  cTivo will notice pretty quickly that happened and kill the others, so you probably won't have much time between them.
