### ISSUE TITLE
Missing episode numbers? 

### ISSUE THREAD

**Issue by heyneenz** [dscottbuch/cTiVo#207]
I'm not sure if it's the beta version or the move to the Rovi guide but there seems to be a high number of missing episode numbers. When it downloads, the air date replaces the episode number. Any idea why this might be happening? (There were actually more shows previously that had the missing episode number but I had already deleted them prior to this post.) All of the Doctor Who episodes are missing Ep number info now though it listed them previously. Same with shows like "Full Frontal with Samantha Bee," "Once Upon a Time," and others. When I look at the TiVO guide, it lists the Season_EpNumber so I can rename the downloaded show but just wondering if this is a known issue or if I should reinstall? 

Also, really love the ffmpeg ComSkip/5.1 setting. Thank you for this and for all the hard work you put into this! 

<img width="690" alt="screenshot 2016-10-16 21 51 58" src="https://cloud.githubusercontent.com/assets/13545523/19423290/e107414a-93ec-11e6-867e-4c30c2653d24.png">

**Comment by mackworth** [comment]
It is indeed related to the Rovi transition. Tivo has a long-standing problem where the S/E info we get through the XML API is wrong or incomplete; frustratingly, it's different than what displays on the screen. With the older data, we could look up a series on TVDB by ID number, but now we're limited to doing the lookup by series name, which--not surprisingly--fails a lot.  Feel free to complain to TiVo; more voices may help.
