### ISSUE TITLE
Show downloads consistently fail

### ISSUE THREAD

**Issue by Dnelson024** [dscottbuch/cTiVo#208]
I've been trying to download a few shows and I consistently get a FAILED on the download status. It works briefly, then starts over before failing. 

I did find that short videos I had previously uploaded to the TIVO myself could be downloaded successfully, but nothing I recorded off TV. 
[com.cTiVo.cTiVo 2016-10-30 14-06.log.zip](https://github.com/dscottbuch/cTiVo/files/560549/com.cTiVo.cTiVo.2016-10-30.14-06.log.zip)

**Comment by mackworth** [comment]
Your cable provider (Comcast?) has transitioned to MP4, so you'll need the 2.5 version of the software (currently in beta, but should have no problems with it):

https://github.com/dscottbuch/cTiVo/releases

**Comment by mrfusiontm** [comment]
I'm having the same problem even after I updated to 2.5.
I'm on Comcast and its having trouble downloading shows from BBC America.
Here's a fresh log file

[com.cTiVo.cTiVo 2016-10-30 15-54.log.zip](https://github.com/dscottbuch/cTiVo/files/560584/com.cTiVo.cTiVo.2016-10-30.15-54.log.zip)

**Comment by mackworth** [comment]
@mrfusiontm  Thanks.  You did find a problem there (if commercialling fails due to the H.264, beta2 doesn't necessarily mark the channel as needing TS, so when it retries, it does the Program Stream again.  As a workaround, just go to Channel>Edit and add BBC to your list and specify TS downloads (or you can hit Test All Channels button and it'll scan all channels you have shows on and confirm whether it needs TS or not.

Secondly, the mencoder program is having real problems with H.264, so I strongly recommend trying the ffmpeg/comskip-5.1 format. Beta3 will deprecate mencoder entirely.

**Comment by Dnelson024** [comment]
I upgraded to 2.5 Beta and it was still not getting downloads to work. I emptied caches on cTivo, restarted the program, and it all seems to be good now.

THANKS!

**Comment by mackworth** [comment]
Hmm, that shouldn't be necessary. Can you post the log after 2.5 transition?

**Comment by mrfusiontm** [comment]
Ok, switching to the ffmpeg/comskip-5.1 seemed to help a bit.  The first BBC America show downloaded and is encoding now, however the second episode continues to fail.
Attached is the log for the second episode that keeps failing

I also noticed when I tried to test all the channels, only the first one came up as "Test PS" format - all the others came up as Youtube.  I was able to expose that format and switch them all by hand to complete the test.  

[com.cTiVo.cTiVo 2016-10-30 22-53.log.zip](https://github.com/dscottbuch/cTiVo/files/560832/com.cTiVo.cTiVo.2016-10-30.22-53.log.zip)

**Comment by mackworth** [comment]
ok, on the first issue, both tries for the second episode show Program Stream in the log, so that won't work.

> 2016-10-30 15:54:58:720 MTDownload>download@1565>Starting 4 download for Dirk Gently's Holistic Detective Agency: Lost and Found (Living Room); Format: ffmpeg ComSkip/5.1;  Skip commercials; Keep after iTunes; tivodecode-ng; Program Stream
> 2016-10-30 15:56:40:905 MTDownload>download@1565>Starting 4 download for Dirk Gently's Holistic Detective Agency: Lost and Found (Living Room); Format: ffmpeg ComSkip/5.1;  Skip commercials; Keep after iTunes; tivodecode-ng; Program Stream
> 
Is the channel now marked Use TS? If so, were these after that?

On the second issue, you're right. If TestPS Format is hidden, then it's not allowing its use.   Sorry for manual process, and thanks; will fix.

**Comment by mackworth** [comment]
@mrfusiontm Any progress with the "Lost and Found" episode?

**Comment by mrfusiontm** [comment]
No, both Dirk episodes continue to fail.
Two other shows came through just fine last night (CW and Fox)

**Comment by mackworth** [comment]
So, is BBC marked as "Use TS"?

**Comment by mrfusiontm** [comment]
No

**Comment by mackworth** [comment]
Then if you set that box, your shows should transfer ok.

**Comment by mrfusiontm** [comment]
I thought I tested that, but I'll try it again

**Comment by mrfusiontm** [comment]
Ok, set BBCA to TS and downloads still fail.  The Flash on CW also fails where that worked before.
Both seemed to fail in the encoding phase.  Here are a couple of fresh logs from this morning.

[com.cTiVo.cTiVo 2016-11-02 13-28.log.zip](https://github.com/dscottbuch/cTiVo/files/566892/com.cTiVo.cTiVo.2016-11-02.13-28.log.zip)
[com.cTiVo.cTiVo 2016-11-02 14-56.log.zip](https://github.com/dscottbuch/cTiVo/files/566893/com.cTiVo.cTiVo.2016-11-02.14-56.log.zip)

**Comment by mackworth** [comment]
So, I'm seeing the two encoding failures, but it's very strange that there is no encoding log shown in the master log.  It's getting to the point where it seams the non-commercial parts back together, but then failing.

Can you go into Advanced Prefs (Cmd-Opt-Comma), and set Delete tmp files Off. Should set Log level to Detail, and then run one of the files, say the Flash. Finally, after it fails, go to (Cmd-Shift-G in the finder to `/tmp/ctivo/`. You should see a see a folder `Flash- Monster_ffmpeg`. If you can zip up that folder and post it, that would be great. If this doesn't work, I'll have to give you a version with special logging.

**Comment by mrfusiontm** [comment]
Working on that now.  In the mean time, I set the Dirk show to "Handbreak AppleTV" and it downloaded without problems.

**Comment by mrfusiontm** [comment]
Hmmm, the file is too large to upload.  Looks like there's a 10MB limit.

**Comment by mackworth** [comment]
oh, sorry; of course,  that would have all the mp4s as well.  Let me know what the directory structure is, and just upload the logs therein.

**Comment by mrfusiontm** [comment]
Ah, that's better

[logs.zip](https://github.com/dscottbuch/cTiVo/files/570083/logs.zip)

**Comment by mrfusiontm** [comment]
Not sure if you need this as well

[segment_list.txt.zip](https://github.com/dscottbuch/cTiVo/files/570086/segment_list.txt.zip)

**Comment by mackworth** [comment]
Is there a file `/tmp/ctivo/The Flash - - Monster-1_ffmpeg/segments/segment_000067_001202.mp4`

**Comment by mrfusiontm** [comment]
Yes

**Comment by mrfusiontm** [comment]
691 MB zipped

**Comment by mackworth** [comment]
And are there files `/tmp/ctivo/encodeThe Flash -  - Monster.err` or `/tmp/ctivo/encodeThe Flash -  - Monster.txt`

**Comment by mrfusiontm** [comment]
[Archive.zip](https://github.com/dscottbuch/cTiVo/files/570108/Archive.zip)

**Comment by mackworth** [comment]
So, the script converts each of the non-commercial segments into separate MP4s, and then merges them into the output file. Everything looks good here, but when trying to merge, ffmpeg gives the error `Impossible to open '/tmp/ctivo/The Flash - - Monster-1_ffmpeg/segments/segment_000067_001202.mp4'` suggesting that file's not there.  Can you open that file in a player, make sure you can view it?

In addition to that, it's supposed to put that error message in the ctivo log, so that's a separate problem.

**Comment by mackworth** [comment]
and the file is named exactly that, correct?

Can you post the ctivo log that would include this latest run?

**Comment by mrfusiontm** [comment]
Here's two logs files from today and a screen shot of the mp4 filenames

[LogFiles.zip](https://github.com/dscottbuch/cTiVo/files/570127/LogFiles.zip)
![screen shot 2016-11-03 at 2 15 52 pm](https://cloud.githubusercontent.com/assets/6153579/19985503/31baf44c-a1d0-11e6-8ea8-30c51e9ea188.png)

**Comment by mrfusiontm** [comment]
Yes, I could open that first file and play it.  has picture and sound

**Comment by mackworth** [comment]
so strange.  If you cut and paste this directory:  `/tmp/ctivo/The Flash - - Monster-1_ffmpeg/segments/` into a Cmd-Shift-G in the finder, it works, correct?

**Comment by mrfusiontm** [comment]
Ah!  No it takes me to here:
![screen shot 2016-11-03 at 2 32 58 pm](https://cloud.githubusercontent.com/assets/6153579/19986059/7d2d36fe-a1d2-11e6-8bfb-0e3fd43e7c7f.png)

**Comment by mrfusiontm** [comment]
If I try to go to:
/tmp/ctivo/The Flash - - Monster-1_ffmpeg/

it says "The folder can't be found"

**Comment by dscottbuch** [comment]
You might try a second space between the two dashes. 

D. Scott Buchanan

Sent from my iPad

This email and any files transmitted with it are confidential and intended solely for the use of the individual or entity to whom they are addressed. If you have received this email in error please notify the system manager

**Comment by mrfusiontm** [comment]
oh, that worked

**Comment by mackworth** [comment]
Thank you, scott!

Ok, so now why do you have the  -  - anyways?  Did you set the filename template in Adv Prefs?

**Comment by dscottbuch** [comment]
Hugh,

maybe a string’s getting trimmed in one path and not another?

Scott Buchanan

4124 Stonebridge Lane
Rancho Santa Fe, CA 92091

**Comment by mrfusiontm** [comment]
I'm noticed lately that many of the shows on my TiVo no longer have episode numbers.

**Comment by mackworth** [comment]
I'm sure that's right. The script is written in bash, and I'm sure bash will happily change two spaces for one at the drop of a hat.  

So, what does Adv Prefs show for a filename?

**Comment by mrfusiontm** [comment]
Certainly the ones I'm having trouble with don't have episode numbers.

**Comment by mrfusiontm** [comment]
[mainTitle] - [seriesEpNumber] - [episodeTitle]

**Comment by mackworth** [comment]
Episode numbers is a problem due to the Rovi transition. 

ok, so seriesEpnumber is returning nothing (which is not correct), so you're getting two spaces and so bash is having a problem.  I should be able to recreate that and fix. 

In the meantime, if you just Mark commercials rather than Skip them, you should be ok.

**Comment by mrfusiontm** [comment]
What does marking them do compared to skipping them?

**Comment by mackworth** [comment]
It doesn't remove the commercials from the video, but adds Chapter markers, so you can easily skip them during playback.

**Comment by mrfusiontm** [comment]
ok, I'll try that for these problem shows

**Comment by mackworth** [comment]
Yup. Found the filename being copied into the temp file without quoting, which bash takes as meaning "convert this string into a array of words separated by whitespace, then put them back together into a string". It's fixed for beta 3.

**Comment by ryanchild** [comment]
Doh! I thought we had covered all the weird filename possibilities.  Let me guess, ```    echo file \'$segment_absolute_path_escaped\' >> "$merge_filename"``` ?

**Comment by ryanchild** [comment]
Also regarding ffmpeg error not showing up in the cTiVo log file, looks like I forgot to redirect `cat "$logfile"` to stderr

**Comment by mackworth** [comment]
Yup.  Those things that look like kinda like quote marks...not so much!

Not sure about the latter problem. In a later log, it did dump both the log and err files.  Appropriate change though.

Gotta admit; I keep coming to the same conclusion: bash semantics (let alone syntax) are just the worst.

**Comment by ryanchild** [comment]
Bash is certainly not built to gracefully handle filenames with odd characters or spaces that's for sure.  The `\'` are necessary though, for ffmpeg to correctly handle filenames in the filelist with quotes in them.

**Comment by mackworth** [comment]
Indeed.  It now reads:
`echo file "\'$segment_absolute_path_escaped\'" >> "$merge_filename" `
and works fine.
