### ISSUE TITLE
Audio is missing after download.

### ISSUE THREAD

**Issue by someoneAnyone** [dscottbuch/cTiVo#209]
There is a quick pop at the beginning of the downloaded movie but there is no audio throughout the movie. I've tried using the iPhone preset and the H.264 presets. Is there something I'm doing wrong?

I downloaded Version 2.5 beta2 (668)

**Comment by mackworth** [comment]
That's a problem with mencoder, probably a conflict with comskip. I'm deprecated all the mencoders in the next release.  

Try the new ffmpeg/comskip 5.1 Format

**Comment by someoneAnyone** [comment]
That seems to work! thank you.

**Comment by mackworth** [comment]
Glad to hear it.
