### ISSUE TITLE
TS downloads are audio only

### ISSUE THREAD

**Issue by hastryn** [dscottbuch/cTiVo#210]
Hi,

I'm using cTiVo on a Mid 2011 Mac Mini with Mac OS 10.11.16
Using Release 2.5; Beta 2, clean install (deleted all caches, logs, etc).
I'm pretty sure comcast has moved this channel to .mp4
"Channels" preference pane shows the Channel with all three boxes checked. 
Downloading a show from my TiVo HD using "Decrypted TiVo Show" Format
Results are: an mpg file with only 5.1 Audio (AC3) and no video.  File size is small as would be expected with only this content.
It plays fine on the TiVo

The Normal Log file says:
2016-11-07 12:48:55:843 MTTiVoManager>notifyForDownload:withTitle:subTitle:isSticky:forNotification:@1403>Notify: Warning: Show may be damaged/incomplete./nTransfer is too short: Possible Problem

Verbose Log File is attached with two attempted downloads, second attempted a different naming convention (after reading the other issue report).

Any ideas?

Thanks,
Gus

[com.cTiVo.cTiVo 2016-11-07 20-43.log.zip]
(https://github.com/dscottbuch/cTiVo/files/576810/com.cTiVo.cTiVo.2016-11-07.20-43.log.zip)

**Comment by mackworth** [comment]
So, that's not good.  I'd certainly try rebooting the TiVo.

Try doing the URL in your browser:
http://dvr-1d52.local.:80/download/Star%20Wars%20Rebels.TiVo?Container=%2FNowPlaying&id=10192696&Format=video/x-tivo-mpeg-ts
It'll ask for "user/password", give it "tivo/YourMAK"
I'm pretty sure it'll give you the same size file (albeit encrypted).

Does it have no video stream, or a zero-length one (you can use MediaInfo to be sure).
Does Audio play ok?

Is it just this one file? If so, it may just be damaged.

**Comment by hastryn** [comment]
Thats for the quick responce.

I rebooted the TiVo for these tests:
It downloads a .tivo file using the URL and the downloaded .tivo file is the same size as the previous attempts through cTiVo (as you expected).

There is no video stream.  Stream 0 is the AC3 5.1 and it plays fine.

I made another quick recording on the same channel and it had the same outcome...

I connected directly to the TiVo "now playing" over my browser and the only link provided is "Download MPEG-PS" as you might expect.

on a lark I tried Format=video/x-tivo-mp4 and the results were the same as the previous Format=...

Any other ideas?

**Comment by mackworth** [comment]
Well, you could try http://dvr-1d52.local.:80/download/Star%20Wars%20Rebels.TiVo?Container=%2FNowPlaying&id=10192696 , which would give you the PS stream.

Actually, I'm surprised that there wasn't a Download MPEG-TS option. 

Any issue on other channels?  Do you have another TiVo? If so, you could try moving it there (and check it) and then try downloading from there.

**Comment by hastryn** [comment]
That link has the same outcome of course.  I'm wondering if the TiVo HD doesn't support TS streams.  Do you have any experience from users with a TiVO HD showing that they can download TS streams?

This is the first channel I've found that uses mp4, the rest still work with PS streams as far as I can tell.  Unfortunately I don't have another TiVo to test against/with....   I've tried googling for "TiVo HD TS but I'm apparently not using the right keywords to find what I want, any suggestions on places to ask this question?

**Comment by mackworth** [comment]
Ah, that's it exactly.

http://www.tivocommunity.com/community/index.php?threads/tivo-adding-mpeg-4-support-to-tivo-hd.535769/page-3

Can you send me the Verbose log of cTiVo starting up?

**Comment by hastryn** [comment]
Well at least it looks like there is a work around to transfer the files to another TiVo device and then download it.  I'll post a question on that forum - thats for pointing me there.  

I think this log has what you need.  Let me know if it doesn't.

Thanks again,
Gus

[com.cTiVo.cTiVo 2016-11-08 16-00.log.zip](https://github.com/dscottbuch/cTiVo/files/579090/com.cTiVo.cTiVo.2016-11-08.16-00.log.zip)

**Comment by mackworth** [comment]
Thanks, yes:
016-11-08 10:39:50:191 MTTiVoManager>netServiceDidResolveAddress:@1616>TXTKey: swversion = 11.0n.H1-01-2-652
2016-11-08 10:39:50:191 MTTiVoManager>netServiceDidResolveAddress:@1616>TXTKey: platform = tcd/Series3

i can add a warning msg for other HD users

**Comment by mackworth** [comment]
@hastryn, can you do me a favor? Turn on "Always use Transport Stream" in Preferences>Channels, run a show from a channel that is still working (aka not converted to H.264), and then let me know whether it worked anyways or not. (And then turn off the preference)

**Comment by hastryn** [comment]
Sure no problem, it worked fine!

Thanks again for all the help!  I really appreciate all the work you do on this app.

Gus

**Comment by mackworth** [comment]
Good, so that means I don't have to prevent TS on HDs, just properly report whenever we see a damaged file. I'll have a next-version beta shortly, if you could just test that warning, that'd be great.

**Comment by hastryn** [comment]
Sure will do
