### ISSUE TITLE
Download Fails - Transfer too short?

### ISSUE THREAD

**Issue by mrfusiontm** [dscottbuch/cTiVo#211]
cTiVo ver 2.5 beta 2

I'm getting an error that says the "transfer is too short" and it fails.  I've checked the program on my TiVo and it appears to be the correct length.  Downloading with ffmpeg ComSlip/5.1 where I'm marking the commercials instead of skipping them.

Here's the log:

[com.cTiVo.cTiVo 2016-11-14 13-10.log.zip](https://github.com/dscottbuch/cTiVo/files/589289/com.cTiVo.cTiVo.2016-11-14.13-10.log.zip)

**Comment by mackworth** [comment]
I've hit that problem in beta2 as well. It's a H264 channel you're downloading as Program, but it's not recognizing it due to the particular path you're taking. 

Just mark the channel as TS and you should be fine.

**Comment by mrfusiontm** [comment]
It is marked as TS....


![screen shot 2016-11-14 at 5 47 54 pm](https://cloud.githubusercontent.com/assets/6153579/20290053/8a4d1a70-aa92-11e6-8008-2bdc25b7d38f.png)

**Comment by mackworth** [comment]
Ok, that is bizarre. Your log shows:
Starting 8 download for Dirk Gently's Holistic Detective Agency: Watkin (Living Room); Format: ffmpeg ComSkip/5.1;  Mark commercials; Keep after iTunes; tivodecode-ng; Program Stream

Reading the code, I can't see any way it should spec Program Stream  if that Use TS column is on.

**Comment by mackworth** [comment]
Have you tried it again; maybe that got set later?

**Comment by mrfusiontm** [comment]
Its been set that way since the last time we had a problem with this show.  I'll try setting it to always use the TS and see if that make a difference.

**Comment by mrfusiontm** [comment]
Forcing it to always be TS seems to be working.  Is there some way to know for sure which channel a show corresponds to on the channels pref panel?  I know this show is on BBC America and that is set to use TS, but how can I know for sure which channel this show *thinks* its coming from?

**Comment by mrfusiontm** [comment]
And alternately, is there any reason why forcing it to always use TS would be a problem?

**Comment by mackworth** [comment]
If you right click on table heading, you can show the channel column.  Could be the HD channel?

Mencoder has a lot of trouble with Transport Stream. There's anecdotal evidence of more frequent transfer problems, but you may not have a problem.

**Comment by AToner** [comment]
Same issue (OS X 10.12.1)

`
Log below.
2016-11-14 20:16:16:426 MTAppDelegate>applicationDidFinishLaunching:@213>Starting cTiVo; version: 668
2016-11-14 20:16:16:826 MTTiVo>updateShowsStartingAt:withCount:@348>Initial loading from TiVo TiVo Name (192.168.7.46:80/443) at URL https://192.168.7.46:443/TiVoConnect?Command=QueryContainer&Container=%252FNowPlaying&Recurse=Yes&AnchorOffset=0&ItemCount=15
2016-11-14 20:16:24:609 MTDownload>download@1750>Starting URL http://192.168.7.46:80/download/Dirk%20Gently's%20Holistic%20Detective%20Agency.TiVo?Container=%2FNowPlaying&id=318385 for show Dirk Gently's Holistic Detective Agency: Watkin in 0.0 seconds
2016-11-14 20:17:15:328 MTTiVoManager>notifyForDownload:withTitle:subTitle:isSticky:forNotification:@1403>Notify: Warning: Show may be damaged/incomplete./nTransfer is too short: Possible Problem
2016-11-14 20:17:16:184 MTTask>failedTaskCompletion@206>Task encode failed
2016-11-14 20:17:16:197 MTTiVoManager>notifyForDownload:withTitle:subTitle:isSticky:forNotification:@1403>Notify: TiVo show failed/nRetrying: Can't Download
2016-11-14 20:17:18:212 MTDownload>download@1750>Starting URL http://192.168.7.46:80/download/Dirk%20Gently's%20Holistic%20Detective%20Agency.TiVo?Container=%2FNowPlaying&id=318385 for show Dirk Gently's Holistic Detective Agency: Watkin in 57.1 seconds
2016-11-14 20:17:57:830 MTAppDelegate>cleanup@1063>cTiVo exiting`

**Comment by mackworth** [comment]
So, let's start with checking the same cause: Is BBC marked as Use TS in Edit>Channels ? If not, mark it as Use TS, and you should be fine.

(If not, right-click on Download Table's header to add the Station column, and make sure that the station name of the download is the same as the one in the Channel table.)

**Comment by AToner** [comment]
It wasn't checked and checking Use TS got it.  Thanks!

**Comment by mrfusiontm** [comment]
Ok, so here's what I found.  If I look at the info on the show, I see this:

[image: Inline image 1]


It doesn't show up in the list of channels tested (even though I know I ran
the tests just the other day when we were trouble shooting)
Here's what showed up:

[image: Inline image 2]

So, let me know if adding a new one by hand like this is correct:

[image: Inline image 3]

I'm not sure if the name is correct.  Do I need the -W-810 HD part after or
is BBCAMHD enough?

Oh, on a side note, when I clicked the "+" and it added a new channel named
"???", when I tried to rename it, I could only put one letter at a time.  I
had to keep double clicking on it, add a letter, it would think I was done
and I'd have to double click it again to add the next letter.

**Comment by mackworth** [comment]
GitHub lost the images, but that sounds correct.  Just BBCAMHD should be correct, and then check Use TS. Looks like you have two channels BBCAMHD and BBCAPH, so that would explain the problem.  

Your side note is accurate and fixed for next release (it's trying to keep it sorted, so it resorts after each letter, losing the focus)

**Comment by mackworth** [comment]
So, I think this is all resolved. Let me know otherwise.

**Comment by mackworth** [comment]
In fact if you could remove both BBCs and try it again with beta3, that would be great.
