### ISSUE TITLE
Can I make cTiVo just work on one file at a time?

### ISSUE THREAD

**Issue by alecksjaycubs** [dscottbuch/cTiVo#212]
I'd like to force cTiVo to download and encode one file completely before moving on to the next. When it tries to encode two shows things get bogged down.

**Comment by mackworth** [comment]
Yes.  It's a hidden option, but documented in the Advanced Topics wiki page: 

There are a few options that are not presented in the user interface. ... To set these, use the OS X defaults command in Terminal, e.g. 'defaults write com.cTiVo.ctivo MaxNumberEncoders 3', then use 'defaults read com.cTiVo.ctivo' to lock them in
