### ISSUE TITLE
How does cTiVo determine whether a Handbrake encode has stalled?

### ISSUE THREAD

**Issue by jfrancin** [dscottbuch/cTiVo#213]
How does cTiVo determine whether a Handbrake encode has stalled? I know that cTiVo expects to get output from standard out and uses the percentage to figure things out.

I'm asking because I've been having problems where cTiVo seems to arbitrarily decide that a Handbrake encode has stalled and hasn't reached 100%, and will fail the transfer. Is there an upper time limit that it uses in addition to the percentage reports coming through standard output?

**Comment by mackworth** [comment]
Yes there is.  For all encoders, if cTiVo sees no progress reports (either pipe reading if concurrent with download, or the % reports if not) over 4 minutes, then it will terminate the download and try again.  (Note though that we found that after HB, in particular, reports 100%, then it can take even longer than that to finish things up, so we extend that time to 10 minutes at 100%.)

You can extend those times using secret preferences, but before you do...

Which Format are you using? I'm just about to release Beta3, which has a much newer version of Handbrake, which has many new presets and a lot of other fixes.

**Comment by jfrancin** [comment]
Yeah, that's exactly what Handbrake is doing -- reporting 100% (with no ETA estimate) long after the encode is allegedly done. 

This seems to happen most frequently for "Conan" on TBS.

I'm using the "AppleTV 3" preset that I use in the GUI version of HandBrake. My GUI version is newer than what you're shipping, I think. (HandbrakeCLI in your bundle is 0.10.1, I'm using 0.10.5). However, there are reports of HB hanging at 100% as well, but in the most recent one reported, it's not using 100% of the CPU, whereas in my case it is using 100%, as if it's not quite finished.

Just for giggles I'm trying the most recent nightly HandbrakeCLI file in place of the one you shipped to see if it works any better.

**Comment by mackworth** [comment]
So you're seeing even longer than 10 minutes?  Let me know if it's still true in latest Handbrake, and I'll extend that number.  (If you want to experiment:

`defaults write com.ctivo.ctivo MaxProgressDelay 300`   will set it to 5 minutes. 

I was incorrect, there is currently no separate preference for the 100% timeout value, but if you sent MaxProgressDelay greater than 600, it should affect the 100% timeout as well.

**Comment by jfrancin** [comment]
The latest Handbrake (version string HandBrake 20161116195531-b9c5daa-master) worked fine. I suspect it's a bug in the older Handbrakes. So at this point I'm marking this as closed. Thanks for the hidden setting -- I'll keep it in mind if I encounter another situation like this.
