### ISSUE TITLE
Beta 3 issues thread

### ISSUE THREAD

**Issue by mackworth** [dscottbuch/cTiVo#214]
For any problems or concerns with the new beta release. Candidate for final release

**Comment by mrfusiontm** [comment]
I've tried using HB_SuperHQ and Higher Quality and both are giving me a lot of artifacts like this:

![screen shot 2016-11-23 at 11 55 42 am](https://cloud.githubusercontent.com/assets/6153579/20576775/261741b4-b174-11e6-8dcf-b950ec47906c.png)

I've seen it on at least two shows so far.  I tried both formats on one show and got the same results both times.

Here's the log:
[com.cTiVo.cTiVo 2016-11-23 14-42.log.zip](https://github.com/dscottbuch/cTiVo/files/609858/com.cTiVo.cTiVo.2016-11-23.14-42.log.zip)

**Comment by mackworth** [comment]
So, the logs don't say anything, because the encoders (ffmpeg for Higher Quality and Handbrake for HB_SuperHQ ) simply report a successful conversion. The more detailed logs from those encoders are deleted upon success, so to see them, you'd have to temporarily set "Don't delete files" in Adv Prefs to read them. THey'd probably report errors at those points in the conversion process, but continue on.

But, unless this is unique to those 2 formats, my presumption is that the files are indeed damaged at those points? Are you seeing any glitches on the TiVo itself?  Have you had your cable signal level checked? 

Have you tried the Decrypted TiVo Show version, and looked at those same frames? If you're seeing glitches there, nothing either ctivo or the encoders can do to recover.  (Although if they look good on the TiVo and bad in Decrypted, there is a small chance that the decoding process itself is failing; similarly you might check the logs in decryptxxx.log and .err and/or switch to the Java TiVoLibre decrypter.)

BTW, not really recommended to run regularly at Verbose Debug level. It generates a lot of data, which masks any real problems, and can slow down the process. I normally keep it at Major.

**Comment by mrfusiontm** [comment]
The shows look fine on the TiVo itself.
I'll try a Decrypt TiVo format and then
another Higher Quality version without deleting the temp files.

My Debug level was set at default when I checked it.  Not sure why you were
seeing the verbose debug level....  I've set to it Major now.
I'll clear out the log before I start the HQ download.


Two other questions:  Do you know why the commercial skipping is causing
problems yet and do you think the episode numbers will ever come back?  I
know you said that was a TiVo thing but I'm just curious if you think there
could eventually be a work around.


Thanks!

**Comment by mrfusiontm** [comment]
Ok, the Decrypted TiVo show was messed up as well.
I downloaded  the TiVoLibre java file for testing  from:
https://github.com/fflewddur/tivolibre
and put it into /usr/local/bin.  I'm not sure what the next step is to test
decoding with that.
I can see in the advanced settings and option to Decode with:  but
the TiVoLibre is greyed out.

I'll include the logs as soon as the encoding is done. (or can you see what
you need as soon as downloading is done?)

Tom

**Comment by mackworth** [comment]
Tivolibre is included in ctivo, but you need to install Java runtime to make it work. Once that's installed, TiVoLibre should no longer be greyed out. 

https://www.java.com/en/

Encoding with Decrypted TiVo Show should be done as soon as it's finished downloading. The ctivo log won't say much, but you can look in the encryptxxx.log and .err to see if there are msgs. (It's huge, so posting the whole thing is prob not an option.)

**Comment by mrfusiontm** [comment]
Flash downloaded with Decrypt TiVo:
In the decryptxxx.err file I'm seeing stuff like this:

1000336 : stream_id: e0, block_no: 1
1001088 : stream_id: e0, block_no: 1
1001840 : stream_id: e0, block_no: 1
1002592 : stream_id: e0, block_no: 1
TS ProgAssocTbl : Program Num : 1
TS ProgAssocTbl : Program PID : 0x64 (100)
Re-use existing stream for PMT PID 0x0064
TS ProgMapTbl   : StreamId 0x02 (2), PID 0x0eb3, Type 0x02 (2 : Video)
Re-use existing stream for PID 0x0eb3
TS ProgMapTbl   : StreamId 0x81 (129), PID 0x0eb4, Type 0x01 (1 : Audio)
Re-use existing stream for PID 0x0eb4
TS ProgMapTbl   : StreamId 0x97 (151), PID 0x0eb6, Type 0x03 (3 :
PrivateData)
Re-use existing stream for PID 0x0eb6

TiVo Private    : Validator                 : 0x5469566f (TiVo)
TiVo Private    : Unknown                   : 0x81 0x3 0x0 0xcd
TiVo Private    : Stream Bytes              : 40
TiVo private data : matched PID 0x0eb3

Updating PID 0x0eb3 Type 0xe0 Turing Key
88 c0 00 20 30 00 08 07 ff ff ff fc 00 02 00 01  ... 0...........
88 c0 00 20 50 00 08 07 ff ff ff fc 00 02 00 01  ... P...........
TiVo Private    : Block No                  : 1
TiVo Private    : Crypted                   : 0x00000000
TiVo Private    : PID                       : 0x0eb3 (3763)
TiVo Private    : Stream ID                 : 0xe0 (224)
TiVo Private    : Turing Key                :
88 c0 00 20 50 00 08 07 ff ff ff fc 00 02 00 01  ... P...........
TiVo private data : matched PID 0x0eb4

Updating PID 0x0eb4 Type 0xbd Turing Key
88 c0 00 20 30 00 08 07 ff ff ff fc 00 02 00 01  ... 0...........
88 c0 00 20 50 00 08 07 ff ff ff fc 00 02 00 01  ... P...........
TiVo Private    : Block No                  : 1
TiVo Private    : Crypted                   : 0x00000000
TiVo Private    : PID                       : 0x0eb4 (3764)
TiVo Private    : Stream ID                 : 0xbd (189)
TiVo Private    : Turing Key                :
88 c0 00 20 50 00 08 07 ff ff ff fc 00 02 00 01  ... P...........
Do NOT flush packets for write
1047336 : stream_id: e0, block_no: 2
1048088 : stream_id: e0, block_no: 2
1048840 : stream_id: e0, block_no: 2
1049592 : stream_id: e0, block_no: 2
1050344 : stream_id: e0, block_no: 2

and this:

1303392 : stream_id: e0, block_no: 2
1304144 : stream_id: e0, block_no: 2
TS ProgAssocTbl : Program Num : 1
TS ProgAssocTbl : Program PID : 0x64 (100)
Re-use existing stream for PMT PID 0x0064
TS ProgMapTbl   : StreamId 0x02 (2), PID 0x0eb3, Type 0x02 (2 : Video)
Re-use existing stream for PID 0x0eb3
TS ProgMapTbl   : StreamId 0x81 (129), PID 0x0eb4, Type 0x01 (1 : Audio)
Re-use existing stream for PID 0x0eb4
TS ProgMapTbl   : StreamId 0x97 (151), PID 0x0eb6, Type 0x03 (3 :
PrivateData)
Re-use existing stream for PID 0x0eb6
1305272 : stream_id: e0, block_no: 2
1306024 : stream_id: e0, block_no: 2
1306776 : stream_id: e0, block_no: 2
1307528 : stream_id: e0, block_no: 2

But nothing that says "error"



Gotham is using format High Quality and I found this:


In decryptGotham*.err I see the same kind of things I found in the Flash
decrypt:


but in bufferGotham- -Mad City - Time Bomb.log, I see a bunch of things
like this:

[mpegts @ 0x7f9b0e006200] PES packet size mismatch
[mpegts @ 0x7f9b0e006200] Could not find codec parameters for stream 2
(Unknown: none ([151][0][0][0] / 0x0097)): unknown codec
Consider increasing the value for the 'analyzeduration' and 'probesize'
options
Input #0, mpegts, from '/tmp/ctivo//bufferGotham -  - Mad City- Time
Bomb.mpg':
  Duration: 01:01:02.60, start: 15629.936611, bitrate: 5195 kb/s
  Program 1
    Stream #0:0[0xe75]: Video: mpeg2video (Main) ([2][0][0][0] / 0x0002),
yuv420p(tv, bt709), 1280x720 [SAR 1:1 DAR 16:9], 25000 kb/s, 59.94 fps,
59.94 tbr, 90k tbn, 119.88 tbc
    Stream #0:1[0xe76]: Audio: ac3 ([129][0][0][0] / 0x0081), 48000 Hz,
stereo, fltp, 448 kb/s
    Stream #0:2[0xe78]: Unknown: none ([151][0][0][0] / 0x0097)
[mpeg2video @ 0x7f9b0e00e800] gray decoding requested but not enabled at
configuration time
[mpeg2video @ 0x7f9b0e00e800] warning: first frame is no keyframe
[mpeg2video @ 0x7f9b0e00e800] ac-tex damaged at 18 1
[mpeg2video @ 0x7f9b0e00e800] ac-tex damaged at 43 5
(these damage messages run through out the file)

Going to restart Tivo now and see if I can use the TiVoLibre option

**Comment by mackworth** [comment]
That decoding msgs look fine; probably won't improve with TivoLibre.  

As this looks like mpeg2 over TS, another thing to try is downloading via Program Stream if that channel supports it.

**Comment by mrfusiontm** [comment]
Well, I tried over PS and it looks the same.  I even went back to the
previous version of cTiVo and its downloading with the same artifacts in
all three shows from two different stations.
I rebooted the TiVo and it still looks the same.
I'm open to any suggestions for why this might be happening and how to fix
this because these are pretty unwatchable.

**Comment by mackworth** [comment]
I think the issue is damage in the original recording on the TiVo. Frequently there are digital artifacts that are not visible on the screen, but due to TiVo's encryption/transfer process become worse. Sometimes this means that the file can't be transferred at all, sometimes it just screws up the video. 

At this point, my main suggestion is to have the cable signal checked. There is a signal meter available in the TiVo UI, so you can see if there's a signal strength issue. There also can be effects from microwaves, garage door openers, etc, particularly if any cable connections are loose or the cable is damaged anywhere. 

https://support.tivo.com/articles/Troubleshooting/Troubleshooting-Digital-Cable-Signals-Roamio-Series-Premiere-Series-and-Series3-DVRs

**Comment by mackworth** [comment]
Beta 4 is now available
