### ISSUE TITLE
[2.5 beta 2] Problems with "ffmpeg ComSkip/5.1" Video Format

### ISSUE THREAD

**Issue by ooglek** [dscottbuch/cTiVo#217]
I use cTivo to download NBC Nightly News each evening, then share it to my iPhone via a private Podcast URL.

Since using cTivo 2.5, it is super reliable at downloading and encoding the video, but the output is extremely inconsistent.

Issues include

1. Skipping in the middle of the broadcast where there is seemingly no full black screen or other indication of a commercial start/break
2. The video stops about 15 minutes in, but the video in the PodCast app seems to continue on the last frame for another 15-20 minutes (no more video or audio though)
3. Some Commercials are not skipped

I've moved away from using ComSkip for now, since the output is very inconsistent. 

What version of ComSkip are you using (I cannot find 5.1, only mentions of 3.5.3 and 0.80) and what changes should I make to the parameters to pass to ComSkip in order to tweak the detection?

In Resources/comskip.ini, it looks like you are using detect_method=255, but maybe I just need to play with the settings?

**Comment by mackworth** [comment]
So, first, sorry to hear that. You should upgrade to beta5 to make sure we're on the same version; I think that's an older version of comskip.  Second, I haven't spent any time with comskip settings in a long time, so I don't have many suggestions and would actually appreciate any input here.  You could also work directly with the comskip forums, just take the output of a Decrypted TiVo Show download as the source video. There's a good guide to tuning here:  http://www.kaashoek.com/files/tuning.htm . Note that if you decide a certain subscription (e.g. Nightly News) should have a different tuning (ini file) than general, you can duplicate a Format and add your own ini file in the duplicated one.

The 5.1 refers to the ability to pass through 5.1 channel surround sound, not comskip's version. You can see the current executable in the 2.5 branch on this site. 

Third, there's a difference between what the output of comskip is (an Edit Decision List that is readable text which specifies the range of commercial times) and the resulting edit of a video. Point 1 and 3 sound like comskip issues, where that file specifies an incorrect range, and there's not much cTiVo can do about that (except for comskip parameters). But number 2 sounds like an encoder issue, where the EDL may be correct, but the encoder is creating a wierd video; I'd love to see that EDL and source video that causes that issue.

If you go to Adv Prefs (Cmd-Opt-Comma), and turn on `don't delete tmp files`, then you can see the EDL file in the tmp directory. (Be sure to put it back, or your hard disk will explode.).

**Comment by mackworth** [comment]
@ooglek Any news?

**Comment by mackworth** [comment]
@ooglek  Let me know if there's still an issue.
