### ISSUE TITLE
None of the shows on my TiVo are listed on cTiVo (2.5)

### ISSUE THREAD

**Issue by srbny** [dscottbuch/cTiVo#224]
cTiVo lists my TiVo, which I assume means TiVo is on my network, but indicates there are "0" shows avaliable to download, when I have 2 programs in "My shows" on my TiVo.  I have signed in to my TiVo account and my TiVo is set to download shows.  cTIVO has "show protected shows" checked. Is this a problem with TiVo or with cTiVO? If the latter, what can I do?

**Comment by mackworth** [comment]
Sorry to hear that.  To figure out what's going wrong, can you change the Debug level to Detail in cTiVo's Preferences, hit Cmd-R (Refresh TiVo), and then post the resulting log (Help>Show Log Files; look for today's log).

**Comment by srbny** [comment]
Thanks for your quick reply. It looks like cTiVO can't connect to the server. Hopefully, you can tell me what to do about that.

**Comment by srbny** [comment]
I can't tell if the log was included in my previous comment, so I'll try again.
[cTiVo log.txt](https://github.com/dscottbuch/cTiVo/files/684181/cTiVo.log.txt)

**Comment by mackworth** [comment]
Well, the most likely reason would be a problem in the TiVo. Have you tried restarting it? 

You can check if it's working by using the URL directly in your browswer:

https://dvr-2312.local./TiVoConnect?Command=QueryContainer&Container=%252FNowPlaying&Recurse=Yes&AnchorOffset=0&ItemCount=15

You'll need the username: "tivo" and the password is your MAK.

A couple of other questions:
The names are strange. You have one called TiVo Name? and one called srb?
Do you have anything configured in Edit>Edit Tivos? Can you paste a screen shot there?

**Comment by srbny** [comment]
1. The authorization fails when I try to sign in to the link
2. Restarting TiVo doesn't help
3. I called TiVo support who told me I need TiVo Desktop, which is not available for Mac. (I apparently don't have this app on my computer or Time Machine backups, but I was able to use cTiVo a few months ago when I had a different TiVo DVR.)
4. As for the names, DVR 2312 is the name that came with the machine. I changed it to srb 160, and then switched back, but both names remain in the TiVo list.
![ctivo](https://cloud.githubusercontent.com/assets/24904103/21654891/8a0643a0-d285-11e6-92db-08aff0c45b73.jpg)
5. The entry called "Tivo Name" is offline in cTivo.  How can this be fixed?

**Comment by mackworth** [comment]
TiVo support is incorrect. They know nothing of ctivo. 
There is no tivo named TiVo Name. It was manually configured in cTiVo at some point. You should just delete it (select it, and hit the minus sign). This was confusing me.
If you exit ctivo and go back in, it should remove the extra copy of TiVos

The extra Tivo's confused me. I recognize the symptom now: I'll bet you're using an antivirus package (e.g. Avast or Kaspersky) on your Mac. That will block any secure connection to a tivo.  You need to "whitelist" your TiVo to let it get through the software. Check with the website, and let me know what the process is, so I can post it here.

You shoud have gotten cTivo's Antivirus error msg though.  I see from your log that you're getting a slightly different error, so I'll check for that in the future. Once I generate that, I'd like your help: you'll need to "unwhitelist" your tivo, run the test version and make sure you get the error message, and then whitelist it again.

**Comment by srbny** [comment]
You are right: if I turn my Avast antivirus software off, the program list appears. HOWEVER, the TV program doesn't actually download. The DL stage just stays on "Waiting."

Also, for some reason, cTiVo is not generating logs. The last one I have is from yesterday.

**Comment by srbny** [comment]
I forgot to mention that I had a long telephone conversation with Avast tech support. At least with the free version of Avast, there's no way whitelist the TiVo DVR.

**Comment by mackworth** [comment]
Well, that's annoying.  But at least you know the problem now.

So, Waiting means that it's pausing between downloads to allow the TiVo's fragile file transfer code to breathe between downloads. Should be no more than 60 seconds.
If it's longer than that, I need the logs, so I can see what's happening.  

So, when you do the Show logs in Finder, there's none modified today?  (After a certain amount of logging, it stops writing to the previous one and creates a new one.)

**Comment by srbny** [comment]
It still does nothing but wait, but at least I have a log now -- quite a long one.
[com.cTiVo.cTiVo 2017-01-05 01-23.log.txt](https://github.com/dscottbuch/cTiVo/files/686250/com.cTiVo.cTiVo.2017-01-05.01-23.log.txt)

**Comment by mackworth** [comment]
So the reason it's saying Waiting is that it's getting a tiny file (containing "Access Forbidden", so it's waiting a minute and trying again.  Should Fail in about 20 minutes.

And, "Access Forbidden" answer from TiVo is not good.

Check in TiVo's System Information screen. TiVoToGo should be a,a,a (or a,a,a,a) otherwise there is a problem.
Double check your MAK, compare with Tivo and cTivo.

Try rebooting everything.  Start with your TiVo and your router/wifi and your Mac.  There may be corruption in some of the caches.

**Comment by srbny** [comment]
First, thank you so much for putting s much attention into my issue. TiCoToGo is i,i,a,a. What can I do about that? Can I simply change it myself?
Over the past 2 days I have rebooted everything, but not at the same time.
The TiVo box has a "Network Remote Control" option which allows devices on the network (e.g., my Mac) to access and control the TiVo box. Should that be enabled?

**Comment by mackworth** [comment]
cTiVo doesn't currently use the network Remote control, although we may in an upcoming release.

Should be able to go to  https://www.tivo.com/tivo-mma/dvrpref.do ( logging into your account).  There's a column for Video sharing, which is probably off. If it is, turn it on, and tell your TiVo to Connect to the network service and then check TiVoToGo again. If not, wait a few hours and connect again. If still not, then call TiVo Tech Support; tell them your TivoToGo (on a PC) isn't working, that someone online told you that it should be a,a,a,a and it's not.  I suggest you not mention either (a) ctiVo or (b) Macintosh.

**Comment by mackworth** [comment]
So, please try this version,preferably with the avast in and/or the service not authorized for transfer. It will give me more info about why you weren't alerted

**Comment by mackworth** [comment]
Here's the file:

https://dl.dropboxusercontent.com/u/21507587/cTiVo.zip

**Comment by srbny** [comment]
Sorry, I didn't mean to close the thread. I'll get back to you as soon as I have TiVo service again.

**Comment by srbny** [comment]
I think it just won't reboot. We'll see tomorrow. Since it's from the cable company, if it's dead, they'll simply give me a new one -- but then I won't have the program I want to save that started all this.

**Comment by srbny** [comment]
The problem was not in cTiVo, but in my TiVo DVR (which, it turns out, had many problems, including the "i,i,a,a" designation for TiVo-to-go.  I can now download programs using either my original cTiVo or the beta version you sent me.   I can't thank you enough for all the suggestions you offered and the time you spent.

**Comment by mackworth** [comment]
Okay, glad to hear it's doing well.  One favor before you go?  Can you turn on Avast, and try downloading again with the one I just sent. It obviously wont work, but I need to see the log to know why you didn't get a warning message about Anti-virus.
Thanks

**Comment by srbny** [comment]
This is the most recent log for cTiVo.  If it contains more than 1 project, the last one is definitely the beta version.  In any case, I had Avast turned on for all of them. With the new TiVo, Avast does not block the transmission.  Thanks again. If I can do anything else for you, don't hesitate to ask.

**Comment by mackworth** [comment]
Glad to hear!

**Comment by srbny** [comment]
I was wrong. Avast was NOT on. When I turned it on, the transmission failed! 
[cTiVo log2.txt](https://github.com/dscottbuch/cTiVo/files/691070/cTiVo.log2.txt)

**Comment by mackworth** [comment]
As expected.  Thanks for the log; it explained why you weren't getting the message. Please try this one; again, it won't fix the transmission, but you should at least get the error now.

https://dl.dropboxusercontent.com/u/21507587/cTiVo.zip

**Comment by srbny** [comment]
I'm not sure what you're asking for. With Avast on, cTiVo doesn't recognize any of the saved shows on the DVR (so there's no log). Heres the log generated for the downloading by cTiVo beta3.
[com.cTiVo.cTiVo 2017-01-06 18-42.log.txt]

**Comment by mackworth** [comment]
No, sorry. I'm actually looking for it "not recognizing" it, not the downloading.  It's supposed to warn you about the 

So, turn avast on, and start ctivo (the one I just sent, not beta3), let it see your TiVo, and say 0 shows. Hopefully it gives you the warning; if not,  then send me the resulting log.

**Comment by srbny** [comment]
No warning, but a long log saying it couldn't connect.
[cTiVo 2.5.1beta2 with Avast.txt](https://github.com/dscottbuch/cTiVo/files/691313/cTiVo.2.5.1beta2.with.Avast.txt)

**Comment by mackworth** [comment]
darn.  Could you set it to Detail logging, quit and do the exact same thing again?

**Comment by mackworth** [comment]
Ah, never mind. I figured it out. 
Please try this one:
https://dl.dropboxusercontent.com/u/21507587/cTiVo.zip

**Comment by srbny** [comment]
This is what your link leads me to:
"Error (404) We can't find the page you're looking for."

**Comment by mackworth** [comment]
Hmm, can you try again , sometimes dropbox takes a bit to sync

https://dl.dropboxusercontent.com/u/21507587/cTiVo.zip

**Comment by srbny** [comment]
This time cTiVo just keeps searching and gives me this message:
[cTiVo message.txt](https://github.com/dscottbuch/cTiVo/files/691381/cTiVo.message.txt)
[cTiVo log.txt](https://github.com/dscottbuch/cTiVo/files/691382/cTiVo.log.txt)

**Comment by mackworth** [comment]
Ok, I bet I got it now!   (There are two places where antivirus failure could occur, and I only fixed one of them previously.)

https://dl.dropboxusercontent.com/u/21507587/cTiVo.zip

**Comment by srbny** [comment]
If what you're aiming for is that cTiVo will report that the problem is antivirus software, you've achieved it.
[com.cTiVo.cTiVo 2017-01-08 04-01.log.txt](https://github.com/dscottbuch/cTiVo/files/691878/com.cTiVo.cTiVo.2017-01-08.04-01.log.txt)
