### ISSUE TITLE
Unplayable Shows from 2.5.x, but only from 1 TV channel

### ISSUE THREAD

**Issue by WhyAkron** [dscottbuch/cTiVo#229]
Here's an odd one - Tivo shows recorded from a specific channel, downloaded in 2.5.0, 2.5.0 for 10.7, 2.5.1b3 will not open in VLC and a few others (saved as Decrypted Tivo Show). Some will open in QuickTime Player. All will open in Roxio Video Player. Possible clue: in MPlayerX the start time for one of them shows as 2:40:56 and plays, but there is no control of position in the show.
Downloaded the problem shows in cTivo 2.4.4 and they play in everything with no problem.
The problem channel is a subchannel (WEWS-DT2) but other subs of other channels are ok.
Is there any information I can provide that could help, or is it more likely a broadcasting glitch that 2.4.4 happens to ignore?

**Comment by mackworth** [comment]
Huh. Can you use Mediainfo to compare the different files?  It's possible this is a glitch in the new tivodecode. Depending on what mediainfo shows, I may generate a 2.5 with the old tivodecode to test it.

**Comment by mackworth** [comment]
I put a copy of a multi-window version of media info here: 
  https://dl.dropboxusercontent.com/u/21507587/MediaInfo-Multi.zip

**Comment by WhyAkron** [comment]
Here are the results for 2 episodes. For the ones names with 2.5.x, I don't remember which 2.5 version I used, but all 3 I tried did the same thing.
New discovery - If I change the file name for the "bad" .mpg file it will play. If the .srt file name is changed to match, it won't play. If only the .srt name is changed (.mpg name left original), it won't play. ?!?!?!?

[MediaInfo Results.zip](https://github.com/dscottbuch/cTiVo/files/711205/MediaInfo.Results.zip)

**Comment by WhyAkron** [comment]
Sorry, clicked wrong button.

**Comment by mackworth** [comment]
Ok, so with 2.5, you're downloading using Transport Stream on a channel that is still using MPEG2.  That's an unusual combination and many players (apparently from your tests) do not understand it. 

My assumption is that you've set TS manually, either for all channels (at the top of the Edit>Edit Channels screen) or for this particular channel ( in the table of that screen). If you didn't manually set that, then we have a situation I haven't seen, where ctivo sees a MP4 file that needs TS, marks the channel as needing TS, and then later sees a MP2 file. I'll want to investigate this more if it's the case. In particular, send me a screenshot of that screen, scrolled if necessary to show WEWS-DT2.  Then go ahead and clear that channel and try it again.

So assuming you set it manually, you have a couple choices. One is to clear that and let cTivo automatically use Program Stream on MP2 channels, and TS on MP4 channels. Then you should be ok with your players. Alternatively, you can use one of the converting Formats, such as Default, which will convert PS or TS into an MP4 format.

**Comment by WhyAkron** [comment]
Screenshot attached. "Use TS" is on. I didn't set it manually, but I remember at some point I clicked on Test All Channels, which resulted in a message something like "Your processor may be too old for mencoder. You may need 10.7 version of ctivo." After that I didn't go back to see if anything had changed, but maybe that did it. (For the record, using a Macbook Pro mid-2010, 2.53 GHz Intel Core i5, 8GB ram, El Capitan 10.11.6. Will not be going to 10.12 because of other software not compatible.)

Anyway, I removed the channels in that screen, and new downloads of the "bad" shows play ok.

Thank you

[cTivo Edit Channels.pdf](https://github.com/dscottbuch/cTiVo/files/714715/cTivo.Edit.Channels.pdf)

**Comment by mackworth** [comment]
Thanks for reporting back and glad we've identified it. 

So, that message comes up if mencoder crashes in a certain way, which indicates that the current version is not compatible with your processor. Unless you prefer mencoder for some reason, you should be fine otherwise.  

Sounds like ctivo took that failure during a TestPS to mean that mencoder is seeing H.264, which is a wrong interpretation. Reading the code, that shouldn't happen, so if you don't mind, could you set Debug level to Verbose and do a Test All again, and post the the log?

**Comment by WhyAkron** [comment]
OK. But will have to do it later today.

**Comment by WhyAkron** [comment]
Here's the log, but I don't know if it will have anything helpful. I let the "testing" run for over 2 hours. One show was listed as downloading, with no other indication of anything happening, the whole time (a 2.4 GB file, should have taken somewhere under 15 minutes). So I removed it and the others listed as TS Test from the download list. Anyway, the Edit Channels screen remained empty. Maybe I previously did something else I don't remember. Sorry for the trouble. At least we know why those shows were unplayable. Thank you.

[com.cTiVo.cTiVo 2017-01-18 23-11.log.zip](https://github.com/dscottbuch/cTiVo/files/715398/com.cTiVo.cTiVo.2017-01-18.23-11.log.zip)

**Comment by mackworth** [comment]
Okay, glad it's working for you now!
