### ISSUE TITLE
very slow downloads, like 1 week to get 30 min show

### ISSUE THREAD

**Issue by arrrcarlson** [dscottbuch/cTiVo#230]
Greetings. I'm getting incredibly slow downloads, like over a 24 hour period I'll get a minute or two of a show. Some issue usually crops up, tivo busy or something, and the download fails. I'm speculating that it would take me a week to get a 30 min show, since I'm getting about 5 min a day. I've never actually gotten a show, my record is about 10 minutes, something always comes up to make it fail.

thanks in advance for any help.

I've read the archives, haven't found anything that's worked. Seems like my Tivo's brain is just too slow to send a file, but this used to work, years ago.

I've tried setting the tivo to channel 0 to free up the tivo processor (on both tuners). No noticable difference, even after a fresh restart of the tivo.

My tivo is wired, I've tried my mac on wired and wireless. Not much difference but wired seems a little more reliable, a little more likely to keep a connection up overnight, more than flat out speed.

I always use Tivo's transport stream format. If I don't check that, I almost immediately get a "tivo busy, please reboot it" and the download fails.

I've tried different formats, lately I've been sticking with basic raw decrypted just to eliminate variables.

I last used cTivo a long time ago, a year or more, and it used to work. Something changed, and now I can't get it to work anymore. 

What I've got:
Tivo TCD746320 and TCD746500 TiVo Premiere Series4 HD DVR, service #746

MacBook running 10.12.2, but this has been going on a while.
cTivo 2.5.0 (704), but again, this has been going on for several builds.

Here's a verbose blog. I only let it run for 15 minutes, it got 0.0% of the show in that time.

[com.cTiVo.cTiVo 2017-01-22 17-28.txt](https://github.com/dscottbuch/cTiVo/files/722150/com.cTiVo.cTiVo.2017-01-22.17-28.txt)

**Comment by mackworth** [comment]
Well, definitely the next thing to try would be to isolate cTiVo out entirely. 

Try clicking on this URL in your browser:  http://dvr-4448.local.:80/download/How%20We%20Got%20to%20Now%20With%20Steven%20Johnson.TiVo?Container=%2FNowPlaying&id=4745&Format=video/x-tivo-mpeg-ts 
(You'll probably need the user name of "tivo" and the password is your MAK) and see what the throughput is. 

Secondly, your statement that `I always use Tivo's transport stream format. If I don't check that, I almost immediately get a "tivo busy, please reboot it" and the download fails.` is very interesting. I'd like to see the log on that. You get that message when the TiVo responds to a download request with "Server Busy", which is usually if we request a show too quickly after another one.  Tivo's file server is very sensitive, and we try hard to avoid requesting a second show within a minute of the previous one.  If you're not pulling down any shows and then you request a Program Stream version, you should not get that message. If it's a H.264 channel, then you should get a message in the log like "Found evidence of audio-only stream"

You can check this yourself with the URL:
http://dvr-4448.local.:80/download/How%20We%20Got%20to%20Now%20With%20Steven%20Johnson.TiVo?Container=%2FNowPlaying&id=4745
but wait a minute after running either ctivo or the above download URL

Let me also ask if you have any antivirus sw installed?

**Comment by arrrcarlson** [comment]
Thanks for the help.

I have no antivirus software installed.

I have not tried the browser method before. With that method, I'm getting the file at about 50KB/sec. I'll try a longer transfer now and see if I can get a whole file, that would be great. 

When I try the second URL, I sometimes get a server busy error, but it does work sometimes. Maybe it's a little heavier process load, a little more sensitive? When it works, I get about the same download speed, 50KB/sec or so.

attached are 2 logs, "don't use stream" has the immediate failure, "do use stream" I let run for a little bit and then quit manually.

[log 1 dont use stream.txt](https://github.com/dscottbuch/cTiVo/files/722224/log.1.dont.use.stream.txt)


[log 2 do use stream.txt](https://github.com/dscottbuch/cTiVo/files/722225/log.2.do.use.stream.txt)

**Comment by arrrcarlson** [comment]
well, even the direct URL is slowing to a crawl, I'll let it run overnight, maybe try it wired and wireless, I'll try the channel 0 trick too, but right now this doesn't seem like a cTivo issue, just a Tivo issue. Thanks for the help.

**Comment by mackworth** [comment]
Even 50KB is painfully slow; with a Premiere i would expect at least 1MB. With my Roamio, I'm seeing sustained throughput of 10MB, so 200x what you're seeing.   The Channel 0 trick is probably a 10-20% improvement. Wired v Wireless, maybe double, unless there's a problem with one that doesn't apply to the other.

So, to isolate and diagnose where the problem is... Fortunately, you have two TiVos. Can you watch one tivo's shows on the other? Are both TiVos behaving the same with regard to downloading to your machine? What about to Tivo's phone app? 

Any other way to test throughput on your network (downloads from offsite or between macs or...)? Maybe there's a device flooding your network with packets.  Have you tried rebooting all your devices? (Turn everything off, then bring them up one at a time starting with your network router and then wifi, and then one TiVo and then your Mac and try that before bringing anything else up.).

You also have the oddity that it's complaining about simultaneous streams. Is one tivo accessing the other? Presumably you'd know if any other PC or Mac was accessing either one of them. What about IOS or Android?

**Comment by arrrcarlson** [comment]
Actually, I only have one TiVo, sorry for the confusion. 

I have a decent network, I'm able to copy files to my nas at a pretty high rate. 

I've tried shutting off IPv6 and UpNP, no change. I really don't think I have a lot of chatty clients on my LAN, but that's a great idea, I'll kill the wireless entirely and get the LAN down to only the TiVo and one other machine, and try again, maybe trying a few OS's as you suggest. I'll let you know.

**Comment by mackworth** [comment]
Any luck?

**Comment by arrrcarlson** [comment]
Nope. Using the URL, downloading from a browser, wired network, nothing on my network but my laptop and the tivo, still slow. I just plain have a slow TiVo.

**Comment by mackworth** [comment]
Sorry to hear that (and still a little puzzled, given that it can receive Netflix ok). It's too old to send to iOS, right? Any difference between the Transport Stream and Program Stream URLs?

**Comment by arrrcarlson** [comment]
no significant difference between the transport stream and program stream URLs.

I think it is too old to send to iOS, it does not offer me that on the iOS app.
