### ISSUE TITLE
Remote Access for TiVo

### ISSUE THREAD

**Issue by the47thman** [dscottbuch/cTiVo#231]
Just wanted to ask a (hopefully) basic question to see if cTivo was designed for a user to be able to access/download from a Tivo when they're not on their home network. Because while at home, I can connect just fine (even when I'm technically not on the same network as the Tivo). When I leave, though, the program spins for a while and ultimately cannot connect. I figured I should start with the simplest question to figure out if this is intended, or not.

**Comment by mackworth** [comment]
It's not automatic nor simple, but it can be done. 

From:
https://github.com/dscottbuch/cTiVo/blob/master/wiki/Advanced-Topics.md#manual-tivos

Interestingly, you may also be able to use cTiVo remotely, although this can take considerable network ability and patience. Patience both in the sense of trial and error as well as in the upload bandwidth available on your connection to the Internet. You will need to set your router to pass external accesses to your main IP address through to your TiVo. As you may be doing this for other devices as well, we also let you adjust the ports cTiVo uses to match whatever port mapping you're doing in your router. If you didn't understand this paragraph so far, then you probably shouldn't be doing this. Note that whether this violates your terms of service with your cable company, TiVo Inc, your internet provider, any random film studio in Hollywood, or anybody else is entirely up to you.

**Comment by the47thman** [comment]
Thanks for the response! Yeah, that seems... tricky. But it was worth a shot!
