### ISSUE TITLE
tivodecode error

### ISSUE THREAD

**Issue by djdonohu** [dscottbuch/cTiVo#232]
Hey. Love the app, but having an problem. Upgraded to 2.5.0 and my downloads immediately started failing with the message "Can't find tivodecode" and tells me to visit the the ctivo site for help. I searched high and low and couldn't find help on the error. I tried the 2.5.1 beta and got the same thing. I went back to 2.4.4 and everything works fine again.

Using macOS Sierra 10.12.2, downloading from a Premiere. On 2.5.0 I tried almost every format and they all failed. On 2.4.4 I used to use iPhone or Apple TV, going back to that worked. Please let me know what info I can supply to figure this out.

**Comment by mackworth** [comment]
Hmm, I'm guessing you ran one of the betas and selected tivodecode st one point. Try going into Advanced Preferences (Cmd-opt-comma) and set the decoder to tivodecode-ng.

**Comment by djdonohu** [comment]
Exactly correct, and that resolved it. Thanks!

**Comment by mackworth** [comment]
Glad to hear it!
