### ISSUE TITLE
Failed downloads since 2.5 upgrade

### ISSUE THREAD

**Issue by noone001** [dscottbuch/cTiVo#233]
C-Tivo 2.5, MacOS 10.9.5

I am running on an older MacMini, so I have not upgraded my MacOS.

I fail with downloading now every time. I have reset my computer and TiVo with no improvement. Would you mind looking at my log?

When I am watching in real time, the file seems to download, but the transfer fails later.

Is the previous version still available?

I'd love to get this working! This is a great program that I have come to depend on!

Bob

[com.cTiVo.cTiVo 2017-01-25 02-40.txt](https://github.com/dscottbuch/cTiVo/files/734351/com.cTiVo.cTiVo.2017-01-25.02-40.txt)
[com.cTiVo.cTiVo 2017-01-26 02-46.txt](https://github.com/dscottbuch/cTiVo/files/734352/com.cTiVo.cTiVo.2017-01-26.02-46.txt)

**Comment by mackworth** [comment]
There is a known problem that will be fixed in v 2.5.1. Try the beta here:  https://github.com/dscottbuch/cTiVo/releases

**Comment by noone001** [comment]
Still not working. It seems to work all the way through "detecting ads" then fails.

[com.cTiVo.cTiVo 2017-01-27 02-56.txt](https://github.com/dscottbuch/cTiVo/files/735081/com.cTiVo.cTiVo.2017-01-27.02-56.txt)

**Comment by mackworth** [comment]
Interesting; you seem to have a different linking problem. Can you turn commercials skipping off and see if that works? And also try Default for Format, rather than AppleTV2

**Comment by mackworth** [comment]
Oops, I was reading the older part of the log.  Looks like commercial is ok now.  Just try Default for Format, and you should be fine (mencoder is giving a lot of problems still).  If it still doesn't work, please increase the logging to Detail in Preferences and run one more show.

**Comment by noone001** [comment]
Thanks for your help. I did turn off commercial skip and let it run, I will see what it looks like when I get home from work. I will try to change the format also.

**Comment by mackworth** [comment]
So the Appletv2 will definitely not work on your machine (nor any mencoder-based Formats).  Default should be ok, with or without commercials.

**Comment by noone001** [comment]
Thanks. I looked at your very helpful page on video formats, and it looks like default will work for me. My issue is getting compatibility for my AppleTV 2, and my ancient original iPad, even though I use my AppleTV 3 most of the time.

I will try to encode things overnights, and let you know if I have problems. Thank you so much for your help, and your great software!

I will look into your page more, but do you take software donations?

Bob

**Comment by mackworth** [comment]
Let me know how it goes.  Thanks for the offer, but no, this is purely a volunteer activity.

**Comment by noone001** [comment]
Thank you for your help. Changing the encoding to "Default" fixed the problem. It seems mencoder is the problem.

**Comment by mackworth** [comment]
Great to hear.
