### ISSUE TITLE
I am having trouble transferring one particular episode to my computer.....

### ISSUE THREAD

**Issue by burdell1** [dscottbuch/cTiVo#234]
There is an episode that I have transferred over using CTiVo and it says that it has transferred the whole thing...However, when i watch it, it quits playing at around 45 minutes. Is there a way to fix this? also, I can transfer the entire episode to my iPad or iPhone with the TiVo app....If there was a way to extract it from that? (I believe I posted this before on here, but couldn't find the original thread and I have to transfer it over because i might have to get a new TiVo.)

**Comment by mackworth** [comment]
Sorry; if it's just one episode, there's probably a digital glitch at that point that's messing with the encryption process. We see this regularly, and TiVo doesn't care about these transfers. The only suggestion I would have would be to try both Program Stream and Transport Stream transfers; they use different code, so may be affected differently by a glitch. 

And no, the iOS version is not accessible at all.

**Comment by mackworth** [comment]
Oh, and if you have two TiVo units (such as your potential new one), you can also try the [technique described here](https://www.tivo.com/support/how-to/stream-and-transfer-recordings-between-tivo-boxes). Basically, it consists of watching the show on your TV and skip to the point just after the failure point, then go back to the My Shows menu. Now on the second TiVo, navigate to the first's list and transferring the show to the second tivo, saying "from the pause location" and then download the rest of the show from the second TiVo.  Similarly, if you buy a new TiVo, then you may be able to transfer the entire show directly.

**Comment by burdell1** [comment]
Ok thanks for the tips! i will try both of them and get back to you...
