### ISSUE TITLE
At 2.5.0 but program says no update available

### ISSUE THREAD

**Issue by tdlivings** [dscottbuch/cTiVo#235]
Just wanted to let you know, when I click on check for update it says I am up to date at version 2.5.0. So, I had to go pull the 2.5.1 manually.

Thank you

**Comment by mackworth** [comment]
Correct. I usually put the final version up for a few days before triggering the update. That way if there's something really stupid my testing didn't catch, only a few have to suffer. :)

**Comment by mackworth** [comment]
And just updated it, so folks should be getting it now.
