### ISSUE TITLE
Some programs only partially downloading

### ISSUE THREAD

**Issue by jsfranks** [dscottbuch/cTiVo#238]
For some reason, a few programs I have tried to download have only successfully downloaded the first 20 or so minutes. They seem to be correctly encoded and play back perfectly, except that the files only includes 20 minutes of video for programs that was originally 1 to 3 hours long. The entire program exists on the TiVo. I have deleted and re downloaded the offending programs several times, and each time the same thing happens, and the video is cut off at the exact same spot. Any ideas what could be causing this problem, or how I can possibly retrieve the complete video?

**Comment by mackworth** [comment]
So, I just helped someone else with a very similar problem., so let me jump to conclusions and ask you to try an experiment. 

If you're using a ffmpeg-based Format (e.g Default or 1080p), try one if the HB ones (e.g. HB1089P). You may need to go into Edit>Edit Formats to enable the HB one. (Disable "Hide in User Interface")

**Comment by jsfranks** [comment]
No luck, unfortunately. I tried using both HBDefault and HB1080p, but the
same programs are still being truncated.


On February 26, 2017 at 10:16:32 AM, Hugh Mackworth (
notifications@github.com) wrote:

So, I just helped someone else with a very similar problem., so let me jump
to conclusions and ask you to try an experiment.

If you're using a ffmpeg-based Format (e.g Default or 1080p), try one if
the HB ones (e.g. HB1089P). You may need to go into Edit>Edit Formats to
enable the HB one. (Disable "Hide in User Interface")

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/dscottbuch/cTiVo/issues/238#issuecomment-282566879>,
or mute
the thread

**Comment by mackworth** [comment]
Okay, sorry to hear that. First let me warn you that some programs just can't be transferred. The way to test is use Decrypted TiVo Format. This does nothing but download and decrypt the file. If it fails, nothing we can do. (Although some with two Tivos have been successful in transferring a difficult file to the other TiVo and then downloading.)

If it does download, then try Default again, and look in the log for the failure messages. Happy to help translate.

**Comment by mackworth** [comment]
Any luck?

**Comment by mackworth** [comment]
Let me know if there's any further concerns?
