### ISSUE TITLE
Enhancement: Add selection for Plex file naming convention 

### ISSUE THREAD

**Issue by gespensen** [dscottbuch/cTiVo#239]
cTiVo is a great app for my Tivo Bolt and archiving my favorite TV shows on my Mac. It would be very convenient to have an file naming option to select for Plex naming convention. I would be happy to contribute payment support to add this enhancement.

**Comment by mackworth** [comment]
While it could be less hidden, it is indeed already there. Just go to Advanced Features, then pull down the Filename Template to Plex folders. Let me know if this is what you were looking for?

**Comment by gespensen** [comment]
Thanks for the feedback mackworth. Yes, I found the hidden advanced options as you pointed it out to me and the file names are now in Plex format. However now the Download folder location destination is broken. I normally have an external NAS drive destination location. I'm not sure if the location problem is a cTiVo issue or not at this time. Still I'm happy the cTiVo has the Plex format for output file names. Thanks for your assistance.

**Comment by gespensen** [comment]
Update all is working correctly with cTiVo using the Plex naming convention. Thank you for your assistance mackworth.

**Comment by mackworth** [comment]
Glad to hear it, and I take it your drive is working properly now.
