### ISSUE TITLE
Shows returned to TiVo Bolt Plus in 480p

### ISSUE THREAD

**Issue by githubgrub** [dscottbuch/cTiVo#240]
I use cTIVO to archive TiVo shows for future use on a TiVo (I also used TiVo Transfer but it will not see my Bolt Plus). If I record shows from my TiVo HD and/or my new Bolt Plus in Decrypted TiVo or 1080p, they are converted to 480p when returned to TiVo Bolt Plus. What's the best video  format to record TiVo shows to be able to send them to the Bolt Plus in (at least) their original resolution?
Thanks!

**Comment by mackworth** [comment]
So Decrypted TiVo just records the video bits on disk (decrypted but otherwise unchanged), so if it was a 480p on TiVo, it will be on the Mac and same with 1080i.  Best is to look at the file itself (even with Finder's Get Info), to see what the actual encoding is. Then assuming it's higher-res than 480p on the Mac, then you need to look at the return trip to see if it's reducing the resolution. For example (and the most common), PyTiVo will transcode files as they are sent, depending on your configuration, but you'll need to look at its log files to see what it's doing.

**Comment by githubgrub** [comment]
Hi. Thanks for the response. As you can probably tell from my question, I'm not exactly a computer guru. I looked at pyTiVoX's log via console, but the info isn't easy to get anything meaningful (to me).
So, now I've deleted the shows I'd already transferred TiVo Bolt Plus -> Mac Pro via cTiVo today, reset cTiVo Format preference to "Decrypted TiVo Show", hit the done button, restarted cTiVo, and the Format is changed(?) to "Higher Quality" w/file extension set to be ".mp4".
Don't understand why the Format default changes but am now transferring a show. Will transfer back to both my TiVo HD and my Bolt Plus to see if it gets to either TiVo correctly.

**Comment by githubgrub** [comment]
The two files that are recording to my Mac Pro are: ".mp4", and a ".srt"

**Comment by githubgrub** [comment]
So, I copy back to my TiVo HD and the show is full screen and HD. I copy the same cTiVo recording to the Bolt Plus and the show looks much less than HD, and is windowed. 

Looking at the info on the .mp4 file = 1280x720/ H264, AAC, AC3. I assumed the difference in screen size is the individual TiVos' video settings, but changing the Bolt+'s output didn't change the view, and the video is really not HD.

**Comment by mackworth** [comment]
On the tivos, look in the info screen for the video and see what resolution it says.

**Comment by githubgrub** [comment]
My first thought after I saw the difference... that data isn't available in the Info window for these cTiVo recordings when they are returned to either TiVo...

**Comment by mackworth** [comment]
Ah, sorry 'bout that. Well, really the resolution sent back to the TiVos is a pytivo issue, but I can try and help. Can you post your pytivo.conf and your log file?

So, on  'I reset cTiVo Format preference to "Decrypted TiVo Show", hit the done button, restarted cTiVo, and the Format is changed(?) to "Higher Quality" w/file extension set to be .mp4".  The Done button may explain this. To select the Format, you just use the pulldown in the main window.  If you're in the Edit Formats window, you can look (and edit) at different Formats, but that doesn't select the Format for future shows."

**Comment by githubgrub** [comment]
Thanks for offering to help! I am lost... let me know if there's anything else I can send...

github wouldn't accept the .log file, so I made a .pdf of a large portion of my pyTiVo log.
Also, I don't find any pytivo.conf anywhere...

[170406_1200PDT_pytivo_log.pdf](https://github.com/dscottbuch/cTiVo/files/903680/170406_1200PDT_pytivo_log.pdf)

**Comment by githubgrub** [comment]
Also,I was not aware that I couldn't select a default format in cTiVo... Thanks. I'm transferring a new HD show right now with the Decrypted TiVo Show selected

**Comment by githubgrub** [comment]
So, I transferred a 720p show and a 1080i show, then copied them back to the Bolt Plus... both came over as 480p... so I guess pyTiVo is to blame, but I don't see anything wrong with my pyTiVo preferences... I actually haven't changed them.
I just had a thought, my Bolt+ is connected via HDMI to my older receiver (Onkyo TX-SR805). Maybe it's a copyright thing?

**Comment by mackworth** [comment]
Sorry for delay. So you're getting all kinds of very weird software crashes there.  I'd suggest posting on the pytivo site and asking for help.  It's at http://www.tivocommunity.com/community/index.php?threads/pytivo-transcoding-server.328459/page-288

**Comment by githubgrub** [comment]
Thanks for that suggestion. I signed up for the tivocommunity site and put in my info... hopefully someone will have an answer. For now, I'm transferring shows I want to keep from the Bolt to the HDXL.

**Comment by githubgrub** [comment]
Hi Hugh,

Sorry I forgot to close that.

I tested cTiVo just the other day and the recording was the same resolution as the original show. Returning it to the TiVo I see some artifacts (I do not know the technical term, but there is this sparkly fuzziness in some edges) but the picture is good. I’m not recording for archival anyway.

BTW: the pyTiVo folks had no idea as none use cTiVo. I have been using pyTiVo online to make my recordings, though, and it seems to work well.

Thanks again for the help.

John
