### ISSUE TITLE
How can I make my SD recordings look their best?

### ISSUE THREAD

**Issue by wjmt3** [dscottbuch/cTiVo#241]
What encoder settings can I use to make my SD recordings look their best? 

Everything I have tried with the built-in presets looks considerably worse than original playback quality. I know it's not HD quality but, so far, it's not even close to SD quality. Help! :)

I am using the latest version. I have not tried Handbrake yet; never used it before.

It's effortless to get great-looking HD from cTiVo, but the majority of my space is taken up by older SD  recordings.

**Comment by mackworth** [comment]
Sorry for delay; I was trying a few shows on this, and found nothing wrong.  So I assume the shows look find on your TiVo, but not when moved to the Mac.  Have you tried Decrypted TiVo? This involves no recoding at all, so if that looks bad, there's nothing any Format can do.  Also, make sure when playing it back on the Mac, you're doing it at 1-1 pixel size. It's amazing how small that is, but blowing it up bigger than that will only make any SD artifacts worse.  What issues are you seeing? Just fuzzy, or actual problems?

**Comment by wjmt3** [comment]
Interesting. I just tried Decrypted TiVo, and the result is MUCH better—even if I do go full-screen, it’s still watchable, even if it’s not perfect outside 1-1 pixel size. It’s an .mpg, but I guess this is incompatible with a video editor? And no option for subtitles with that.

In contrast, even "Higher Quality" is a lot worse. More artifacts, and **very** ugly if enlarged.

I also tried Decrypt MP4, because I like subtitles, but it failed completely. The file wouldn’t even open. It is an older recording, so maybe it's a file format issue (pre H.264 transition?)

**Comment by mackworth** [comment]
So, have you tried Standard Def or HB Std Def?

**Comment by wjmt3** [comment]
Standard Def was the first I tried. I was completely unimpressed, so I went to Higher Quality, thinking the resulting file would be marginally better (which it indeed was).

Haven't tried HB. I assume I have to download and install HandBrake? That's not a problem, but I've no experience using it.

**Comment by mackworth** [comment]
No, HB is built in now. Just enable Format in Edit>Edit Formats (aka disable Hide in User Interface).

When you try these two, can you do a screen grab or otherwise describe what the problem is?

**Comment by mackworth** [comment]
any progress?

**Comment by wjmt3** [comment]
Hi,

Sorry for the huge delay. I have decided to use Decrypted TiVo Show, but there seems to be a problem today.

It’s been my experience that after the download, there was no encoding process.

But as I type this it’s finished downloading a supposedly decrypted show, but it’s taking forever to “encode” it.

I thought the whole point of that was that NO processing is done. Something’s not right here. It worked normally just last month.

Any help appreciated.

I’m on 2.5.1 on Yosemite 10.10.5

Thanks,
-Will

**Comment by mackworth** [comment]
Best thing would be to post a log (Help>show log files) that covers the timeframe of a download failure. Even better would be to increase the debug level in preferences to detail and run it again.

**Comment by wjmt3** [comment]
2017-10-03 11:03:04:986 MTAppDelegate>applicationDidFinishLaunching:@205>Starting cTiVo; version: 714
2017-10-03 11:03:06:662 MTTiVoManager>netServiceDidResolveAddress:@1687>Got new TiVo: Premiere at 192.168.1.19
2017-10-03 11:03:06:726 MTTiVoManager>netServiceDidResolveAddress:@1687>Got new TiVo: Roamio at 192.168.1.93
2017-10-03 11:03:06:776 MTTiVo>updateShowsStartingAt:withCount:@376>Initial loading from TiVo Premiere at URL https://DVR-19EC.local./TiVoConnect?Command=QueryContainer&Container=%252FNowPlaying&Recurse=Yes&AnchorOffset=0&ItemCount=15
2017-10-03 11:03:06:777 MTTiVo>updateShowsStartingAt:withCount:@376>Initial loading from TiVo Roamio at URL https://DVR-04C5.local./TiVoConnect?Command=QueryContainer&Container=%252FNowPlaying&Recurse=Yes&AnchorOffset=0&ItemCount=15
2017-10-03 11:03:40:749 MTDownload>launchDownload@1608>Starting 3 download for KATU News at 6 (Premiere); Format: Decrypted TiVo Show; simul encode Generate Subtitles; Keep after iTunes; tivodecode-ng; Program Stream
2017-10-03 11:03:40:913 MTDownload>launchDownload@1797>Starting URL http://dvr-19ec.local.:80/download/KATU%20News%20at%206.TiVo?Container=%2FNowPlaying&id=2292968 for show KATU News at 6 in 0.0 seconds
2017-10-03 11:21:06:047 MTDownload>launchDownload@1608>Starting 3 download for KATU News at 11 (Premiere); Format: Decrypted TiVo Show; simul encode Generate Subtitles; Keep after iTunes; tivodecode-ng; Program Stream
2017-10-03 11:21:06:149 MTDownload>launchDownload@1797>Starting URL http://dvr-19ec.local.:80/download/KATU%20News%20at%2011.TiVo?Container=%2FNowPlaying&id=2292954 for show KATU News at 11 in 0.0 seconds
 
Background: I had originally started with a recording of the News at 6, a 45-minute recording. I cancelled it partway through the encoding process.

I then transferred the News at 11, a 19-minute recording, simply because it would take less time as a test. But it's still going (encoding).

I was just hoping to transfer the recordings quickly and free up some space, but the universe has other ideas today.

**Comment by mackworth** [comment]
Try turning off the captioning; that may be interfering.
Also, if you can increase the debug log to detail, it may give me more of a clue...

**Comment by wjmt3** [comment]
OK, I’ve unchecked Handle Captions — strange that it might suddenly interfere when it hasn’t before.

With regard to logging, is Major sufficient, or do you prefer a higher level? Encoding takes so long — I’ve got a quad-core i7 late 2012 iMac with 32 GB RAM. I’m surprised it still takes as long as it does. That being the case, I’d rather raise the logging level just once instead of having to raise it and try a third time. :)

**Comment by mackworth** [comment]
Not arguing that it should interfere, just that it takes processing time. Without it,  Decrypted should just download straight through the decode process onto disk. 
Well, Detail should be sufficient, but might as well go to Verbose. (Just be sure to turn it off later.)

**Comment by wjmt3** [comment]
Interesting…

So my Tivo is a Premiere from 2010…7 years old now.

When I transferred this recording the first time, it was reasonably fast. Connected via Ethernet, it transferred at 4.9 MBps.

This time, on the same recording, it started out at 1.1MBps, but has steadily plummeted to under 400KBps.

I know that no cTiVo settings would impact that speed. I’m hoping this whole thing isn’t just a sign of a failing Tivo.

Are there things I can do on the Tivo to maximize throughput? I know I wouldn’t want to be recording a program at the same time, for example. As I have done everything today, the Tivo has been watching but not recording live TV.

There is nothing on my network that would account for the drop in throughput.

**Comment by mackworth** [comment]
The only tip I know is to put it on a channel you don't get. Then the processor isn't spending any time recording that channel, so it can focus on transferring. 

But that might pick up 20-30%, not a 10x issue.  Rebooting TiVo might  help. 

If you try the URL above in Safari, (e.g.  http://dvr-19ec.local.:80/download/KATU%20News%20at%206.TiVo?Container=%2FNowPlaying&id=2292968), then it will show you the raw transfer rate without any cTiVo processes. (you'll need to provide "tivo" as user and your MAK as the password).

**Comment by wjmt3** [comment]
After a fresh reboot of the Tivo, I did a fresh download of a show, using the link you provided. Nice fast throughput.

I then tried to download the save file with cTivo, and it was much worse. See the attached screenshots.

Note that these particular screenshots are just samples. I aborted them just after seeing that the speed was consistent and snapping the picture.

But previously I did do a full direct download (in Firefox), and the throughput was consistently fast.

I can consistently reproduce the difference in throughput.

**Comment by wjmt3** [comment]
Oops, looks like the attachments didn't accompany the email, even though I did attach them.

Here they are
![screen shot 2017-10-03 at 3 16 51 pm](https://user-images.githubusercontent.com/27032337/31151977-d0bac65a-a84e-11e7-9162-90ffcba5c125.png)
![screen shot 2017-10-03 at 3 16 10 pm](https://user-images.githubusercontent.com/27032337/31151978-d0bec4bc-a84e-11e7-8f9a-0fa72b9b661f.png)

**Comment by mackworth** [comment]
So definitely should be seeing comparable rates in Decrypted mode; if you could post a log in Verbose mode, that may give me a clue about what’s going on.

**Comment by wjmt3** [comment]
OK, I’m going to choose a smaller recording for the sake of speed, unless it is really crucial that it be the same recording.

**Comment by wjmt3** [comment]
It’s working on it. Given the size and amount of data, I don’t really want to post the logs on a publicly viewable ticket. Is there a way I can email it to you privately?

It’s only 27% done and still “encoding”, which doesn’t make sense.

**Comment by mackworth** [comment]
You can stop it. That’ll be enough. Just compress to a zip file (finder right-click, compress).

**Comment by wjmt3** [comment]
I can certainly do that, but I don’t want it viewable or downloadable publicly or by registered users (not to mention indexed by Google), as are everything else I’ve posted. This verbose log contains my MAK, which is important to keep private, as you know.

If I knew what to look for, I would send just that.

**Comment by mackworth** [comment]
Shouldn’t have your MAK in it; I try pretty hard to block that in the logging subsystem.  If you are seeing it, let me know what line it’s on (the rest of the text).
You can also edit the file in TextEdit and just find/replace.

**Comment by wjmt3** [comment]
Might be a bug then?

It’s definitely there (3 separate times), on this line (number replaced)

LaunchPath: /Applications/cTiVo.app/Contents/MacOS/tivodecode-ng -m 0123456789 -v — -

I can also see random details (descriptions, etc. of other completely unrelated recordings). Is that normal for verbose mode?

**Comment by mackworth** [comment]
Yup, def a bug.  I hadn’t realized that launchpath includes the parameters.  I’ll fix in next release.  Thank you for noticing.
In the meantime, you can either just edit that, or email to mackworth at aol dot com (but do compress before sending).

Yes, Verbose in Preferences covers every module in the program, so as it loads the now playing list from your TiVo, it tells me what’s happening.

**Comment by wjmt3** [comment]
Thank you! Glad to help make cTiVo better!

I will compress and email.

**Comment by wjmt3** [comment]
I sent it through. In the meantime, a question: Can cTivo do anything with a manually downloaded .tivo file?

**Comment by mackworth** [comment]
Didn't get the log. How big was it after compression? 

On .tivo files, the short answer is no.  

The very long answer is that I wrote a Terminal script that you can edit to convert them, so if you're comfortable running Terminal, it should help:

This script looks at the cTivo temp directory, finds any .tivo files, decrypts them and then uses mencoder to convert them. Everything in `<<>>` must be replaced (including the brackets). Specifically, you must supply your MAK for your tivo, and you can steal the <<VIDEO, AUDIO, OTHER Options>> part from Edit>Edit Formats for your favorite ctivo format (assuming it's mencoder-based). 
Tip: You can Duplicate a built-in format in cTiVo to enable copy/paste in those fields.

```
cd /tmp/ctivo
for file in *.tivo
do
    filename="${file%.*}"
    echo "Processing $filename.tivo"
    /Applications/cTiVo.app/Contents/Resources/tivodecode -m<<MAKHERE>>  $filename.tivo |  /Applications/cTiVo.app/Contents/Resources/mencoder <<VIDEO, AUDIO, OTHER Options>> -- -o %filename.mpg
done

```
Possible changes for above:

- If you've got .TiVo files in another directory, remove the first line, and just drag the folder with the .tivo files onto the Terminal icon in the dock. This opens a Terminal window already in that folder. Then run the rest of the script.
- If you want to use ffmpeg, change everything after the "|" character to  (should work, I haven't tried it).
` /Applications/cTiVo.app/Contents/Resources//ffmpeg <<VIDEO, AUDIO, OTHER Options>> --  %filename.mpg`
- If you just want to decrypt the files, you could delete everything after the "|" character (including it), and replace it with >> %filename.mpg

**Comment by wjmt3** [comment]
The log was emailed to the AOL address provided. Just 1.6 MB zipped, or 2.1 if you count the encoding applied during the emailing process. Did it get caught in a spam filter? It didn’t bounce, and I copied and pasted the username portion of your email address to be sure I wouldn’t mistype it.
