### ISSUE TITLE
Superfluous .srt files?

### ISSUE THREAD

**Issue by sugyfelix** [dscottbuch/cTiVo#242]
I have been using cTiVo for few years now...Thanks!

Recently I changed to using a custom HB conversion. Mostly this was to get around aweful bugs in mencoder and ffmeg when the recording has transmission related garbage. Typical end result is video/audio out of sync at point if glitch that could be resynced by skip forward/skip backward in quick succession. Had 2 shows with permanent out of sync on the order of 10 seconds! Obviously unwatchable. 

TiVo played these fine with maybe a audio skip or a video sparkle. I looked at the code for mencode and ffmpeg and decided they had no code to handle video/audio/sync errors from TS streams. Then looked @ HB. Logic was in place and a quick test on one of the very bad shows produced a watchable file with one minor glitch.

Switched all my downloads to use a custom HB format. Much improved. My wife even commented on the improvements.

At the same time I experimented with HB including the subtitles or cTiVo including them. HB seems to not understand the language setting so leaves then undefined, which can cause player problems. Switched to using cTiVo as it seems to be fine,

Long way to get to the problem...after download and conversion the .srt files are left hanging around in the output directory. It's a small annoyance to clean them up, but I thought I would bring it up. Hasn't bothered me enough to explore in cTiVo to see how easy it might be to fix.

Thanks for all the work!

**Comment by mackworth** [comment]
Glad you like ctivo.  When I first put the MP4-subtitle-embedding code in, I then automatically removed the SRT files and folks told me that certain players didn't recognize the embedded files and required the SRT ones.  I agree they're annoying and that was a while ago, so I'll check and see if the major ones work without it, and if so, try removing them again. 

If you're feeling urgent and codey, you could use [Apple's watch folders scripting](https://developer.apple.com/library/content/documentation/LanguagesUtilities/Conceptual/MacAutomationScriptingGuide/WatchFolders.html) to automatically get rid of the SRTs.  Note that these are written out by ccextractor and then read back in by cTiVo to embed into the MP4 after encoding completes.  So you'll need to wait until the encoding finishes before deleting them.  Although you could just set a timer and wait x hours to delete, the official way would be to wait for the disappearance of a lock file in the temp directory (typically for ~/Movies/ctivo/.../basename.srt you'd look for /tmp/ctivo/basename.lck).

You mentioned a custom HB format. With the new default settings, I'm curious if those work for you, or what/why you're doing something custom.

**Comment by mackworth** [comment]
And yes, mencoder in particular has become a disaster, so 2.5 is working hard to move people off it.  

Haven't seen same problems in ffmpeg, so an example (that works in HB, but not ffmpeg) that I could send to them would be good.

**Comment by mackworth** [comment]
And finally, if instead of coding, you'd do the legwork of trying the different players with/without SRT, that would clearly accelerate my adding that feature!

**Comment by sugyfelix** [comment]
Looks like I kept  a copy of the really bad file. It’s 5.6G. Not sure of the best way to cut out the bad section, or if thats even possible?

**Comment by sugyfelix** [comment]
Using a custom HB format because I'm trying to reduce the size of the resulting file and nothing fits the bill.

Usually I reduce the video to something smaller (like the old apple tv size) and down mix the primary AC-3 audio to stereo, and drop any secondary audio.AC-3. Gives me about ~400MB files. Without the audio tweaks it costs another 200MB.

I Use this to download and watch shows when I'm in my second home in Mexico for 6 months/year.

**Comment by sugyfelix** [comment]
Finally got around to checking out other players wrt needing .srt files. Seems like it is needed more then it seems. Some players say that don't need .srt files but they do (eg. omxplayer on the raspberry pi.) My use case is an Apple TV or raspberry pi as the player. So its a toss up. If I need the subtitles I use the Apple TV.  Just changed by workflow that downloads any new .mp4's to delete any remote .srt's. So not a issue anymore for me.

Still need to get a sample of a .ts with serious dropouts that not huge...

**Comment by mackworth** [comment]
So, sounds like moving it to optional would be a good idea.  Thanks for checking.

BTW, that sounds like what I did with Smallest (720p max) and Standard Def (480p max), both dropping the AC3. The Std Def one in particular is very fast, but therefore not quite as small.  (See results here: https://github.com/dscottbuch/cTiVo/wiki/Video-Formats )

**Comment by mackworth** [comment]
cTiVo now removes superfluous SRTs in version 3.0.1.  (Superfluous means the captions are themselves embedded in the MP4 output file; otherwise the SRT is kept).

If anyone finds this a problem, let me know.
