### ISSUE TITLE
Fastest possible download to .mp4

### ISSUE THREAD

**Issue by K2Kevin** [dscottbuch/cTiVo#243]
Im looking for the fastest possible way to get Tivo videos to the mac (converted to mp4.)

In general, these are 3 hour long sporting events I will be then transferring from Mac to cellphone.  Doing this directly from the Tivo app takes hours (3-4), transferring from other remote apps (Same size file) can take only 30 minutes to an hour.

The built in format for "Faster" is still very slow.

**Comment by mackworth** [comment]
Do you know if the channels are MP4 already?  If so, you could try the Decrypt MP4 Format, which just copies it over, decrypts, and saves it at full speed. It doesn't convert to Progressive scan, so if it's 1080i, it might be incompatible with iTunes

**Comment by K2Kevin** [comment]
iTunes doesn't really matter, I can convert faster with other software.  Just wondering the fastest download option.

Right now all my downloads stop after a few minutes anyway.

On Apr 12, 2017, at 11:52 AM, Hugh Mackworth <notifications@github.com> wrote:

Do you know if the channels are MP4 already? If so, you could try the Decrypt MP4 Format, which just copies it over, decrypts, and saves it at full speed. It doesn't convert to Progressive scan, so if it's 1080i, it might be incompatible with iTunes
