### ISSUE TITLE
download folder - export folder

### ISSUE THREAD

**Issue by kevinmhack** [dscottbuch/cTiVo#246]
Hi,

Running the most current version of CTivo on a MacPro 2013, 12 core.  I notice that that the same folder being used for download is also the same folder where the export file appears.  It's taking a long time to export the downloaded files.
Is there a way to make the export run faster?  I was thinking if the export location is different from the download location, this could speed up the process.  However, I don't see an option to set the location for the export folder.

Any ideas?  Thanks!

**Comment by mackworth** [comment]
I don't think that'll make much difference, but you're welcome to try!  The temporary files (including the downloaded file) default to "/tmp/ctivo" and is set in Advanced Preferences (cmd-opt-comma). 

Mostly, converting video takes a while.   In Activity Monitor, is ffmpeg using all your cores?
