### ISSUE TITLE
Local network TiVo disappeared overnight

### ISSUE THREAD

**Issue by desilinguist** [dscottbuch/cTiVo#249]
My TiVo Roamio Pro has been working fine with cTiVo for years now and this morning, it's just disappeared. I rebooted the mac and the tivo both and it didn't make a difference. Comparing the log (attached) with the URLs that I see for the TiVo via Bonjour Browser (screenshot attached), it looks like it's not getting the right IP address or something? I read in the other issues that some AntiVirus software may be to blame but I am not running any AV software on my Mac. 

macOS v10.10.5
cTiVo v2.5.1

Any help would be greatly appreciated.

Log file: [com.cTiVo.cTiVo 2017-05-28 13-19.log.txt](https://github.com/dscottbuch/cTiVo/files/1034200/com.cTiVo.cTiVo.2017-05-28.13-19.log.txt)

![Bonjour Browser Screenshot](https://cloud.githubusercontent.com/assets/161680/26529303/97ca7c1e-438b-11e7-83af-2d132874a038.png)

**Comment by desilinguist** [comment]
And ... it just started working by itself! Very, very strange. I am not sure what happened which makes me worry that if it happens again, I will not know how to fix it.

**Comment by mackworth** [comment]
Well, the 0.0.0.0 reference is probably due to a an extra Manual TiVo.   Just go into Edit>Edit TiVos and you 'll see an entry "TiVo Name 0.0.0.0". Select that row and delete it with the "-" (minus sign) button

Second, it looks like the TiVo may have been slow to respond. Has anything changed in your network recently?

**Comment by mackworth** [comment]
Oh, btw, I closed it as there's no active issue, but if you do have further problems, happy to help diagnose.
