### ISSUE TITLE
Request: Sub-sort Now Playing Episode Number

### ISSUE THREAD

**Issue by mortax** [dscottbuch/cTiVo#250]
Currently, when shows are sorted by `Now Playing`, i.e. _show_/_episode name_, the actual episodes appear in random order.

Request: Please sub-sort `Now Playing` by `Episode Number`, or allow a more general way to sub-sort by any column (e.g. with _Shift Click_ on additional columns).

**Comment by mackworth** [comment]
So, to be precise, it's not random. It should be sorting by show name, then episode name (exactly what's shown in the column).  I assume you mean if there is no episode name? Then it should preserve whatever order you previously sorted, so as a workaround, if you sort by episode number, then by Now Playing, it should be in the order you're looking for.

OTOH, I think you're right, it should sort by something when the episode name is blank. Generic secondary key is very hard, but I could add a specific one for programs. I think First Air Date would be better than Episode Number, as (at least with my system) most of the shows that don't have episode names, also don't have episode numbers.

I would use the same sort key pair for Series name as well, for people using separate columns, but not Episode (better to preserve previous order). Can you see any other columns that need a secondary key?

**Comment by mortax** [comment]
> So, to be precise, it's not random. It should be sorting by show name, then episode name (exactly what's shown in the column)

unfortunately, that's not what i see:

![screen shot 2017-06-29 at 1 58 03 pm](https://user-images.githubusercontent.com/788303/27710011-067aaade-5cd3-11e7-87ad-f19758ff94f2.png)

ami i doing something wrong?

**Comment by mackworth** [comment]
That looks right to me; Series Name then Episode Name:  Blood Washed Way < Bodies of Water < Brothers < Causality < ... < Primary

**Comment by mackworth** [comment]
If you'd like to see 12 Monkeys ordered by episode number, then (for now) hide Now Playing column, show Series and Episode columns, then sort by Episode Number and finally sort by Series.

**Comment by mortax** [comment]
oh, i see what you're saying. yes. i want it sorted by _Series_ then by _Episode Number_.

you're suggestions names perfect. sense. thanks!
