### ISSUE TITLE
Sorry for the stupid question: what replaced AVConv?

### ISSUE THREAD

**Issue by Greenysmac** [dscottbuch/cTiVo#253]
Sorry to ask. I just noticed my Roamio/Comcast no longer rewrapping - but converting.

And I see in 2.5 or so that the AVConv was removed.

Is there an easy preset so myself system is just remuxing/copying the stream vs. encoding?

Thanks.

**Comment by mackworth** [comment]
Yup, mencoder was giving us grief, especially with TS files so we deprecated it.  There's a whole treatise on formats in https://github.com/dscottbuch/cTiVo/wiki/Video-Formats , but it sounds like you want Decrypt MP4, which copies the original TiVo stream into an MP4 file.  It therefore can have commercial skipping and captions added without re-encoding.

You may need to make it visible with Edit>Edit Formats, select the Format you want to use, and clear its Hide in User Interface checkbox

Let me know if that works.

**Comment by mackworth** [comment]
ps if you really want AVconv itself, just install it.  If it's in the usual system places, we should find it.

**Comment by Greenysmac** [comment]
Fantastic - it works great. Thanks!

**Comment by mackworth** [comment]
Glad to hear it!
