### ISSUE TITLE
Hangs during "Updating"

### ISSUE THREAD

**Issue by sdegro** [dscottbuch/cTiVo#254]
I have 2 tivo boxes.  One works fine with cTivo but the other one says "Updating ...." and will not stop.   If I stop cTivo and restart it, then the new shows are there.   Somehow the Updating hangs on just the one tivo.

[ctivo.docx](https://github.com/dscottbuch/cTiVo/files/1154290/ctivo.docx)

**Comment by mackworth** [comment]
So if it works ok (e.g. the second time above), then later when it refreshes (default of 15 minutes later), does it hang up then, or does it continue to work?

When it hangs up on Updating, and you hit Cmd-R (Refresh TiVos), does that work then?

(We're looking to see if there's a pattern to when it hangs up: is it only on initial access of a cTiVo session? Is it every other time you access it?  Does it always stop on the same show number?)

Second is possible network issues...
Which kind of TiVos are they?  How are they connected to the Mac (e.g. wifi/ethernet)? Do transfers from the problematic one work ok?

Can you post the log (Help>Show logs) in finder.  Probably compress them with Finder's Right-Click Compress, and then attach to a comment here.

**Comment by sdegro** [comment]
That was fast.  Here is some more information.

 

 

Family Room:   Tivo Series 4 with WD eSATA expansion connected

Bedroom:  Tivo Series 5

 

When I first start ctivo, both load fine and download the subscriptions


However, Family Room keeps saying updating and nothing is added to “Now Playing” Panel from Family Room after is says “Updating Family Room” and keeps circling.

The bedroom does continue to refresh and does download the subscription.  The 15 minute refresh seems to work

 

If I want to see that is on the Family Room, I stop cTivo and restart it and everything (including new things) will show.

 

The Tivos are connected to the mac only through wifi; not direct connected.

 

The transfers work from both Tivos just fine.  The family room just requires that I stop and restart cTivo to get the latest.   I have rebooted the Family room to see if that helps.  It did not.

 

Thanks for your help.  It is a great tool

**Comment by mackworth** [comment]
That's a pretty old version of cTiVo ya got there. I don't think upgrading will fix your problem, but it's certainly worth a try.

If not, after upgrading, can you go into Adv Prefs (Cmd-Opt-Comma), and set the TiVo debug level to Detail, and give me that log?

**Comment by mackworth** [comment]
Oh, BTW,  Update is at:
https://github.com/dscottbuch/cTiVo/releases/download/2.5.1/cTiVo.zip

**Comment by sdegro** [comment]
I did the update and so far so good.   I’ll know in the morning when I get up but it seems to be working

**Comment by sdegro** [comment]
Thanks, the latest version works fine.

**Comment by mackworth** [comment]
Ah, always good to hear!
