### ISSUE TITLE
Not totally a cTivo issue, but has anyone else run into this...

### ISSUE THREAD

**Issue by WhyAkron** [dscottbuch/cTiVo#255]
Time Warner/Spectrum decided to fix what was working and pushed out a firmware update to their modems. Mine is Arris TG862G/TW (internet, phone, router with wifi). After that update I can't connect to the Tivo with cTivo or Tivo Transfer. Finally narrowed it to Bonjour not working. The Bonjour pulldown in Safari doesn't show the Tivo or a printer that is usually there. Called TW tech support. Not sure the rep ever fully understood what I was talking about, but he finally said that I would have to call Arris. Did that. Arris rep said that they are not allowed to provide any support for that model because it was made for service providers only and TW should have all technical info. He did say that in general their modems support Bonjour, and hinted that the problem could be due to it being an older model. Next step will be to see if I can exchange for a newer modem without having to pay for it.

Anyway, cTivo will see the Tivo and works if I enable "Remote (Manual) Tivo's."

Here's my problem: in cTivo I use "Decryped Tivo Show" but if I put the show back on the Tivo there are no subtitles. That's why I also use Tivo Transfer, even with the restriction of viewing only on the computer that downloaded the show or back on the Tivo it came from. Is there a cTivo setting or format that will embed the subtitles so they will be usable if the show is sent back to the Tivo?

Thank you for any suggestions.

**Comment by sugyfelix** [comment]
A comment on the first part: Bonjour is a local subset only protocol, so one thing to check is if the Tivo and the Mac are on the same subnet. Check network settings on the Tivo and the Mac. If they are on the same network are they both using Ethernet or WiFi or a mix? If WiFi is involved, some WiFi setups isolate clients from each other (e.g., so a guest can't browse around your network looking fir interest things.) This is more typical of commercial installs but I have seen the option available on a few different personal routers. It is interesting that manually entering the address works.  Points more to a broadcast type problem than an isolation problem, but it depends on the mechanism being used to enforce isolation. Hopefully is done defaults that has changed on your modem.

**Comment by mackworth** [comment]
A little more on Bonjour. It's only used by cTiVo to discover the address, so once you have the actual address and create a Manual TiVo, that'll work fine across any routing. Best thing would be to run [Bonjour Browser](http://www.tildesoft.com/files/BonjourBrowser.dmg) It will simply list all the bonjour services your mac can see, so it may make diagnosis easier.

On the subtitles, there's a known problem with modern TiVos with this, but I may have good news for you.  Try using TS streams  (with cTiVo 2.5 or later), and use Decrypt MP4 Format to save the files w/ captioning but without re-encoding them. I just sending one back with PyTivo, and it played the captions properly on my Roamio.

**Comment by WhyAkron** [comment]
sugyfelix & mackworth: Thank you for Bonjour suggestions, but I had checked all network settings and nothing had changed after the modem update. Anyway, yesterday I got a no charge swap for a newer modem (Arris TG1672G) and Bonjour is back. Side note: found out that the Time Warner system saves modem settings (except initial login to the modem) and puts them on to the new one. Paranoid me says what else are they saving, but lazy me says good, don't have to redo setup on everything that uses wifi, except I did have to get into some to change go 5GHz which the old one didn't have - much less congested in my neighborhood.

 mackworth on Subtitles: still waiting to test your suggestion. (Wife is hogging the Tivo!) On using TS streams - do I need to set that for the channels I want, or turn on "Always Use Tovo's Transport Stream Format" (back in January I had problems with some channels when that was turned on), or will cTivo default to TS streams?

Thank you

**Comment by mackworth** [comment]
So, (partly due to some issues as you report), cTiVo will default to PS until a channel converts to H.264 (as PS streams can't support that), but you can enable it for a single channel or all of them.

**Comment by WhyAkron** [comment]
I guess the real question is - is TS input required for Decrypt MP4 output?

**Comment by mackworth** [comment]
Physically not, but the resulting MP2 stream inside an MP4 may confuse various players.  Feel free to try it out though.

**Comment by mackworth** [comment]
Oh, and in particular, you'd be handing a PS back to the TiVo which will probably trigger the no-caption bug.

**Comment by WhyAkron** [comment]
OK. Looks like I have some experimenting to do.
One more question for now - how do I find out if a channel is using TS stream? Can't find anything in the wiki or help.
Thank you

**Comment by mackworth** [comment]
On the Edit Channel screen, it'll list any channels that have converted to H.264 (and hence must use TS) as well as any you have manually converted to TS.

**Comment by WhyAkron** [comment]
The list is empty. I'll turn on Always Use and see what happens.
Main thing will be testing the captions issue.
Thanks for the suggestions.

**Comment by WhyAkron** [comment]
The list is empty. I'll turn on Always Use and see what happens.
Main thing will be testing the captions issue.
Thanks for the suggestions.

**Comment by WhyAkron** [comment]
Tried cTivo downloads to Decrypt MP4. Tried to put them back on the Tivo to test for subtitles, but using Mac2Tivo (Roxio) the Tivo didn't see the files at all but it showed the other files in the same folder. Tried pyTivoX (version 1.4.1b) and the Tivo saw the files, but transfer failed with "Message #86."

If it means anything, on the Mac VLC, Mac Media Player, and MPlayerX play OK.
Roxio Video Player (1.0.3) does not, says "The movie contains some invalid data."
Quicktime Player (10.4) says only "The operation could not be completed" (opens a black screen, shows "Opening...")
iTunes (12.6.2.20) copies the files, but only "plays" a black screen with no audio.

The TiVo is a Premiere XL4. Mac is Mid 2010 MacBook Pro 17", 2.53GHz Intel Core i5, 8GB RAM. OS 10.11.6. cTivo 2.5.1 (714). All cTivo format settings are as they came.

Do I maybe have something that's too old for this to work?

**Comment by WhyAkron** [comment]
Forgot to add - changing TS stream settings doesn't make any difference to playability.

**Comment by mackworth** [comment]
I'd want to see the actual streams in the file. There's a program called media info that will tell you that. 

PytivoX is way old. Def want to try the real pyTivo.

**Comment by WhyAkron** [comment]
Here are examples generated by MediaInfo-Multi.
TS On / Not On refers to "Always Use Tivo's Transport Stream Format"

[MediaInfo for MotorWeek TS Not On.txt](https://github.com/dscottbuch/cTiVo/files/1171824/MediaInfo.for.MotorWeek.TS.Not.On.txt)
[MediaInfo for MotorWeek TS On.txt](https://github.com/dscottbuch/cTiVo/files/1171826/MediaInfo.for.MotorWeek.TS.On.txt)
[MediaInfo for Today TS Not On.txt](https://github.com/dscottbuch/cTiVo/files/1171825/MediaInfo.for.Today.TS.Not.On.txt)
[MediaInfo for Today TS On.txt](https://github.com/dscottbuch/cTiVo/files/1171827/MediaInfo.for.Today.TS.On.txt)

**Comment by mackworth** [comment]
So you're definitely getting MP2 streams, so putting them in an MP4 container is problematic, as you've found. 

I would first upgrade the pyTivo, then try Decrypted TiVo Show but with TS turned on. I would also suggest renaming the .MPG file to .TS to make sure PyTivo understands what the file is (I'm changing this in next rev).

**Comment by WhyAkron** [comment]
Getting somewhere... Installed latest wmcbrine pytivo. Decrypted TiVo Show with and without TS turned on play on TiVo, but no captions. Decrypt MP4 TS on and not on both play on TiVo with captions, BUT but TiVo shows wrong timing. A 31 minute show reads as 43 minutes in info and on the bar that shows when play or pause is pressed. Actual (timed) running time is correct. If it is then downloaded by cTivo the correct timing shows on the Mac, including with MediaInfo. "If it's not one thing, it's 17 others."

**Comment by mackworth** [comment]
So it's only a time display problem?  Does the file just end with 12 minutes to go?

Just checking, did you rename the .Mpg files as .TS for the transport stream ones?

**Comment by WhyAkron** [comment]
Files runs to its end, with the time display running proportionally, I think. I'll have to double check that, but at the end of the show the time shows as 43 minutes.
Didn't do the rename yet. Moving the files around takes time, so maybe tomorrow.

**Comment by mackworth** [comment]
No moving needed. Wherever you have them for pyTivo, just rename to .ts

**Comment by WhyAkron** [comment]
More results - Renaming worked. Plays on Tivo with captions, correct time display. (Renameing a file that was done without TS turned on plays with captions, but with the time error.) The time error is proportional - at what shoulld be 25-26 minutes, it shows 36, and at 30 it shows 41. The one that worked (TS on, renamed) won't play in VLC renamed, but that's not a big deal, just have to remember to change it back. The moving I mentioned refered to was to and from the Tivo. Anyway, this one seems to be solved.

There is one other thing - when I try to test channels in Edit Channels, it either does nothing, or adds to the Download Queue with one of them showing as downloading, but never shows progress and never ends on it own. Some of the time it will pop a notification that says "Your processor may be too old for Mencoder. You may need '10.7' version of cTivo." When I look at Test PS in Edit Formats it has mencoder in "Encoder to use." Is that supposed to be there?

**Comment by mackworth** [comment]
So, I tried both a MP4-encoded and an MP2 encoded "Decrypted TiVo Show" and both ran fine in VLC.  Do you have a current version? What was exact symptom?  (Need to know if this is ok, because I am changing the default in the next version.)

On the testPS, I use mencoder, as it reports very quickly there's a problem, but looks like you ran into one of the problems with it, that it's increasingly incompatible with older machines.  Sounds to me that your cable provider hasn't started their H.264 transition yet, so the Test is irrelevant to you for now at least.  In general you can ignore it, if a channel changes, then cTiVo should automatically recognize it and change to TS for that channel.  Further, if you're using TS across the board, then you'll never notice.

**Comment by WhyAkron** [comment]
Tried again with different shows to be sure. "Decrypted TiVo Show" with "Always Use..." turned on, and .mpg renamed to .ts is the only combination that will play with captions and correct time display when put back on the TiVo. However, it will not play on VLC with either name extension. VLC puts it into its playlist, but nothing else happens (doesn't even open a window for the video). Using VLC Version 2.2.6 Umbrella (Intel 64bit) which it says is the current version.
Attaching MediaInfo files for a show with/without TS turned on.
[MediaInfo for ATK TS OFF.mpg.txt](https://github.com/dscottbuch/cTiVo/files/1178597/MediaInfo.for.ATK.TS.OFF.mpg.txt)
[MediaInfo for ATK TS On.mpg.txt](https://github.com/dscottbuch/cTiVo/files/1178596/MediaInfo.for.ATK.TS.On.mpg.txt)

**Comment by mackworth** [comment]
So 3.0 should rename transport streams as ".ts" automatically now.

**Comment by mackworth** [comment]
So, I think this thread is complete now, but let me know.
