### ISSUE TITLE
cTivo performance after latest apple update ( macOS Sierra 10.12.6 )

### ISSUE THREAD

**Issue by cgurley** [dscottbuch/cTiVo#256]
After latest Apple update, cTivo performance has become almost unusable. Has anyone else experienced extremely slow encoding or shows not completing at all after installing the update?

**Comment by mackworth** [comment]
Hmm?  Closed issue, meaning you figured it out, or are you still having the problem?

**Comment by cgurley** [comment]
Closed - had to uninstall the version I had and installed newest version. Most current version works as expected with the update

**Comment by mackworth** [comment]
Good to hear.  Thx
