### ISSUE TITLE
Couple of shows which refuse to download

### ISSUE THREAD

**Issue by blankgm** [dscottbuch/cTiVo#257]
I have a couple shows which refuse to download.  For example, Stargate SG-1 S03 E16 "Urgo", which was recorded on two separate TiVO boxes.  Every time cTiVo attempts to download it I get a return of "Invalid Media Access Key?" error message.

Most programs download without issue.  However, other random shows within various series have this issue as well.  X-Files comes to mind.

The show is not flagged (as far as cTiVo / TiVo are concerned) as protected.

Mac Pro Early 2009 
Processor 2x2.26 GHZ Quad-Core Intel Xeon
Memory 32GB
cTiVO v2.5.1 (714)

**Comment by mackworth** [comment]
So that message is reporting that tivodecode is having a problem decrypting the file, that the decryption algorithm is failing.  Most obvious reason is the MAK being incorrect, but if other shows are working, that doesn't apply.  It may be a weak digital signal on those channels, especially if you notice that they're on the same channel. you can go into the TiVo help menus to test that.  If a weak signal across all channels, then talk to your cable provider about fixing your cable; if on certain ones, then you'll have to talk to the head-end people about the problem.

Another test would be to enable Java on your machine and switch to the tivolibre decoder; it may do better for you.

**Comment by blankgm** [comment]
Thank you for your reply.

The issue however, is that the file isn't even downloading (the /temp/buffer[program].mpg file].  But somehow CTiVo is trying to process it.  

When the file begins download - it almost immediately (within seconds) goes to the encoding process - which of course fails and flags the error.  (The program is fully viewable on either  TiVo in playback without issue.)

Unless, of course, I don't fully understand the process and the decryption is part of the downloading process followed by encoding?

There is a resulting mpg of 0 bytes created in the target directory - but really nothing in the working /tmp directory.  After CTiVo is finished processing current files - I will kick off an example run and clip some log entries for inclusion.

I started looking into enabling Java and trying tivolibre - I am having some issues there as well.  Java is installed, but tivolibre still is not available.  But until the files actually transfer - conversions won't work regardless of which option I use.

**Comment by mackworth** [comment]
So, for efficiency, cTiVo simultaneously downloads and decrypts the file.  It does so in memory and then hands the resulting file to the encoder before it even hits the disk.  

Thus if you're getting an error immediately within the file, then you won't see a downloaded file at all.

First step is to remove the encoding from the process, so use the Format "Decrypted TiVo Show", which just writes the decrypted file to disk.  To keep things simple, you can also turn off memory-based buffering in Advanced Preferences. Then you should see the .tivo file generated as well in tmp/ctivo

On TivoLibre, if it's greyed out in Adv Preferences, go into Terminal and type "/usr/libexec/java_home"  If it says "Unable to find", then java is not properly installed.  (This is literally what cTiVo does to check.)

And yes, a log at Debug level Detail would be helpful to advise.

**Comment by blankgm** [comment]
After getting the JDK installed and tested, implementing TivoLibre as the decoder, and turning off memory-based buffering - things seem to be working fine now.

- GMB

**Comment by mackworth** [comment]
Glad to hear it! Let me know if you have any other problems.
