### ISSUE TITLE
New cTiVo on Mac not auto downloading shows

### ISSUE THREAD

**Issue by gespensen** [dscottbuch/cTiVo#258]
I had cTiVo running flawlessly on another mac that is out of commission atm. I installed cTiVo on a new mac OS X 10.12.6 and it's sort of running. It will download the show only when I refresh the tivo. Also I'm getting a strange Tivo Status, offline and on line at the same time. Pic attached. Any help would be greatly appreciated.

Thank you

[cTivo issues 2.pdf](https://github.com/dscottbuch/cTiVo/files/1211884/cTivo.issues.2.pdf)
[cTivo issues 1.pdf](https://github.com/dscottbuch/cTiVo/files/1211885/cTivo.issues.1.pdf)

**Comment by mackworth** [comment]
First thing is that you have both Manual and automatic connections to the same TiVo, not a great thing. Just hit the Enabled switch on the manual copy to disable it.

**Comment by mackworth** [comment]
Any luck?

**Comment by gespensen** [comment]
Hugh,

Sorry I didn’t get back to you about my cTiVo issue. I did as you suggested and removed the manual refrease and only have the auto. Citvo took a very long time to find my Tivo on the network. All the shows appeared as I expected and started to download the subscribed shows. Then I went on vacation, I just returned yesterday and no new shows had downloaded. I had to again perform a manual refresh to read the new show. 

It looks like half of my problem is solved. The issue now is that there is no auto refresh for new shows.






Thanks for your assistance.

**Comment by mackworth** [comment]
Interesting. It’s strange that Bonjour worked, but slowly.  One unlikely possibility: is your network divided up somehow?  Second, could you attach the section of the log when ctivo starts up? (Help>Show Logs in Finder). Third, try disabling the automatic one and enabling the manual one.

**Comment by gespensen** [comment]
Attached log of Tivo starting up:


I have an eero mash wifi system installed.

**Comment by mackworth** [comment]
Unfortunately, github strips attachments from emails. I think you need to either paste the relevant text into your post, or go to the website and attach it there.

**Comment by gespensen** [comment]
2017-08-31 09:45:11:648 MTAppDelegate>applicationDidFinishLaunching:@205>Starting cTiVo; version: 714
2017-08-31 09:45:12:238 MTTiVoManager>netServiceDidResolveAddress:@1687>Got new TiVo: Family Room at 192.168.7.100
2017-08-31 09:45:12:305 MTTiVo>updateShowsStartingAt:withCount:@376>Initial loading from TiVo Family Room at URL https://DVR-EED9.local./TiVoConnect?Command=QueryContainer&Container=%252FNowPlaying&Recurse=Yes&AnchorOffset=0&ItemCount=15
2017-08-31 09:45:15:474 MTTiVo>parserDidEndDocument:@618>TiVo returned ZERO requested shows! Ignoring shows from 180 to 183
2017-08-31 10:00:17:030 MTTiVo>parserDidEndDocument:@618>TiVo returned ZERO requested shows! Ignoring shows from 180 to 183

**Comment by mackworth** [comment]
Thx.  So, that snippet shows it finding the tivo within 0.6 seconds, which seems adequately fast, no?  Maybe go back through earlier logs to find a slower one?

**Comment by gespensen** [comment]
I think we have a misunderstanding. It only took a long time to find the tivo when I enabled the network tivo.I had 
![screen shot 2017-08-31 at 8 14 51 am](https://user-images.githubusercontent.com/6163544/29936539-79a30c5a-8e37-11e7-875c-8df19e4edd06.png)
![screen shot 2017-08-31 at 8 15 06 am](https://user-images.githubusercontent.com/6163544/29936540-79a319d4-8e37-11e7-8c88-bb94ca6c2be9.png)

disabled both manual and network Tivo's and only reenabled the network tivo which took a long time. When it did connect lag the shows started up and started to auto download. That was back on Aug 16th. Yesterday when I returned no new shows were downloaded until I performed a manual Tivo refresh. I normally leave the Tivo running all the time. My only issue is Tivo does not auto download new shows. I believe everything else on Tivo is working, just not the auto download new subscribed shows.

**Comment by mackworth** [comment]
So, it occurred to me that you could have the Scheduling turned on in Preferences. That will block any downloads, but it should still enter the subscribed shows.  Can you post a log?  Go into Adv Pref (Cmd-Opt-Comma) and set Debug level to Major, then Subscription to Verbose, and then record a show you are subscribed to (you can (1) set a temporary subscription to record all shows with Cmd-N and ALL, or just put in the name of a show that is currently showing, and then (2) record a few seconds, and then (3) stop the recording  , and (4) refresh the tivo Cmd-R.

**Comment by gespensen** [comment]
Ok it seems to be working. Thank you for your help.

**Comment by mackworth** [comment]
Okay, let me know if it stops again!
