### ISSUE TITLE
cTiVo no longer downloading

### ISSUE THREAD

**Issue by technologizer** [dscottbuch/cTiVo#259]
I've been using and loving cTivo but it's stopped working. (I installed High Sierra beta on this Mac, though I don't know if that explains anything.)

cTivo still sees my TiVo Roamio and the shows on it, but when I add a show to the queue, it doesn't download and I don't even see any indication that the download starts.

I rebooted my TiVo and it didn't fix this. Any other tips?

Thanks,

--Harry

**Comment by mackworth** [comment]
Can you post your logs (Help>Show logs in Finder)

**Comment by technologizer** [comment]
Thanks. Here's the logfile, which shows me trying to download the same show over and over...

[com.cTiVo.cTiVo 2017-08-15 06-46.log.txt](https://github.com/dscottbuch/cTiVo/files/1226852/com.cTiVo.cTiVo.2017-08-15.06-46.log.txt)

**Comment by mackworth** [comment]
Ok, so see the line: 
MTTask>setTaskName:@84>Could not create logfile at /tmp/ctivo//decryptThe Dick Cavett Show- Jim Henson and the Muppets.txt

That's most likely saying either /tmp (your system's temporary directory) has somehow been deleted, or you've lost permission to write there ( or in /tmp/ctivo)

So next step would be to run Disk Utility and run Repair Permissions.  I would then reboot and try ctivo again.

**Comment by technologizer** [comment]
Thanks very much, this helped, and it looks like I have it working again.

**Comment by mackworth** [comment]
So good to hear. Thanks for checking in; I'll add a code to detect that case and give a warning message.
