### ISSUE TITLE
Synchronization issues with Subtitle (.SRT) file

### ISSUE THREAD

**Issue by dwhe** [dscottbuch/cTiVo#26]
Using 2.3.1 version currently - I am noticing that with lengthier video files (e.g. movies), the generated .SRT file has synchronization issues of varying degrees throughout the video. 

Usually synchronization issues in .SRT files are consistent throughout the video and can be fixed with time shifting applied across the entire .SRT file (e.g. adjusting the timing by adding 2 milliseconds to all subtitle lines).  

However with .SRT files generated by cTivo, the synchronization error at the beginning of the video is not the same as the end of the video which is very unusual in my experience. The result is that the synchronization issues can only be corrected on a line by line basis, which is not feasible. Im not sure if ccextractor is bugged or something is corrupting the .SRT file somehow.

**Comment by mackworth** [comment]
Closed due to, well, time.  Let me know if this is still an issue and if i can help figure it out.
