### ISSUE TITLE
MSNBC content protected ? 

### ISSUE THREAD

**Issue by cyberchucktx** [dscottbuch/cTiVo#260]
I notice that MSNBC content (all of the political shows) is apparently copy protected. 

Is that a problem with the provider (Suddenlink) or is this a "feature" from MSNBC? 

Curious,

**Comment by mackworth** [comment]
That's your cable provider. They control that bit.

**Comment by cyberchucktx** [comment]
Ah. So Suddenlink (not MSNBC) is doing the copy protection. 

Interesting, as other paid cable channels are not copy protected within the TiVO (HBO is, but that's not suprising).

Thanks,
C

**Comment by mackworth** [comment]
It may be a mistake on their part.  Time Warner is famous for copy-protecting almost everything, but if most of your other basic cable is not, then it'd be worth checking with them.  The problem will be finding someone that understands what the heck you're talking about.
