### ISSUE TITLE
High Sierra Compatibility

### ISSUE THREAD

**Issue by tdlivings** [dscottbuch/cTiVo#262]
tldr:  If you're using High Sierra beta, and cTiVo won't download, then as a workaround,
 In Advanced Preferences (Cmd-Opt-Comma) in cTivo, select a new temporary directory.  Put it somewhere other than /tmp, for example in your Documents folder, anything other than your existing ctivo download folder.

-----Original msg ------
Are you planning a High Sierra compatibility update?

Thank you

**Comment by mackworth** [comment]
Only if there’s a problem :)

Are you having one?

**Comment by tdlivings** [comment]
Yes, but I am not supposed to talk about it. I filed a bug report. Maybe they will fix it on their end.

**Comment by mackworth** [comment]
Well, I’m subject to the same NDA, and I don’t think Apple will be concerned about our having a private discussion to improve compatibility.  My admittedly ancient email that I use for just this kind of purpose is just Mackworth hosted via the aol com site. (Sorry for cryptic phrasing)

**Comment by tdlivings** [comment]
Attachment available until Sep 22, 2017
I can offer a video of the thing if you want I can upload it to Mail Drop
Click to Download
 <https://www.icloud.com/attachment/?u=https%3A%2F%2Fcvws.icloud-content.com%2FB%2FAcN8TrOsos3nnqIZgOU_ZmY9yzMpAbmIz_E52KS_P1fH8q0q0b1ciZ9e%2F%24%7Bf%7D%3Fo%3DAvrVW3hIZlM7GD7nSZCdVDeZIJVrfLZsWtFuE6rIbptz%26v%3D1%26x%3D3%26a%3DBf6ukJ6eOsDiA7oAPgEA_wHIAP8TfvHQ%26e%3D1506109043%26k%3D%24%7Buk%7D%26fl%3D%26r%3D81712549-52F4-43BE-9B52-52CFDEC15108-1%26ckc%3Dcom.apple.largeattachment%26ckz%3DB71C166A-1CFE-4D15-BCDF-A65F08D13F23%26p%3D68%26s%3Du9EOjrIPg9gupMzUvlPVXolghpU&uk=TcN84iN2e50wJ1cFY29Ssg&f=ctivo.mov&sz=37930982>ctivo.mov
37.9 MB

**Comment by mackworth** [comment]
Interesting!  I'll see if I can reproduce on my end.

**Comment by tdlivings** [comment]
Attachment available until Sep 22, 2017
No go on downloads either. 
Click to Download
 <https://www.icloud.com/attachment/?u=https%3A%2F%2Fcvws.icloud-content.com%2FB%2FASOb1ECcxyCWYLu3rUt6qeozsVnpAZG0_2q346WevspWaNLBzcolNuBK%2F%24%7Bf%7D%3Fo%3DApy60Mustn-mh4W2hS20Utx9seuYKEyWE1BKdB-rjEH0%26v%3D1%26x%3D3%26a%3DBaQLKFb7FaazA8wAPgEA_wHIAP8uUIMt%26e%3D1506110128%26k%3D%24%7Buk%7D%26fl%3D%26r%3D95C7DB71-37A2-4E46-B911-623A30FFA04B-1%26ckc%3Dcom.apple.largeattachment%26ckz%3DB71C166A-1CFE-4D15-BCDF-A65F08D13F23%26p%3D68%26s%3DsgX-sxjg_Y92ZSJtKQhAMGhMXpw&uk=Yu14y8nP_7frRA0xCBqgzg&f=ctivo%20downloads.mov&sz=114096526>ctivo downloads.mov
114.1 MB

**Comment by kteare** [comment]
I had these issues with cTivo and High Sierra. Re-booting my Tivo fixed it.

**Comment by tdlivings** [comment]
No go on the downloads. 
Tried a reboot of the TiVo, 
Tried an uninstall and reinstall of the app. 
Tried another format. 
Tried to save the temp file but I could not find it.

This is not a mission critical event. I am just testing some stuff. I still have production box online. 

Thank you for your efforts.

**Comment by kteare** [comment]
I don’t know if its VooDoo from this thread, but mine also is not initiating a download now.



Full log here:


2017-08-26 15:24:09:129 MTAppDelegate>applicationDidFinishLaunching:@205>Starting cTiVo; version: 714
2017-08-26 15:24:09:629 MTTiVoManager>netServiceDidResolveAddress:@1687>Got new TiVo: Living Room at 192.168.86.87
2017-08-26 15:24:09:670 MTTiVo>updateShowsStartingAt:withCount:@376>Initial loading from TiVo Living Room at URL https://DVR-FEDA.local./TiVoConnect?Command=QueryContainer&Container=%252FNowPlaying&Recurse=Yes&AnchorOffset=0&ItemCount=15
2017-08-26 15:24:11:283 MTDownload>launchDownload@1608>Starting 0 download for Squawk Alley (Living Room); Format: 1080p;  Add to iTunes; tivodecode-ng; Transport Stream
2017-08-26 15:24:11:284 MTTask>setTaskName:@88>Could not create logfile at /tmp/ctivo//decryptSquawk Alley.txt
2017-08-26 15:24:11:284 MTTask>setTaskName:@94>Could not create errfile at /tmp/ctivo//decryptSquawk Alley.txt
2017-08-26 15:24:11:284 MTTask>setTaskName:@101>decrypt Could not write logfile at /tmp/ctivo//decryptSquawk Alley.txt
2017-08-26 15:24:11:285 MTTask>setTaskName:@106>decrypt Could not read logfile at /tmp/ctivo//decryptSquawk Alley.txt
2017-08-26 15:24:11:285 MTTask>setTaskName:@111>decrypt Could not read error file at /tmp/ctivo//decryptSquawk Alley.err
2017-08-26 15:24:11:285 MTTask>setTaskName:@88>Could not create logfile at /tmp/ctivo//encodeSquawk Alley.txt
2017-08-26 15:24:11:285 MTTask>setTaskName:@94>Could not create errfile at /tmp/ctivo//encodeSquawk Alley.txt
2017-08-26 15:24:11:286 MTTask>setTaskName:@101>encode Could not write logfile at /tmp/ctivo//encodeSquawk Alley.txt
2017-08-26 15:24:11:286 MTTask>setTaskName:@106>encode Could not read logfile at /tmp/ctivo//encodeSquawk Alley.txt
2017-08-26 15:24:11:286 MTTask>setTaskName:@111>encode Could not read error file at /tmp/ctivo//encodeSquawk Alley.err
2017-08-26 15:24:11:287 MTTask>launch@430>Error on launch: working directory doesn't exist. for decrypt; cannot launch: Task Name: decrypt
LaunchPath: /Applications/cTiVo.app/Contents/MacOS/tivodecode-ng -m 6931461977 -o '/tmp/ctivo//bufferSquawk Alley.mpg' -v -
Does not require output pipe
Standard Input: <NSConcreteFileHandle: 0x6000002f2600>
Standard Output: <_NSStdIOFileHandle: 0x6080002ecc00>
Standard Error: <_NSStdIOFileHandle: 0x6080002e8c00>
logFilePath = /tmp/ctivo//decryptSquawk Alley.txt
errorFilePath = /tmp/ctivo//decryptSquawk Alley.err
File Handles: output: 0x0; error: 0x0, logFileRead:0x0, logFileWrite:0x0 
Tracking RegEx = (null)
Has completionHandler
Does not have progressCalc
Does not have startupHandler
DirectoryPath: /tmp/ctivo/
Environment: (null)
2017-08-26 15:24:11:289 MTTiVoManager>notifyForName:withTitle:subTitle:isSticky:forNotification:@1419>Notify: TiVo show failed/nRetrying
2017-08-26 15:24:15:296 MTDownload>launchDownload@1608>Starting 0 download for Squawk Alley (Living Room); Format: 1080p;  Add to iTunes; tivodecode-ng; Transport Stream
2017-08-26 15:24:15:297 MTTask>setTaskName:@88>Could not create logfile at /tmp/ctivo//decryptSquawk Alley.txt
2017-08-26 15:24:15:297 MTTask>setTaskName:@94>Could not create errfile at /tmp/ctivo//decryptSquawk Alley.txt
2017-08-26 15:24:15:297 MTTask>setTaskName:@101>decrypt Could not write logfile at /tmp/ctivo//decryptSquawk Alley.txt
2017-08-26 15:24:15:297 MTTask>setTaskName:@106>decrypt Could not read logfile at /tmp/ctivo//decryptSquawk Alley.txt
2017-08-26 15:24:15:297 MTTask>setTaskName:@111>decrypt Could not read error file at /tmp/ctivo//decryptSquawk Alley.err
2017-08-26 15:24:15:298 MTTask>setTaskName:@88>Could not create logfile at /tmp/ctivo//encodeSquawk Alley.txt
2017-08-26 15:24:15:298 MTTask>setTaskName:@94>Could not create errfile at /tmp/ctivo//encodeSquawk Alley.txt
2017-08-26 15:24:15:298 MTTask>setTaskName:@101>encode Could not write logfile at /tmp/ctivo//encodeSquawk Alley.txt
2017-08-26 15:24:15:298 MTTask>setTaskName:@106>encode Could not read logfile at /tmp/ctivo//encodeSquawk Alley.txt
2017-08-26 15:24:15:298 MTTask>setTaskName:@111>encode Could not read error file at /tmp/ctivo//encodeSquawk Alley.err
2017-08-26 15:24:15:299 MTTask>launch@430>Error on launch: working directory doesn't exist. for decrypt; cannot launch: Task Name: decrypt
LaunchPath: /Applications/cTiVo.app/Contents/MacOS/tivodecode-ng -m 6931461977 -o '/tmp/ctivo//bufferSquawk Alley.mpg' -v -
Does not require output pipe
Standard Input: <NSConcreteFileHandle: 0x6000002f2780>
Standard Output: <_NSStdIOFileHandle: 0x6080002ecc00>
Standard Error: <_NSStdIOFileHandle: 0x6080002e8c00>
logFilePath = /tmp/ctivo//decryptSquawk Alley.txt
errorFilePath = /tmp/ctivo//decryptSquawk Alley.err
File Handles: output: 0x0; error: 0x0, logFileRead:0x0, logFileWrite:0x0 
Tracking RegEx = (null)
Has completionHandler
Does not have progressCalc
Does not have startupHandler
DirectoryPath: /tmp/ctivo/
Environment: (null)
2017-08-26 15:24:15:301 MTTiVoManager>notifyForName:withTitle:subTitle:isSticky:forNotification:@1419>Notify: TiVo show failed/nRetrying


---
Best Regards

Keith Teare
Chat with me instantly at https://chat.center/keith
________________________________________________________

**Comment by tdlivings** [comment]
Go to private/tmp and create ctivo folder. This will allow the program to put the temp files in there and you will be able to download once again.

**Comment by mackworth** [comment]
Yup. same thing.  In Finder, use the Go>Go To Folder (Cmd-Shift-G) command, and put in "/tmp" (without quotes).  Then Cmd-N  and name the folder "ctivo"; then you should be fine.

**Comment by kteare** [comment]
Thank you…

fixed


---
Best Regards

Keith Teare
Chat with me instantly at https://chat.center/keith
________________________________________________________

**Comment by kteare** [comment]
Interesting…

This folder (/private/tmp/ctivo) keeps getting deleted between reboots or after some period of time (a day or so). Then I re-create it and I am fine until it disappears again….


---
Best Regards

Keith Teare
Chat with me instantly at https://chat.center/keith
________________________________________________________

**Comment by mackworth** [comment]
Yup, the official rule us you can't count on /tmp folders hanging around after execution. In practice this has meant three days without access. I'm going to create a testbed to figure out what's wrong with creating the folder. 

There's actually a fair amount of code to check that it worked already in the current version, so I'm puzzled. 

A better workaround might be to use a temporary directory in your documents directory (just not the same as ctivos download folder). This is set in adv prefs (cmd-opt-comma)

**Comment by tdlivings** [comment]
The private Tmp is mapped as a alias. The rights are consistent going back several OS X versions.

**Comment by mackworth** [comment]
So what's changed this time?

**Comment by tdlivings** [comment]
APFS container in my case.

**Comment by tdlivings** [comment]
One other thing to consider is the dynamic environment with rapid os version changes

**Comment by tdlivings** [comment]
The engineers are testing a virtual reformat to gauge the impact with each new version.

**Comment by kteare** [comment]
BTW I am running APFS in case its crucial….


---
Best Regards

Keith Teare
Chat with me instantly at https://chat.center/keith
________________________________________________________

**Comment by tdlivings** [comment]
If I was you I would migrate the ctivo to an external and change program pointer for now. Even an sd card would do.

**Comment by mackworth** [comment]
Any chance the new release today fixed the problem?

**Comment by tdlivings** [comment]
I am out of the office but will check tomorrow.

**Comment by jeffsep** [comment]
Just installed latest HS 10.13 Beta (17A360a)and ran into a few issues: 1) Launching cTiVo opens 2 duplicate app windows (this is just a nuisance and doesn't affect functionality), 2) Unable to download videos (was able to fix with "In Finder, use the Go>Go To Folder (Cmd-Shift-G) command, and put in "/tmp" (without quotes). Then Cmd-N and name the folder "ctivo"; then you should be fine.", 3) This is likely a HS issue but the videos are not able to be opened in Quicktime/Quick Look but are able to be opened in VLC.

Just my input.

Love this application and look forward to an update that will resolve these minor issues!

Thanks!!

**Comment by mackworth** [comment]
Okay, so here's a little test program that will simply check whether we can find and/or create a tmp directory. Please let me know what it says; just hit Validate Tmp Directory. If it says you already have one, you can hit Remove tmp directory first.

[TestDirectory.zip](https://github.com/dscottbuch/cTiVo/files/1278558/TestDirectory.zip)

**Comment by tdlivings** [comment]
Looking for temp dir
temp dir /tmp/ctivo not found. Creating...
Reported that we created tmpDir /tmp/ctivo
Found temp dir /tmp/ctivo
/tmp/ctivo is confirmed as a directory
You have write permission on /tmp/ctivo.
Test file successfully created
Removed test file

**Comment by mackworth** [comment]
Thank you; I think I know what the problem is then. I'm traveling, but I'll have another test in a couple days.

**Comment by tdlivings** [comment]
Cool

**Comment by mackworth** [comment]
try the 3.0 alpha:  https://github.com/dscottbuch/cTiVo/releases/tag/3.0alpha1   I changed one thing that might fix the tmp issue.

**Comment by tdlivings** [comment]
Success

**Comment by tdlivings** [comment]
Single window opens, file added to queue, download starts, ctivo created in tmp. 

I wanted to send you the log file but none was created under verbose.

Nice addition of the artwork

**Comment by mackworth** [comment]
Ok, very glad to hear on the tmp fix working, but I literally hadn't looked at the double window issue, so that's just a bonus. 

But now...no log file?? Really?

Thank you on the artwork. My OCD got a little carried away on providing the various options, and making all the combinations work.

**Comment by tdlivings** [comment]
I did not see a time stamped log file that reflected today’s date. Last one was 9/5. Is it possible it just updated an existing files?

**Comment by tdlivings** [comment]
Just a side note: I verified ctivo did not exist before the download, so the fix added it as it was designed.

**Comment by mackworth** [comment]
Great, and yes, it reuses logs until it exceeds 10M, so that is fine. (Might want to turn down Verbose to at least Major. )

Let me know if you see any other issues!

**Comment by jeffsep** [comment]
Tried the 3.0 alpha and everything works great so far and I like the UI tweaks. Thanks for fixing it so quickly! Will let you know if I run into any more issues.

**Comment by mackworth** [comment]
Great! Thanks for letting me know.

**Comment by jeffsep** [comment]
Doh! It's still double windowing. Just a heads up.

**Comment by mackworth** [comment]
Ah, too bad, but not surprising. 

So when you close one, does everything still work?  Can you send me any Console entries during the opening?  (Not the ctivo log, the main system log, as it may have relevant error msgs)

**Comment by jeffsep** [comment]
Everything still works, just a bit of a nuisance. I first noticed it when I had a Safari window on top of the cTiVo window and clicked the cTiVO icon in the dock to bring it to the top. Hope this helps.

[system.log.zip](https://github.com/dscottbuch/cTiVo/files/1288188/system.log.zip)

**Comment by mackworth** [comment]
So, I'm beginning to look at some possibilities on the double window. Can you set Logging to Detail, exit ctivo, restart it and then send me the log?

**Comment by mackworth** [comment]
Actually, I found one possibility. Try this version:  https://www.dropbox.com/s/51a5hf411gjo2qz/cTiVo3.0a3-0.zip?dl=0

**Comment by jeffsep** [comment]
Just downloaded the new version (3.0a3) and so far in initial testing it no longer has the double window issue. I will continue to use it and report back.

**Comment by mackworth** [comment]
Good to hear. I found a path that the initializing window code could be run twice. “Shouldn’t” happen, and I don’t know why High Sierra triggered it, but good that it may have worked.  Let me know if it reoccurs. 

I’ll be releasing the next version soon, which will include this.

**Comment by mackworth** [comment]
Can you try dragging things around?  E.g. A show onto the download table, and changing the download order w/ drag/drop?  Does it crash?
