### ISSUE TITLE
mp4 files won't play in quickTime

### ISSUE THREAD

**Issue by tivotravel** [dscottbuch/cTiVo#263]
I just downloaded cTiVo and transferred a couple of programs from my tivo to mac (as .mp4 files).  But the quickTime player can not OPEN the mp4 files.  Any insight will be appreciated!

**Comment by mackworth** [comment]
Which Format did you use?
When you do a Get Info (Cmd-I) in the Finder, what does it say about the files?

**Comment by tivotravel** [comment]
Thanks so much for your response. Just fyi, I am not as familiar with
computer as most of the members here.  I use cTivo downloaded a few shows
from Tivo Roamio to MacBook air.  But those shows,* in .mp4 format*, won't
play in quickTime.  So I searched and came across this forum.  But after
having left the question/message here, I learned about using "handbrake"
app to convert the problematic .mp4 to the mp4 that would play in Quick
Time.  The funny thing was, after I converted the first show, it worked and
played as it should, and then all the following downloaded cTivo files
seemed to be fixed without me having to convert them.  I don't know why,
but I consider the problem is solved.  Don't know if I've answered you
properly, but thanks again!

**Comment by mackworth** [comment]
No problem, and sorry for a rather short response before, I was responding from my phone.

So the Format determines what process the file goes through after it's downloaded.  It's the pulldown in the upper right.  In particular, if you use Decrypt MP4, you'll run into problems like you had. If you use the Default one, that should be fine.    The GetInfo command in the finder will give us some clues about what's actually nside the file.

Glad to hear it's working, and don't hesitate to ask if you have any further problem!
