### ISSUE TITLE
cTiVo not seeing TiVo

### ISSUE THREAD

**Issue by puddle1** [dscottbuch/cTiVo#266]
I've been searching for an answer for this, but can't find one. I think I need someone to help me decipher the log.

I have 2 Premeires. I am using cTiVo 2.5.1 on my mac (10.12.6). Only in the last month did I have trouble. cTiVo sees my FamilyRoom unit both via Local Network and Manual. It can also download shows. That unit is on wireless.

The Bedroom unit cannot be detected by cTiVo. It is seen on Bonjour Browser. It has a static IP and is wired. I see it under Attached devices in my router page with the correct MAC address. I can ping the IP successfully in Terminal. I cannot access the URL (whereas the family room unit I can) in my browser. 

Also, the TiVo shows the appropriate IP address, and has successfully connected to TiVo servers. It also show the Family Room TiVo and my Mac (tivo desktop) in the Now Playing list.

**Comment by mackworth** [comment]
Sure, but you'll need to post the log (Help>view in Finder; then Compress in Finder). Also, what do you see in the Edit>Edit TiVo list?

I assume you're not running Tivo desktop at the same time as CTivo.

**Comment by puddle1** [comment]
The TiVo list shows the 2 units which I entered in Manual. Both are checked. The Local only show the Family Room unit. nothing is checked in local.

I am running TiVo desktop  at the same time. Always have been without issue.

I will note that the Bedroom unit is new in that I inherited it. The MAK is the same, and sharing is checked for the tivo in my tivo account.
[com.cTiVo.cTiVo 2017-09-05 05-33.log.zip](https://github.com/dscottbuch/cTiVo/files/1279481/com.cTiVo.cTiVo.2017-09-05.05-33.log.zip)

**Comment by mackworth** [comment]
It's seeing the bedroom unit, but showing timeouts on trying to get the show list. If you haven't rebooted your TiVo, that would be the next step

You might also try disabling the manual ones and letting it find them. If it doesn't, that would be a clue. 

Also, what's Cosette?

**Comment by puddle1** [comment]
I have tried disabling manual, and deleting the local. The Family Room unit does show up again in local.

Cosette is my Mac.

I have rebooted the tiVo before. I'll do it again.

For what it's worth, I have no problem using the TiVo app on my phone to access the bedroom TiVo.

**Comment by mackworth** [comment]
Okay, then...
1) get your Media Access Key (MAK), e.g from Edit>Edit Tivos in the  Media Key column 
2) Quit cTivo and Desktop and try the following link:
https://192.168.1.13:443/TiVoConnect?Command=QueryContainer&Container=%252FNowPlaying&Recurse=Yes&AnchorOffset=0&ItemCount=15

Accept the certificate warning, and then username is "tivo" (without quotes), and password is your MAK
You should see something like
> <TiVoContainer xmlns="http://www.tivo.com/developer/calypso-protocol-1.6/">
> <Details>
> <ContentType>x-tivo-container/tivo-videos</ContentType>
> <SourceFormat>x-tivo-container/tivo-dvr</SourceFormat>
> <Title>Now Playing</Title>
> <LastChangeDate>0x59AF64FE</LastChangeDate>
> <TotalItems>1140</TotalItems>
> <UniqueId>/NowPlaying</UniqueId>
> </Details>
> <SortOrder>Type,CaptureDate</SortOrder>
> <GlobalSort>Yes</GlobalSort>
> <ItemStart>0</ItemStart>
> <ItemCount>15</ItemCount>
and then pages of text, maybe formatted as an outline, maybe just straight text.

Let me know if that's what you get, and if you see the 0 and 15 at the bottom two lines there.

Ah, just re-read your previous notes. Is that what you meant by the URL not working?  

If so, there's definitely some sort of network problem. Are you running an antivirus program?  They hate the Tivos self-signed certificates, so you need to whitelist it.

On the other hand, if the URL you used had text in the host part (versus the 192.168.1.13) and it failed, but this one worked, then you have a DNS problem on the network.  As it's a decentralized name service, to fix you might need to bring the whole network down (router, switch, mac, IOS) and back up again.  

If neither work, then there's probably something weird in the physical layer, maybe a bad cable?

**Comment by puddle1** [comment]
The link shows the text as you said, only it's 0 and 14 (i assume because there are only 14 shows on the TiVo currently?)

And now the 192.168.1.13 works in my browser. (it's been whitelisted already). I have no antivirus, just a firewall which is still running. 
It still works even with both cTiVo and TiVo desktop running...
And now shows are listed in cTiVo from the bedroom unit.

the Bedroom unit doesn't show up in the local network in cTiVo, still. It is listed in the Manual section.

Perhaps the reboot of the TiVo worked? 
I don't understand what happened or why it's actually working again...

**Comment by mackworth** [comment]
One possibility is that the TiVo is somewhat sensitive to overloads, and different parts can crash without affecting the others. So with both TiVo Desktop and cTiVo running, it may have overloaded the XML server, which would be fixed by a reboot.

On why it's not appearing in the local tivos, I think I check if an appearing TiVo is already listed, so the manual listing may be blocking the local one (but disabling it may add it for future versions...). Or not, I haven't checked the code there for a while.

So assuming you're good for now, I'll close this.  Let me now if  you have any other trouble.
