### ISSUE TITLE
Cannot download any TiVo shows

### ISSUE THREAD

**Issue by EurovisionGS** [dscottbuch/cTiVo#267]
I have the latest version of cTivo, running MacOS SIerra 10.12.6
The TiVo is visible in Bonjour as well, restarted TiVo several times, and keep getting the "Failed" popup after about a minute of each attempt before any download starts.
Any ideas?

**Comment by mackworth** [comment]
Yup, so this is a known problem with High Sierra: #262 .  As a workaround, you can create a temporary directory outside of /tmp/ctivo using Advanced Preferences in cTivo (Cmd-Opt-Comma), or you can try the new alpha of 3.0!
