### ISSUE TITLE
High Sierra Crash when Dragging content from top to download

### ISSUE THREAD

**Issue by tdlivings** [dscottbuch/cTiVo#269]
App Crash when Dragging content from top to download
[cTivo Crash.docx](https://github.com/dscottbuch/cTiVo/files/1333870/cTivo.Crash.docx)

**Comment by tdlivings** [comment]
Sorry, I have been offline, tested the drag and it is crashing as you suspected. I am not sure how much use I will be, I travel 6 days a week usually.

**Comment by mackworth** [comment]
No problem at all (on being "offline" as opposed to the dragging problem); I saw some crash reports that suggested this was a problem, but no one reported it here.  

Before I post an update, can you give a quick try of this one? (version marked as 3.0a4 (771)  If you're out and about, just let me know!
https://www.dropbox.com/s/e36lch2to9mukwe/cTiVo3.0a4%28Drag%20test%29.zip?dl=0

**Comment by mackworth** [comment]
Okay, that should be fixed in alpha 4. Let me know otherwise.
