### ISSUE TITLE
Right click- remove from queue does nothing.

### ISSUE THREAD

**Issue by tdlivings** [dscottbuch/cTiVo#270]
Right click- remove from queue does nothing. But, the button still works.
And, yes the drag and drop works fine now.

**Comment by mackworth** [comment]
And you expected it to do something?

Quite rightly too.  I see that I renamed it in one place and not the other.  Now fixed for next release. 

Thanks for reporting it!

**Comment by tdlivings** [comment]
Sorry. I will stop now......

**Comment by mackworth** [comment]
Just in case you're NOT kidding, let me be overly clear that I really do appreciate the feedback.  

It offendeth me to have any bug out there, no matter how small, so I want to know about it.

**Comment by tdlivings** [comment]
It is all good. As much as I travel, your program is a life saver. I appreciate it immensely. 

I too have OCD.
