### ISSUE TITLE
Version 3.0 alpha4 (772) does not download (OSX High Sierra)

### ISSUE THREAD

**Issue by tigeralum2001** [dscottbuch/cTiVo#271]
Perhaps I jumped the gun, but I upgraded to High Sierra and I have and nothing but trouble.  I uninstalled and reinstalled to Version 3.0 alpha4 (772).  It finds my Tivos, but will not download anything.  I've tried right click to download, drag & drop to download.  Nothing seems to work.  What do you recommend I submit to help troubleshoot?  My defaults are Default resolution, skip commercials, and export .srt file.

**Comment by mackworth** [comment]
If you go to Help>Show Log Files, and find the most recent log file and post it here, that'll be a good start!

So it does create the entry in the  Download queue, but nothing happens, or you get an error message, or ?

**Comment by tigeralum2001** [comment]
[com.cTiVo.cTiVo 2017-10-03 02-48.log](https://github.com/dscottbuch/cTiVo/files/1353781/com.cTiVo.cTiVo.2017-10-03.02-48.log)

I've attached the log showing it has failed for multiple shows.  Most of my files have the yellow dot with exclamation point.  So I went in and adjusted the settings to only manually delete the one's I'd like to download.  The dots turned green, but they still fail.  

It does create an entry in the Dowload queue, then I get several errors in Growl in rapid sequence, then it tells me the download failed.

Thanks

**Comment by mackworth** [comment]
So are you running Antivirus software? If so, you have to "whitelist" the TiVo as an exception.

Alternatively, I note that it's retrying the TiVo too soon (instantly versus waiting a minute after a failure). If you could set the log for Detail and try again, that should tell me why it's doing that.  After you do that, then restarting the TiVo may work.

**Comment by tigeralum2001** [comment]
Thank you!  I forgot I put an antivirus on my Mac. (Never used one for over a decade, but added one recently.)  I'll work on the whitelist, but disabling it made everything work right.

**Comment by mackworth** [comment]
glad to hear. I've added the error code you got to my antivirus warning list for next release.
