### ISSUE TITLE
Contents of TiVo not displayed

### ISSUE THREAD

**Issue by emmayche** [dscottbuch/cTiVo#274]
I was on 2.4.2 with the issue that cTiVo would not display the contents of my TiVo. Upgrading to 3.0a5 did not solve this problem. Is there a way to rebuild/repair/replace the database to solve this problem, or does it have another possible origin?

**Comment by mackworth** [comment]
Well, it's really good to upgrade, and I'm sorry that the auto-upgrade broke in 2.4.2
Are you on High Sierra?
Does it "see" the TiVo (e.g. put the name at the top of the screen) and just not list files, or does it not see it at all?

Can you post the most recent log (Help>Show Logs in Finder) and attach to an entry here.

**Comment by mackworth** [comment]
Just checking if you've had a chance to do the logging?

**Comment by emmayche** [comment]
Hi Hugh,

No, sorry, things around my house have been in something of an uproar recently. Will let you know soon; thanks for your patience.

**Comment by mackworth** [comment]
No problem, but I’m gonna close this for now. Let me know if the newest release fixes your issue or if there’s still an issue, just post the log and reopen it
