### ISSUE TITLE
Tivo not found

### ISSUE THREAD

**Issue by rtteachr** [dscottbuch/cTiVo#275]
Just tried the latest alpha and it doesn't find my Tivo Bolt. I used the command-option-shift fix for 2.5.1 and able to download using the old version for now.

**Comment by mackworth** [comment]
Sorry (and somewhat surprised) to hear that!

 Can you run 3.0 again with control-option keys held down during startup, let it run for a minutes, and then find the latest log (Help>show logs in finder) and post it here?  That should help me figure out what’s changed.

**Comment by rtteachr** [comment]
I might have figured it out. I removed the Tivo and readded it and it found the Tivo. However, I am unable to add it to the local network panel because the “+” button is not there anymore. Just the “-“ button. I seem the keep have to do that in order to have the Tivo seen. I will post logs shortly.

**Comment by mackworth** [comment]
The local panel is only for automatically found TiVos, so delete is the only option.

**Comment by rtteachr** [comment]
So I get nothing in the local panel. Have to uncheck and check the Tivo in the ip address panel each time app is opened to see content on Tivo.

**Comment by mackworth** [comment]
So, before then, it doesn’t appear in the upper left corner, or it does but no shows appear?  If the latter, does Cmd-R cause the shows to load?  Either way, can you post the Verbose logs to see what’s happening?

Also, how did it get in the IP section (Manual TiVo, right?) in the first place?

**Comment by rtteachr** [comment]
Top left just shows searching no Tivo until I uncheck and check the box in settings. I entered the IP address info manually.

Will post logs when I’m at computer. They don’t share media key or up address info do they?

**Comment by mackworth** [comment]
>  don’t share media key or up address info do they?

Media key, no; but might have the IP address. 
>

**Comment by mackworth** [comment]
If that's an issue for you, you can either edit out (just use Text Edit) or email to me at mackworth at aol dot com

**Comment by rtteachr** [comment]
That’s what I was planning on. I actually did it and forgot to send. I will send later today.

**Comment by rtteachr** [comment]
Just sent to AOL address

**Comment by mackworth** [comment]
So there's two different problems here, I believe.  

First, we're not seeing any Bonjour notifications for TiVo devices in either 2.5.1 or 3.0.  Most obvious reason that would be the case is if your network were subdivided by a router or other device. Presumably you'd know if something like that were going on.
Can you run [Bonjour Browser](http://www.tildesoft.com/files/BonjourBrowser.dmg) and see if they show up?
I know you took out the IP addresses, but were they local NAT addresses (192.168.xx or 10.0.x.x) or open internet?

Second, the lack of any Bonjour notifications is leading to not loading the manually defined ones. I think this is a bug in 3.0 and I think I know where it is.

**Comment by rtteachr** [comment]
The Tivo is not showing up on the Bonjour Browser. Network is not subdivided. IP address is local.

I don’t think the TIVO showed up when I set up CITO 2.51, but it was there via iP and bonjour when I checked the settings to set up 3.0.

Thanks!

**Comment by mackworth** [comment]
Fixed in Beta.
