### ISSUE TITLE
3.0 Beta Release

### ISSUE THREAD

**Issue by mackworth** [dscottbuch/cTiVo#277]
Please use this issue for any comments or suggestions on the beta release.

**Comment by mackworth** [comment]
The beta release broke a couple of things.  There's a beta 2 release available.

**Comment by mackworth** [comment]
And now beta3. Documentation updated on wiki. 
 Looking very solid; final release soon unless I hear otherwise.

**Comment by KevDoc** [comment]
I’m using beta 3 on a 2012 mac mini with the latest version of High Sierra installed. Since upgrading to High Sierra and subsequently to ctivo 3.0beta3 I’m getting macro blocking when decrypting programs from one channel (bien sports). Any ideas / suggestions?

**Comment by mackworth** [comment]
So, that's very interesting.  A channel is added to that list when cTiVo believes it requires Transport Stream([more background here](https://github.com/dscottbuch/cTiVo/wiki/Advanced-Topics#edit-channels). It decides that when it sees a program without a video stream embedded (a characteristic failure for H.264-encoded video being transport over Program Stream) and so it tries again with Transport Stream.

So, it's odd that only one channel would be converted. I would check on your TiVo in the Signal Strength diagnostic for this channel. You may simply be getting a weak signal, which might give both a problem for Program Stream and a poor video for Transport Stream. 

If not,which encoder are you using? If you're using TiVo Decrypt, for this channel, I'd recommend MP4 Decrypt, which wraps it in an MP4 file instead. Secondly, try Default, which will actually convert the file.   If neither help, then delete the channel from Edit>Edit Channels, set the Log to Major, and run the show again, so that I can see the log from the Program Stream failure.

Also you should upgrade to RC2!

**Comment by mackworth** [comment]
As mentioned above, we now ar eup to RC2, and folks should definitely upgrade. (RC1 folks really needn't bother, but everyone else should.)

**Comment by KevDoc** [comment]
Thanks for the help, I’ll play around and post back my findings.

**Comment by mackworth** [comment]
Oh, one other possibility, if it does need TS, you could try switching to TivoLibre for decryption in Advanced Preferences (assuming you have or are willing to install Java). Haven’t seen much difference, but it’s possible.

**Comment by KevDoc** [comment]
Ok good news, simply removing that channel from that list seems to have worked! I’ll now try a second transfer to be 100% sure.

**Comment by mackworth** [comment]
Good to hear. My guess is you had a bad recording and it triggered the TS comment. If it happens again, send me the log; I’d be very interested.

**Comment by mackworth** [comment]
And 3.0 is released.
