### ISSUE TITLE
Transfer is too Short

### ISSUE THREAD

**Issue by tdlivings** [dscottbuch/cTiVo#280]
I am getting a message "Warning: Show may be damage/incomplete.", Transfer too short
[com.cTiVo.cTiVo 2017-11-04 03-55.log](https://github.com/dscottbuch/cTiVo/files/1443625/com.cTiVo.cTiVo.2017-11-04.03-55.log)

Probably nothing because the show seems to be editable and watchable.

**Comment by mackworth** [comment]
So, that's not particularly strange. Tivo only estimates the actual file size for some reason, usually high. We give that warning when actual file size is below an arbitrary 80%, so maybe it happened to be slightly lower than that. 

The odd thing is actually the prior stuff; It shows that it doesn't have a tmp directory, but then it launches the download anyways, suggesting that it successfully created the directory.  It should have created it before the download started.  

Could you do a test?  
Set cTiVo to Major logging, 
Quit. 
In Finder, Go To Folder (Cmd-Shift G) `/tmp`
move `/tmp/cTiVo` to the trash
Run cTiVo
see if it automatically creates the `/tmp/ctivo` folder again
Run same download again 
Send me the log. 

(It'll also confirm that it's just below 80%)

**Comment by tdlivings** [comment]
Yes it recreated ctivo and here is the log.

**Comment by mackworth** [comment]
I think it strips off the log in emails; have to post on site.

**Comment by tdlivings** [comment]
[com.cTiVo.cTiVo 2017-11-04 23-19.log](https://github.com/dscottbuch/cTiVo/files/1443650/com.cTiVo.cTiVo.2017-11-04.23-19.log)

**Comment by mackworth** [comment]
So, yes, it finishes at 70%, a surprisingly low number, but maybe due to being a black and white 480i show.

When it starts downloading, does it create six files like  `decryptPerry Mason-The Case of the Meddling Medium.txt` in the tmp directory?
It's saying it can't create them, which is very strange, and yet the download is working, which it shouldn't without those files.

**Comment by tdlivings** [comment]
It does not create any files at all for this one. If I do a larger 1920*1080 it does create several files. This is the same show that mysteriously change to TS on on TiVo box. I changed it back and now all it well again. No worries. I did not want to kill your Saturday.

**Comment by mackworth** [comment]
Ok, let me know if you further issues..
