### ISSUE TITLE
OS volume still used for download step even if target folder is on external volume

### ISSUE THREAD

**Issue by briancline** [dscottbuch/cTiVo#282]
If I tell cTivo to download shows to an external disk, it will do so, but only after the download phase. It still uses `/tmp/ctivo` on my OS volume regardless, where space is pretty thin.

I manually symlinked /tmp/ctivo to a folder on my external disk to get around this for now, but it would be great if cTivo picked a temp folder on the same volume as the target folder.

**Comment by mackworth** [comment]
If you go to Advanced Preferences (Cmd-Opt-Comma), then you can set your temporary folder to be anywhere you like!  [More info here](https://github.com/dscottbuch/cTiVo/wiki/Advanced-Topics#advanced-settings)

**Comment by briancline** [comment]
Huh, I never knew those were there. Good to know. Might you consider just making that tab visible in the normal options? Some of those are extremely useful.

**Comment by mackworth** [comment]
I’ve debated (mostly with myself) back and forth. There are several things in there that can really blow things up (“Don’t delete temp files” most obviously) or are quite complex (file name templates), so for my support sanity, it’s good to have them a bit hidden. 

The Plex one is one I need to promote to the main preferences, as many people need that.

**Comment by mackworth** [comment]
Oh, if you like things on the edge, note that comments on the bottom of that page about Terminal-only options.

**Comment by briancline** [comment]
I definitely appreciate trying to prevent footgun syndrome. To be fair, as an advanced user (or so I thought!) I still shot myself in the foot not knowing that was configurable 😄 Same on file name templates -- I'd written up a separate script a while back to rename mine for me based on the metadata text files. After a few months of use I just figured both were just a limitation.

One concern on the original issue, though -- if I change my download folder, and there's no parity with the temp folder and no indication in the UI outside of the hidden preferences that it's still going to use storage elsewhere, it's easy for folks to miss that they need to keep an eye on usage/etc. for potentially two separate volumes.

**Comment by briancline** [comment]
Is there a better way to provide this feedback?

**Comment by mackworth** [comment]
Not really, as I am reading it!

 I think you're right; I'll add a warning line and make Adv Pref visible.
