### ISSUE TITLE
New TiVo Experience  (Hydra)

### ISSUE THREAD

**Issue by morrisjosephd** [dscottbuch/cTiVo#285]
Codename Hydra.  

Will I loose the ability to use cTivo on my Bolt if I upgrade my device to the latest UI.

This project is too valuable to me to loose its functionality to an UI upgrade.

Thoughts?

**Comment by mackworth** [comment]
I haven’t installed personally, but no problems have been reported on cTiVo or other programs relying on file transfer FROM TiVo.

TiVo does say that the reverse is not yet supported (e.g. PyTivo sending files back TO TiVo).
