### ISSUE TITLE
Resizing artwork column messes heavily with table rows

### ISSUE THREAD

**Issue by briancline** [dscottbuch/cTiVo#288]
In v3.0.1, when resizing the artwork column to make it smaller, there seems to be a disparity in the rows that are already visible -- they do not get redrawn properly, though it is clear their metrics are updated (so as a result, clicking on one row might select another). The rows that weren't in view **do** get drawn correctly when scrolling into view, though.

Similarly, if I scroll to the bottom of the view afterwards, there's also a lot of dead space (whose height I assume is roughly equal to the sum of all superfluous vertical pixels on rows that were not redrawn).

**Comment by mackworth** [comment]
Indeed it does.  Sigh, that was working well earlier in the release, and now it's clearly broken.  Will fix.

**Comment by mackworth** [comment]
Okay, this should be all better in 3.1.0 beta 1 
Let me know if you find otherwise.

**Comment by hbankstoo** [comment]
HI,

Wondering whether anyone else has raised this issue? In 3.1 or later, will there be any way to get back the compact row spacing from previous formats? (See attached screenshots). 

For example, if there were a way, in preferences for example, to eliminate the "Art" column, might that restore the earlier row heights?

Thanks in advance.


![ctivo 2 5 1](https://user-images.githubusercontent.com/24724309/35187488-79720828-fdf2-11e7-8c0b-e3e8e4a323d9.png)
![ctivo 3 1](https://user-images.githubusercontent.com/24724309/35187489-799fe02c-fdf2-11e7-9bd4-44d529f2435a.png)

**Comment by mackworth** [comment]
I'm not quite clear here. There definitely was an issue in 3.0.1, but it should be better in 3.1.0. If not, let me know.

You should be able to adjust the height of the row simply by adjusting the width of the Art column (which shrinks the height proportionately). 

Also, like most Mac apps, you can hide/show the Art column (or any column) by option-clicking in the column headers

**Comment by hbankstoo** [comment]
Brilliant! Getting rid of the Art column did it!

Thanks from my not very savvy self.

Hannah

**Comment by mackworth** [comment]
No problem. Some of these things are only  obvious when you know they exist!

Note you can make the Art column small enough to keep the same spacing.
