### ISSUE TITLE
"Create sub-folder per series" no longer works

### ISSUE THREAD

**Issue by Fofer** [dscottbuch/cTiVo#291]
I just updated to v3.0.1 (from 2.5.1) and noticed that the "Create sub-folder per series" menu item no longer does anything.

**Comment by mackworth** [comment]
Just tried it; works fine for me.  
So, it's putting all your shows at the top level of your download directory?  What's it set to?
Do you have the Adv Preferences (Cmd-Opt-Comma) `Filename Template` configured?

**Comment by Fofer** [comment]
Oops, sorry, I was confused. I thought the "sub-folder per series" was referring to how the shows appear in the main cTiVo window, not in the resulting download directory.  Considering it's placed in the menu right next to "Show Protected Shows" and "Show TiVo Suggestions," that seemed like the intuitive assumption to make.

Anyway, please consider this a feature request, to be able to group episodes together by series name, in collapsable folders.  That would make it a lot easier to browse through, especially on TiVo's with lots and lots of recordings.

Cheers and happy holidays!  Thanks for making this excellent software.

**Comment by mackworth** [comment]
Thanks for the suggestion; I keep meaning to get around to that!

**Comment by mackworth** [comment]
Well, after a couple of days of coding, there you go:

3.1.0 beta 1 release now includes Folder support (and reworded options).
Let  me know what you think.
