### ISSUE TITLE
Retrieve TiVo's show embedded commercial skip timing for com skipping

### ISSUE THREAD

**Issue by Neosocra** [dscottbuch/cTiVo#293]
Add ability to utilize the newer TiVo's natural commercial skipping information (see kmttg for example) instead of running comskip for detection to cut commercials out before running the encoder

**Comment by mackworth** [comment]
I've looked at this before. I'd love to, but it's not easy as it sounds. TiVo doesn't publish the actual points on your local TiVo, only generically for a given show across all TiVos. Kevin did some impressive work here to locate the actual cut points. Even to follow his path here, I'd have to implement the full remote control suite as well as communicate with the central TiVo infrastructure, (requiring the user's TiVo password). It also disrupts the current show viewing, so there would need to be a whole separate off-hours scheduling mechanism.

I'll keep it on the list, but wouldn't expect it any time soon.
