### ISSUE TITLE
‘Prevent Sleep’ not working?

### ISSUE THREAD

**Issue by bg3dev** [dscottbuch/cTiVo#298]
I’ve got the “prevent sleep” setting set in cTivo preferences, but checking the Energy tab of Activity Monitor, cTivo is listed as “No” under the preventing sleep header (even though it’s currently downloading and encoding shows) . Checking "pmset -g assertions” in Terminal also doesn’t list cTivo as any kind of sleep prevention process. I’m on macOS 10.13.2.

**Comment by mackworth** [comment]
So, is it actually going to sleep while downloading?

Haven’t checked it out yet, but I do know we use an older technique for preventing sleep which may not register the same.

**Comment by mackworth** [comment]
I think that's the reason. The older technique is that when the sleep timer goes off, the OS asked "Can we go to sleep", and cTiVo replies "Not now, thank you". The newer one is the app preemptively says "I'm about to start a long process and don't want to go to sleep during it". Thus pmset/Activity Monitor would know that it can't go to sleep now without having to ask.

So, assuming you're not seeing it fail, the only symptom is the pmset/Activity Monitor messages?

**Comment by bg3dev** [comment]
I’ve had some miscellaneous failures during scheduled downloads. I theorized maybe the machine was sleeping and disconnecting during the process. But, I haven’t watched it when the sleep timer fired to make sure yet. The other question I had about the pref was that I wasn’t sure if this was to prevent sleep at all times, or only to prevent sleep while downloading / encoding.

**Comment by mackworth** [comment]
No, it should only prevent sleep if it has work to do. 

Note that there is around a surprisingly high 5% failure rate overall, mostly due to digital glitches in files that the TiVo can't send over properly, or that ffmpeg chokes on. That's after the automatic retries, which recover about 5% of shows. (so ~90% on first try, 5% on retries, and 5% fail).

Let me know if you see anything different!
