### ISSUE TITLE
Using HandBrake to encode

### ISSUE THREAD

**Issue by rqchin** [dscottbuch/cTiVo#300]
When using HandBrake to encode (transcode?) a show, is there a way to control the number of encoding sessions that cTivo allows HandBrake to perform? Currently it appears to allow 2 simultaneous encoding sessions, which seems to keep my CPU too maxed out for any other tasks. Alternatively, is there a way to limit/cap the maximum CPU utilization the HandBrake sessions can consume?

**Comment by mackworth** [comment]
okay, let me know how it goes.  You might try ffmpeg as well.  Note that upscaling all shows to 1080p may not be productive; have you tried Default?

**Comment by rqchin** [comment]
Using 1 thread has improved responsiveness greatly (limiting MaxNumberEncoders to 1) and while I don't have hard numbers on this yet, it seems like overall throughput has increased. I have not tried Default yet - does that maintain the size/resolution they were recorded at and adjust per recording? That probably would be better.

**Comment by mackworth** [comment]
Glad to hear.  Yes, IIRC, Default passes through the file without rescaling.
