### ISSUE TITLE
Shows not ending up in the proper subfolders

### ISSUE THREAD

**Issue by mrfusiontm** [dscottbuch/cTiVo#303]
I've noticed with this most recent update that when cTiVo copies TV shows over, they stay in the main download directory and no longer get filed into their appropriate show subdirectory.  See attached image.
I've also included the log from that time period.  Let me know if you need any other information.

![screen shot 2018-02-02 at 5 08 30 am](https://user-images.githubusercontent.com/6153579/35734906-a2a35c26-07d7-11e8-8f4e-e6e78b641f31.png)
[com.cTiVo.cTiVo 2018-02-01 12-58.log](https://github.com/dscottbuch/cTiVo/files/1689462/com.cTiVo.cTiVo.2018-02-01.12-58.log)

**Comment by mackworth** [comment]
So, I did make a major change here, but it should have ported your Preferences to the new structure.

What does it show in Preferences under `Save Shows`? If it says `In Download Dir`, just change to `In Series Folders` and you should be good.  (If it says `Custom (Adv Prefs)`, then go to Advanced Preferences, and see what it says for `Filename Template`.

**Comment by mrfusiontm** [comment]
Thanks, I'll give that a look when I get home.

Not sure if you hear this enough, but thank you for creating, maintaining
and improving this program.

Tom

**Comment by mrfusiontm** [comment]
That solved the problem.  Thanks, you can close this out.

**Comment by mackworth** [comment]
Great to hear, and thanks for the nice thanks!  I do mostly hear from people when it doesn’t work!

**Comment by mrfusiontm** [comment]
I've offered to pay for this program before and you've always refused, but
is there a charity that you support?

**Comment by mackworth** [comment]
Thanks, but really no need for that; just pay it forward elsewhere!
