### ISSUE TITLE
Thank You

### ISSUE THREAD

**Issue by WhyAkron** [dscottbuch/cTiVo#306]
Thank you for the time you previously took to help me with various issues.
Unfortunately, I won't be using cTiVo any more. Time Warner/Spectrum in Akron is now protecting EVERYTHING. Used to be almost everything except broadcast channels, but now even those are protected. It started in December when they changed to "all digital." 
Does anyone know if they are allowed or required to do that (protect everything)?

**Comment by mackworth** [comment]
It's [just a bit](https://en.wikipedia.org/wiki/Copy_Control_Information) they can set in their digital stream. There's absolutely no reason for them to do so, but so few people actually do copy anything that they can do it with impunity. 

AFAIK, I believe that means you can't even use a TiVo Mini to view in another room. Instead, TWC wants you to buy a whole-house DVR from them.  They [describe it here](https://www.spectrum.net/support/general/digital-copy-control-tv-programming/), but don't admit that they're adding it where it isn't needed

[Looks to me](https://www.law.cornell.edu/cfr/text/47/76.1904) like they're not allowed to copy protect broadcast tv, whether or not it's delivered encrypted. You can complain to your local tv stations, and/or to the FCC, as they're clearly violating the intent of that bit. Nonetheless, many have tried...  The joys of a poorly regulated monopoly...
