### ISSUE TITLE
HandBrake question

### ISSUE THREAD

**Issue by tdlivings** [dscottbuch/cTiVo#307]
Does handbrake need to be open for the profiles to render the video?

Thank you in advance

**Comment by mackworth** [comment]
Nope, not even installed. (I embed a copy of their command-line version in cTiVo, which is what the default Formats call)

**Comment by tdlivings** [comment]
Oh, Thank you. I was having a problem with the file. I suspect it was because I have encode and transfer at same time checked. It was stuck in a download loop. I unchecked the box and it finished but did not skip commercials even though the detecting ad (com skip) ran. I was just scratching my head.

**Comment by mackworth** [comment]
Correct, encode/transfer won't work with Handbrake (it can only accept a completed file, not an indefinite stream.) Beyond that, happy to assist if you want to post the log and the exported Format.

**Comment by tdlivings** [comment]
can it do com skip though?

**Comment by tdlivings** [comment]
[com.cTiVo.cTiVo 2018-02-15 06-03.log](https://github.com/dscottbuch/cTiVo/files/1728599/com.cTiVo.cTiVo.2018-02-15.06-03.log)

**Comment by mackworth** [comment]
Nope. The command line doesn't accept an EDL (Edit Decision List) to specify which sections to cut out. Without the encoder's help, cTiVo can Mark commercials with the chapter headings, but it can't cut sections out.

**Comment by tdlivings** [comment]
ah, thank you
