### ISSUE TITLE
Cannot delete more than one show at a time

### ISSUE THREAD

**Issue by SpectreGadget** [dscottbuch/cTiVo#308]
If you highlight multiple shows, or a folder of shows and select "Remove from TiVo", only one item will be removed, instead of the expected action of deleting all the selected items.

**Comment by mackworth** [comment]
I believe so, but I still appreciate the effort to let me know. That’s how things get fixed!

**Comment by SpectreGadget** [comment]
I kept meaning to report it, and finally did this morning.  In the process of coming here and reporting it, I saw there was a new beta with some nice features, so I installed it.  I just went back and did a little more testing.  Deleting a 'folder' with grouped items deletes all, but deleting several selected shows still only deletes one.

**Comment by mackworth** [comment]
So, there’s two different delete commands. If you use the contextual one (right-click), it’s supposed to do the one line you’re pointing at, whether or not it’s selected.  The main menu command though,applies to the whole selection. Is that different from what you’re seeing?

**Comment by mackworth** [comment]
So, you are correct; it does incorrectly select the new item (or group) when right-clicking and then only apply to one item. It should either (A) not do that and differentiate between right-click and main-menu or (B) perform the command on the whole selection.  Looking for guidance from Apple's apps, I am amused to find that Finder, Xcode, and Mail do A, but Photos, Safari, iTunes and Notes do B.

**Comment by SpectreGadget** [comment]
I haven't yet found anything quite specific enough, but [here](https://developer.apple.com/macos/human-interface-guidelines/menus/menu-bar-menus/) it talks about Edit menu items and most relate to 'selected data'.  The [page on Contextual Menus](https://developer.apple.com/macos/human-interface-guidelines/menus/contextual-menus/) has this, "Always make contextual menu items available in the menu bar too. A contextual menu is hidden by default and a user might not know it exists, so it should never be the only way to access a command. In particular, avoid using a contextual menu as the only way to access an advanced feature."

**Comment by mackworth** [comment]
So thanks for raising this. I have completely reworked this in the next version. Now, like Mail, when you right-click, if it's anywhere within the current selection, then it applies to the whole current selection; otherwise, cTiVo puts a blue bar around the single item you're pointing to, and will apply only to that item. Either way, it doesn't change the selection. . I'm tracking down a freezing bug, but then I will post an alpha.  I've also added most of the commands to the main menus to allow them to be both more easily discovered and applied to current selection.

**Comment by SpectreGadget** [comment]
Sounds good.  Look forward to trying it out!

**Comment by mackworth** [comment]
I think this is all better in [version 3.2.0.](https://github.com/dscottbuch/cTiVo/releases/tag/3.2.0beta1) Let me know if you agree!
