### ISSUE TITLE
Additional Options box appears to ignore input unless cursor moved off box

### ISSUE THREAD

**Issue by gew95001** [dscottbuch/cTiVo#309]
System: iMac Pro 10 core, High Sierra 10.13.3
Handbrake Version 1.0.7 (2017040900)

I've been trying to limit thread usage using the "threads" option via the Additional Options box. It seemed to work once with the value of '1', but it jumped back to using all cores after I put anything else in the box.
I figured out that I could import a Preset with the value set to what I want and that it worked every time.   That made me think about whether the value I put in when using the OOTB Presets was "saved" for use. If I put "threads=1" (or any value) and leave the cursor at the end and simply hit Start, it is ignored. If I put the value in, then click on the end of the destination file (so that the cursor is blinking there and not in the Additional Options box) then the value is used.

**Comment by mackworth** [comment]
So...is this about cTiVo?

**Comment by gew95001** [comment]
Oh, for crying out loud. I've been researching and testing for cTiVo and Handbrake for a while, and somehow picked here to report it instead of reporting it for Handbrake (where it belongs).

I apologize for the noise - please feel free to mark this report "Submitted by Fool" and close it.

**Comment by mackworth** [comment]
No problem. As I recently added an option for # simultaneous encoders (not threads/encoder), I tried to "map" it to ctivo, but ... couldn't quite do it. Let me know if you find anything interesting...
