### ISSUE TITLE
Is there a way to only download part of TV show?

### ISSUE THREAD

**Issue by burdell1** [dscottbuch/cTiVo#311]
I was trying to get one of the commercial from the Super Bowl and didn't want to download the entire 5 hour TiVo file unless i had to. I assume there isn't a way, but i thought I'd ask

**Comment by mackworth** [comment]
Sorry, no. 

Only approximation would be to interrupt it after enough of the show has transferred. You would use Decrypted TiVo Format, turn on “don’t delete files” in Adv Prefs, and off “use memory buffer”, then after it’s downloaded enough, Pause the queue. Then the partial file could be edited to get the part you want.
