### ISSUE TITLE
Paused?

### ISSUE THREAD

**Issue by mrfusiontm** [dscottbuch/cTiVo#313]
I just rebooted my computer and when cTiVo came back up is has the word "paused" across the download area (even though the download was complete)  Any idea what this means and how do I "unpause" it?

![screen shot 2018-03-31 at 8 30 10 am](https://user-images.githubusercontent.com/6153579/38164762-063cb152-34be-11e8-8bdd-2297330e44e5.png)

**Comment by mackworth** [comment]
That's an easy one. "Paused" means cTiVo is not currently going to launch any new downloads. This can happen automatically in Preferences, where you can specify that it shouldn't process, say, during daylight hours, or manually with the Pause command (Cmd-U). So check your preferences, and if Queue Restricted is Set, turn it off.  If not, just type Cmd-U, and you should be processing again.

See docs on [Pause command here](https://github.com/dscottbuch/cTiVo/wiki/Overview#menu-items) and [Preferences here](https://github.com/dscottbuch/cTiVo/wiki/Configuration#settings-in-preferences-screen)

**Comment by mrfusiontm** [comment]
Great, thank you!  I'd never seen that before.  I did a try doing a search
in the help menu for "paused" and got no results, but when I tested it
again, I saw something come up for "pause".  I guess I wasn't looking at
the menu while I was typing the first time and missed it.

Thanks,
Tom

**Comment by mackworth** [comment]
Glad to hear it!
