### ISSUE TITLE
enhancement - can’t adjust settings during download

### ISSUE THREAD

**Issue by bg3dev** [dscottbuch/cTiVo#314]
Something to consider? When you add a program to queue, if it’s the only thing in queue then you can’t make changes to settings like format, or selecting the skip commercials checkbox. Maybe wait 30 seconds before starting the download (put “waiting” instead of “downloading” as status) so that the user has an opportunity to tweak settings. 

Or, would it be possible to not lock out these settings until the download is completed and the encoding has started?

**Comment by mackworth** [comment]
Not a bad thought; I will consider the delay. 

I should mention Pause (Cmd-U), which will (admittedly manually) accomplish the same thing. Although better before you hit Download, even afterwards you could hit it to cancel the download and make your changes. 

FYI, the latter idea is much harder, as upon start of download, we set up complex pipelines of parallel programs and data flow to make the system work as efficiently as possible.

**Comment by bg3dev** [comment]
If you add this, might make the label "preparing" instead of "waiting". Otherwise the user might ask, "what are you waiting for? is something wrong?"

Probably overthinking this, but figured I'd mention it anyway.
