### ISSUE TITLE
cTiVo hangs when api.thetvdb.com is unavailable

### ISSUE THREAD

**Issue by sarpent** [dscottbuch/cTiVo#315]
cTiVo hangs when api.thetvdb.com is unavailable -- as happens not too infrequently.

**Comment by mackworth** [comment]
True. There’s even a note in the code I left to remind me to fix the problem. It requires some restructuring that I have gotten to.

**Comment by sarpent** [comment]
Can you currently get to that database? I can’t and I’m assuming it’s not just me. This has been going on since last night.

Thanks!

**Comment by mackworth** [comment]
So, it's back up again.  (Of course, just as I finished an emergency patch version without TVDB at all!)
I'll look at handling this failure better.

**Comment by mackworth** [comment]
Should be fixed in 3.1.2
