### ISSUE TITLE
OnDisk Flag

### ISSUE THREAD

**Issue by tannebil** [dscottbuch/cTiVo#317]
I had to reformat my external drive with iTunes on it. I restored from the backup and everything looks good except that the onDisk flag is missing for all the existing programs. Is there a way to force it to rescan?

Even before this, I'd noticed that it sometimes wouldn't be accurate. Hawaii Five-O was a particular problem. Maybe because the typical episode name is full of accented letters, e.g. "Kōpī wale nō i ka i'a a 'eu nō ka i" for the latest episode? As far as I can tell, the name matches in cTiVo, iTunes, and Finder, e.g. "Hawaii Five-0 - S08E22 - Kōpī wale nō i ka i'a a 'eu nō ka ilo. (Though the Fish is Well Salted, the Maggots Crawl.) - 2018-04-27)"

**Comment by mackworth** [comment]
Sorry, no easy way to recover the onDisk markers. For each file, there's three metadata items set: 
* com.apple.metadata:kMDItemFinderComment to cTiVoDownload;  
* TiVoName to the name of your TiVo
* TiVoID to the tivo ID Number.

Matching em up would be hard, as the filename can be any format.
I could write a shell script that would set these for all the mp4s in a directory, but you'd have to manually put in each ID number.

Should not be dependent on file name, as we use the id number to mark which files have it. 
If you do a spotlight search for cTiVoDownload, does the missing file show up in the list?
ps. Why didn't your backup system save the metadata; this should be possible.

**Comment by tannebil** [comment]
I used the Finder to copy the files to another HFS+ volume, restructure and reformat the original HFS+ volume (it’s a Drobo and I changed from 16TB to 64TB although I didn’t add any actual physical space), and then copied them back.

**Comment by mackworth** [comment]
BTW, did you try the spotlight search for cTiVoDownload? Are new shows getting the flag? If not, is the drive excluded from Spotlight indexing?

**Comment by tannebil** [comment]
I had excluded the Drobo and backup drive from Spotlight when I was doing the backup restore and had not included it yet. I was getting OnDisk flags for new shows.

I added the Drobo back to Spotlight and all the OnDisk flags for the new shows disappeared as well. Maybe Spotlight needs more time?

**Comment by tannebil** [comment]
And the OnDisk flags are back for almost all the shows so it looks like Spotlight was the issue. Hawaii Five-O is still inconsistent but I’ll rerun them since I still have them on my TiVo

**Comment by tannebil** [comment]
Rerunning the problem episodes didn’t fix it. Shows with special characters in the title don’t get the OnDisk flag set while all the episodes without special characters in the title show the OnDisk flag, e.g. "O nā hōkū o ka lani wale no kai 'ike i kahi o Pae (Only the Stars of Heaven Know Where Pae Is)” doesn’t show the flag while "Aohe mea make i ka hewa; make no i ka mihi ole (No one has ever died for the mistakes he has made only because he didn't repent)” does show it.

Hawaii Five-O is on tonight (Friday) at 9pm and tonight's episode has special characters in the title.

**Comment by mackworth** [comment]
I’ll check into that. Given that we get the path names through a C API, that seems quite possible. 

I’m recording the episode

**Comment by tannebil** [comment]
As long as you are popping the hood, there is anomaly with the HD flag where some shows that are HD don’t get flagged. The Americans, Full Frontal with Samantha Bee, House Hunters, Property Brothers, Legion,  Orphan Black, and a few others. It's not every episode (that would be too easy). They show up in iTunes with an HD flag (which might be completely unrelated).

i don’t personally use the flag (SD is so 2012) so the accuracy matters not to me but i figure that if you want to have it, you’d want to know if it’s not working right.

**Comment by mackworth** [comment]
So, yes; that was the problem. Thank you for reporting it; it'll be fixed in next rev.  

FYI, unfortunately, existing shows aren't marked, so it won't pick those up. If you want to mark them while you still have the tivoID numbers, then the Terminal commands are:
````
xattr -w TiVoName cTiVoDownload "TIVONAME" "FILEPATH"
xattr -w TiVoID cTiVoDownload TIVOID  "FILEPATH"
xattr -w com.apple.metadata:kMDItemFinderComment cTiVoDownload  "FILEPATH"
xattr -l  "FILEPATH"
````
While it still won't show in current rev, it will be picked up with new rev.

The HD one is like the episode numbers, Looks like Tivo isn't keeping the XML version up to date, so I'll have to switch to the newer RPC for that. One of these days, I'll have to swap to using the RPC as the prime source, but that's a big change.
