### ISSUE TITLE
Cannot move shows from TiVoBolt to MacPro2010 HighSierra10.13.4 using TiVo3.1.2

### ISSUE THREAD

**Issue by tomwickland** [dscottbuch/cTiVo#319]
Hi.
- I’ve used cTiVo for years and love it. 

- Since late Dec 2017, I not been able to move shows from my TiVo Bolt to my Macro (late 2010).
----My Mac is running High Sierra 10.13.4.
----cTiVo is version 3.1.2 
----My TiVo Bolt is running 21.8.1.RC6-USC-11-849
----I been updating everything as soon updates are available hoping things will begin working again.
----FYI: Both my Mac and my TiVo are connected to my home network with Ethernet cable.

- WHAT I OBSERVE: When cTiVo attempts to move a show to my Mac, the "DL" column first displays "Downloading" and then displays "Encoding". It always eventually fails--even though I have retries set to 6.

- WHAT I'VE TRIED:
----uninstalling and reinstalling cTivo
----shutting down and restarting my Mac
----shutting down and restarting my TiVo
----shutting down and restarting my router

- I hate to bother you folks with this, but I really miss being able to move shows to my Mac--and my TiVo is filling up.
- I've searched the web and this forum for a solution, but I’ve been unsuccessful in finding an answer.
- I’d greatly appreciate any help you have to offer.

Thanks.
Tom

**Comment by mackworth** [comment]
Happy to help.  If you could go to Preferences, set Debug Level to Detail, run a show (you can reduce retries to 2 or 3; above that isn’t going to help), then Help>Show logs in finder, and post the most recent log here, (you can then reduce the log level back to Report).  That will tell me what’s going on.

**Comment by mackworth** [comment]
Just checking in if you were able to run that sample log?

**Comment by mackworth** [comment]
Closed due to lack of response. Let me know if I can help!
