### ISSUE TITLE
Reduce encoding process priority

### ISSUE THREAD

**Issue by verticalscience** [dscottbuch/cTiVo#32]
On an i3 mac mini, other applications become sluggish during the encoding process, especially when two encoding processes are running at the same time.  One example of sluggishness is, characters don't echo for 2-3 seconds sometimes when typing in a browser search bar.

A great  enhancement would be to launch encoding processes with a reduced priority using nice.  This would give foreground processes extra cpu time when they need it.

Similar example here:  https://en.wikipedia.org/wiki/Nice_(Unix)

**Comment by mackworth** [comment]
Included in beta release 2.5.0.  Finally!
