### ISSUE TITLE
cTivo 3.1.2 encoding fails and keychain access

### ISSUE THREAD

**Issue by rqchin** [dscottbuch/cTiVo#322]
Occasionally cTivo will fail to encode a show and no matter how many time I try to repeat it, it fails. It seems to have something to do with the encryption key which doesn't make sense since everything else decodes/encodes without an issue. Just lately cTivo occasionally pops up asking for access to something in Keychain but I can't figure out what password it wants and I can't find the item in my Keychain. when I eventually give up and cancel, that show fails. Any idea what it it doing or what I could provide to you for further diagnostics? Other than these particular shows, I probably can't duplicate it at will.

**Comment by mackworth** [comment]
Sorry for delay. It is indeed very odd that it asks for the password only sometimes. 

If you could post the recent logs that would be a good starting point. Just go to Help>Show Logs in finder, then select one (or more) that cover the time period when a failure happened. Then Right click to compress, and post them in a new comment here.

**Comment by mackworth** [comment]
Has the problem been continuing?

**Comment by mackworth** [comment]
closed due to lack of response. Let me know if you still need help.

**Comment by rqchin** [comment]
Sorry, been traveling for six weeks. Will get a chance to try to replicate the problem soon.

Rick


On Jul 29, 2018, at 2:39 PM, Hugh Mackworth <notifications@github.com <mailto:notifications@github.com>> wrote:

closed due to lack of response. Let me know if you still need help.

**Comment by mackworth** [comment]
No proble; let me know.

**Comment by mortgagemetrix** [comment]
This problem has started happening for me today as well. Let me know if I should be looking elsewhere.

![error message](https://user-images.githubusercontent.com/35441071/48813084-2611c000-ecea-11e8-8e7f-ebecb192a126.png)

**Comment by mackworth** [comment]
So, I fixed some things in this area in the current beta, but if you don't want to try that, you might try using the password `password` and see if it gets you through that prompt.

**Comment by mortgagemetrix** [comment]
Using `password` worked. I'm using 3.2.0 beta 2 (build 981 master branch) by the way. I should have posted this on the proper thread. Thank you!
