### ISSUE TITLE
Suggestion: Ability to send Pushover notification (or trigger a script) when download complete

### ISSUE THREAD

**Issue by JoelGit** [dscottbuch/cTiVo#323]
I use Pushover to receive notifications on my iPhone. It has a fairly simple API (https://pushover.net/api). I'd love to see cTiVo get the ability to trigger a script when download is complete that would allow me to send myself a Pushover notification. Thanks for considering!

**Comment by mackworth** [comment]
That sounds like a reasonable idea. So are you comfortable writing the script itself? I would be fine with checking for a script in the user's script directory and then calling it, say, with parameter something like :  success, title, filename, episode, startTime, tivo? (where success = 1 if file is successful, 0, if a failed attempt, or -1 if final failure)

**Comment by mackworth** [comment]
Done in [version 3.2.0.](https://github.com/dscottbuch/cTiVo/releases/tag/3.2.0beta1)  Let me know how it works for you.

**Comment by mackworth** [comment]
Have you had a chance to try it out?
