### ISSUE TITLE
No log file created; specific shows can't be downloaded but not marked protected.

### ISSUE THREAD

**Issue by sfenwick** [dscottbuch/cTiVo#324]
Original problem: Can't download some shows (2 of 77) that are not marked protected. No problems with any other shows. These two may both have been recovered from the deleted shows folder.

Second (bigger) problem is that there is no log file being created in ~/Library or /Library. There is a folder in ~/Library /Application Support called com.cTiVo.cTiVo, but that only has a com.crashlytics folder in that, and only the CLSUserDefaults.plist file in that. Debug level is set to Major.

This is all with cTiVo 3.1.2, running on MacOS 10.9.5. The TiVo is a Series 5.

**Comment by mackworth** [comment]
So, the logs should be in ~/Library/Logs/ctivo , which should open if you do Help>Show logs in finder.

The deleted thing shouldn't matter of course, but in fact, I recently noticed something. Try exiting cTivo and logging back in. It may reconnect the shows.

**Comment by sfenwick** [comment]
Thanks for the quick reply. Tried exiting cTiVo and restarting; no joy. Detailed log attached.

**Comment by mackworth** [comment]
For some reason, Github strips attachments on email, so ... not so detailed!

**Comment by mackworth** [comment]
And when you say "can't download", does that mean it won't let you select, or drag, or hit Download/Add to Queue, or that it fails when download starts?

**Comment by sfenwick** [comment]
Odd--I tried to use the website to attach the log file. Let's try again.

"Can't download" means it fails when the download starts. I have it set to attempt the DL three times, and it never succeeds.
[com.cTiVo.cTiVo 2018-06-24 18-19.log](https://github.com/dscottbuch/cTiVo/files/2131129/com.cTiVo.cTiVo.2018-06-24.18-19.log)

**Comment by mackworth** [comment]
So, tivodecode, which decrypts the video file, is saying Invalid MAK (Media Access Key).  Usually this would be simple: just find your correct MAK, but you’re saying other shows are working. Then it might be a corrupted show, causing a weirdness in the encryption process, but you’ve seen two of them, and usually corruption causes encoding problems, not decryption. 

So, let me double check: that since you got these failures, you’ve run other shows that have worked (on the same TiVo)?

If so, do you happen to have Java installed?  If so, try changing to TivoLibre in Adv Prefs.

**Comment by sfenwick** [comment]
Installing Java 8 Update 171 and turning on TivoLibre caused shows that had downloaded correctly to fail to download, and did not file the broken files. Turning off TivoLibre allowed previously working shows to download, but broken shows still won't download.

Logs attached.
[com.cTiVo.cTiVo 2018-06-24 18-19.log](https://github.com/dscottbuch/cTiVo/files/2131206/com.cTiVo.cTiVo.2018-06-24.18-19.log)

**Comment by mackworth** [comment]
Surprising that ffmpeg is choking on the Tivolibre output.  Maybe try Tivo Decrypt only Format, rather than Decrypt MP4. If that works, could you post the result (somewhere that candle big files)?

**Comment by mackworth** [comment]
Any luck?

**Comment by mackworth** [comment]
closed to lack of response; let me know if you still need help.
