### ISSUE TITLE
cTiVo 3.1.2 Fails Every Time

### ISSUE THREAD

**Issue by nyyjack** [dscottbuch/cTiVo#325]
Since the latest update (I think) programs keep failing to download.

**Comment by mackworth** [comment]
Hi, please post the latest log, so I can see what error you’re getting (Help>Show logs in Finder).

**Comment by nyyjack** [comment]
[com.cTiVo.cTiVo 2018-07-10 12-12.log](https://github.com/dscottbuch/cTiVo/files/2184859/com.cTiVo.cTiVo.2018-07-10.12-12.log)

**Comment by mackworth** [comment]
As that’s almost empty, I’ll need the one before that.

**Comment by nyyjack** [comment]
[com.cTiVo.cTiVo 2018-07-09 05-58.log](https://github.com/dscottbuch/cTiVo/files/2184865/com.cTiVo.cTiVo.2018-07-09.05-58.log)

**Comment by mackworth** [comment]
So that shows the Royal Wedding being downloaded and failing after five hours. How big is that file, and how fast is the transfer going?  Could you try a smaller file?

**Comment by nyyjack** [comment]
I'm not sure of the size but it is HD and run's 10 hours (my wife wanted to see the whole thing; she's not watched much yet). I did try to download a 2:30 movie, School of Rock, not premium channel, got the same results. The last successful download was on July 1, a movie, Twister, which is about 2:30 long. I think that was before the latest update. I'll try to do a regular 1 hour HD show and see what happens.

**Comment by nyyjack** [comment]
This one worked, though it took quite a while. Here is the log so you can compare them:
[com.cTiVo.cTiVo 2018-07-11 12-13.log](https://github.com/dscottbuch/cTiVo/files/2185476/com.cTiVo.cTiVo.2018-07-11.12-13.log)

I'm going to try the movie School of Rock again.

**Comment by nyyjack** [comment]
Question: doe the computer need to stay unlocked once a download begins? As these take awhile I'd like to be able to lock the screen and walk away.

**Comment by mackworth** [comment]
Assuming the Preference (General) to "Disable Sleep during downloads" is enabled, then you should be fine.

**Comment by mackworth** [comment]
Back on the Wedding, assuming it's just the length that's giving you grief, you might try the Format of `Decrypted TiVo Show`, which will avoid doing any conversions at all. This will separate any problems due to glitches within the file from the transfer process itself.

**Comment by mackworth** [comment]
Any luck?

**Comment by mackworth** [comment]
Closed due to lack of response. Let me know if I can help.

**Comment by nyyjack** [comment]
I apologize for not getting back to you sooner. Unfortunately, personal issues kept me busy. With the exception of the Royal Wedding I am able to download everything else downloads correctly. I suppose since it’s a 6 hour HD recording the file may be too large.

**Comment by mackworth** [comment]
No problem. Glad to hear it’s working otherwise!
