### ISSUE TITLE
Suggestion: Ability to subscribe to a Station

### ISSUE THREAD

**Issue by jahavri** [dscottbuch/cTiVo#326]
It is nice to subscribe to shows but it would be nice to be able to download everything captured on a given channel as it completes recording.

**Comment by mackworth** [comment]
Thanks for the suggestion. I’m curious; how would this be of use?

**Comment by jahavri** [comment]
I regularly record movies on a given channel and I download them manually every day or two.  They are all unique so not part of a series which subscriptions are set up for.  I would like to just start cTiVo and have them download as recorded on that channel.

**Comment by mackworth** [comment]
And it's only on that one station that you want to record all shows?  I'll think about how to do this that doesn't introduce more complexity.

**Comment by jahavri** [comment]
Yes, TCMHD.  Good source for commercial-free full length movies.

 

I took a look at the source code and it’s beyond my capability to make the mods.  I greatly appreciate your taking a look at it.

 

Thank you.

**Comment by mackworth** [comment]
Done in version 3.2.0.  Just Right click on SubscriptionTable and add Channel column. Let me know how it works for you.

**Comment by mackworth** [comment]
And 3.2.0 beta is available here:  https://github.com/dscottbuch/cTiVo/releases/tag/3.2.0beta1

**Comment by jahavri** [comment]
Thank you very much—I will check it out.

**Comment by jahavri** [comment]
I tried that but I’m not sure I follow?  Once in the Subscription table the item is still limited to just the title of that movie.  I would have expected it to work such that when I right click on a movie in the top window, there would be an option in addition to “Subscribe to Series” that would be “Subscribe to Channel” that would grab _any_ title from that channel.  Alternatively, if I could wildcard the title in the subscription window to * so any title on the selected channel would be pulled into download when it shows up in the recording list.  Unless I’m missing something?

 

Thank you.

 

Joe

**Comment by mackworth** [comment]
So there's a new column in the Subscription Table which will restrict a subscription to that channel. It's hidden by default, so just control-click in the header of the Subscription table to get the list of columns, then select Channel to make it visible.  

Then to subscribe to all shows on a channel, create a a manual Subscription with Cmd-N,  type ALL, OK, then in the Channel column, select the channel you want to restrict it to.

**Comment by mackworth** [comment]
ah, just tried it and FYI, it will enter a download for all existing shows as a result. Just select them all and delete them. 

I should probably change that so manual subscriptions don't apply to existing shows (as you can ask for that afterwards).

**Comment by jahavri** [comment]
Thanks for the tips—I’ve got it now.  Works just the way I want, thanks!

**Comment by jahavri** [comment]
A small quirk: when I start cTiVo with the channel subscription, it adds 4 of the [latest recorded] movies from the channel.  I have 4 concurrent encoders selected in preferences and am using simple “Decrypted TiVo Show” as the format.  I would expect all available [10 movies] to have been added to the download queue.  Waiting now to see if after the first four, the others are added afterward or maybe 4 at a time? Just FYI,  experimenting.

Thanks again—great feature.

**Comment by jahavri** [comment]
Window cap

**Comment by mackworth** [comment]
Nope, it should get all on the first try (and then download one at a time, as there’s no real encoding). Try the right click reapply command. (Note that GitHub strips attachments from email replies, so I can’t see your screenshit

**Comment by jahavri** [comment]
I restarted and it still did not add the rest to the queue.  I rights clicked and reapplied and that did work.  Thanks.

**Comment by mackworth** [comment]
If you can post the screenshot, I’d like to see it.

**Comment by jahavri** [comment]
Attached.
<img width="2021" alt="ctivo" src="https://user-images.githubusercontent.com/40746052/45669666-99723800-bad5-11e8-8be5-fd25d99374b5.png">
<img width="2101" alt="update" src="https://user-images.githubusercontent.com/40746052/45669675-a000af80-bad5-11e8-8b45-a800f4325aa0.png">
