### ISSUE TITLE
unable to download any files at all

### ISSUE THREAD

**Issue by sabrina5by5** [dscottbuch/cTiVo#327]
I just downloaded this software and hav been trying for a few day to get it to download any of my shows. i have no idea what is going on, but it doesn't appear that anything is happening. these are the only 2 logs in the file... can anyone give me some tips on what i am doing wrong?

[com.cTiVo.cTiVo 2018-07-22 17-15.log](https://github.com/dscottbuch/cTiVo/files/2225891/com.cTiVo.cTiVo.2018-07-22.17-15.log)
[com.cTiVo.cTiVo 2018-07-24 01-57.log](https://github.com/dscottbuch/cTiVo/files/2225892/com.cTiVo.cTiVo.2018-07-24.01-57.log)

**Comment by mackworth** [comment]
Sorry for your troubles!  

So, you’re running the older 10.7 version of cTiVo.  Unless you’re on MacOS 10.7 or 10.8, I’d recommend the regular version.  If you do need to run the older version, I can walk you through some possible fixes.

**Comment by sabrina5by5** [comment]
How do I get the newer version? I have the newest Mac OS high sierra. I thought I was downloading the current version of cTivo. 

Any help is much appreciated. Thanks

**Comment by mackworth** [comment]
You can download the new version [here:](https://github.com/dscottbuch/cTiVo/releases/download/3.1.2/cTiVo.zip).  It's in the Releases page in this site. 
After you download it, it will check occasionally for the latest release.

I keep the old one around for folks still running 10.7 and 10.8, but really it's time to get rid of it, as it has many problems now.

 (Just curious, how did you get the 10.7 version?)

**Comment by sabrina5by5** [comment]
I downloaded it from the github site, I think. I updated it this morning and it appeared to be working once I did so!!!!  I had no idea it wasn’t the newest version. Thanks again!!!

**Comment by mackworth** [comment]
Glad to help. Let me know if you have any other issues!
