### ISSUE TITLE
cTivo 3.1.2 occasionally failing with Invalid media key

### ISSUE THREAD

**Issue by rqchin** [dscottbuch/cTiVo#329]
Occasionally cTivo will fail to encode a show and no matter how many time I try to repeat it, it fails. It seems to have something to do with the encryption key which doesn't make sense since everything else decodes/encodes without an issue.
[com.cTiVo.cTiVo 2018-08-10 06-00.log.zip](https://github.com/dscottbuch/cTiVo/files/2279675/com.cTiVo.cTiVo.2018-08-10.06-00.log.zip)

Might be related to this issue https://github.com/dscottbuch/cTiVo/issues/322#issuecomment-408705026

**Comment by mackworth** [comment]
So something is wrong with that file as delivered by TiVo, as that message comes up when the decryption algorithm comes up with complete junk.
But there are a few things to try. 

Before these, I would change Format to Decrypted TiVo Show, to avoid any interactions with the Format.
First would be to try changing the channel to require Transport Stream (Edit>Channels), and see if that fixes it. 
Second would be to download the show using your browser at [this link](http://dvr-162b.local.:80/download/Marvel's%20Agent%20Carter.TiVo?Container=%2FNowPlaying&id=102324), and post on a cloud site with the URL here. Then I could see what's wrong with the file. (You'll need to send me your MAK privately though).
Third would be to enable "Don't delete tmp Files" in Adv Prefs,to be able to see and post the decode log in your temp directory; be sure to turn it off after running a sample. 
Fourth would be to try changing "Decode With" in Adv Prefs to TiVoLibre (but that requires installing the Java runtime assuming you don't already have it).

**Comment by rqchin** [comment]
OK, changing the channel to require Transport Stream worked when it was set to Decrypted TiVo Show. Should I try it again with Default? What does require Transport Stream do?

**Comment by mackworth** [comment]
Yes, try again with Default. If it doesn't work, run one with Logging set to Major and post the results.
And did other shows work on that channel? With Default or Decrypted. That's first I've heard of tivodecrypt failing on PS and working on TS.

There's some notes on [Transport Stream here ](url
https://github.com/dscottbuch/cTiVo/wiki/Advanced-Topics#edit-channels)

**Comment by rqchin** [comment]
Yes, other shows worked on that channel without any hiccups. Puzzling. Trying it with Transport Stream and Default now. It seems to be working. When it failed, it did it almost immediately. Not sure what to think since most shows worked.

**Comment by mackworth** [comment]
Well, not leaving anything to chance, could you try PS again, and confirm that it still doesn't work?

**Comment by rqchin** [comment]
OK, it worked with Transport Stream on and set to Default. I tried it again with Transport Stream off (this means I'm using Progressive Stream, right?) and it failed immediately with the status message Invalid Media Key? BTW, this is what the Transport Stream preferences window looks like. It doesn't have any channels in there, which I think means it hasn't automatically detected any channels that use H.264 but seem to have no video, just audio.
![transport stream](https://user-images.githubusercontent.com/33967440/44092265-ef30d178-9f9d-11e8-9ca6-fbb46f394fca.jpg)

**Comment by mackworth** [comment]
Thank you for the experiments, and I'm glad you have a workaround. And, yes, that means your cable provider hasn't converted to TS (yes, the opposite of PS, which means Program Stream), so I'd leave "Always use TS" off. 

I think your file triggered a bug in either the PS encoder on your TiVo or the decoder in cTiVo's tivodecode-ng program.   If it's just the one program, then let's just quietly leave it behind us. But if you see it happening more than a couple times, let me know.

**Comment by rqchin** [comment]
OK, thanks for helping me find the workaround!
