### ISSUE TITLE
CTivo download fails multiple times

### ISSUE THREAD

**Issue by Dial430** [dscottbuch/cTiVo#333]
I have used cTivo multiple times to download and encode NFL football games.  I am unable to download and encode a game, although I am able to download and encode other shows recorded the same day.  This has happened a couple of times and I would like to know what is causing this Tivo file to fail.  I have attached the log from my most recent failure.

Thank you for your help.
[com.cTiVo.cTiVo 2018-09-18 19-14.log](https://github.com/mackworth/cTiVo/files/2394824/com.cTiVo.cTiVo.2018-09-18.19-14.log)

**Comment by mackworth** [comment]
The symptom you’re showing is one I’ve been seeing more lately from ffmpeg.  It is complaining the TiVo show is badly formed, but in reality it’s probably fine.  I’m going to try and find someone there to work with on this, but in the meantime, you could try using one of the other Formats, either HB Default, or Decrypt MP4

**Comment by Dial430** [comment]
Thank you for the help.  I am trying HB Default, then Decrypt MP4, I'll let you know what happens.  The Tivo file did have pixelation and NBC in on comcast has quality issues so the file may appear to be corrupted in part.

**Comment by mackworth** [comment]
Well, let me know. Unfortunately TiVo won’t restart a download in the middle (to try and skip over a bad spot).

**Comment by Dial430** [comment]
I tried HB Default.  It downloaded and created an mp4 file, but there was only audio, the video did not get downloaded, so I can listen to the 3 hour broadcast but no video.  I am trying Decrypt MP4-1 now.
Unfortunately, the bad spots are intermittent throughout the broadcast.

**Comment by Dial430** [comment]
I tried Decrypt, the file downloaded but nothing would playback, no sound, black video.

**Comment by mackworth** [comment]
So, it's possible that this is a Transport Stream issue (as that is the symptom for a TS video being downloaded as a Program Stream(PS).  In Edit>Channels, make sure that the video's channel is marked as Use TS.  If not, then check that box, and try the video downloading again, especially the Decrypt MP4 (also use Decrypt MP4, not Mp4-1, which is a copy, and might have changed somehow).

BTW, the TS issue is not your original problem, as the log you sent before showed TS downloads, with a size of 7.3GB.

**Comment by mackworth** [comment]
Any luck?

**Comment by Dial430** [comment]
No, I tried all of your suggestions, no joy.  I can watch it on my Tivo, but unable to get the file to download, fails each time, or no video depending on which alternative I have tried.
Thanks for following up, but the file is corrupted and uncooperative.
Regards, 
Fred Dial
