### ISSUE TITLE
HQ thumbnails

### ISSUE THREAD

**Issue by verticalscience** [dscottbuch/cTiVo#34]
Enhance the initial thumbnails displayed in iTunes and alternative media players using images from  http://thetvdb.com

Suggest using the http://thetvdb.com  season specific "season banner" in the "covr" tag instead of a frame from the show.   Eg: Mad Men has a different cover for each season.

Save the show specific "poster" from  http://thetvdb.com as  folder.jpg.   The folder.jpg image can also be saved in the tag when season is unknown.

**Comment by mackworth** [comment]
Well, a little while later, this has been greatly enhanced in 3.0. Let me know if there's still an issue.
