### ISSUE TITLE
Enhancement Request - Filenames

### ISSUE THREAD

**Issue by thejrose1984** [dscottbuch/cTiVo#41]
Regardless of format, would it be possible to add features normally seen in iTunes such as folder organization done on the fly and metadata prefixing?

For example,
Show - Royal Pains
Episode - S06E01
Title - Smoke and Mirrors

Output - Royal Pains / Season 6 / S06E01 Royal Pains - Smoke and Mirrors.mp4

The above example shows that the file, S06E01 Royal Pains - Smoke and Mirrors.mp4, is created in folder "Season 6" and has a parent folder "Royal Pains"

Currently, CTivo creates the folder that houses the series, but doesn't do anything else to the output file.

In addition, the file name would add the metadata that is shown in CTivo's Episode Number column as a prefix.

**Comment by thejrose1984** [comment]
Yes and No. I tweaked the keywords for the "Plex Folders" Filename Template to this:

[MainTitle / "Season " Season / SeriesEpNumber " - " EpisodeTitle]["Movies"  / MainTitle " (" MovieYear ")"]

The end result is this:

TV Show Name / Season ID / TV Show Name / File with correct template
![screen shot 2015-01-10 at 9 54 55 am](https://cloud.githubusercontent.com/assets/7573083/5691983/c1f22076-98ae-11e4-94cc-368b986f9fd2.png)

How do I get the second sub-folder with the Main Title out?

**Comment by thejrose1984** [comment]
Nevermind, this has been resolved due to conflicting settings. Thank you again for your assistance.

**Comment by mackworth** [comment]
Right; for others following this, as it sounds like you discovered, if you are using the custom naming options (e.g. the Plex version), then it's probably best to turn off  the "Create Sub-folders for Series" option.

**Comment by thejrose1984** [comment]
Correct, that's exactly what it was.

**Comment by kaynenh** [comment]
+1 for this advice. I also added a base path of "TV Shows" to the default naming scheme. Thanks!

**Comment by mackworth** [comment]
So what was your final file template?

**Comment by kaynenh** [comment]
Final template I used was:

["TV Shows"  / MainTitle / "Season " Season / MainTitle " - " SeriesEpNumber " - " EpisodeTitle]["Movies"  / MainTitle " (" MovieYear ")"]

Sorry for the late response!
