### ISSUE TITLE
Comskip failure should re-try, not continue

### ISSUE THREAD

**Issue by fitzage** [dscottbuch/cTiVo#54]
Comskip has this habit of failing occasionally, and usually succeeds the next time without any trouble. When Comskip fails, I would like the option of having ctivo re-try Comskip until it works instead of continuing on with the rest of the process.

As it is currently, I have to then re-download and process the file to do the Comskip step. If it just retried the step, it would usually succeed without having to start over.

**Comment by adrian152** [comment]
Good evening, one question, how do you run ComSkip.exe in a Mac using cTivo?, not sure how that works, or do they have a Mac version we can run?, can someone offer some guidance on this? Thanks.

**Comment by mackworth** [comment]
It's built in. Just select the commercial skip or commercial mark options. Skip cuts the commercials out entirely, Mark adds chapter marks for start of commercials and content. I like Mark, because comskip isn't perfect and mark lets me move backwards when it gets it wrong.

**Comment by adrian152** [comment]
That's nice, and do you know why the option Skip is greyed-out for the shows?, I'm currently using the Handbreak AppleTV format with a Tivo Roamio

**Comment by mackworth** [comment]
Sure. Handbrake's encoder doesn't support the idea of cutting a video based on an Edit-Decision List, which is what comskip generates. As far as I remember, only mencoder does.

**Comment by mackworth** [comment]
Included in 2.5 alpha1
