### ISSUE TITLE
Is there any way to retrieve a list of recordings on the Tivo?

### ISSUE THREAD

**Issue by WhyAkron** [dscottbuch/cTiVo#76]
I hope this isn't something obvious I missed, but is there any way to get a printable and/or editable list of the recordings on the Tivo? (Currently using cTivo 2.3.1, OSX 10.9.5)
Thank you

**Comment by mackworth** [comment]
I have an alpha available for this now, if you'd like to try it at 

https://dl.dropboxusercontent.com/u/21507587/cTiVo.zip

You can now drag/drop (or cut/paste) from all three tables (Shows, Downloads and Subscriptions). Note that the receiving program must handle the idea of multiple text items; notably MS Word and Excel do not, but TextEdit does, so you can drag it there and then cut/paste into Word or excel.  

As a advanced-user feature, you can also drag or paste Subscriptions back into the program. This allows someone to back up their subscriptions or even edit them in a text editor. As we don't support two subscriptions with the same name, you must either change the name or delete the old one before reimporting it.

**Comment by WhyAkron** [comment]
Thank you for the chance to try the alpha. Unfortunately, it only partially works for me. In the Shows list only the items not in bold (whether or not they are marked as "Que'd")  can be dragged or copied/pasted. The items in BOLD (by the way, what does bold in the listing signify?) and ALL items in Downloads list result in a warning from TextEdit - "Warning Do you really want to copy the contents of the dragged items into the text?" and gives choices of Alias, Cancel, Copy. Choosing Alias or Copy goes to everlasting beach ball. Drag/drop or Copy/Paste no difference. Did not try Subscriptions because I don't use that feature.
Same results dragging or pasting into Pages, Numbers, and even Stickies. (I don't have any MS products.) Non-bold Items work. BOLD items into Pages and Numbers don't give a warning, but show a progress bar instead of beach ball, and in any case I gave up after several minutes. Into Stickies only an icon shows up after a few seconds.
I hope these comments make enough sense to be useful. Let me know if I can try anything else or supply any more information
Using a mid-2010 Mac Book Pro, 8GB ram, OSX 10.9.5.

Thank you
WhyAkron

**Comment by mackworth** [comment]
Well, thank you for being the guinea pig! And for some great feedback.

So, bold means that there is a version of the show already downloaded currently on the disk. When I do a copy (or drag), for downloaded shows (bold shows and downloads that have already completed), I put both the text and the file reference on the clipboard (so for example, you can drag the file to a different directory in the Finder). The warning is that you're about to paste a huge video into the file, which you might not mean to do. Alias means that it puts a pointer to the file there; Copy means put the whole file there.  

On the beachballing; I'm guessing you were doing a bunch of files at a time (or running out of disk space or have too many apps running), which would require a lot of thrashing. On my (admittedly rather fast) MacBook Pro, it takes about 10 seconds to insert a video into a Pages. (And Stickies as well, although I find that an odd use case.)

So, one thing to try: TextEdit can edit both Rich Text and plain text documents. (Format>Make Plain Text or Format>Make Rich Text switches back and forth.) I bet you will get all the show names if you're in Plain Text mode (as the program cannot insert video then), which is the mode I had tested it in.

Another trick (that might go away; I have to think about all the uses): If the FIRST show is not bold (or already downloaded), then there's a bug right now that it only copies the text string for all the shows. This should then work for all those apps. This is why I didn't notice it doing the video copy in Pages.

Let me know if those help. I'll have to see if I can make this more intuitive.

**Comment by WhyAkron** [comment]
Thanks for the response. Plain text in TextEdit works. I didn't know the choice was there, as I use TextWrangler to deal with plain text. In this case TextWrangler doesn't work for the initial paste (absolutely nothing happens, like I didn't even do anything). Doesn't matter. Going through TextEdit serves same purpose.
Beachball was happening even with only one bold item, I guess because of video.
Overall, it works.
About non-bold, marked as Que'd, I finally realized those are files that I downloaded, moved to another disk, and deleted from download disk.

Thank you for the help
WhyAkron

**Comment by WhyAkron** [comment]
Something I didn't check before sending my last response...
Can the list copying be extended to include protected shows?
I know it's not really part of cTivo's purpose, but would be very useful in dealing with what is on the Tivo.

Thank you
WhyAkron

**Comment by mackworth** [comment]
Sure. I've moved the check on protected shows from drag/copy to drop/paste; thus it won't try and download protected shows, but they'll be included on text versions.  Try new Version 2.4.0b6 (523) here:
    https://dl.dropboxusercontent.com/u/21507587/cTiVo.zip

Note that you can empty your queue of completed items (those Que'd ones) with Cmd-E or Edit>Clear Completed History

**Comment by WhyAkron** [comment]
Got it. Tried it. Works! Odd thing about it - protected selections don't highlight, but when I select all they all copy in the list. Not a complaint, just an observation. One last(!) thing - can some kind of marker for protected status be included in the copied list? If it's too involved to do, I'll use cTivo as it is. Thank you for the list copying addition. I hope others find it useful too.
Haven't had any other issues with this version, but I don't think I push its capabilities - single downloads, no subscriptions.
TextWrangler - using 4.5.12 checked that pref, still no go. But as I said before, going through TextEdit is fine, just different for me.

Why Akron
