### ISSUE TITLE
cTiVo conversion fault

### ISSUE THREAD

**Issue by macjoe10** [dscottbuch/cTiVo#80]
So this is my first post here, but came across a problem with cTiVo conversion that I think I figured out the cause.  Probably 90% of my converted files are fine, I load into iTunes and then down to iPad to watch on planes.  Recently I have had a few instances when at some random point into the show it will freeze, the counter will keep going but the video and audio freezes.  

I can restart and it will stop again at the exact same point for that show.  I even reconverted the show, and again freezing at the exact same point.  Upon checking the Tivo actual source on the Tivo and local TV, the file is fine... well almost.  At the exact point where the cTiVo conversion froze, I noticed a short but heavy pixelation on the actual TiVo.  My conjecture is that there is enough of a hiccup (BER I'm guessing) to freeze the process, although the counter for encoding keeps going.... like it losing sync but keeps running.  

Not sure the fix, but perhaps enough buffer to allow a skip ahead or something.  Better to lose a few seconds than the whole show.

Anyway... hope this helps someone figure out a workaround.  I'm actually going off direct cable feed, can't imagine how big of a pain this might be if the TiVo were antenna connected with fades and such.

Thanks.. joe

**Comment by mackworth** [comment]
Okay. Let me know if you see any results.
