### ISSUE TITLE
Season Episode Number Incorrect

### ISSUE THREAD

**Issue by tMHwFFopPNEY** [dscottbuch/cTiVo#84]
Episode numbers on TV Series can be incorrect in cTiVo.  S01E01 seems to always be correct, but S02E02 (per Tivo) can be reported as S02E11 in cTiVo.  Exact example:  Per Tivo - Malaney [S01E02] The Doula.  Per cTiVo - Malaney: The Doula [S02E07].

**Comment by mackworth** [comment]
This is a reporting issue from the TiVo. the data we get from the device says one thing, even though sometimes the display says another. We've added a feature called "Trust TVDB" which can help. It looks up the shows on theTVDB and when the season/episode info conflicts with TiVo's information, it uses TVDBD's instead.
