### ISSUE TITLE
Blank when connected to Tivo Roamio

### ISSUE THREAD

**Issue by ktemerian** [dscottbuch/cTiVo#86]
Hi all, not sure what happened but 2 days ago my ctivo won't list anything on my Tivo Roamio.  Was downloading and had an problem so I shut it down and restarted it (only 2nd or third time ever) and it seems to find the Tivo (acknowledges if I'm online or not, so I'm notsure if it actually sees my Roamio) but none of my movies or shows are listed.  I've tried restarting router, tivo, and computer.  Plus reinstalled ctivo and tried using the beta 2.4.0b4 version.  Any ideas on what happened and how to fix?

**Comment by mackworth** [comment]
Hi, sorry for delay; I didn't see this question for some reason.  

Can you be a little more precise about what you see? Not quite sure what you mean by "acknowledges if I'm online or not". 

If the tivo name doesn't appear, or says "offline", then you've got a network problem of some sort. 

If it does show a name and you see an "Updating <tivo Name>", then turn logging up to Detail in Preferences and refresh the tivo. Then use the "Help>Show logs in finder" menu item and double click the latest log file into the Console program. Then search for "NowPlaying", and you should see a URL  like `https://dvrname/TivoConnect?Command=Command=QueryContainer&Container=%2FNowPlaying&Recurse=Yes&AnchorOffset=0&ItemCount=15`   Put that URL into your browser (username Tivo; password is your MAK) and let me know what you see.

**Comment by ktemerian** [comment]
Hi Hugh, 

Thanks for responding.  I did do a complete restart of my Tivo Roamio and everything seems to be okay.  Once in a while there seems to be a glitch but when I restart my Tivo things work again.  I did have another problem though, if you don’t mind.  I tried going through an ethernet from my laptop to the Tivo and the downloads get about 5% through and then goes from Download to Encoding and then freezes.  Then it goes to the next one in the queue and does the same thing.  When I unplug the cable and go back to wifi things work fine and the downloads complete.

Any ideas why?  I was hoping to speed up the transfer process by using ethernet instead of wireless.

Kathleen

**Comment by mackworth** [comment]
Hmm, shouldn't have to reboot the tivo that often. We work pretty hard to not overstress it.

On the other part, I'm curious if you plugged in the ethernet before or after launching cTivo?  That might be a factor. Regardless, if you can turn logging up to Detail as described above and then post the log somewhere with a URL here, then I can see some more detail.

I should mention that unless your wireless is pretty slow, it's probably not the bottleneck.

**Comment by ktemerian** [comment]
I did plug it in with the Ctivo running but then closed it down and powered it back up.

I’ll email back with the logging details.

Thanks

**Comment by mackworth** [comment]
Any results?

**Comment by mackworth** [comment]
Closed due to lack of response. Let me know if there's any news.

**Comment by ktemerian** [comment]
Sorry about the delay - I’m not very good with computers so I’m still trying to figure out how to “get” the log to you.

**Comment by mackworth** [comment]
Best is to just put the file on any fileshare service (e.g. Dropbox). If you don't have that, just copy/paste into a note here. that'll be fine.

**Comment by ktemerian** [comment]
Where do I retrieve the log from?

**Comment by mackworth** [comment]
Which version of the software are you using?  If there's a menu item in the Help menu called `Show cTiVo Logs`, then just do that. If not, use the Finder command Go>Go To Folder and copy/paste `~/Library/Logs/cTiVo`.  Then look for the most recent one. Be sure that you've set the logging level to Detail in cTiVo's preferences and run at least one show that fails before doing all that!

**Comment by ktemerian** [comment]
Hello,

I’ve tried several times to attach the log file but it keeps coming back as delivery notification.  I’m using 2.4.0b4.

Any ideas, it now Pauses itself from time to time for no reason.

**Comment by mackworth** [comment]
Sorry; GitHub doesn't support posting files (0ther than images). Best is to put the file somewhere else, like DropBox public folder, and then post a link here.  

On the Pause (assuming you mean the big red Paused msg), there's two reasons that would come up. If you type Cmd-U, then that will manually Pause/Unpause the system. Alternatively, if you go to Preferences, in the lower left, if `Scheduling Active` is turned on, then cTiVo will only run during the period specified in the Start/End range.

**Comment by ktemerian** [comment]
https://www.dropbox.com/s/39mccqcrmmx7r37/com.cTiVo.cTiVo%202015-02-12%2022-13.log?dl=0 <https://www.dropbox.com/s/39mccqcrmmx7r37/com.cTiVo.cTiVo%202015-02-12%2022-13.log?dl=0>

**Comment by mackworth** [comment]
So this log shows the following download "transitions" for the shows being transferred:

Changing DL status of The Prisoner of Zenda (Family Room) to Encoded (12)
Changing DL status of The Prisoner of Zenda (Family Room) to Complete (14)
Changing DL status of The Sea Hawk (Family Room) to Encoding (7)
Changing DL status of The Sea Hawk (Family Room) to Encoded (12)
Changing DL status of The Sea Hawk (Family Room) to Complete (14)
Changing DL status of Sergeant York (Family Room) to  (0)
Changing DL status of Sergeant York (Family Room) to Downloading (1)
Changing DL status of Sergeant York (Family Room) to Encoding (7)

So, so far, that looks pretty good.  Maybe there's another log that's later?

**Comment by ktemerian** [comment]
I must have made an error on what times the log recorded - sorry - I’ll try again, thanks for being so patient.  The way it went on the screen - the file started downloading, normally until about 5-10% of the file, then it switched to encoding and just stayed there and started downloading the next file in the Queue.

**Comment by mackworth** [comment]
If you want to make the logging the most effective (and avoid creating too large a file), go to the Adv Preference window (Cmd-Opt-Comma), set Debug Level to Detail and then in the lower section, set the TiVo to Major, TiVoShow to Major, and Download to Verbose.

**Comment by ktemerian** [comment]
https://www.dropbox.com/s/luv5hpjyk6akszy/com.cTiVo.cTiVo%202015-02-18%2001-49.log?dl=0 <https://www.dropbox.com/s/luv5hpjyk6akszy/com.cTiVo.cTiVo%202015-02-18%2001-49.log?dl=0>

**Comment by mackworth** [comment]
So, a similarly interpreted version would be:

<<prior to Log, presumably Adding Montana and Changing DL to Downloading>>
2015-02-17 17:50:52: Adding show: A Damsel in Distress

2015-02-17 17:55:41: Changing DL status of Montana to Encoding (7)
2015-02-17 17:55:48: Changing DL status of A Damsel in Distress to Downloading (1)
2015-02-17 17:56:06: Adding show: You Were Never Lovelier 

2015-02-17 18:29:31: Changing DL status of A Damsel in Distress to Encoding (7)
2015-02-17 18:29:39: User Delete shows:   "Montana ", "A Damsel in Distress", "You Were Never Lovelier"

2015-02-17 18:31:00: Adding show: Montana 
2015-02-17 18:31:00: Changing DL status of Montana to Downloading (1)

2015-02-17 18:31:04: Adding show: A Damsel in Distress
2015-02-17 18:31:07: Adding show: Cyrano de Bergerac 
2015-02-17 18:38:16: Changing DL status of Montana to Encoding (7)
2015-02-17 18:38:30: Changing DL status of A Damsel in Distress to Downloading (1)
2015-02-17 19:18:51: Changing DL status of A Damsel in Distress to Encoding (7)
2015-02-17 19:25:11: <<End of log>>

So, that looks fine except it looks like the encodes are taking too long. Are you sure you're giving enough time for the encoding to complete?  As we are simultaneously downloading and encoding, depending on the machine, the network connection, and the encoder chosen, the encoding may complete as soon as the download does or take much longer.  As long as the little orange bar is moving (or hover the cursor over it and get performance information), it's still going. And there's a dead-man's timer that should go off if the encoder fails completely and no progress is made. 

If you're not seeing any progress going on, then I'll need to get a different log.  Still set TiVo to Major, TiVoShow to Major, and Download to Verbose, but also set Task and TaskChain to Verbose. This will tell me if the subtask of encoding is giving a problem. Just launch one show and let it run to completion.

**Comment by ktemerian** [comment]
Hi,

I’ve got a strange question.  There is one movie I’ve downloaded twice and both times (AppleTV) there is no audio.  The movie on my tiro has audio and so do the rest of the ones I downloaded during the same time.

Why?

Katie

**Comment by ktemerian** [comment]
Hello,

For some reason my cTivo application fails on any attempted download.  I recorded it on a detailed log and can’t figure out why it won’t work.  I have a Tivo Roamio, Apple MacBook (1 yr old), El Capitan software, and the latest version of the cTivo.  I put the log in my dropbox although I’m not familiar with how this all works.  My tivo has access to wifi.

Thanks,
Kathleen

**Comment by ktemerian** [comment]
Kathleen shared a file with you on Dropbox

View file "com.cTiVo.cTiVo 2015-11-12 07-52.log"[1] 

[1]: https://www.dropbox.com/l/s/qL2Lq7vMEP2aAtBJY5n55g?text=1

**Comment by mackworth** [comment]
I'll take s look in more detail later, but a quick glance suggests that rebooting your TiVo may help. Note also that after a failure, we wait about a minute to try again to avoid stressing the TiVo

**Comment by mackworth** [comment]
Yes, looking at it in more detail, that's certainly the next step. It was downloading listings and part of a file, then had a problem, and then refused to communicate any more.

**Comment by ktemerian** [comment]
I have rebooted the TiVo but it still doesn't work.  Any ideas?

**Comment by mackworth** [comment]
Then the next most likely  would be some sort of network problem. Try using your browser to access it directly with the following URL
https://dvr-44a6.local./

You'll be asked for a name & password. Use `tivo` and your MAK (see cTiVo's Edit Tivo command for the MAK).

That should give you a list of shows, then click on one of the -PS shows (preferably a smaller one) and let me know how that goes.

**Comment by ktemerian** [comment]
Hi,

I’ve been using the cTivo for a while now and was wondering if there was a different way I should be formatting the files.  I’ve been using the Apple TV format (since I have one) but if I ever change how I store the movies or don’t want to use the apple tv later on - should I be downloading the files in Decrypted or High Quality (with the intention that they can be reformatted later to fit what tech gadget I’m using)?  I’m not very tech minded so I don’t know if the Apple TV format can be reformatted later on to be used on other TV options.

Thanks, Kathleen

**Comment by mackworth** [comment]
There's nothing particularly specific about that format to the Apple TV; it's a good general purpose one that will run great on almost any device that you have or will have. Just FYI, "High Quality" would be if you wanted the best possible quality (but at a cost of space and conversion time), and Decrypted just copies the files over as is, so no processing at all, which is good for video quality and future conversions, but not very compatible and a very inefficient format.

So, I take it everything is all right on the prior network problems?

**Comment by ktemerian** [comment]
Yes, I just restarted everything from the modem to the TV to the TiVo to my computer, and it fixed itself.  Ok, do you notice a big difference between the high quality and the Apple TV format?

K

**Comment by mackworth** [comment]
Personally, not at all, although I'm not a true videophile.  I do all my personal videos (when I'm not testing ctivo) in the AppleTV format

**Comment by ktemerian** [comment]
Kathleen shared a file with you on Dropbox Hello again, I'm running into the same problem - nothing can get cTivo to download files from my Tivo Roamio.  I've reset all items (mac, cTivo, Tivo Roamio, Modem) and still nothing.  I've contacted Comcast and everything with my WiFi connection is good.    com.cTiVo.cTiVo 2015-12-28 18-39.log[1] View file[1]  

[1]: https://www.dropbox.com/l/s/O8NtCJTLvvAXqe3vtV6RUm?text=1
