### ISSUE TITLE
Constant failed downloads

### ISSUE THREAD

**Issue by gdroth** [dscottbuch/cTiVo#87]
All I'm trying to do is transfer some Tivo content for a 30 minute TV show to an external hard drive so that I can view it on an airplane using my MacBook Air.  However, I keep getting a failed download message.  I've tried different video formats ranging from iPod to Decrypted Tivo show, and turned skid commercials on/off.

I have a log in Dropbox 

https://dl.dropboxusercontent.com/u/16606588/com.cTiVo.cTiVo%202015-01-04%2022-46.log

**Comment by mackworth** [comment]
Sorry to hear that. To diagnose, you'll need to increase the logging level in Preferences to Detail. That will give much more information about the reason for the failure. Also, there are occasionally certain shows that the TiVo download software fails on (due to reception glitches in the file), so if you could try one other show as well that would be great.

**Comment by gdroth** [comment]
I will try that the next time I have problems.  I seem to have solved some of them by using H.264 rather than udencrypted TIVO.
> On Jan 7, 2015, at 9:01 AM, Hugh Mackworth <notifications@github.com> wrote:
> 
> Sorry to hear that. To diagnose, you'll need to increase the logging level in Preferences to Detail. That will give much more information about the reason for the failure. Also, there are occasionally certain shows that the TiVo download software fails on (due to reception glitches in the file), so if you could try one other show as well that would be great.
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/dscottbuch/cTiVo/issues/87#issuecomment-69024916>.
> 


GD Rothenberg

**Comment by mackworth** [comment]
Ok; let me know!  Personally I like the AppleTV setting. excellent quality, and quite small.
