### ISSUE TITLE
CTiVo receiving or using wrong Episode Number

### ISSUE THREAD

**Issue by thejrose1984** [dscottbuch/cTiVo#89]
Not sure if this is an issue with TVDB or CTivo, but I notice that the episode number (e.g. S03E09) it gets from records are wrong. It's not a constant issue, just with certain shows such as The Big Bang Theory. Any ideas?

**Comment by mackworth** [comment]
It's the data that TiVo sends us. Annoyingly, not the data that it chooses to display on the screen.  As this has been increasing as a problem, there's an option in 2.4 "Trust TVDB". If you select this, if theTVDB.com and Tivo disagree on season/episode information, then we will use the TVDB info. I find this works well for this problem.
