### ISSUE TITLE
Really dumb question

### ISSUE THREAD

**Issue by nicknace** [dscottbuch/cTiVo#91]
I download the zip file, then drag its contents into my Applications folder. Now a I have a folder with multiple files and items. I've tried clicking on (maybe) all of them. None of them opens the app

**Comment by mackworth** [comment]
I'm guessing you have the wrong download. The zip file should auto-decompress into one file called cTiVo. Which button are you downloading/ what's the URL represented?

**Comment by nicknace** [comment]
I found it now. Thank you.

**Comment by nicknace** [comment]
How rude of me - many thanks for sharing this program with all of us. 
Nick Nace

**Comment by mackworth** [comment]
No problem at all. Hope it works well for you!
