### ISSUE TITLE
How to get cTIVO output onto DVD that will work with a player with a regular TV set?

### ISSUE THREAD

**Issue by lar01** [dscottbuch/cTiVo#93]
Hi. cTIVO has worked fine, but so far when I've downloaded to my Mac from my TIVO Roamio, and burned the output to a DVD, that DVD will only work on my Mac (i.e. I assume though QuickTime) I want to take the DVD to a friend's Sony combination DVD player and VCR, to play the DVD through her TV set,, and can't figure out how to do that.  Any help would be appreciated.

**Comment by mackworth** [comment]
There's two ways to write data to a DVD. One treats it like a read-only file system, so your video is just a big data  file and the other builds a DVD-player compatible format. You can easily see this by putting an existing video DVD into your Mac, you'll see a complicated series of directories and files. The OS can only write data disks (e.g. for backup, or to move a video to another Mac), not video disks.  Here's a good article (albeit a bit old) on different options for burning a DVD video disk. Note that DVD is a standard definition format only; for HD, you'll need Blu-ray players, which is another world of complexity.

http://lifehacker.com/5859277/the-best-disc-burning-app-for-mac

**Comment by mackworth** [comment]
Ok, don't know if you're the same person as on the Apple forum, but in case not...

I hadn't tried a DVD in quite a while, and it looks like the built-in DVD format needed some updating. I've taken the latest recommended [NTSC DVD format commands from mencoder](http://http//www.mplayerhq.hu/DOCS/HTML/en/menc-feat-vcd-dvd.html) and created a format that you can import into cTiVo, using the `File>Import Formats...` command. It's [available here]( https://dl.dropboxusercontent.com/u/21507587/DVD-NTSC.plist) . That should give you a compatible MPG file, but then you need DVD software to write out the actual disk. You could use Toast or others, but there's [a simple, free one called Burn](http://burn-osx.sourceforge.net/Pages/English/home.html) (instructions below). Note that DVD is standard definition only.

1) [Download  Burn](http://burn-osx.sourceforge.net/Pages/English/home.html)
2) Copy to your Applications folder.
3) Run Burn. (First time, use right-click and Open as the program is unsigned)
4) In Preferences/Video, switch Region to NTSC (in US). (First time only)
5) In Preferences/Burner/General, turn on Verify burned data. (First time only)
6) Switch to Video tab and select DVD-Video from pull-down.
7) Drag the video created by cTiVo into the list.
8) Hit Burn and wait a while.

Let me know if that works for you...

**Comment by mackworth** [comment]
Did that work for you?
