### ISSUE TITLE
Programme determined to be of type Movie, when it is a TV Show

### ISSUE THREAD

**Issue by kteare** [dscottbuch/cTiVo#94]
This happens for "Morning Joe" the MSNBC morning news show

**Comment by kteare** [comment]
The consequence of this is that it is added to iTunes as a Movie.

**Comment by mackworth** [comment]
I'll record it tomorrow morning and take a look. TiVo doesn't actually report whether it's a TV show or a movie, yet iTunes wants that info.  The heuristic I settled on was that a program is a TV Show if it's got an episode Title, or an episode number, or it's less than 70 minutes.

**Comment by mrfusiontm** [comment]
I'm having the same problem with Archer and it has a show name, episode
number and is less than 30 minutes.
It keeps putting it into /Movies/Home Movies.

**Comment by mackworth** [comment]
I've looked at some Archer episodes here, and I'm also seeing some of them classified as a movie as well (as is the Morning Joe from this, um, morning). I also think I see a way to improve the classification for both of these (and a couple others I see in my TiVo's Suggestions list). I'll run some more experiments.  

@mrfusiontm so I'm not surprised at the Movies classification, but I'm surprised on the Home Videos sub-classification. That's iTunes' default when a video is not marked as either Movie or TV Show, and AFAIK, cTiVo always marks one or the other. When I ran the movie-marked Archer from my TiVo, it went to the the Are your other movies going there as well?

**Comment by mrfusiontm** [comment]
No, that seems to be the only show that this happens with.  I'm not viewing
the shows in iTunes, I'm using plex.  So, cTivo creates the movie in
/Movies/Home Movies.  Plex thinks its this show:
http://thetvdb.com/?tab=series&id=75318&lid=7
 and I have to move it to the "Archer" directory and then tell Plex it
needs to fix an incorrect match and force it back to Archer.

**Comment by mackworth** [comment]
So, ... where does the phrase "Home Movies" come from? Do you have a custom filename string setup?

**Comment by mrfusiontm** [comment]
Nope.  I have no idea why it puts it there.  The file in named correctly
its just put in the wrong place

**Comment by mackworth** [comment]
Sorry to be specific, but let me confirm that you have the options 
  `Download Folder`: <<somewhere>>
  `Create Sub Folder per Series`: On; 
  `Add to iTunes When Complete`: Off; 
  `Filename Template`: Blank  (in Advanced Prefs)

With the configuration, cTiVo should put all movies (including this mistaken one) into `<<somewhere>>/Movies`, not into a further subdirectory of `<<somewhere>>/Movies/Home Movies`. Could Plex be moving the file?

**Comment by kteare** [comment]
Maybe the solution would be to allow the user to decide Movie, TV Show, At the subscribe stage…And maybe add metadata (season etc).
---
Best Regards

Keith Teare
Chat with me instantly at http://chatcenter.me/keith
________________________________________________________

**Comment by mrfusiontm** [comment]
No, Plex doesn't move anything.  I'll have to confirm this information you
requested when I get home tonight.

Actually, maybe I'm mistaken and it does just put it in the movies
directory....  In Plex it shows up in the "Home Movies"
listing.  Sorry for the confusion.

**Comment by mackworth** [comment]
Ah, that works. No problem, and I'll leave this open while I experiment with the different options.

@kteare, I try to keep it as automated as possible, and I think I'll be able to make this more accurate.  The metadata (especially season) should be picked up automatically. If you're seeing mistakes on episode info, you can tell cTiVo to "Prefer theTVDB episode info", as I find that to be more accurate.

**Comment by mackworth** [comment]
Ok, I've done a fair amount of testing, and I'm happy with the new algorithm for determining whether it's a movie or a show. It'll be in the next beta.

Thanks for reporting the problem!

**Comment by kteare** [comment]
Thank You Hugh


---
Best Regards

Keith Teare
Chat with me instantly at http://chatcenter.me/keith
________________________________________________________
