### ISSUE TITLE
Audio and Video out of sync

### ISSUE THREAD

**Issue by TimMeade** [dscottbuch/cTiVo#96]
Latest Beta playback on Roku with Plex.    Audio and Video are about 1/4 second out of sync.  2 different downloads and convert to H .264 High Quality

**Comment by mackworth** [comment]
Thanks for the report. Is this only recently? Have you tried any other Formats yet?  Other players with the bad files?

**Comment by TimMeade** [comment]
I tried a few formats all were out of sync.   This was the latest beta.

I downloaded the decrypted tivo mpg without add skip and it was fine.  So I moved it over to videoredo and edited it.

I’m a 25 year coder, anything you want me to look into let me know.

Tim

**Comment by mackworth** [comment]
Thanks for the offer. Let me know which formats and which options (skip/mark/captions etc) you're using and what the results are. Have you tried VLC or Apples player?

**Comment by mackworth** [comment]
Any further feedback on this?

**Comment by j2pro** [comment]
I have the same issue with Plex on Roku and the AppleTV format. I tried it in VLC and the audio is out of sync.

**Comment by j2pro** [comment]
I tried skip commercials and not skipping. no captions. Did not mark commercials.

**Comment by mackworth** [comment]
Okay, not clear where we are on this. Please let me know if this is still an issue, and if you could try a few different formats and/or players and let me know, maybe in a format like:


Options | Format  | Player  | Time out of sync
-------------|-------------|-------------|-------------
HD/SkipComm/captions |AppleTV  |   VLC |   3 seconds at begin; catches up by middle
SD/NoComm/NoCaptions|Decrypted Tivo|QuickTime | no sync issue

If you're not familiar with markdown, you can just cut/paste/edit the following text to create such a table:

````
Options | Format  | Player  | Time out of sync
-------------|-------------|-------------|-------------
HD/SkipComm/captions |AppleTV  |   VLC |   3 seconds at begin; catches up by middle
````

**Comment by wabplana** [comment]
I know this thread is dated, but I wanted to add I started having this problem with the most recent update (2.4.0).  I've tried the h.264 codecs and the mpeg-2 codecs.  I've tried playing the converted videos in VLC and Quicktime.  I've also tried pulling video from different tivos with the same results. It seems like the audio will catch up to the video about 15-ish minutes into the show, but until then the video and audio is out of sync.

**Comment by mackworth** [comment]
So, strange as it may sound, cTiVo doesn't actually do much to control that, a we don't interpret the audio or video streams. We take the video file from th TiVo, and hand it to the encoder (ffmpeg, mencoder, etc) with the parameters from the format command and then write the result to disk.  So it becomes necessary to identify a common element in the failure to figure out what's messing up.  For example, can you try the decrypt only format? That literally makes no changes to the video file, so if it has a problem, then somethings wrong with the TiVo. Then try and isolate between Handbrake v ffmpeg.  Happy to try and help, but need to be very precise on which Formats work and which don't

**Comment by wabplana** [comment]
Thanks for the reply. I will continue to test the converters, but I wanted to update and let you know that when pulling it just as a decrypted tivo show, that the video and audio is in sync.  I'll try the other converters and update once I have the chance to try them out.

Thanks!

**Comment by mackworth** [comment]
Well, that's actually good news, as it means your input data is correct, and we can then isolate where a problem is arising!

**Comment by mackworth** [comment]
Still working ok for you?

**Comment by wabplana** [comment]
Sorry for the delayed response. I welcomed our first child last month, so I've been occupied. I plan on getting some time in front of the computer to do some tests soon.

Thanks for checking in.

Bill

**Comment by mackworth** [comment]
Well, congratulations! But clearly, though, you are confused on your priorities. What's more important: properly welcoming your new child to the world and enjoying their first moments (and maybe some occasional sleep ), or helping to fix audio sync issues??

**Comment by mackworth** [comment]
Any sleep yet?

**Comment by wabplana** [comment]
Good Morning!  Thanks for the email.  Sleep???  I wish :)


I have been trying to collect all my data so I can share it with you at
once, but I haven't tried everything yet.  This is what I've learned so far:

1) I've tried both tivo's I own and both have the audio lag issue.
2) I've tried different shows to make sure it wasn't something specific
about the episodes I was downloading.
3) I still need to test the DVD encoder, and Apple TV settings, but all
other encoders I have tried are not working - H.264, divx, mpeg (I cannot
remember the others off the top of my head - sorry I am at work)
4) I was originally saving the encoded file to an external hard drive, but
to make sure that wasn't an issue I saved it locally on the main hard
drive.  My computer is base Mac Pro (late 2013 - i.e. the black trashcan)
running El Capitan. That did not solve the issue.
5) The only thing that seems to work is the decrypted Tivo file.  That
comes across clean.

I do not know what version I was running, but probably 8 months-ish an
update came out, and that is where I started having this problem. Before
the update everything was working well. I have no idea if it was in
conjunction with an OS update, or any other update I had on the system.
Are there any logs that I can produce that may show if I am having
trouble?  Also, if I am the only one having this problem I don't want you
to go through too much trouble.

Please let me know if there is anything else I can do to diagnose the
problem.

Thanks again!

**Comment by wabplana** [comment]
Good evening.  One quick update.  The Handbreak Apple TV settings are
succesful!  I have been able to get a good file using that encoder.

DVD did not work.

Thanks,
Bill

**Comment by mackworth** [comment]
So, in general, audio/video sync problems are due to some interaction between the file and the encoder options that you're using. The fact that it doesn't on the encrypted says the source file is basically ok. If you're using our built-in Formats, then it's surprising, but not impossible.  I am truly surprised that it happens on all shows on all but one format for you.

BTW, If you use VLC as your player, then you can control the sync manually during playback. if you press G, it will increase the audio delay by 50 ms (1/20 second), and F will decrease it (J and K on Windows).  As a test, see if the sync problem is consistent at the beginning of the video versus the end; also whether it's related to commercial cutting, as that slicing can introduce audio sync problems.

When you say DVD doesn't work, do you mean that it has the audio sync problem, or doesn't work at all?

**Comment by mackworth** [comment]
So I'll close this for now, let me know if you're still having a problem.
