### ISSUE TITLE
PBS - WLIW - Marked as Copy Protected?

### ISSUE THREAD

**Issue by christopherdawes** [dscottbuch/cTiVo#97]
Hello,
I've been watching, recording, and transferring WNET and WGBH television programs for years on my TiVo. I recently started recording WLIW from Time Warner Cable on my TiVo, but they all show up as Copy Protected, which sort of defeats the purpose of "Public" in "Public Television". Do you know why WLIW would be handled one way, while all the other PBS affiliates are handled in the opposite way? I can understand HBO being copy protected, but PBS? Is this something WLIW is doing? or TiVo? or cTiVo? Could you please look into it on your end? I've written to WLIW and am waiting to hear back. 
Thanks,
Chris

**Comment by mackworth** [comment]
Well, it's most likely a mistake or decision on the part of your cable provider. Time Warner is famous for abusing the ["CCI byte"](http://en.wikipedia.org/wiki/Copy_Control_Information), which lets content providers mark how much copying is allowed (copy-none will prevent tivo from recording, copy-once lets it record but not retransmit, and copy-freely lets it redistribute).  TiVo respects this byte, but some cable companies abuse it (and I'm puzzled as to how it's in their interest, but... )

Here's a couple of articles about it:
http://consumerist.com/2012/06/12/time-warners-copy-protection-might-just-drive-tv-lover-to-piracy/
http://zatznotfunny.com/2012-02/the-best-worst-cable-companies-for-tivo-owners/

So, I'm pretty sure it's not legal for them to mark OTA content as copy-once, but they apparently do it anyways.  So, I'd ask TW why they're doing it, and then complain to the FCC, although they apparently haven't changed behavior in the last few years despite TiVo users being annoyed.  I would think WLIW would be able to have some influence...

**Comment by christopherdawes** [comment]
Thanks for the response, Mackworth! I've written to WLIW and Time Warner. We'll see if I get anywhere.
